### ISSUE TITLE
Add Logging Dashboard

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#1151]
Provide a separate endpoint and screen that allows the adopter to:

1. Review the current logging configuration
2. Review active running loggers in the given context
3. Ability to change log levels or additive settings at runtime (without writing changes back to the config file). This purely for the runtime config.  

This is yet another stat for the CAS deployer to use. Ties to the log4j API may be necessary.

**Comment by mmoayyed** [comment]
Now ideally, log management and views should be delegated to an external dashboard such as Splunk or Logstash, etc. Here, we simply intend to provide a modest dashboard that presents a basic functionality of reviewing the log configuration, not necessarily the log output.

**Comment by leleuj** [comment]
Viewing logs is not an easy feature to implement. It's better to delegate to some dedicated solution.

Reviewing the logs configuration is a good feature, but I'm always worried about the risk of enabling DEBUG logs on all the server and filling disks or slowing the server.

**Comment by mmoayyed** [comment]
Yes, an external system would be a recommended solution. For those who wouldnt want to spend thousands on a capable system such as splunk, I think we should provide a modest feature, similar to Travis CI.

Turning on DEBUG can be a risk yes. I think you run that risk either way whether it's by config or a dashboard. With dashboards, we possibly have the option to warn the user to be careful.

**Comment by mmoayyed** [comment]
I have a prototype coming up. The biggest disadvantage is that ties to the logging framework is absolutely required. This cannot be done alone with slf4j. Since we support log4j2 officially, users can still choose to swap that out with logback, etc but  they wouldn't be able to take advantage of this dashboard.

**Comment by mmoayyed** [comment]
There is a chance we might drop this from the 4.2 release. Not sure yet.

**Comment by mmoayyed** [comment]
This is done
