### ISSUE TITLE
Add support for HTTP Digest Authentication

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#1384]
Based on https://github.com/pac4j/pac4j/issues/414

**Comment by leleuj** [comment]
Copy that

**Comment by mmoayyed** [comment]
Made a bit of progress on this. Need 1.9 before moving forward.

**Comment by leleuj** [comment]
I'm currently in holidays, I hope to finish: https://github.com/pac4j/pac4j/issues/558 next week before the 1.9 release.
