### ISSUE TITLE
OAuth implementation should not use HttpSession

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#1571]
The `WebContext` used in the OAuth implementation stores data into the session, which by default is the web session. This imposes the requirement of session replication/affinity, and should be removed. 

Options might be to store data into the webflow context, or a replicated cache.

**Comment by mmoayyed** [comment]
Another alternative might be use something like Spring Session.

**Comment by leleuj** [comment]
Or use the `SessionStore` capability already existing in pac4j.

**Comment by mmoayyed** [comment]
Had a look. With that SessionStore, what is the actual store? Whatever that may be, it needs to be replicated.

**Comment by mmoayyed** [comment]
In Oauth's case, what is it that we actually need to store into the session? I would want to get rid of the session requirement all together if possible.

**Comment by leleuj** [comment]
You attach the appropriate `SessionStore` to the `Config` object. By default, it's the `J2ESessionStore`, but we can have other implementations, like a `WebflowSessionStore` for example.
Just an idea, it needs to be thought a little more.

**Comment by leleuj** [comment]
In fact, with CAS server v4.3, only the requested url (the /authorize url with parameters) is saved into the web session by the `CasClient`. I think we could create a `DirectCasClient` which validates the service ticket if present on the url or redirect to the CAS server with the current url as CAS service. That way, no need for session.

**Comment by mmoayyed** [comment]
Excellent. Lets proceed that way. 

I noticed the IdP impl has the same problem. Working on a solution.

**Comment by leleuj** [comment]
I opened: https://github.com/pac4j/pac4j/issues/499

Likely, I'll add this one only on pac4j v1.9 as I planned a big refactoring between `CasClient` and the new `DirectCasClient` and `DirectCasProxyClient`. Thus, I'll handle that after upgrading to version 1.9 of pac4j.

**Comment by mmoayyed** [comment]
Noticed something else:

```
final UserProfile profile = manager.get(true);
```

where `true` is "readFromSession". This I think also needs to be accounted for.

**Comment by leleuj** [comment]
Good catch! You're perfectly right.

**Comment by mmoayyed** [comment]
@leleuj I don't think this issue can yet be resolved right? 1.9 does not handle this yet?

**Comment by leleuj** [comment]
Right, maybe in 1.9.2 or 1.9.3, I'll let you know...

**Comment by mmoayyed** [comment]
Having reviewed this, we can safely close this:

1. pac4j allows for a session-store implementation today.
2. the default session-based implementation can be perfectly replicated via provided CAS modules based on hazelcast, redis, etc
3. alternative impls can also be written as session-stores (probably a good idea for pac4j as well)
4. session affinity is a solved problem generally; we should not over complicate the situation here.
