### ISSUE TITLE
Enhancement: provide (maven) Bill of Materials for overlay dependencies

### ISSUE THREAD

**Issue by aukevanleeuwen** [apereo/cas#1586]
It would be great if CAS would provide a Bill of Materials for the dependencies that are used in the war overlay. That way I could just specify something along the lines of:

```
<dependencyManagement>
   <dependencies>
      <dependency>
         <groupId>org.jasig.cas</groupId>
         <artifactId>cas-overlay-bom</artifactId>
         <version>${cas.version}</version>
         <type>pom</type>
         <scope>import</scope>
      </dependency>
   </dependencies>
</dependencyManagement>
```

That means I would import all the libraries that used in the war overlay into the dependencyManagement section, which would greatly help with accidentally adding duplicate dependencies.

If currently I would (for example) add another dependency to my pom such as 

```
       <dependency>
          <groupId>org.springframework.retry</groupId>
          <artifactId>spring-retry</artifactId>
          <version>1.1.0.RELEASE</version>
       </dependency>
```

that would actually pull in another spring version (4.0.2.RELEASE or something). You don't really notice that until you look at the actual generated (overlayed) war file that has all sorts of duplicate jars in `/WEB-INF/lib`. Having a BOM would greatly help.

---

Note: for the spring transitive dependencies I currently use:

```
      <dependency>
         <groupId>org.springframework</groupId>
         <artifactId>spring-framework-bom</artifactId>
         <version>${spring.version}</version>
         <type>pom</type>
         <scope>import</scope>
      </dependency>
```

so that is often the bulk of it, but there are other things like different versions of log4j / slf4j / jaxb / apache-common-* to name a few of the likely suspects.

**Comment by mmoayyed** [comment]
So a few things:

1. Every CAS dependency that you need in your overlay can be provided in provided scope already. So you shouldn't have to declare anything that would result into a conflict.
2. If you need a separate dependency that CAS does not provide, like spring-retry, there is nothing we can do about that avoid conflicts. You'll need to ensure transitive dependencies are excluded, and only pick what is actually required. It would be near impossible to guess what all is needed. 
3. Another possible approach to help with 2 is to use Gradle which has far far better dependency management and controls over transitives. 

Does that help?

**Comment by mmoayyed** [comment]
That said, I think we already have a BOM in the root. We just don't release it for some reason.

**Comment by aukevanleeuwen** [comment]
In response to (1):

I realise that, it's just such a pain to keep track of them over releases (mainly the version numbers). If you provide the BOM and I include that in the `<dependencyManagement />` section I can simply output any dependencies that are already included without a version number. That way I don't end up with two `spring-context` jars with different version numbers.

In response to (2):

Sure I realise you can't do anything about conflicts. I wasn't really talking about conflicts. Generally there are no conflicts there are slight version mismatches. Maven isn't smart enough to figure out that there are dependencies in the `WEB-INF/lib` of the overlay that it should keep track of / manage.

As an example: suppose I say I depend on `spring-context-4.0.0` and I depend on `spring-retry-1.0.0`. If `spring-retry-1.0.0` would transitively depend on `spring-context-4.1.0` maven would figure out whether to use spring-context-4.0.0 **or** spring-context-4.1.0, not both. 

Now if I have a war overlay that includes `spring-context-4.0.0` and in my pom I specify that I depend on `spring-retry-1.0.0` I would end up with `spring-retry-1.0.0`, `spring-context-4.0.0` **and** `spring-context-4.1.0` in `WEB-INF/lib`.

**Comment by mmoayyed** [comment]
> As an example: suppose I say I depend on spring-context-4.0.0 and I depend on spring-retry-1.0.0. If spring-retry-1.0.0 would transitively depend on spring-context-4.1.0 maven would figure out whether to use spring-context-4.0.0 or spring-context-4.1.0, not both.

OK, this is a very confusing situation.

In your example, the `spring-context-4.0.0` dependency is coming from CAS right? and you do then add `spring-retry` which brings in an extra dependency and maven isnt smart enough to detect the new version? Do I have that right?

**Comment by aukevanleeuwen** [comment]
Yes you have that right, because the overlaying is purely file-based. It doesn't 'know' about the `spring-context-4.0.0` dependency. Let me show you the dependency graph for https://github.com/Jasig/cas-overlay-template:

```
$ mvn dependency:tree                                                                                                                                                                            java-1.7.0_80
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building cas-overlay 1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ cas-overlay ---
[INFO] org.jasig.cas:cas-overlay:war:1.0
[INFO] \- org.jasig.cas:cas-server-webapp:war:4.1.5:runtime
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.635 s
[INFO] Finished at: 2016-03-07T08:36:07+01:00
[INFO] Final Memory: 12M/245M
[INFO] ------------------------------------------------------------------------
```

Looking at `https://github.com/scalding/gradle-waroverlay-plugin` gradle has a bit smarter plugins that allow you to specify `transitive = true`:

```
dependencies {
    runtime("org.jasig.cas:cas-server-webapp:3.5.2@war") {
        transitive = true // setting this to true calculates transitive dependencies for addition to the target WAR
    }
}
```
---
However since I was searching for this information I came across [this repository](https://github.com/srstclair/war-deps) which seems to have a way to make it work with maven as well, adding another dependency for the war with type `pom`. 

```
cas-overlay-template 2w master / mvn dependency:tree                                                                                                                                                                            java-1.7.0_80
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building cas-overlay 1.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ cas-overlay ---
[INFO] org.jasig.cas:cas-overlay:war:1.0
[INFO] +- org.jasig.cas:cas-server-webapp:pom:4.1.5:compile
[INFO] |  +- org.jasig.cas:cas-server-webapp-support:jar:4.1.5:compile
[INFO] |  |  +- org.jasig.inspektr:inspektr-support-spring:jar:1.3.GA:runtime
[INFO] |  |  |  +- org.jasig.inspektr:inspektr-audit:jar:1.3.GA:compile
[INFO] |  |  |  +- org.jasig.inspektr:inspektr-error:jar:1.3.GA:runtime
[INFO] |  |  |  +- org.jasig.inspektr:inspektr-common:jar:1.3.GA:compile
[INFO] |  |  |  +- org.springframework:spring-web:jar:4.1.6.RELEASE:compile
[INFO] |  |  |  +- org.springframework:spring-webmvc:jar:4.1.6.RELEASE:compile
[INFO] |  |  |  +- org.springframework:spring-tx:jar:4.1.6.RELEASE:compile
[INFO] |  |  |  \- org.springframework:spring-jdbc:jar:4.1.6.RELEASE:compile
[INFO] |  |  +- org.springframework.security:spring-security-core:jar:4.0.1.RELEASE:compile
[INFO] |  |  |  +- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |  |  \- org.springframework:spring-context:jar:4.1.6.RELEASE:compile
[INFO] |  |  +- org.springframework.security:spring-security-web:jar:4.0.1.RELEASE:compile
[INFO] |  |  +- org.springframework.security:spring-security-config:jar:4.0.1.RELEASE:runtime
[INFO] |  |  +- org.springframework:spring-aop:jar:4.1.8.RELEASE:compile
[INFO] |  |  +- org.jasig.cas:cas-server-core:jar:4.1.5:compile
[INFO] |  |  |  +- org.jasig.cas:cas-server-core-api:jar:4.1.5:compile
[INFO] |  |  |  +- org.jasig.service.persondir:person-directory-impl:jar:1.7.0:compile
[INFO] |  |  |  |  +- org.ldaptive:ldaptive:jar:1.0.6:compile
[INFO] |  |  |  |  +- com.sun.xml.bind:jaxb-impl:jar:2.2.7:compile
[INFO] |  |  |  |  |  +- com.sun.xml.bind:jaxb-core:jar:2.2.7:compile
[INFO] |  |  |  |  |  |  +- javax.xml.bind:jaxb-api:jar:2.2.7:compile
[INFO] |  |  |  |  |  |  \- com.sun.istack:istack-commons-runtime:jar:2.16:compile
[INFO] |  |  |  |  |  \- com.sun.xml.fastinfoset:FastInfoset:jar:1.2.12:compile
[INFO] |  |  |  |  |     \- javax.xml.bind:jsr173_api:jar:1.0:compile
[INFO] |  |  |  |  \- org.jasig.service.persondir:person-directory-api:jar:1.7.0:compile
[INFO] |  |  |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  |  |  +- org.apache.commons:commons-lang3:jar:3.4:compile
[INFO] |  |  |  +- org.springframework:spring-orm:jar:4.1.8.RELEASE:compile
[INFO] |  |  |  +- org.hibernate:hibernate-core:jar:4.3.10.Final:compile
[INFO] |  |  |  |  +- org.jboss.logging:jboss-logging:jar:3.1.3.GA:compile
[INFO] |  |  |  |  +- org.jboss.spec.javax.transaction:jboss-transaction-api_1.2_spec:jar:1.0.0.Final:compile
[INFO] |  |  |  |  +- dom4j:dom4j:jar:1.6.1:compile
[INFO] |  |  |  |  |  \- xml-apis:xml-apis:jar:1.0.b2:compile
[INFO] |  |  |  |  +- org.hibernate.common:hibernate-commons-annotations:jar:4.0.5.Final:compile
[INFO] |  |  |  |  +- org.hibernate.javax.persistence:hibernate-jpa-2.1-api:jar:1.0.0.Final:compile
[INFO] |  |  |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  |  |  \- org.jboss:jandex:jar:1.1.0.Final:compile
[INFO] |  |  |  +- org.springframework.webflow:spring-webflow:jar:2.4.1.RELEASE:compile
[INFO] |  |  |  |  +- opensymphony:ognl:jar:2.6.11:compile
[INFO] |  |  |  |  +- org.springframework.webflow:spring-binding:jar:2.4.1.RELEASE:compile
[INFO] |  |  |  |  \- org.springframework.webflow:spring-js:jar:2.4.1.RELEASE:compile
[INFO] |  |  |  |     \- org.springframework.webflow:spring-js-resources:jar:2.4.1.RELEASE:compile
[INFO] |  |  |  +- commons-jexl:commons-jexl:jar:1.1:runtime
[INFO] |  |  |  +- commons-io:commons-io:jar:2.4:compile
[INFO] |  |  |  +- joda-time:joda-time:jar:2.8.1:compile
[INFO] |  |  |  +- org.reflections:reflections:jar:0.9.10:compile
[INFO] |  |  |  |  +- org.javassist:javassist:jar:3.19.0-GA:compile
[INFO] |  |  |  |  \- com.google.code.findbugs:annotations:jar:2.0.1:compile
[INFO] |  |  |  +- org.apache.httpcomponents:httpclient:jar:4.4.1:compile
[INFO] |  |  |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.1:compile
[INFO] |  |  |  +- javax.cache:cache-api:jar:1.0.0:compile
[INFO] |  |  |  +- org.jsr107.ri:cache-ri-impl:jar:1.0.0:runtime
[INFO] |  |  |  |  \- javax.enterprise:cdi-api:jar:1.0-SP4:runtime
[INFO] |  |  |  |     +- org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.1_spec:jar:1.0.0.Beta1:runtime
[INFO] |  |  |  |     +- javax.annotation:jsr250-api:jar:1.0:runtime
[INFO] |  |  |  |     \- javax.inject:javax.inject:jar:1:runtime
[INFO] |  |  |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  |  |  +- org.bitbucket.b_c:jose4j:jar:0.4.1:compile
[INFO] |  |  |  \- org.apache.commons:commons-collections4:jar:4.0:compile
[INFO] |  |  +- org.jasig.cas:cas-server-support-generic:jar:4.1.5:runtime
[INFO] |  |  +- org.springframework:spring-context-support:jar:4.1.8.RELEASE:compile
[INFO] |  |  +- org.hibernate:hibernate-validator:jar:5.1.3.Final:runtime
[INFO] |  |  |  \- com.fasterxml:classmate:jar:1.0.0:runtime
[INFO] |  |  +- org.codehaus.woodstox:woodstox-core-asl:jar:4.4.1:runtime
[INFO] |  |  |  +- javax.xml.stream:stax-api:jar:1.0-2:runtime
[INFO] |  |  |  \- org.codehaus.woodstox:stax2-api:jar:3.1.4:runtime
[INFO] |  |  +- org.quartz-scheduler:quartz:jar:2.2.1:compile
[INFO] |  |  +- org.jasig:spring-webflow-client-repo:jar:1.0.0:runtime
[INFO] |  |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.7:runtime
[INFO] |  |  |  +- log4j:log4j:jar:1.2.17:runtime
[INFO] |  |  |  \- org.cryptacular:cryptacular:jar:1.0:runtime
[INFO] |  |  |     \- org.bouncycastle:bcprov-jdk15on:jar:1.50:runtime
[INFO] |  |  +- com.sun.jersey:jersey-core:jar:1.19:compile
[INFO] |  |  |  \- javax.ws.rs:jsr311-api:jar:1.1.1:compile
[INFO] |  |  +- com.sun.jersey:jersey-server:jar:1.19:compile
[INFO] |  |  +- com.sun.jersey:jersey-servlet:jar:1.19:compile
[INFO] |  |  +- com.sun.jersey.contribs:jersey-spring:jar:1.19:runtime
[INFO] |  |  \- org.apache.logging.log4j:log4j-web:jar:2.3:runtime
[INFO] |  +- org.springframework:spring-expression:jar:4.1.8.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-core:jar:4.1.8.RELEASE:compile
[INFO] |  +- javax.servlet:jstl:jar:1.2:runtime
[INFO] |  +- taglibs:standard:jar:1.1.2:runtime
[INFO] |  +- org.jasig.cas:cas-server-security-filter:jar:2.0.4:runtime
[INFO] |  +- com.ryantenney.metrics:metrics-spring:jar:3.1.0:runtime
[INFO] |  |  +- io.dropwizard.metrics:metrics-core:jar:3.1.2:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-healthchecks:jar:3.1.2:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-annotation:jar:3.1.2:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:4.1.6.RELEASE:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jvm:jar:3.1.2:compile
[INFO] |  +- io.dropwizard.metrics:metrics-servlets:jar:3.1.2:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-json:jar:3.1.2:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.4.2:compile
[INFO] |  |     +- com.fasterxml.jackson.core:jackson-annotations:jar:2.4.0:compile
[INFO] |  |     \- com.fasterxml.jackson.core:jackson-core:jar:2.4.2:compile
[INFO] |  +- org.aspectj:aspectjrt:jar:1.8.6:compile
[INFO] |  +- org.aspectj:aspectjweaver:jar:1.8.6:compile
[INFO] |  +- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  +- org.glassfish.web:javax.el:jar:2.2.6:runtime
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.12:compile
[INFO] |  +- org.slf4j:jul-to-slf4j:jar:1.7.12:runtime
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.3:runtime
[INFO] |  +- org.apache.logging.log4j:log4j-core:jar:2.3:runtime
[INFO] |  +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.3:runtime
[INFO] |  +- org.apache.logging.log4j:log4j-jcl:jar:2.3:runtime
[INFO] |  |  \- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  \- org.jasig.inspektr:inspektr-aspects:jar:1.3.GA:compile
[INFO] \- org.jasig.cas:cas-server-webapp:war:4.1.5:runtime
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.208 s
[INFO] Finished at: 2016-03-07T09:00:25+01:00
[INFO] Final Memory: 17M/310M
[INFO] ------------------------------------------------------------------------
```

That makes it a whole lot better, **however** not quite the same as with a with a BOM declaring a dependencyManagement section, since that would take preference over which libraries are actually preferred (i.e. those that are in the war overlay).

**Comment by mmoayyed** [comment]
Right. So a number of options/notes:

1. A BOM is purely a maven thing right? Since we are on gradle, I imagine there may be a way to have gradle generate a BPM for us. Otherwise, as much as I hate to say it, I don't think it's worth the effort, because of the next point. 
2. While you are able to declare a pom dependency on the war, you can also exclude dependencies directly from WAR in your overlay. This is similar to the transitive flag that gradle provides. Something like this might work?

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <warName>cas</warName>
                    <packagingExcludes>WEB-INF/lib/stax-api-1.0-2.jar</packagingExcludes>
                    <overlays>
                        <overlay>
                            <groupId>org.jasig.cas</groupId>
                            <artifactId>cas-server-webapp</artifactId>
                            <excludes>
                                <exclude>WEB-INF/cas.properties</exclude>
                                <exclude>WEB-INF/login-webflow.xml</exclude>
                                <exclude>WEB-INF/classes/log4j.xml</exclude>
                            </excludes>
                        </overlay>
                    </overlays>
                </configuration>
            </plugin>
```

It's still not very pretty, but per our example, you can go ahead and start excluding JARs that come from the final war directly.

I would also that if you look at the project root here, you'll see a parent build.gradle pom that effectively has all dependencies listed and then they are declared individually where needed. Similar maven behavior when it comes to dependency management, etc. I wonder if we could "release" the parent, and then you'd have a pom with nothing in but dependencies?

**Comment by dima767** [comment]
My 2c. - doesn't matter if CAS itself uses Gradle. I think that providing a
'module' with a carefully crafted Maven BOM (just a pom.xml with harmonized
dependencies) would be beneficial for folks to make the dependencies mess
in their war overlays manageable

**Comment by aukevanleeuwen** [comment]
Ad 1) I think it is mainly a maven thing, although I read that Gradle can benefit from it as well (https://spring.io/blog/2015/02/23/better-dependency-management-for-gradle)

Ad 2) Apparently I'm still not able to provide you with the information to transfer my point exactly. That might very well be my own fault btw :-P But I'll take another shot:

Given these hypothetical project dependencies:
```
org.jasig.cas:cas-overlay:war:1.0
+- org.jasig.cas:cas-server-webapp:pom:4.1.5:compile (the pom dependency)
|  \- org.springframework:spring-expression:jar:4.0.0
|     \- org.springframework:spring-core:jar:4.0.0
\- org.springframework:spring-retry:1.0.0
   \- org.springframework:spring-core:jar:5.0.0
```

To be clear: in this case my `pom.xml` would **only** declare: `org.jasig.cas:cas-server-webapp:pom:4.1.5` and `org.springframework:spring-retry:1.0.0`, the transitive dependencies are not explicitly in the `pom.xml`.

The resolution for the transitive `org.springframework:spring-core` dependency will actually be version `5.0.0`, [because it has the shortest path to the root](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html). That means that if this project would be build without an overlay the following jars would end up in `WEB-INF/lib` of the `war` file:

* spring-expression-4.0.0.jar
* spring-retry-1.0.0.jar
* spring-core-5.0.0.jar

But it becomes interesting if the maven war plugin with an overlay is configured. This plugin simply works on file level (as you can also see by the way you can exclude files from the war overlay: _by filename_, not by artifact). If the overlay would be applied one would end up with the following files `WEB-INF/lib`:
* spring-expression-4.0.0.jar
* spring-retry-1.0.0.jar
* spring-core-5.0.0.jar
* spring-core-4.0.0.jar

Now my assumption when working with an overlay is that you ideally would like to follow the libraries of the 'main product', CAS in this case. CAS libraries are leading and you should follow suit if at all possible. There are a couple of way you can resolve this problem with multipe versions of the same war ending up in `WEB-INF/lib`:

1. Exclude the files from the war overlay (as you were doing), but this is not ideal as I said before you want to follow the libraries of the main product.
2. You make explicit excludes for `spring-core-5.0.0.jar` when specifying the `spring-retry-1.0.0.jar` dependency. Possible, but this becomes very tedious. And you may have to exclude `spring-core` a dozen times.
3. You can add `spring-core-4.0.0.jar` as a top level dependency. It will then have the shortest path and always win.
4. You can specify a dependency in the `<dependencyManagement />` section of your `pom.xml` because that will overrule the versions of any transitive dependencies.

So version (3) and (4) are almost identical in what they will achieve, they will make sure that the correct version is used, however version (4) is preferred (by me) for the following reasons:

1. Semantically: if you are specifying it directly (as in (3)) you are basically also saying the code that I wrote **directly** depends on it. Maybe you can argue about these semantics.
2. Within the `<dependencyManagement />` section you can specify a single **import** of a dependency of type `pom`, which will then add any dependencies inside the dependencyManagement section of _that_ pom into your own pom. This would be a 'Bill of Materials' (BOM). 

So my idea (with this ticket) would for CAS to provide a BOM that I can directly use into my own `<dependencyManagement />` section and never worry about duplicate jars ending up in my overlayed war file.

I hope this is more clear than before :-) and I'll let you see what you do with this information.

**Comment by dima767** [comment]
It's clear to me. With the "harmonized" dependencies published by CAS' bom
module, managing dependencies in deployer's overlays will become a "sane"
activity :-) BTW, Spring IO platform provides a BOM for all its "blessed"
deps just for the same reason

**Comment by dima767** [comment]
The idea would be to prototype the BOM and collab on it here:
https://github.com/UniconLabs/cas-bom see how it works out and then move it
to CAS core
