### ISSUE TITLE
Updating Service Registry name does not remove old json file

### ISSUE THREAD

**Issue by tsschmi** [apereo/cas#1631]
I have been testing some things with the Manage Services functionality with the cas-management webapp on the 4.2.x branch.  If we change the name of an existing service, a new JSON file is written using the new name.  The old file with the old file is still present and the Manage Services table does not reflect the new name of the service.

Looking at logs when services are reloaded there is entries that show that the new files are ignored because the url matches the url of old file.

So I am thinking the old file should be removed when a service name changes, or if detecting that is difficult, perhaps not allow a rename when editing a service

Travis

**Comment by mmoayyed** [comment]
Probably should disallow.
