### ISSUE TITLE
Services Management Webapp can not add custom properties and clears properties on edit

### ISSUE THREAD

**Issue by tsschmi** [apereo/cas#1663]
CAS Services Management web application in the current 4.2.0 release does not have fields in the services-form.jsp to show and edit custom properties of a Service Registry.  A negative side effect is that if custom properties are added to a json file manually, those properties are removed by the application if the service is edited and changes are saved.

**Comment by mmoayyed** [comment]
Yes, this is a known issue. I am working on this with @mindblender . Hopefully we can fix this under 4.2.1. There are a bunch of other settings missing from the webapp that we might also add.

**Comment by mmoayyed** [comment]
We are making some changes to the app in 5 to support properties, mfa and more. Once that happens, we can backport changes to 4 to take care of this issue via supporting properties.
