### ISSUE TITLE
Consider removing aspectJ compilation from the build

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#1677]
In today's CAS, aspectJ is mostly used to weave in an external aspect that deals with TRACE-level logs. Not much else. I am wondering if that is simply extra overhead we could remove simply because the instances where we have had to use TRACE logs have been too rare and few. I am open to other alternatives to handle TRACE logs, but I don't think for today, this is an optimal solution.

**Comment by dima767** [comment]
+1 for removing

**Comment by frett** [comment]
I believe AspectJ is also used for inspektr and JPA transaction wiring. I don't think they would require compile time weaving, but they still require some type of AOP support to work.

**Comment by dima767** [comment]
Sure thing. It's just the proposal to lift the compile time weaving requirement from CAS codebase itself, by removing those log aspects.

**Comment by mmoayyed** [comment]
I am sort of debating this internally. On the one hand, I'd love to provide the same kind of functionality without having to deal with aspectj kicked into the build. On the other hand, brief research tells me that this sort of thing is not possible without aspects. I do think there is value in being able to provide TRACE level logs that, if needed, would show input/output parameters of CAS pieces. 

The aspectj compilation is somewhat optional, that you can turn off during local build and dev. It is only turned on during an official CAS release. So, it should not get in the away of contributor workflows.

**Comment by dima767** [comment]
Just a quick question - have you seen this trace level log aspects usage in the wild anywhere?

**Comment by mmoayyed** [comment]
I have used it a couple of times troubleshooting some very hairy and bizarre issues that dealt with bean instantiation and proxies. It was useful to see exactly what the method received and what it produced. I admit, its usage has been rare but it is extremely helpful when you have no other option, can't reproduce the issue and can't debug the code.

**Comment by mmoayyed** [comment]
Pushing this to future for now. Needs further investigation.

**Comment by mmoayyed** [comment]
Examined this some more. The pros outweigh the benefits. We no longer need this functionality for build-time weaving of all components. It makes debugging a lot more difficult, and slows the build down quite significantly. Going to remove unless there are objections.

**Comment by dima767** [comment]
+1

**Comment by mmoayyed** [comment]
This is done
