### ISSUE TITLE
Consider HTTP 500 on un-recoverable errors

### ISSUE THREAD

**Issue by dima767** [apereo/cas#1680]
Currently, in the `master`, the login flow transitions to the fresh login view state on any unrecoverable errors during authentication process: https://github.com/Jasig/cas/blob/master/cas-server-webapp/src/main/webapp/WEB-INF/webflow/login/login-webflow.xml#L97

This could become very confusing to end users during any miscellaneous, unrecoverable errors (other than authentication errors covered by authentication error handler) i.e. no UI messages presented and fresh login screen is just repainted. Consider changing this behavior to propagate the un-handled exceptions up the stack resulting in HTTP 500 and painting a pretty 500.html explaining that something catastrophic happened (of course also logging the exception in the logs)

**Comment by mmoayyed** [comment]
@dima767 shall we push this back to M2?

**Comment by dima767** [comment]
Yes sure. And I don't have currently anything specific on my mind as far as implementation (hence the tag `Discussion`)

**Comment by mmoayyed** [comment]
This is done
