### ISSUE TITLE
Use @Conditional bean definitions

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#1702]
Presently, adopters are required to alias bean definitions when declaring a module to turn on a CAS feature. While this works fine, long-term we should start to move towards Conditional bean definitions and leverage the actuator/starter pattern with modules, such that when you declare a module to turn on a feature, ALL bean declarations and XML configuration must be accounted for and provided automatically without the need for aliasing and that needs happen conditionally to allow the adopter the chance to override the bean definition if need be in their own configuration.

This sort of change hints at two possible changes in the core codebase:
- It is likely that we might have to break modules further apart to make this easier.
- We do have to take into account the possibility of defining multiple bean definitions. If I declare the LDAP module, the automatic configuration must take into account the fact that I might want to have more than 1 LDAP authN handler, etc

**Comment by mmoayyed** [comment]
Marking this for 5.1 now, but we might get to it sooner.

**Comment by dima767** [comment]
Yes, this sort of autoconfig bootiful architecture is a must. I think we need to start with smaller modules to test the waters to see how it might work, etc.

**Comment by mmoayyed** [comment]
Staring with this item. Planning to get it ready before M3. This is a big one.

**Comment by dima767** [comment]
+1 And remember - not everything is a "nail" when we possess the "hammer" :-)

**Comment by mmoayyed** [comment]
Handled via https://github.com/apereo/cas/pull/1834 See docs and new settings/properties for more info please.
