### ISSUE TITLE
Remove Javadocs from Github Pages

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#1713]
The javadoc.io service provides us with the ability to present javadocs to deployers directly from Maven Central, which means that our build/publishing tools must be equipped to produce javadocs for all modules, including the root that aggregates everything. This helps us to:

1. Reduce the size of the repo by removing all published javadocs and simply pointing folks to the new links
2. Faster builds, since we no longer have to publish javadocs on every commit.

**Comment by mmoayyed** [comment]
Clarification: Javadocs are today already published for every individual module. They are not however published for the cas-server root project that is an aggregated view of all javadocs for all modules. This issue addresses the need to publish an aggregated report to central, so that we can leverage the javadoc.io service easily without having to host the docs separately under the gh-pages branch. 

Nothing else changes.

**Comment by leleuj** [comment]
Yes, javadoc.io already exposes the javadocs of all projects available in the Maven central repository. But no aggregated javadocs, that's why for pac4j for example, I publish them separately.

**Comment by mmoayyed** [comment]
I have prepared the build to build the aggregate and publish it to central. Once we publish and release 5, I plan to explore this further and then possibly start removing javadocs from the gh-pages branch

**Comment by mmoayyed** [comment]
http://www.javadoc.io/doc/org.apereo.cas/cas-server/
