### ISSUE TITLE
JPA Ticket Registry: TransactionRequiredException: no transaction is in progress

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#1717]
Apparent in master only, the JPA Ticket Registry seems to be missing configuration that would enable transactions for some ops, reported by @frett 

This was discovered during the testing of a recent pull request, so I am tracking it here as a separate issue. Passing this onto Daniel for now.

**Comment by dima767** [comment]
As M1 release date is nearing (next week), we could move this to M2 which is currently scheduled for May-30 2016

**Comment by frett** [comment]
I really need to find some time in my schedule to do some work on this and a couple other outstanding issues for 5.0

**Comment by frett** [comment]
Also, I can't assign this to myself, I'm guessing my permissions didn't get added to the Apereo organization yet. @mmoayyed

**Comment by dima767** [comment]
I moved it to M2 for now

**Comment by mmoayyed** [comment]
@frett I re-sent the invitation. Let me know if you don't see it.

**Comment by frett** [comment]
@mmoayyed got it this time, maybe it was lost in my spam folder

**Comment by mmoayyed** [comment]
Great!

**Comment by waronlive** [comment]
thanks im just now trying clean up my PC from bugs and various

**Comment by mmoayyed** [comment]
@frett think we could address this one by May 20th?

**Comment by frett** [comment]
I spent a couple hours on it tonight, having an issue getting CAS to even initialize the JPA ticket registry right now, I get the following error just enabling JPA on the current master branch:
```
2016-05-13 00:12:41,714 WARN [org.springframework.beans.factory.support.DefaultListableBeanFactory] - <Bean creation exception on non-lazy FactoryBean type check: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ticketEntityManagerFactory' defined in BeanDefinition defined in class path resource [org/apereo/cas/config/JpaTicketRegistryConfiguration.class]: Initialization of bean failed; nested exception is java.lang.IllegalStateException: Cannot create scoped proxy for bean 'scopedTarget.ticketEntityManagerFactory': Target type could not be determined at the time of proxy creation.>
```
I'm guessing it's something to do with the new `@RefreshScope`, I tried disabling the annotation for `ticketEntityManagerFactory` and that led to an `NullPointerException` somewhere in the middle of an AOP call stack for `CentralAuthenticationService.createTicketGrantingTicket()`. Guessing this is because the `ticketEntityManagerFactory` was no longer getting created/injected into the other objects.

I have no experience with `@RefreshScope` yet, so any insight you have or quick fixes you have for the scope issue would be appreciated, if not I'll continue googling for a solution.

**Comment by dima767** [comment]
OK, I've spent the most of yesterday, working on another issue (improvement) related to JPA and bumped into these refresh scope lazy shinannagans. Was traveling in the dark corners of this wonderful "boot black box", etc. Had to update spring cloud to the latest 1.1.0 among other things. It's a work in progress and I might have a PR some time next week (not sure if it'll make M1). 

Anyway, for now I'll suggest you just get rid of @RefreshScope fro entity manager factory bean. And we want to be careful in the future - we just don't want to slap these magical, wonderful, black box annotations on EVERY possible component :-)

D.

**Comment by mmoayyed** [comment]
I am seeing similar issues with the JPA svc registry. Once I run through that and get it fixed, I'll probably apply the same sort of idea to the ticket registry.

**Comment by mmoayyed** [comment]
So registry is coming up now:

```
Hibernate: alter table SERVICETICKET drop constraint FK60oigifivx01ts3n8vboyqs38
Hibernate: alter table TICKETGRANTINGTICKET drop constraint FKiqyu3qw2fxf5qaqin02mox8r4
Hibernate: drop table locks if exists
Hibernate: drop table SERVICETICKET if exists
Hibernate: drop table TICKETGRANTINGTICKET if exists
Hibernate: create table locks (application_id varchar(255) not null, expiration_date varbinary(255), unique_id varchar(255), primary key (application_id))
Hibernate: create table SERVICETICKET (TYPE varchar(31) not null, ID varchar(255) not null, NUMBER_OF_TIMES_USED integer, CREATION_TIME varbinary(255), EXPIRATION_POLICY blob(2147483647) not null, LAST_TIME_USED varbinary(255), PREVIOUS_LAST_TIME_USED varbinary(255), FROM_NEW_LOGIN boolean not null, TICKET_ALREADY_GRANTED boolean not null, SERVICE blob(2147483647) not null, ticketGrantingTicket_ID varchar(255), primary key (ID))
Hibernate: create table TICKETGRANTINGTICKET (TYPE varchar(31) not null, ID varchar(255) not null, NUMBER_OF_TIMES_USED integer, CREATION_TIME varbinary(255), EXPIRATION_POLICY blob(2147483647) not null, LAST_TIME_USED varbinary(255), PREVIOUS_LAST_TIME_USED varbinary(255), AUTHENTICATION blob(2147483647) not null, EXPIRED boolean not null, PROXIED_BY blob(2147483647), SERVICES_GRANTED_ACCESS_TO blob(2147483647) not null, ticketGrantingTicket_ID varchar(255), primary key (ID))
Hibernate: alter table SERVICETICKET add constraint FK60oigifivx01ts3n8vboyqs38 foreign key (ticketGrantingTicket_ID) references TICKETGRANTINGTICKET
Hibernate: alter table TICKETGRANTINGTICKET add constraint FKiqyu3qw2fxf5qaqin02mox8r4 foreign key (ticketGrantingTicket_ID) references TICKETGRANTINGTICKET
```

but I am seeing a host of other issues. I'll post a PR with the changes so far, and then possibly @frett can take over? Sound good?

**Comment by dima767** [comment]
Just before going crazy on the svc registry - there is a PR: https://github.com/apereo/cas/pull/1771 that I just submitted. Among other things it took care of that RefreshScope and eager vs lazy bean instantiation mode - updated to the spring cloud 1.1.10 where the eager mode for refresh scope is the default

**Comment by mmoayyed** [comment]
So @frett 

Pull down this branch:
https://github.com/apereo/cas/tree/empty-svc-reg

Change the application.properties file to:

```
ticketreg.database.ddl.auto=create-drop
ticketreg.database.dialect=org.hibernate.dialect.HSQLDialect
ticketreg.database.batchSize=10
ticketreg.database.driverClass=org.hsqldb.jdbcDriver
ticketreg.database.url=jdbc:hsqldb:mem:cas-ticket-registry
ticketreg.database.user=sa
ticketreg.database.password=
ticketreg.database.pool.maxSize=18
ticketreg.database.pool.maxWait=10000
ticketreg.database.pool.maxIdleTime=120
ticketreg.database.jpa.locking.tgt.enabled=true

...

ticketRegistry=jpaTicketRegistry
```


Change the webapp's build.gradle file to include:

```
    compile project(':cas-server-support-jpa-ticket-registry')
    
    compile("org.hsqldb:hsqldb:$hsqlVersion")
```

This should get you started fairly easily.

**Comment by mmoayyed** [comment]
What I am seeing right now are issues that deal with:

```
Caused by: java.sql.BatchUpdateException: integrity constraint violation: unique constraint or index violation; SYS_PK_10120 table: TICKETGRANTINGTICKET
        at org.hsqldb.jdbc.JDBCPreparedStatement.executeBatch(Unknown Source) ~[hsqldb-2.3.3.jar:2.3.3]
        at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-2.4.6.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-2.4.6.jar:?]
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.performExecution(BatchingBatch.java:110) ~[hibernate-core-5.1.0.Final.jar:5.1.0.Final]
        at org.hibernate.engine.jdbc.batch.internal.BatchingBatch.doExecuteBatch(BatchingBatch.java:97) ~[hibernate-core-5.1.0.Final.jar:5.1.0.Final]
        at org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl.execute(AbstractBatchImpl.java:147) ~[hibernate-core-5.1.0.Final.jar:5.1.0.Final]
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:214) ~[hibernate-core-5.1.0.Final.jar:5.1.0.Final]
```

or attempting to issue STs are failed because some transaction is silently rolled back.

**Comment by frett** [comment]
Yeah, that's what I was seeing when we pulled out the delegators. I'll try and dive back in later this evening

**Comment by mmoayyed** [comment]
Cool. I should be around this evening if you need my help. Ping me on gitter or Google and we can troubleshoot this together if you'd like.

**Comment by frett** [comment]
I fixed a couple more JPA issues and pushed the changes to the `empty-svc-reg` branch.

I know the ticket cleaner is still broke for JPA. it makes internal calls to `deleteTicket()`, which bypasses any AOP proxies, including the transaction support. We may need to separate the TicketCleaner from the `TicketRegistry` class to force calls to go through normal Spring bean wiring which would add the AOP proxies on.

**Comment by dima767** [comment]
Yes, the direct calls on the impl bypasses AOP proxies and the entire spring tx mgmt facilities. We definitely need to redisegn this cleaner business.

**Comment by mmoayyed** [comment]
Tested. Looks good so far. Going to merge in.
