### ISSUE TITLE
Do not destroy STs when TGT Expires

### ISSUE THREAD

**Issue by tsschmi** [apereo/cas#1761]
As a measure to protect our CAS server from looping or from misconfigured clients that request an ST for every static resource, we are looking into setting a TGT expiration policy that would expire after a set use count.  Our thinking was that CAS would just display the login screen on the next request for an ST after the TGT expired, but what we saw is that the /serviceValidate for the ST we just issued fails, because it is removed from the registry as soon as it is issued with the last valid use of the TGT.  We tracked this down to two places in the code. First is in HazelcastTicketRegistry in deleteTicket() -

` if (ticket instanceof TicketGrantingTicket) {
            logger.debug("Removing ticket [{}] and its children from the registry.", ticket);
            deleteChildren((TicketGrantingTicket) ticket);
  }`

deleteChildren() removes all STs from the registry issued by the TGT being deleted.

The second place is the isExpired() method of AbstractTicket  

` @Override
    public final boolean isExpired() {
        final TicketGrantingTicket tgt = getGrantingTicket();
        return this.expirationPolicy.isExpired(this)
                || (tgt != null && tgt.isExpired())
                || isExpiredInternal();
    }`

This is called during /serviceValidate of an ST and results in INVALID_TICKET response because it is considered expired since the TGT that issued it has expired. 

We get the behavior we wanted if we allow the ST to expire according to its set policy.  Are there reasons for, or concerns that STs need to be removed at the same time TGTs expire?

**Comment by mmoayyed** [comment]
STs always are linked to TGTs. Without a TGT, all STs are automatically invalidated. They should be removed.

**Comment by mmoayyed** [comment]
PS An expiration policy is not the appropriate fix for this. You really need to fix the misconfigured client(s).

**Comment by tsschmi** [comment]
I absolutely agree that clients need to be fixed, but those clients are not under our direct control.  We have plans to reach out and try to get them to play nice with us, but incidents are happening frequently enough that we need to take some action to protect our server and the critical services that rely on it.

**Comment by mmoayyed** [comment]
Sounds like you might need `ThrottledUseAndTimeoutExpirationPolicy`:
http://apereo.github.io/cas/4.2.x/installation/Configuring-Ticket-Expiration-Policy.html

The description of that policy matches your case, word for word, I think :) 

Getting it to work with HZ might be challenging; don't think it's possible at the moment given how timeouts are wired in.
