### ISSUE TITLE
The locale setting from web browser is not works

### ISSUE THREAD

**Issue by yisiqi** [apereo/cas#1768]
In the latest 5.0.0 snapshot version, all views can not recognize user's local language environment.
I traced this issue, found it's caused by `CasWebAppConfiguration`.  There is a default locale setting for `CookieLocaleResolver` in this class. But it will block `CookieLocaleResolver` from getting Locale settings from user's Request. And here is the souce code :

```java
From: spring-webmvc-4.2.6.RELEASE.jar
org.springframework.web.servlet.i18n.CookieLocaleResolver
...
	/**
	 * Determine the default locale for the given request,
	 * Called if no locale cookie has been found.
	 * <p>The default implementation returns the specified default locale,
	 * if any, else falls back to the request's accept-header locale.
	 * @param request the request to resolve the locale for
	 * @return the default locale (never {@code null})
	 * @see #setDefaultLocale
	 * @see javax.servlet.http.HttpServletRequest#getLocale()
	 */
	protected Locale determineDefaultLocale(HttpServletRequest request) {
		Locale defaultLocale = getDefaultLocale();
		if (defaultLocale == null) {
			defaultLocale = request.getLocale();
		}
		return defaultLocale;
	}
...
```

**Comment by yisiqi** [comment]
@mmoayyed Could we just remove this default locale setting?
Or I can provide a new `CasCookieLocaleResolver` to override the `determineDefaultLocale` method?

**Comment by mmoayyed** [comment]
I'll take a look. Hang tight.

**Comment by mmoayyed** [comment]
Cant duplicate. locale=XYZ works fine.

**Comment by yisiqi** [comment]
Query param works fine. But http header(Accept-language) dose NOT. @mmoayyed

**Comment by mmoayyed** [comment]
It doesn't because u r using the wrong component. u need this:
http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/i18n/AcceptHeaderLocaleResolver.html

**Comment by mmoayyed** [comment]
If you want to submit a PR that adds support for accept-header based on that resolver, that is perfectly fine. Happy to reconsider.

**Comment by yisiqi** [comment]
I just read the source code of  `AcceptHeaderLocaleResolver`. It's short and simple. I don't think it can be used.

``` java
public class AcceptHeaderLocaleResolver implements LocaleResolver {

	@Override
	public Locale resolveLocale(HttpServletRequest request) {
		return request.getLocale();
	}

	@Override
	public void setLocale(HttpServletRequest request, HttpServletResponse response, Locale locale) {
		throw new UnsupportedOperationException(
				"Cannot change HTTP accept header - use a different locale resolution strategy");
	}

}
```

We need cookie to storage user's language preference. And if user didn't specified some language, we need to get from his system environment. To make all that happens together, not some signle requires, we need `CookieLocaleResolver` without default locale.

If we removed the default locale setting for `CookieLocaleResolver`:
1. If user's browser support accept-language header, the cas-server will response page with user's default language.
2. If user's browser does NOT support this header, the cas-server will response page with server's default message bundle (which is en_US).
3. If user specified a language, the cas-server will response with user's order.

I think that will be a kind of prefect solution. Please reconsider.

**Comment by mmoayyed** [comment]
> 1. If user's browser support accept-language header, the cas-server will response page with user's default language.

This is the use case the CookieLocaleResolver attempts to handle, as well as the AcceptHeaderLocaleResolver. This is already done for you.  request.getLocale() should take care of this for you. Revisit the javadocs

> 2. If user's browser does NOT support this header, the cas-server will response page with server's default message bundle (which is en_US).

CookieLocaleResolver can be modified to specify a default locale. You can set it to en. 

> 3. If user specified a language, the cas-server will response with user's order.

This can both be done via a locale parameter or a header.

If you are unable to get any of these working as I described that would be then a bug we can reconsider. 

I guess I don't really see where you are coming from. If you wish you store the final outcome of resolvers into a cookie in order to remember the user's settings, fine, sure. But at this point, that would need to be an extension for your deployment. What do you need from CAS to make that extension possible for you, is the question.

**Comment by mmoayyed** [comment]
If you however wish to get the default locale form the system environment, rather than some pre-defined locale set statically, we might be able to do so. Is that what you're after?

**Comment by mmoayyed** [comment]
Something like this:

```
@Bean(name = "localeResolver")
    public CookieLocaleResolver localeResolver() {
        final CookieLocaleResolver resolver = new CookieLocaleResolver() {
            @Override
            protected Locale getDefaultLocale() {
                return Locale.getDefault();
            }
        };
        return resolver;
    }
```

Of course, this needs to be optional. Not all deployments would want to fall back onto system locale.

**Comment by yisiqi** [comment]
I mean cas-sever should NOT specify a default locale for `CookieLocaleResolver`. because:
1. Once the user's browser support `accept-language` header, they will give cas-server a locale. But if we specify a default locale for `CookieLocaleResolver`, the `accept-language` header will no longer works.
2. Once the user's browser do NOT support  accept-language header, the `CookieLocaleResolver` still figure out a locale.

The default locale for `CookieLocaleResolver` is totally NOT necessary, instead, it stop `CookieLocaleResolver` fetch user's default locale from HTTP header.

**Comment by mmoayyed** [comment]
Gotcha. I see what you mean. The default locale CAN be necessary in some cases, but I see what your problem here is. Let me run some tests and I'll get back to you. Thanks for explaining the case.

**Comment by mmoayyed** [comment]
Try the new snapshot for 5
