### ISSUE TITLE
Refactor transactional infrastructure from low level aop XML to @Transactional

### ISSUE THREAD

**Issue by dima767** [apereo/cas#1772]
It will be desirable to move away from old XML-based low level aop advice config model for transactional aspects where needed (for example JPA components) to a higher level `@Transactional` marking of such transactional components. While CAS used to have it, it was interferering with something and it was refactored to the old, low level XML config arrangement. We need to re-visit `@Transactional` and see how we could properly apply it, especially now that CAS configuration model has been modernized with `@Configuration` arrangement where we have much more control over bean creation and all their internals.

**Comment by mmoayyed** [comment]
Handled via https://github.com/apereo/cas/pull/1834 See docs and new settings/properties for more info please.
