### ISSUE TITLE
Start using type-safe configuration properties

### ISSUE THREAD

**Issue by dima767** [apereo/cas#1779]
Start refactoring the CAS Spring Boot configuration facilities to gather and use property sources into type-safe `@ConfigurationProperties` classes instead of scattering and injecting those properties into `@Configuration` classes with "un-typed" `@Value` properties.

http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-typesafe-configuration-properties

**Comment by mmoayyed** [comment]
I am extremely in favor of this idea, and I would even go so far as saying, this is the kind of thing we should absolutely finish before v5. We should introduce a consistent, easy-to-remember property scheme as part of 5. Doing this sort of thing post v5 and requiring folks to change all their setting names later when they wish to upgrade is a very painful thing to ask.

**Comment by dima767** [comment]
This is definitely v5 thing. As soon as M1 hits the streets I could start working on it for M2
