### ISSUE TITLE
Support YAML-based service definitions

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#1783]
CAS services may be defined via JSON. Some folks in the community prefer a YAML syntax and they have internal processes that create YAML service definitions and later convert them over to JSON. 

Might want to consider adding support for YAML-based service defns, based on perhaps something like this:
https://github.com/FasterXML/jackson-dataformat-yaml

**Comment by dima767** [comment]
Look into this for implementation inspiration: https://github.com/unicon-cas-addons/cas-addon-yaml-services-registry
