### ISSUE TITLE
Re-authenticate on every Request

### ISSUE THREAD

**Issue by thiyagarajanth** [apereo/cas#1792]
Hi,

I used "RubyCasClient" 'authenticate_on_every_request' its keep authenticate with server but while sending a post request to server with parameters, after authentication of this request am not getting the post method parameters. i don't know why ?

Regards
Thiyagu.

**Comment by thiyagarajanth** [comment]
Why you closed this issue

**Comment by dima767** [comment]
There is no issue, or at least no valuable evidence to the dev team what is it that warrants an open issue here. I suggest posting a question to CAS user mailing list and or to ruby CAS client maling list.
