### ISSUE TITLE
 Can not build de cas 4.2

### ISSUE THREAD

**Issue by kengan** [apereo/cas#1799]
When I build with  following command on window
gradlew build --parallel -x test -x javadoc -DskipCheckstyle=true -DskipAspectJ=true -DskipFindbugs=true 

I get following error
> Could not resolve all dependencies for configuration ':cas-server-support-pac4
j:compile'.
   > A conflict was found between the following modules:
      - commons-io:commons-io:2.4
      - commons-io:commons-io:2.5

Can you help me? Thank you。

**Comment by dima767** [comment]
https://github.com/apereo/cas/issues/1730

**Comment by zhiaixuexi** [comment]
same questions sovled~
