### ISSUE TITLE
EOL 4.0.x line

### ISSUE THREAD

**Issue by dima767** [apereo/cas#1800]
I'd propose ending maintenance mode for `4.0.x` series starting from the upcoming version.

**Comment by mmoayyed** [comment]
Slightly tricky. Probably should send this to cas-user and see what sort of feedback we get. 4.1.9 might be too aggressive.

**Comment by mmoayyed** [comment]
I did change the topic of this issue to be about 4.0.x. That is a much more legible candidate for EOLing. We probably have a few more months before cutting 4.1.x loose.

**Comment by mmoayyed** [comment]
Discussed in PMC. Got a plan to move forward
