### ISSUE TITLE
pb with personDirectoryPrincipalResolver for attribute release

### ISSUE THREAD

**Issue by vieville** [apereo/cas#1802]
CAS 4.2.2
TOMCAT 8.0.33

The authentication itself works fine..
We have a problem with" attribute release".
They are defined in the bean "**attributeRepository**". 
They are correctly read from ldap by the **authenticator**.
But the bean **personDirectoryPrincipalResolver** returns the keys (as they are defined in the bean) with the  values defined in the file deployerConfigContext.xml and not the values coming from the ldap retrieved by the **authenticator** (a **LdapAuthenticationHandler**). 
We also expected the resolver replaces the name of the ldap attribute by the name of the cas attribute. 

here is an extract of deployerConfigContext.xml :1234: M
`	<bean id="attributeRepository" class="org.jasig.services.persondir.support.StubPersonAttributeDao"
          p:backingMap-ref="attrRepoBackingMap" />

    <alias name="personDirectoryPrincipalResolver" alias="primaryPrincipalResolver" />

    <util:map id="attrRepoBackingMap">
		<entry key="mail" value="mail"/>
		<entry key="cn" value="name"/>
		<entry key="sn" value="sn"/>
		<entry key="givenname" value="givenname"/>
		<entry key="supannEmpId" value="matricule"/>
		<entry key="displayName" value="displayName"/>
		<entry key="ustlRole" value="l1role"/>
    </util:map>`

Moreover, we aren't sure the class StubPersonAttributeDao may be used in production. If true, which class should be used in production site ?

Thanks you

Claude

**Comment by vieville** [comment]
The first line of the code seems to be corrupted 
it is 

`<bean id="attributeRepository" class="org.jasig.services.persondir.support.StubPersonAttributeDao"
          p:backingMap-ref="attrRepoBackingMap" />`

**Comment by mmoayyed** [comment]
reference http://apereo.github.io/cas/4.2.x/installation/Configuring-Principal-Resolution.html#principalresolver-vs-authenticationhandler

**Comment by vieville** [comment]
Thanks you for your precious help !

Now it works.

May be you should adjust the deplyerConfigContext.xml to reflect this on line documention

have a nice day
