### ISSUE TITLE
Hazelcast max.no.heartbeats matches heartbeat interval

### ISSUE THREAD

**Issue by tsschmi** [apereo/cas#1818]
We recently ran into issues that after a period of time ClusterHeartbeatManager in Hazelcast would remove a functioning cluster node because it thought it had become non-responsive.  Log files show the node functioning properly up until it was removed by the master.

We traced the cause of the behavior down to the setting of max.no.heartbeats in CAS to 5 seconds.  Unfortunately the Hazelcast heartbeat interval is set to 5 seconds in com.hazelcast.instance.GroupProperty

HEARTBEAT_INTERVAL_SECONDS("hazelcast.heartbeat.interval.seconds", 5, SECONDS)

This is different than the 1 second interval that specified in the online Hazelcast documentation.

Setting the max.no.heartbeat in CAS to the default of 300 specified by Hazelcast cleared the issue for us.

**Comment by mmoayyed** [comment]
Via https://github.com/apereo/cas/commit/5f6dc4eef052322e4562a541f5d8be9ab9282187
