### ISSUE TITLE
need help to add authentication handlers in service-management

### ISSUE THREAD

**Issue by vieville** [apereo/cas#1831]
Hi,

we run successfully a 4.2 CAS release under Tomcat 8.
Now I would like to oblige CAS server to test credentials on another handler for a particular service.
To do so, I declared the new handler in deployerConfigContext.xml  with id="ldapAuthenticationHandler" and then  in the service management I added this id to the field "Required Handlers" for the service.
But I don't find trace of activity for this handler in the log file...
May be I have made an error...
Does it exist a complete example showing the configuration for enabling this possibility ?
Could you help me to find a solution ?

Thanks you very much,

Claude

**Comment by mmoayyed** [comment]
Did you get a chance to study the issue template here before creating one?! This is not an issue. Consult the mailing list please.
