### ISSUE TITLE
CAS v4.2 + jpaServiceRegistry issues

### ISSUE THREAD

**Issue by lsenecaux** [apereo/cas#1839]
**Issue**
CAS Version : 4.2.2
Server : Tomcat 7.0.54
Client : phpCAS 1.3.4

1/ Set Principal Attribute to custom attribute (ldap source) cause a null pointer exception ([principal-attr-issue.txt](https://github.com/apereo/cas/files/319979/principal-attr-issue.txt))
2/ Set Public Key Location in managment webapp (classpath:services/cert.der or /opt/cert.der) cause a cannot be cast to java.sql.Blob ([sqlblob-issues.txt](https://github.com/apereo/cas/files/319978/sqlblob-issues.txt))
3/ Using v2.0 protocol release all attributes instead of allowed ones.

**Comment by mmoayyed** [comment]
what is 3 about?

**Comment by lsenecaux** [comment]
In my php client application, if I use V2 , all principal attributes are released (nok).
If I use V3 or SAML, only selected attributes are released (ok).

I have not this issue with my production server (vers. 3.5.2.1).

**Comment by mmoayyed** [comment]
V2 releases no user attributes. Must be a custom change u.

**Comment by mmoayyed** [comment]
Dima, let's keep this open to investigate 1 & 2? Those seem valid issues to me.

**Comment by dima767** [comment]
I'd want to organize the issues better in 2 separate issues with appropriate `cas-issues` overlay to reproduce, etc.

**Comment by dima767** [comment]
@lsenecaux Can you please open two separate issues for 1) and 2) and provide a simple overlay to reproduce the issues as described here: https://github.com/cas-projects/cas-issues

Thanks.
