### ISSUE TITLE
JPA Service Registry: Public Key Location causes a "Can not cast to java.sql.Blob" error.

### ISSUE THREAD

**Issue by lsenecaux** [apereo/cas#1842]
### **Issue**
Server : Tomcat 7
CAS Mgmt version : 4.2.2

Set Public Key Location in managment webapp (classpath:services/cert.der or /opt/cert.der) cause a cannot be cast to java.sql.Blob.

[sqlblob-issues.txt](https://github.com/apereo/cas/files/323178/sqlblob-issues.txt)

**Comment by mmoayyed** [comment]
What database?

**Comment by lsenecaux** [comment]
I tried several db, such as hsql (memory), MySQL/MariaDB 5.5 and. PostgreSQL 9.2.

**Comment by dima767** [comment]
This could very well be a bug.
