### ISSUE TITLE
OIDC single logout support

### ISSUE THREAD

**Issue by szabatek** [apereo/cas#1843]
We are planning to set up an identity provider with single sign on and off based on CAS. It raised our attention that in version 5.0 OpenID Connect is supposed to be supported. 

Apart from that it hasn't been released yet, what seems to be missing for us is the single sign out support. Is there any plan to support it in any form? We would be glad to contribute.

**Comment by mmoayyed** [comment]
Yes of course. While it will likely not make the cut for 5, feel free to submit a patch please and/or test this current base functionality.

**Comment by mmoayyed** [comment]
Or, based on the milestone schedules, if you can contribute a patch prior to RC1, that would be even more terrific. Should give you about 2 months.

**Comment by szabatek** [comment]
Thanks for your quick response. We will inform you about our progress.

**Comment by mmoayyed** [comment]
@szabatek just checking in to see if you have found OIDC here useful?

**Comment by szabatek** [comment]
Sorry but I haven't informed you that in the meantime we took a completely different approach so we didn't touch too much it and resigned from developing it in CAS.

**Comment by mmoayyed** [comment]
No problem. Thanks for the update

**Comment by mmoayyed** [comment]
Closing, due to inactivity and absence of demand. Can be revisited later if need be.
