### ISSUE TITLE
LPPE: pwdReset should throw a AccountPasswordMustChangeException

### ISSUE THREAD

**Issue by lsenecaux** [apereo/cas#1844]
### **Issue**
Server: Tomcat 7
CAS: 4.2.2

LDAP (OpenLDAP) Authentication Handler configured with PasswordPolicy, when the attribute pwdReset is set to TRUE, CAS sent a CredentialExpiredException.
I suggest to change it to AccountPasswordMustChangeException.

**Comment by mmoayyed** [comment]
You can experiment with changing the DefaultAccountStateHandler. Change the exception type and test for this:

```
this.errorMap.put(PasswordPolicyControl.Error.CHANGE_AFTER_RESET, new CredentialExpiredException());
```

**Comment by lsenecaux** [comment]
I allready modify the DefauultAccountStateHandler on my test server.
Exception is now alright

**Comment by mmoayyed** [comment]
Great. Feel free to submit a PR.

**Comment by mmoayyed** [comment]
Ported to master. Closing.
