### ISSUE TITLE
JPA Service Registry: Principal Attribute Name causes a "java.lang.NullPointerException" error

### ISSUE THREAD

**Issue by lsenecaux** [apereo/cas#1845]
### **Issue**

CAS Version 4.2.2
Server Tomcat 7

Change user principal attribute from default to custom LDAP attribute causes this exception.
[principal-attr-issue.txt](https://github.com/apereo/cas/files/324929/principal-attr-issue.txt)

Tried with MariaDB or PostgreSQL as backend.

**Comment by mmoayyed** [comment]
This is fixed in 4.2.3. Try 4.2.3-SNAPSHOT.

**Comment by lsenecaux** [comment]
I Will try it asap.
Thank you very much
