### ISSUE TITLE
saml-core - JBoss - java.lang.NoClassDefFoundError: com/sun/org/apache/xerces/internal/util/SecurityManager

### ISSUE THREAD

**Issue by ruckc** [apereo/cas#1854]
I have included the following in my report:

When testing 5.0.0.M1 with cas-server-support-saml, I get a NoClassDefFoundError for com/sun/org/apache/xerces/internal/util/SecurityManager.

My environment is JBoss EAP 7.0 w/ Oracle JRE 8.

I am trying to test the viability of trying to migrate our CAS 3.6 configuration up to CAS 5.0 to gain SAML 2.0 support in addition to our existing CAS integrations.

```
Caused by: java.lang.NoClassDefFoundError: com/sun/org/apache/xerces/internal/util/SecurityManager
	at org.apereo.cas.config.CoreSamlConfiguration.parserPool_aroundBody4(CoreSamlConfiguration.java:92)
	at org.apereo.cas.config.CoreSamlConfiguration$AjcClosure5.run(CoreSamlConfiguration.java:1)
```

I found reference to this issue on an IBM JDK with Shibboleth IdP, and their suggestion was to switch to `org.apache.xerces.util.SecurityManager`, instead of the non-public `com.sun.org.apache.xerces.internal.util.SecurityManager`.  In the Shibboleth IdP this was possible in an `internal.xml`, but in cas-server-support-saml-core's CoreSamlConfiguration.java the com.sun dependency is hardcoded.

I'm opening this issue as I believe it would be appropriate to allow Spring to inject the SecurityManager dependency, to allow running on non-Oracle JRE's or to allow depending on an appropriate public API or org.apache.xerces in JBoss EAP.

**Comment by ruckc** [comment]
This looks to be related to #1129, of which this issue hasn't been addressed yet.

**Comment by mmoayyed** [comment]
Your proposal is perfectly reasonable. Would u be willing to submit a PR to fix this?

**Comment by ruckc** [comment]
I'd like to, but I honestly don't know enough about Spring's dependency injection to know how to accomplish this.

**Comment by mmoayyed** [comment]
No problem. We are revamping the configuration properties a bit to make injection somewhat unnecessary. In the future, you should be able to control the security manager via a simple property settings with a default being what it is now. 

Also note that this change will be available in M3. You're on M1, and M2 has been released for a while. Be prepared to switch over please.

**Comment by mmoayyed** [comment]
Handled via https://github.com/apereo/cas/pull/1834 See docs and new settings/properties for more info please.
