### ISSUE TITLE
Radius attribute NAS-Identifier type mismatch

### ISSUE THREAD

**Issue by olexus** [apereo/cas#1867]
${cas.radius.server.nasIdentifier} has type long but must be String as described RFC 2865.

I have included the following in my report:

- [All since 4.x] CAS server version
- [Tomcat 8, Java 1.8] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
- [] Steps to duplicate the problem
- [] Stacktraces and CAS logs where appropriate.
- [] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

**Comment by dima767** [comment]
You haven't provided what version you are dealing with...

**Comment by olexus** [comment]
Since 4.2.x

**Comment by dima767** [comment]
Feel free to provide a patch along with a passing test case via a Pull Request

**Comment by mmoayyed** [comment]
@olexus is there an update on the PR you posted?
