### ISSUE TITLE
Destroying the TGT Does Not Remove the PGT 

### ISSUE THREAD

**Issue by wcrowell** [apereo/cas#1869]
The discussion for this issue is located here:

[https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/ZF6CIyNACdI](https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/ZF6CIyNACdI)

The Ticket Granting Ticket (TGT) creation and removal was performed using the CAS REST API: [https://wiki.jasig.org/display/casum/restful+api](https://wiki.jasig.org/display/casum/restful+api)

Using the PGTInvalidationByLogoutSpec test in cas-functional-tests: [https://github.com/wcrowell/cas-functional-tests/blob/master/src/test/groovy/org/jasig/cas/test/validation/PGTInvalidationByLogoutSpec.groovy](https://github.com/wcrowell/cas-functional-tests/blob/master/src/test/groovy/org/jasig/cas/test/validation/PGTInvalidationByLogoutSpec.groovy), it was noticed the Proxy Granting TIcket (PGT) could still be used to generate Proxy Tickets (PT).  On line 50 of this test the assertion is commented out:

`assert xml.proxyFailure.@code == 'BAD_PGT'`

This assertion fails because a proxy ticket is generated instead.

To reproduce, clone the git clone cas-functional-tests: `git clone https://github.com/wcrowell/cas-functional-tests.git`

Then run: `gradle clean farmIntegrationTest`

Go to the report: cas-functional-tests/build/reports/tests/classes/org.jasig.cas.test.validation.PGTInvalidationByLogoutSpec.html

See the output:

```
Ticket Granting Ticket ID TGT-1-VboJ29NFir0XZmEj5XNCAzfPgHp2V5KgdaCAnSJlnAgOCMmoIq-cas01.example.org was deleted.
final: 

<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    <cas:proxySuccess>
        <cas:proxyTicket>PT-2-idF5fWrGB7y9OPWdRt1z-cas01.example.org</cas:proxyTicket>
    </cas:proxySuccess>
</cas:serviceResponse>
```

Debug output on the org.jasig package is attached.  You can see from the debug output that it states the TGT is destroyed and cannot be found in the registry, but yet the PT is created from the PGT.

[output-debug.txt](https://github.com/apereo/cas/files/349630/output-debug.txt)

**Comment by mmoayyed** [comment]
Just noting here that we did substantial work on this issue in 5 to make sure the ticket hierarchy is properly cleaned for all registries. I suspect in 4.2, this issue works with the JPA registry, but not with others. PGTs are only removed by the cleaner when they are expired, and not when the parent TGT is killed directly. This should be fixed, and that might simply be backporting what's done for 5. 

In the meantime, @wcrowell it would be great if you could run the same batch against 5 and see how it checks out. 

Much appreciated, regardless.

**Comment by mmoayyed** [comment]
Or, if you want to take this one step further and submit a patch, that would be terrific. I'd start by examining the registry code in 5 and see how the clean up process works, and then pick and choose pieces that are relevant for 4.2. Much of it should translate easily.

**Comment by wcrowell** [comment]
Will do.  Is there a repo where CAS 5 is available for download?

**Comment by mmoayyed** [comment]
Master is on 5.0, or you you could use this: https://github.com/apereo/cas-overlay-template/tree/5.0 (If you do, make sure you use the latest 5 SNAPSHOT)

**Comment by wcrowell** [comment]
I ran the tests against 5.0.0-SNAPSHOT and all 14 tests failed for various reasons.  I attached the output.  I will need to look into why the tests failed before I can go any further with this issue.

**Comment by wcrowell** [comment]
Of course...I forgot to attach the output.
[output-5.0.0-SNAPSHOT.txt](https://github.com/apereo/cas/files/357767/output-5.0.0-SNAPSHOT.txt)

**Comment by mmoayyed** [comment]
Try with 5.0.0.M3-SNAPSHOT. Follow this guide to bring CAS up locally: https://apereo.github.io/cas/developer/Build-Process.html

**Comment by mmoayyed** [comment]
I am in the process of updating the overlay to properly use M3, under the 5.0 branch. Hang tight for a bit.

**Comment by wcrowell** [comment]
Will do.  Thanks!

**Comment by mmoayyed** [comment]
Should be ready now. Give it a shot plz

**Comment by wcrowell** [comment]
By the way, do I follow the steps here: [https://apereo.github.io/cas/developer/Build-Process.html](https://apereo.github.io/cas/developer/Build-Process.html)

The cas-functional-tests ([https://github.com/wcrowell/cas-functional-tests](https://github.com/wcrowell/cas-functional-tests)) can deploy a fully functional CAS server automatically with an embedded Jetty with SSL using any release or snapshot build as you have in that link.  I would need to change some things in my scripts not to bring up a Jetty instance in my functional tests.  I am willing to do that if needed.

Also, I looked for a 5.0.0.M3-SNAPSHOT here: [https://oss.sonatype.org/content/repositories/snapshots/org/jasig/cas/](https://oss.sonatype.org/content/repositories/snapshots/org/jasig/cas/) and could not find that snapshot build.

**Comment by mmoayyed** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/apereo/cas/

**Comment by mmoayyed** [comment]
If you use the overlay, you don't need to follow the build process. If you don't, you do.

**Comment by wcrowell** [comment]
I made the change to [https://oss.sonatype.org/content/repositories/snapshots/org/apereo/cas/](https://oss.sonatype.org/content/repositories/snapshots/org/apereo/cas/)

and I am running into this again:

`
Could not parse POM https://jcenter.bintray.com/org/apache/shiro/shiro-root/1.2.5/shiro-root-1.2.5.pom
> Invalid encoding name "UTF8".`

I am not sure how you are getting around that.  It should be 'UTF-8'.

**Comment by mmoayyed** [comment]
Ignore it. That's a shiro issue, not us. A new version of the snapshot should update shiro and remove that warning in a bit.

**Comment by wcrowell** [comment]
I know they fixed it in Shiro 1.2.6.

**Comment by mmoayyed** [comment]
See https://github.com/apereo/cas/blob/master/gradle.properties#L125

**Comment by wcrowell** [comment]
Still no luck, but this is where the issue is:

[https://oss.sonatype.org/content/repositories/snapshots/org/apereo/cas/cas-server-core-util/5.0.0.M3-SNAPSHOT/cas-server-core-util-5.0.0.M3-20160712.082618-26.pom](https://oss.sonatype.org/content/repositories/snapshots/org/apereo/cas/cas-server-core-util/5.0.0.M3-SNAPSHOT/cas-server-core-util-5.0.0.M3-20160712.082618-26.pom)

Doing a `gradle dependencies` shows this (a lot output removed for brevity):
`
+--- org.apereo.cas:cas-server-webapp:5.0.0.M3-SNAPSHOT
|    +--- org.apereo.cas:cas-server-core:5.0.0.M3-SNAPSHOT
|    |    +--- org.apereo.cas:cas-server-core-services:5.0.0.M3-SNAPSHOT
|    |    |    +--- org.apereo.cas:cas-server-core-util:5.0.0.M3-SNAPSHOT
|    |    |    |    +--- org.apache.shiro:shiro-core:1.2.5 FAILED
`

Can you check or am I doing something unusual and missing something?

**Comment by wcrowell** [comment]
My bad...I am being too impatient and need to wait for a new build.  :)

**Comment by mmoayyed** [comment]
Also my bad :) I didnt realize the snapshot wasnt published by Travis. It should be out there in about 30 mins, or less.

**Comment by wcrowell** [comment]
No problem.  I will be looking for it.

**Comment by wcrowell** [comment]
I saw the new build and found the Apache Shiro 1.2.6 update.  The run got farther this time.  The 14 functional tests (user interface and REST calls combined) failed with "Service Unavailable" or 503 errors.  I am attaching the output.  Investigating...I might be missing some property settings because it looks like the naming changed from org.jasig to org.apereo.  Checking...
[output-5.0.0.M3-20160712.134043-27.txt](https://github.com/apereo/cas/files/359498/output-5.0.0.M3-20160712.134043-27.txt)

**Comment by mmoayyed** [comment]
yes. everything is under org.apereo now.

**Comment by mmoayyed** [comment]
cross check settings with https://apereo.github.io/cas/development/installation/Configuration-Properties.html

**Comment by wcrowell** [comment]
Will do.  I will make adjustments and re-test.

**Comment by wcrowell** [comment]
Still working on this.  Had some interruptions today.

**Comment by wcrowell** [comment]
Did more investigation on this today.  I have most of the configuration properties taken care of, but I am receiving a:

`java.lang.IllegalArgumentException: No ConfigurationProperties annotation found on  org.apereo.cas.config.CasCoreAuthenticationConfiguration`

I am fairly certain this is related to Spring Boot since I see the org.springframework.boot package all over the stacktrace frames.

In CAS 5, since you are using Spring Boot with Tomcat via the spring-boot-starter-tomcat, this is going to be a bit of a challenge for me and that is ok.  

I am using the Gretty framework which supports both Tomcat and Jetty along with Spring boot: [http://akhikhl.github.io/gretty-doc/about.html](http://akhikhl.github.io/gretty-doc/about.html).

My functional tests that run against CAS 4.2.2 currently would need to be switched over to use Spring Boot's spring-boot-starter-tomcat and spring-boot-starter-jetty [http://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html](http://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-servlet-containers.html).

**Comment by wcrowell** [comment]
Issue opened against my project for this: [https://github.com/wcrowell/cas-functional-tests/issues/3](https://github.com/wcrowell/cas-functional-tests/issues/3)

**Comment by mmoayyed** [comment]
Great progress, thank you. If you want, you can push your config to a separate branch for 5 and I can run through the tests and see if I can make any suggestions.

**Comment by wcrowell** [comment]
No problem.  I created a new 5.0.x branch [https://github.com/wcrowell/cas-functional-tests/tree/5.0.x](https://github.com/wcrowell/cas-functional-tests/tree/5.0.x) and went ahead renamed my packages to org.apereo to stay consistent with the new package names.  It does not appear the CAS client has moved from org.jasig over to org.apereo yet.  Today I will be looking into Spring Boot'ifying (if you will) the functional tests.  Let me know if you see anything odd with the configuration properties set in build.gradle.  I have them set as system properties in build.gradle because I have not had time to figure out how to provide them in a properties file.  I probably have redundant system properties set in build.gradle that I need to remove.

**Comment by mmoayyed** [comment]
I would move away from gretty and simply attempt to bring CAS up via `java -Xdebug -Xrunjdwp:transport=dt_socket,address=5000,server=y,suspend=n -jar target/cas.war `. For now at least. We are working on a gradle plugin to make sure cas+boot can function without gretty and such, solely relying on the boot plugin itself. (I didnt have much luck configuring the maven plugin, but didnt spend that much time) Sys Props are also fine. They should be recognized by boot as normal. 

More on this tomorrow. 

Lets split up tasks a bit: how about I focus on the issues with int tests and 5, and you attack the issue with PGTs not getting cleaned up? Or shall we reverse? (Note that 4.2.4 is out by July 24th) We have about 10 days to get a fix in place :)

**Comment by wcrowell** [comment]
That sounds good.  The issue with Gretty is that the original author is not longer active on the project, and it was taken over by another person.  This other individual is great, but I do not know how much longer that project will be alive.  So I am leery of continuing to use it.  I had a distraction today at work that I hopefully will have put to bed by the end of day and I can focus on this tomorrow.  My apologies...

**Comment by mmoayyed** [comment]
No worries at all. Appreciate any time you can spare. 

The rationale you provided for gretty is exactly what we(CAS) moved away from it too...and boot took care of it really. Gretty was also way too buggy in some areas, and startup time was a definite killer. I suspect it might work well for smaller projects, but probably not for one with 116+ modules :)

**Comment by wcrowell** [comment]
Agreed.  I also find it does not shutdown the application server container cleanly when an exception occurs.  This might be due to Gradle or Gretty.  Regardless, we will go with Spring Boot.

**Comment by mmoayyed** [comment]
Quick update: I forked your repo, and switch to the 5.0.x branch to start running tests. Lets see if I can break anything :)

**Comment by mmoayyed** [comment]
First try, I see this:

```
aused by: java.lang.IllegalArgumentException: No ConfigurationProperties annotation found on  'org.apereo.cas.config.CasCoreAuthenticationConfiguration'.
        at org.springframework.util.Assert.notNull(Assert.java:115) ~[na:na]
        at org.springframework.boot.context.properties.EnableConfigurationPropertiesImportSelector$ConfigurationPropertiesBeanRegistrar.registerBeanDefinition(EnableConfigurationPropertiesImportSelector.java:118) ~[na:na]
        at org.springframework.boot.context.properties.EnableConfigurationPropertiesImportSelector$ConfigurationPropertiesBeanRegistrar.registerBeanDefinitions(EnableConfigurationPropertiesImportSelector.java:82) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:352) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:143) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:116) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:333) ~[na:na]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[na:na]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681) ~[na:na]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523) ~[na:na]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[na:na]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760) ~[na:na]

```

This is an artifact of using Gretty I think. For whatever reason, it's not recognizing the fact that there are jars on the classspath that need to be scanned. 

Could you run the war as a standalone executable with something like:

```
java -Xdebug -Xrunjdwp:transport=dt_socket,address=5000,server=y,suspend=n -jar cas.war 
```

?

**Comment by wcrowell** [comment]
That's exactly what I was getting.  Bear with me...trying to get off this call...

**Comment by wcrowell** [comment]
Here's what I ended up doing...I followed your document: [https://apereo.github.io/cas/developer/Build-Process.html](https://apereo.github.io/cas/developer/Build-Process.html)

I noticed in the 4.2.x branch you used Gretty, and the master/5.0.x you are using Spring Boot which is good for me.  I did not realize CAS 4.2.x used Gretty until today.

I have a local copy of my functional tests where I stripped out Gretty, and I am able to reproduce this bug with the PGT on CAS 4.2.2.  I do not think this is going to happen on CAS 5 because in org.apereo.cas.ticket.registry.AbstractTicketRegistry.deleteTicket():94-95 you have:

`...
        if (ticket instanceof TicketGrantingTicket) {
            if (ticket instanceof ProxyGrantingTicket) {
...`

org.apereo.cas.ticket.proxy.ProxyGrantingTicket is a type of org.apereo.cas.ticket.TicketGrantingTicket in CAS 5 (and 4).  There could be a casting issue, but I really doubt it.

Still investigating org.jasig.cas.ticket.registry.DefaultTicketRegistry.deleteChildren in CAS 4.2.2.  More to come.

**Comment by mmoayyed** [comment]
You got it. In 5, children of a TGT are recursively delegated until kingdom come :) Note that also in 5, that strategy is applied to all registries. You want to ensure the same sort of idea is applied to 4 and is done for all registries. Generalize as much as you can.

If you have stripped out gretty for the func-tests and pushed, please LMK and I'll resume testing. 

Thanks.

**Comment by wcrowell** [comment]
Yes, bear with me.  Let me clean it up first.  Do you ever sleep???  :)

**Comment by wcrowell** [comment]
It's out there now under the branch 4.2.x_without_embedded_container: 

[https://github.com/wcrowell/cas-functional-tests/tree/4.2.x_without_embedded_container](https://github.com/wcrowell/cas-functional-tests/tree/4.2.x_without_embedded_container)

I am "cheating" a bit with registering an application registered under CAS called protected-web-app.  You can find that web application here: 

[https://github.com/wcrowell/cas-functional-tests/tree/master/protected-web-app](https://github.com/wcrowell/cas-functional-tests/tree/master/protected-web-app)

It has a filter defined.  The purpose of the filter is a poor man's way to keep a static map of proxy granting ticket IOU's with proxy granting tickets so it can be returned to the test scripts.  If the "requestPgtId" is in the request map, then the proxy granting ticket will be looked up from the PGTIOU.  I did not know of another way of doing this.  Maybe there is a simpler way of doing it.

**Comment by mmoayyed** [comment]
So the new build without the embedded container:

1. Can I use the same build for 5?
2. How does it spin up CAS? or should I do that manually before running tests? 

Your filter is fine. That's mostly how all clients work.

**Comment by wcrowell** [comment]
You should be able to use it for 5.
You should spin it up before running the tests.  You will need to run cas-management-webapp as well.  I am attaching the build.gradle for cas-server-webapp for your reference.  
[build.gradle.txt](https://github.com/apereo/cas/files/366104/build.gradle.txt)

I am running into meetings again this morning.  I had to rename build.gradle to build.gradle.txt

**Comment by mmoayyed** [comment]
So, I got your build.gradle file without gretty and started running integration tests via `gradle clean integrationTest`. I also had v5 M3 running locally. It seems like all tests fail. In my CAS logs, all I see are service ticket validation events and failures. There is no record of an authn attempt. 

I also see things like `Service ticket[foo] does not exist.`. I don't know if this is an artifact of integration tests or maybe it's something else, but foo can never ever be issued by CAS. 

Thoughts?

**Comment by wcrowell** [comment]
On `Service ticket[foo] does not exist`, you are 100% correct.  To stay true to the "CAS Functional Tests" located here: [https://wiki.jasig.org/display/CAS/CAS+Functional+Tests](https://wiki.jasig.org/display/CAS/CAS+Functional+Tests), there are tests where you will see an instruction like:

> visit /login?service=foo

So, I am actually doing that in the org.jasig(apereo).cas.test.login.GatewaySpec.groovy test:

[https://github.com/wcrowell/cas-functional-tests/blob/master/src/test/groovy/org/jasig/cas/test/login/GatewaySpec.groovy](https://github.com/wcrowell/cas-functional-tests/blob/master/src/test/groovy/org/jasig/cas/test/login/GatewaySpec.groovy)

It is just a negative test to make sure that CAS is not issuing a ticket for an invalid service.

As for running your v5 M3 locally, can you attach a log to this issue so I can take a look?  I can tell you that a few of the user interface tests in the [org.jasig.cas.test.login](https://github.com/wcrowell/cas-functional-tests/tree/master/src/test/groovy/org/jasig/cas/test/login) package will fail because it appears that someone prepended a "Login - " to the title HTML element of the page.  That can easily be fixed by going into the [org.jasig.cas.test.pages.LoginPage.groovy](https://github.com/wcrowell/cas-functional-tests/blob/master/src/test/groovy/org/jasig/cas/test/pages/LoginPage.groovy) 
```
static at = {
	title == "CAS – Central Authentication Service"
}
```
But it sounds like you have bigger issues.

Make sure you include the cas-server-support-rest package in compile scope to the cas-server-webapp, but you probably already know that.  Just in case you did not.  That would contribute to the failures to the org.jasig.cas.test.validation scripts.

As for this 1869 issue, I worked a few hours on this problem this morning, but I was running against CAS 4.2.x.   It appears that the PGT is not a child of the TGT or gets disassociated from it and that is why the deleteChildren never finds it.  Still working on this though.

My work has me on something else...trying to get more time to work on this...frustrated because I want more time on this.  Very cool stuff.  Please send your log for CAS 5 M3.  I'll be check email this weekend and can comment.

**Comment by wcrowell** [comment]
By the way, with CAS 5 M3 you will need to run cas-management-webapp along with cas-server-webapp.  I tried this late Friday and really struggled with it.  If I just ran cas-server-webapp, then the embedded application server started up fine.  When I tried to startup with cas-management-webapp and cas-server-webapp, I would receive exceptions and cas-management-webapp would not startup.  A few of the org.jasig(apereo).cas.test.login scripts access the CAS management application just to make sure they can access a protected application.  This was prior to me discovering that I needed to create the protected-web-app as a standalone app for testing.  We can change the scripts so those scripts do not access the CAS Management main page and access the protected-web-app or any app for that matter.  I was just not familiar with all the 116 projects that CAS has.  Again, it is not a hard requirement for a few of those scripts to access the CAS Management application.  I only did that to give us some extra testing.  Eventually, I wanted scripts to test the user interface for the CAS Management application as well, but getting these base scripts done is what is important.

**Comment by mmoayyed** [comment]
Thanks for the update. Excellent progress. 

I suspect I was missing the rest module in my local running CAS. I'll verify and post back. In case I run into some other issue, and just so I understand, did you want the CAS logs or the integration test logs? 

One additional mod I made to the build was to add `mavenLocal()` to the list of repos. I suggest you do that as well by default; For those of us who build and install CAS locally, this is helpful to not download a snapshot from sonatype every day and time we run the tests. (We install it locally and off it goes once) This helps with local development; if we were to run integration tests on a trigger say on Travis/Heroku, it wouldnt matter and sonatype will push it down for us.  

...and you're right. The management app is bootified, but I don't think we have gotten around to making sure it can be run as an overlay, or for a given adopter just yet. That would be taken care of prior to RC1 and I'll spend a bit of time this week polishing that up.

**Comment by wcrowell** [comment]
My bad, I should have clarified which logs.  If you can attach both the cas.log and the integration test reporting logs, then that would be great.  The integration test reporting logs are created by Geb in the directory where you checked out the cas-functional-tests in the following directory: cas-functional-tests/build/reports/tests/

I will add mavenLocal() to my scripts.  Great point!  I made the switch recently from Maven to Gradle and when I used Maven I would always install artifacts locally I was developing with.  I never thought of doing that.

As for the management app being bootified...I actually (and stupidly) briefly tried to use Gretty's farm task to run cas-management-webapp and cas-server-webapp together.  This was a nightmare as I kept running into issues with the wrong auditablePrincipalResolver being injected into the auditTrailManagementAspect constructor in the auditTrailContext.xml.  I think it had something to do with a duplicate Spring Application Context starting up from 2 applications.  I need to get more familiar with Spring Boot quickly.

**Comment by mmoayyed** [comment]
I was able to get the tests working. Looks like most failures have to deal with text comparisons that now fail because the UI has changed. 

I only have an index.html file for logs, which I can't seem to attach here due to Github rules. But if you run the tests, you'll find most failures are due to the forementioned reason. Simply tweak them and let it run once more. Or push and I'll resume.

**Comment by wcrowell** [comment]
That's great.  So any major changes?  Just minor text comparison changes?

**Comment by mmoayyed** [comment]
That's it for the most part. I didn't spot any other failures. 

I suspect there are a few hidden entries in there that I may have missed, due to PGT turned off and such. But that would be step 2 once we get the UI issues out of the way.

**Comment by wcrowell** [comment]
How did you end up getting cas-management-webapp started up with cas-server-webapp with Spring Boot?

**Comment by mmoayyed** [comment]
You can run the both at the same time. 

For CAS I run:

```
cd cas-server-webapp; gradlew build bootRun --parallel -x test -x javadoc -DskipCheckstyle=true -DskipFindbugs=true -DskipAspectJ=true
```

For the Mgmt App, I run:

```
cd cas-management-webapp; gradle build install bootRun --parallel -x test -x javadoc -DskipFindbugs=true -DskipAspectJ=true
```

The trick is, both are configured to run on 8443 (or 8080 if you care). You just have to change the port for one, and update the tests.

**Comment by mmoayyed** [comment]
Needless to say, you ought to be running the latest master. 

PS I did as a result of running tests discover an issue with the REST module which I will get fixed soon. Sometime before Monday hopefully.

**Comment by wcrowell** [comment]
Gotcha, ok, thanks.  I will give that a shot.

**Comment by mmoayyed** [comment]
Moving this issue to 4.2.5, as we wont be able to get to it by Friday. 

PS Note that PGTs are cleaned by the cleaner when they expire.

**Comment by wcrowell** [comment]
My apologies.  I have not been able to get to this due to another project.  I should be able to work on it this week or next.

**Comment by mmoayyed** [comment]
No problem. There is always the next patch release.

**Comment by mmoayyed** [comment]
@wcrowell Checking in: do you think it possible to get this issue fixed before August 20th?

**Comment by wcrowell** [comment]
Funny you pinged me today...I finally got an open day to work on it.  I am free all week and next to work on it.  Yes.  I have the green light so we are good.

**Comment by wcrowell** [comment]
I have been working on this issue this afternoon.

**Comment by mmoayyed** [comment]
Perfect!

**Comment by wcrowell** [comment]
Sorry for the delay.  I should not have any more interruptions.

**Comment by wcrowell** [comment]
Here is my proposal to fix this issue:

org.jasig.cas.ticket.registry.DefaultTicketRegistry's `deleteTicket(final String ticketId)` can be called in at least one of two places:

1) From within the `public void execute(final JobExecutionContext jobExecutionContext) throws JobExecutionException` method in the DefaultTicketRegistry class.

2) org.jasig.cas.CentralAuthenticationServiceImpl's method: `public List<LogoutRequest>  destroyTicketGrantingTicket(@NotNull final String ticketGrantingTicketId)`

I propose at the end of org.jasig.cas.ticket.registry.DefaultTicketRegistry's method `private void deleteChildren(final TicketGrantingTicket ticket)` that the following code checks for proxy granting tickets and removes them from the cache:

```
    private void deleteChildren(final TicketGrantingTicket ticket) {
...        
//  Do usual service ticket check here.  Omitted for brevity
...
        Collection<Ticket> tickets = this.getTickets();
        for(Ticket ticketIterator : tickets) {
        	if (ticketIterator != null && ticketIterator instanceof TicketGrantingTicket) {
        		if (ticketIterator.getGrantingTicket() != null && ticketIterator.getGrantingTicket().equals(ticket)) {
                    logger.debug("Cleaning up expired proxy-granting ticket [{}]", ticketIterator.getId());
                    this.cache.remove(ticketIterator.getId());
                }
            }
        }
    }		
```

What are your thoughts on this?  My one concern is that when the Quartz job runs is that it gets a reference to the registry from the jobExecutionContext and issues a `registry.deleteTicket(ticketId)`.  My fix above removes the ticket from the cache that is kept as a member variable within DefaultTicketRegistry: `this.cache.remove(ticketIterator.getId());`

I was checking some of the other ticket registry implementations, and this issue might extend beyond the DefaultTicketRegistry.  I have no unit test results to back this up. 

I found checks on service tickets in deleteTicketAndChildren but nothing on proxy granting tickets in the following 5 ticket registry implementations:
1) org.jasig.cas.ticket.registry.JpaTicketRegistry
2) org.jasig.cas.ticket.registry.EhCacheTicketRegistry
3) org.jasig.cas.ticket.registry.MemCacheTicketRegistry
4) org.jasig.cas.ticket.registry.IgniteTicketRegistry
5) org.jasig.cas.ticket.registry.HazelcastTicketRegistry

No check on child tickets in the following 2 registry implementations:
1) org.jasig.cas.ticket.registry.CouchbaseTicketRegistry
2) org.jasig.cas.ticket.registry.InfinispanTicketRegistry

**Comment by mmoayyed** [comment]
> I was checking some of the other ticket registry implementations, and this issue might extend beyond the DefaultTicketRegistry.

Yes, that basically was going to be my comment. Your change needs to account for all ticket registries. Only a few the default for production.I'd recommend you look at the same code batch that lives in master now, which solves this problem. That should give you a good start to port it backward.

**Comment by wcrowell** [comment]
I see it.  It is in the class org.apereo.cas.ticket.registry.AbstractTicketRegistry.  Handled in the `public boolean deleteTicket(final String ticketId)` method.

**Comment by wcrowell** [comment]
In CAS 5.0.0.RC1-SNAPSHOT, org.apereo.cas.ticket.TicketGrantingTicketImpl has the following member variable:

`
/** The PGTs associated to this ticket. */
@OneToMany(targetEntity = TicketGrantingTicketImpl.class, mappedBy = "ticketGrantingTicket", fetch = FetchType.EAGER)
private Set<ProxyGrantingTicket> proxyGrantingTickets = new HashSet<>();
`

That JPA mapping is not working for me and the proxyGrantingTickets set is empty.  Is there somewhere in CAS 5 where the cached instanced is being refreshed from the database?  I was assuming JPA would handle this by default and refresh the set.

**Comment by wcrowell** [comment]
Disregard, I see it in org.apereo.cas.ticket.ServiceTicketImpl:144-147:

`        
final ProxyGrantingTicket pgt = new ProxyGrantingTicketImpl(id, this.service,
this.getGrantingTicket(), authentication, expirationPolicy);
getGrantingTicket().getProxyGrantingTickets().add(pgt);
return pgt;
`

My bad.  It works now after porting it backward.

**Comment by wcrowell** [comment]
Just an update where I am at.  I have some unit test failures that I will fix on Monday.  I was able to update the following registry implementations:

org.jasig.cas.ticket.registry.EhCacheTicketRegistry
org.jasig.cas.ticket.registry.HazelcastTicketRegistry
org.jasig.cas.ticket.registry.IgniteTicketRegistry
org.jasig.cas.ticket.registry.InfinispanTicketRegistry
org.jasig.cas.ticket.registry.MemCacheTicketRegistry
org.jasig.cas.ticket.registry.CouchbaseTicketRegistry
org.jasig.cas.ticket.registry.JpaTicketRegistry: This one was more involved because `public boolean deleteSingleTicket(final String ticketId)` does a bit more with calls to `deleteServiceTickets` and `deleteTicketGrantingTickets`.  I left the OAuth code out because it appears that `org.apereo.cas.ticket.code.OAuthCodeImpl` is not in CAS 4.2.x.

Most of the changes were delegating calls to deleteTicket to org.jasig.cas.ticket.registry.AbstractTicketRegistry's `public boolean deleteTicket(final String ticketId)` and defining a concrete method `public boolean deleteSingleTicket(final String ticketId)` for each registry implementation.   Let me know if you think I am off course anywhere here.  I looked at the CAS 5 RC1 code to make sure I was consistent.  I did not make any changes to the class inheritance.  Looks like registry code in CAS 5 does not extend org.jasig.cas.ticket.registry.encrypt.AbstractCrypticTicketRegistry because it was refactored/removed.  1869.patch file is attached to this issue.  
[1869.patch.txt](https://github.com/apereo/cas/files/416212/1869.patch.txt)

More next week...

**Comment by mmoayyed** [comment]
You're on the right track. Thanks. 

Here is what I suggest next:

1. Turn the patch into a pull request
2. Run your batch of tests against the patch/PR. 
3. Not having looked at the patch yet, you should also make sure there are tests in the PR that account and verify for this change.

**Comment by wcrowell** [comment]
Is it ok to skip the Couchbase test because there are no tests in cas-server-support-couchbase-ticket-registry?  I tried creating a org.jasig.cas.ticket.registry.CouchbaseTicketRegistryTests, but I believe you need a Couchbase listener up and running like there is in org.jasig.cas.AbstractMemcachedTests/org.jasig.cas.ticket.registry.MemCacheTicketRegistryTests.

**Comment by mmoayyed** [comment]
Yes. I suppose it's fine for now. I'll run some tests manually once your patch is in, and we could potentially look into using http://developer.couchbase.com/documentation/mobile/current/develop/guides/couchbase-lite/index.html in the future. Might be something else for you to tackle next :)

**Comment by mmoayyed** [comment]
This may also be useful https://github.com/couchbase/couchbase-lite-java-listener

**Comment by wcrowell** [comment]
I'll try a quick shot at that Couchbase Lite Java Listener.  If I get hung up on it, I'll skip it.  I'll issue a pull request in a bit.  All of the unit tests pass and I have created new unit tests for the code I introduced.

**Comment by mmoayyed** [comment]
Awesome work. Thanks!

**Comment by wcrowell** [comment]
I think I would need more time to integrate a lite Couchbase server into the unit test.  It might be best to move just the unit test for Couchbase into the next minor point release.  I came close today to getting this working, and I might be able to get it in the next 3 days.  But it will be cutting it close to August 20th. 

I looked at the Couchbase Lite Java Listener this afternoon which does not have a runnable Couchbase server, but it provides a skeleton that can be used by projects like the couchbase-lite-android-liteserv: [https://github.com/couchbase/couchbase-lite-android-liteserv](https://github.com/couchbase/couchbase-lite-android-liteserv)

I also found this link and tried going through the instructions:
[https://github.com/couchbase/couchbase-lite-android/wiki/Running-unit-tests-for-couchbase-lite-android](https://github.com/couchbase/couchbase-lite-android/wiki/Running-unit-tests-for-couchbase-lite-android)

I had quite a bit of trouble getting this working.  I also downloaded a Couchbase Lite pre-built server: 

[http://www.couchbase.com/nosql-databases/downloads#couchbase-mobile](http://www.couchbase.com/nosql-databases/downloads#couchbase-mobile)

But when I constructed the connection to Couchbase in org.jasig.cas.couchbase.core.CouchbaseClientFactory like so:

```
import com.couchbase.client.java.Bucket;
import com.couchbase.client.java.Cluster;
import com.couchbase.client.java.CouchbaseCluster;
import com.couchbase.client.java.env.CouchbaseEnvironment;
import com.couchbase.client.java.env.DefaultCouchbaseEnvironment;
...
            CouchbaseEnvironment environment = DefaultCouchbaseEnvironment
            		.builder()
            		.bootstrapCarrierDirectPort(11210)
            	    .queryEnabled(true)
            	    .build();
            cluster = CouchbaseCluster.create(environment, new ArrayList<>(nodes));

            bucket = cluster.openBucket(bucketName, password, timeout, TimeUnit.SECONDS);
```

It still would not connect even though it was listening on 11210.  

Maybe I am making this too difficult.

**Comment by mmoayyed** [comment]
I appreciate your persistence. In light of the coming deadline, (and given I do have a couchbase env available) lets not worry about tests for the time being. Go ahead and PR. I'll do the testing on my end.

**Comment by mmoayyed** [comment]
PS It's not August 20th btw. It's this https://github.com/apereo/cas/milestones You still have plenty of time for 4.2.5

**Comment by wcrowell** [comment]
Ok.  I'll dig into the Couchbase unit testing more today.  By the way, I wanted to get you the pull request for this as soon as possible: [https://github.com/apereo/cas/pull/1953](https://github.com/apereo/cas/pull/1953)

Can you double check it when you get a moment?  I have not had to create a pull request for CAS before.  I see the Travis build passed, but there are merge conflicts.

**Comment by mmoayyed** [comment]
Of course. I'll review it in a bit.

**Comment by wcrowell** [comment]
Misagh, now check: [https://github.com/apereo/cas/pull/1955](https://github.com/apereo/cas/pull/1955)

I did not fork to my own github first and had to merge the changes in there before I created the pull request.  My bad.  Should be good now.
