### ISSUE TITLE
Evaluate Vault: how it might fit CAS via Spring Boot

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#1870]
Reference https://www.vaultproject.io/

**Comment by dima767** [comment]
https://spring.io/blog/2016/06/24/managing-secrets-with-vault

**Comment by mmoayyed** [comment]
On a similar note, we probably should look mongodb support for spring-cloud as well. Both are available in incubation mode.

**Comment by mmoayyed** [comment]
I have a functioning prototype. Will see if I can put together a PR sometime next week.

**Comment by mmoayyed** [comment]
Updated docs to note how one might use vault.
