### ISSUE TITLE
CAS-4.2.2 Acceptable Usage Policy with LDAP attribute

### ISSUE THREAD

**Issue by renardarg** [apereo/cas#1878]
Hi,

I want to use Acceptable Usage Policy  in my webflow with Ldap as storage, i use Cas-4.2 .2 overlay, i have set it up like the doc say [here](https://apereo.github.io/cas/4.2.x/installation/Webflow-Customization-AUP.html).
 

In my set up, i authenticate users against Active directory and need to bind with an account first.
 

But in the set up of « ldaptive:connection-factory id="ldapUsagePolicyConnectionFactory » in deployerConfigContext.xml there is nothings about bindDN at all.

Is there a way to add support for binding users against Active directory with Ldaptive:connection-factory ?  

Thanks.
Best regards,
Nicolas

**Comment by mmoayyed** [comment]
No. Not without ldaptive 1.2 or you manually creating beans.
