### ISSUE TITLE
OidcRegisteredServiceTests in Project cas-server-support-oidc-core is in Default Package

### ISSUE THREAD

**Issue by wcrowell** [apereo/cas#1889]
OidcRegisteredServiceTests in Project cas-server-support-oidc-core is in the default package instead of package org.apereo.cas.services:

[https://github.com/apereo/cas/blob/master/cas-server-support-oidc-core/src/test/java/OidcRegisteredServiceTests.java](https://github.com/apereo/cas/blob/master/cas-server-support-oidc-core/src/test/java/OidcRegisteredServiceTests.java)

It is not causing an error, but it was just something I saw and could cause a compile error because it references ServiceRegistryDao and JsonServiceRegistryDao which are in that package.

I checked existing open issues before opening this and did not see a similar issue already opened.

**Comment by mmoayyed** [comment]
Handled via https://github.com/apereo/cas/commit/e7d705ca5b5f6e03a7df84d6ac8ae3a990a41080. Thanks for the catch.

**Comment by wcrowell** [comment]
No problem!
