### ISSUE TITLE
SpnegoWebflowConfigurer has String constant rather than variable

### ISSUE THREAD

**Issue by sisutcliffe** [apereo/cas#1892]
https://github.com/apereo/cas/blob/4.2.x/cas-server-support-spnego-webflow/src/main/java/org/jasig/cas/web/flow/SpengoWebflowConfigurer.java#L34

has the private variable from line 19 as String rather than the variable meaning Spnego can't be configured to use any of the client selection strategies.

**Comment by mmoayyed** [comment]
@sisutcliffe Would you be willing to submit a PR to get this fixed?
