### ISSUE TITLE
CAS 5.0 Stablity and Release Timeline

### ISSUE THREAD

**Issue by loren138** [apereo/cas#1902]
Hi,
We're currently running CAS 4.1.6, however upgrading to 4.1.7 (or anything higher in the 4.1.x chain) results in an error that the principle is null on a successful login.  I tried my best and was unable to find what configuration value in particular we changed or missed that caused that problem.  (We build with a CAS overlay template and fairly minor changes.)

However, if I'm going to need to restructure the config files, it seemed better to jump to the 5.0 release set which seems to have very different (but hopefully much easier) configuration.  I see the M3 release is set for July 29th and the RCs after that so I was wondering how stable the configuration would be at the M3 release (and how good the documentation would be) if I could go ahead and get M3 running on our test server and potentially launch with RC1.

(We customize the deployerConfigContext.xml, propertyFileConfigurer.xml, casLoginView.jsp, top.jsp, and bottom.jsp and use one table SQL Server as our user repository with SHA-1 encrypted passwords and all the attributes for CAS contained in that table.  We do have varying attribute release policies based on the service.)

**Comment by dima767** [comment]
Please use mailing list for such questions - this will benefit the CAS community following the lists at large.

**Comment by mmoayyed** [comment]
If this turns out to be an actual issue with 4.1.x, please create an issue, attach your overlay to the issues project and include all other appropriate logs, and steps to dup. (Otherwise follow Dima's suggestion please)
