### ISSUE TITLE
Support for different password encoders for different authentication handlers

### ISSUE THREAD

**Issue by pmoubed** [apereo/cas#1913]
In CAS 4.2.3 there is no way to configure multiple/different password encoders per authentication handlers.

Practical scenario would be using JDBC and LDAP at same time. There should a way to define plain password encoder for LDAP and SHA1 for JDBC.

Please provide a way to configure different password encoder for each authentication handler.

Thanks.

**Comment by mmoayyed** [comment]
It's possible. It's just not pretty. 

Your LDAP handler does carry a passwordEncoder property. You can set it to to your own password encoder in your xml config and that will override what's preconfigured.

**Comment by pmoubed** [comment]
Can you please give an example of the workaround with proper XML?

**Comment by mmoayyed** [comment]
```
<bean id="ldapAuthenticationHandler" class="org.jasig.cas.authentication.LdapAuthenticationHandler"
      p:principalIdAttribute="sAMAccountName"
      p:passwordEncoder-ref="myEncoder"
      c:authenticator-ref="authenticator" />

<bean id="myEncoder" class="org.apereo.cas.SomePasswordEncoderThatTheProjectHas"
           p:hereWeSetAProperty="xyz" />


```

**Comment by mmoayyed** [comment]
and here are the set of enoders the project supports:
https://apereo.github.io/cas/4.2.x/javadocs/index.html

Or you write your own.

**Comment by netwolfuk** [comment]
Thank you. This solved my problem.
I am doing the exact same thing. JDBC and LDAP.
