### ISSUE TITLE
OAuth20CallbackAuthorizeController can NOT get the any URL from CallbackController(spring-webmvc-pac4j 1.1.1)

### ISSUE THREAD

**Issue by yisiqi** [apereo/cas#1916]
CAS Server: v5.0.0.M3
Container: Tomcat 8.0, Tomcat 8.5

OAuth module can't finish the Authorize Code Flow.

`OAuth20CallbackAuthorizeController` got a `null`, when getting callback url with pac4j's CallbackController. 

```java
package org.apereo.cas.support.oauth.web;

......

/**
 * OAuth callback authorize controller based on the pac4j callback controller.
 *
 * @author Jerome Leleu
 * @since 3.5.0
 */
@Controller("callbackAuthorizeController")
public class OAuth20CallbackAuthorizeController extends AbstractController {

   ......

    @RequestMapping(path = OAuthConstants.BASE_OAUTH20_URL + '/' + OAuthConstants.CALLBACK_AUTHORIZE_URL)
    @Override
    protected ModelAndView handleRequestInternal(final HttpServletRequest request, final HttpServletResponse response) throws Exception {
        final String url = StringUtils.remove(this.callbackController.callback(request, response), "redirect:");
        // url is null
        final J2EContext ctx = new J2EContext(request, response);
        final ProfileManager manager = new ProfileManager(ctx);
        return oAuth20CallbackAuthorizeViewResolver.resolve(ctx, manager, url);
    }

   ......

}
```

**Comment by yisiqi** [comment]
@mmoayyed @leleuj Should this be resolved in `CallbackController` or `OAuth20CallbackAuthorizeViewResolver`?

**Comment by mmoayyed** [comment]
Why is it null? Can you step through?

**Comment by yisiqi** [comment]
I just traced into `CallbackController`(spring-webmvc-pac4j 1.1.1). And it's `callback` method will always return null. 

I have a little confused.

```java
package org.pac4j.springframework.web;

......

/**
 * <p>This filter finishes the login process for an indirect client, based on the {@link #callbackLogic}.</p>
 *
 * <p>The configuration can be defined via property keys: <code>pac4j.callback.defaultUrl</code> (default url after login if none was requested),
 * <code>pac4j.callback.multiProfile</code> (whether multiple profiles should be kept) and
 * <code>pac4j.callback.renewSession</code> (whether the session must be renewed after login).</p>
 * <p>Or it can be defined via setter methods: {@link #setDefaultUrl(String)}, {@link #setMultiProfile(Boolean)} and ({@link #setRenewSession(Boolean)}.</p>
 *
 * @author Jerome Leleu
 * @since 1.0.0
 */
@Controller
public class CallbackController {

    ......

    @RequestMapping("/callback")
    public String callback(final HttpServletRequest request, final HttpServletResponse response) {

        assertNotNull("callbackLogic", callbackLogic);
        assertNotNull("config", config);
        final J2EContext context = new J2EContext(request, response, config.getSessionStore());

        callbackLogic.perform(context, config, J2ENopHttpActionAdapter.INSTANCE, this.defaultUrl, this.multiProfile, this.renewSession);

        return null;
    }

   ......

}

```

**Comment by mmoayyed** [comment]
Looks like a bug in pac4j? I am not sure why that method is designed to have a return value, and yet always returns null.

**Comment by leleuj** [comment]
The `return null` is normal. Redirections or any other HTTP response is applied directly to the response by the `perform` method (remember pac4j fits in for many frameworks with various schemes).
And indeed, the `final String url = StringUtils.remove(this.callbackController.callback(request, response), "redirect:");` does not make sense here.
If you want to get the redirection, you certainly need to get the "Location" header from the response.

**Comment by mmoayyed** [comment]
Shouldnt the return type of that method be changed to be void instead? If you're always returning null, why indicate that you're trying anything? Are there use cases where null is not returned?

**Comment by mmoayyed** [comment]
And, since the old behavior was to return the url: why not preserve compatibility and return that instead? rather than requiring the user to peek into "location"?

**Comment by leleuj** [comment]
You're right, we should certainly return `void`, that should make more sense. Tracked here: https://github.com/pac4j/spring-webmvc-pac4j/issues/8

For Spring Web MVC, `null` is always returned. I admit it's not backward compatible, but it should not be a big deal as you should not need to get this url, the redirection is performed automatically.

Why do you need to get the redirection url?

**Comment by yisiqi** [comment]
I just found this in `CallbackController`(spring-webmvc-pac4j 1.1.1):

```java
    @RequestMapping("/callback")
    public String callback(final HttpServletRequest request, final HttpServletResponse response) {

        assertNotNull("callbackLogic", callbackLogic);
        assertNotNull("config", config);
        final J2EContext context = new J2EContext(request, response, config.getSessionStore());

        callbackLogic.perform(context, config, J2ENopHttpActionAdapter.INSTANCE, this.defaultUrl, this.multiProfile, this.renewSession);

        return null;
    }
```

And

```java
public class J2ENopHttpActionAdapter implements HttpActionAdapter<Object, J2EContext> {

    public static final J2ENopHttpActionAdapter INSTANCE = new J2ENopHttpActionAdapter();

    @Override
    public Object adapt(int code, J2EContext context) {
        return null;
    }
}
```

Seems the redirection doesn't been performed yet.

**Comment by leleuj** [comment]
The redirection is performed here: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/engine/DefaultCallbackLogic.java#L110

**Comment by mmoayyed** [comment]
I'll run some tests later this evening and see if I can reorganize this change. Thanks for reviewing.

**Comment by mmoayyed** [comment]
See if RC1-SNAPSHOT solves this. I tested it somewhat thoroughly.

**Comment by leleuj** [comment]
Committed: https://github.com/pac4j/spring-webmvc-pac4j/commit/b9c283cacd5a5dd553c94c37b923e0defa4f1520
