### ISSUE TITLE
Login warning message appears on initial login

### ISSUE THREAD

**Issue by tduehr** [apereo/cas#1925]
I have included the following in my report:

- [4.3-SNAPSHOT] CAS server version
- [Tomcat8] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
- [see below] Steps to duplicate the problem
- [n/a] Stacktraces and CAS logs where appropriate.
- [n/a] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

When the user previously elected to have warnings when logging into other services and their TGC has expired or been removed, they will be warned they are already logged in after they authenticate.

**Comment by tduehr** [comment]
I will verify this in 5.0.0.RC1-SNAPSHOT once I get it working.

**Comment by mmoayyed** [comment]
Please do. There is no such thing as 4.3 anymore, and the SNAPSHOT if it exists, is super old.

**Comment by mmoayyed** [comment]
I suspect logout does not clear that warning cookie.

**Comment by tduehr** [comment]
Even if it did, there are other ways to be forced to authenticate. I suspect, but haven't tried, `reauth` will trigger this as well. I know if the TGC expires, the user is warned. This warning should only trigger if the login flow was bypassed due to a valid TGC.

**Comment by mmoayyed** [comment]
Agreed.

**Comment by mmoayyed** [comment]
Not relevant for 5 because that feature has been removed.

**Comment by mmoayyed** [comment]
I am wrong. I take that back. It's just not on by default in the UI.

**Comment by mmoayyed** [comment]
This appears fixed in master.
