### ISSUE TITLE
Service Ticket expires while viewing login warning

### ISSUE THREAD

**Issue by tduehr** [apereo/cas#1926]
I have included the following in my report:

- [4.3-SNAPSHOT] CAS server version
- [Tomcat8] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
- [see below] Steps to duplicate the problem
- [n/a] Stacktraces and CAS logs where appropriate.
- [n/a] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

A service ticket is issued before the user is sent to the login warning page. If the user doesn't continue quickly, the ticket will expire.

to reproduce:
1. login to service A checking the login warning box.
1. Visit service B.
1. Wait the configured service ticket life before clicking continue.

The service will provide its configured error for an invalid service ticket.

**Comment by tduehr** [comment]
Like #1925 I need to validate against the 5.0 line but I'm almost positive this is still an issue.

**Comment by mmoayyed** [comment]
Agreed here as well. This is an issue.

**Comment by mmoayyed** [comment]
Btw, no config overlay is available for this issue here: https://github.com/cas-projects/cas-issues/pulls

Although it's not needed really, just wanted to clarify.

**Comment by mmoayyed** [comment]
Not relevant for 5 because that feature has been removed.

**Comment by mmoayyed** [comment]
I am wrong. I take that back. It's just not on by default in the UI.

**Comment by mmoayyed** [comment]
Appears fixed in master.
