### ISSUE TITLE
Google Apps Integration Error

### ISSUE THREAD

**Issue by davidabney9** [apereo/cas#1931]
I have included the following in my report:

- [4.2.3] CAS server version
- [Apache Tomcat 7.0.52, Java 1.8.0_91, Ubuntu 14.04.4] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
- [See Below] Steps to duplicate the problem
- [[cas.log.txt](https://github.com/apereo/cas/files/391148/cas.log.txt)] Stacktraces and CAS logs where appropriate.
- [n/a] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

1. I followed the steps located in this document to enable the Google Apps integration: https://apereo.github.io/cas/4.2.x/integration/Google-Apps-Integration.html.
2. Added the registered service to CAS that is designed to use the Google Apps Integration, it is a Jenzabar portal.
3. I put the public key for CAS on the Jenzabar portal.
4. Went to login to the Jenzabar portal, I was redirected to CAS, I logged into CAS using my LDAP credentials.
5. I received a "CAS is unavailable" error message after logging into CAS and I have attached the error log.  Also, an extra bit of information, the Google Apps Integration appears to work in CAS v4.2.0.

**Comment by mmoayyed** [comment]
Appreciate the submission. 

Try with 4.2.5-SNAPSHOT. Use a -U to force the fix to be downloaded for you. Should be fixed already. Report back please.

**Comment by davidabney9** [comment]
Thanks, that fixed the issue.  I will respond to my message on the listserv.

––––––––––––––––––––
David Abney
ITS Web Developer/Programmer

600 West Walnut Street
Danville, Kentucky 40422
859.238.5761

[email_logo]
www.centre.edu<http://www.centre.edu/>

**Comment by mmoayyed** [comment]
Awesome. Stay on the snapshot and you will receive goodness as we make progress. At release time, switch back to the normal 4.2.5.
