### ISSUE TITLE
Login ticket protocol requirement

### ISSUE THREAD

**Issue by jsumners** [apereo/cas#1939]
[Section 2.2.2][2.2.2] states:

> lt [REQUIRED] - a login ticket. This is provided as part of the login form discussed in Section 2.1.3. The login ticket itself is discussed in Section 3.5.

Whereas [Section 3.5][3.5] states:

> A login ticket is an optional string that MAY be provided by /login as a credential requester and passed to /login as a credential acceptor for username/password authentication. Its purpose is to prevent the replaying of credentials due to bugs in web browsers.

This conflict should be cleared up. The [mailing list][ml] states that the login ticket is optional in the protocol so I believe section 3.5 to be the correct section.

Personally, I think it should be removed completely. This is more of an implementation detail than an actual protocol detail; i.e. it's describing how the reference implementation has chosen to prevent certain types of web form attacks.

[2.2.2]: https://github.com/apereo/cas/blob/c842f06a5f9f60ef0ff8f03f1f193998b61245d5/cas-server-documentation/protocol/CAS-Protocol-Specification.md#222-parameters-for-usernamepassword-authentication
[3.5]: https://github.com/apereo/cas/blob/c842f06a5f9f60ef0ff8f03f1f193998b61245d5/cas-server-documentation/protocol/CAS-Protocol-Specification.md#35-login-ticket
[ml]: https://groups.google.com/d/msg/cas-dev/pXRuYy6RGGk/Sx6smlDhBgAJ

**Comment by mmoayyed** [comment]
Corrected. Thanks.
