### ISSUE TITLE
Invalid ticket type exception when encrypting tickets with Memcached

### ISSUE THREAD

**Issue by johnmichaelbradley** [apereo/cas#1942]
I am working on a clustered CAS 4.2.4 installation (deployed to two Linux-based Tomcat servers) based on the overlay template at https://github.com/Jasig/cas-overlay-template.git. I am using two Memcached instances for ticket management. These Memcached instances are on separate servers in different networks, so encrypting and signing tickets would be desirable.

Thanks to Misagh Moayyed's help, I was able to get past my initial problems. Now CAS is able to render the "Log In Successful" page, but I have my suspicions. The text of the page partially reads "You, _nobody_, have successfully logged into the Central Authentication Service." Also, the following shows up in the server log:

`ERROR org.jasig.cas.ticket.registry.MemCacheTicketRegistry - Failed adding [f26dd67a5b1da390c54cb27cabd0d4a8cd4c59e877851e3eafc77289fd8b232e469f170f522b0a6779ac3135d4a157f9ecbf904a484693ac08d0cdc0a820585a]
java.lang.IllegalArgumentException: Invalid ticket type
    at org.jasig.cas.ticket.registry.MemCacheTicketRegistry.getTimeout(MemCacheTicketRegistry.java:255) ~[cas-server-integration-memcached-4.2.4.jar:4.2.4]
    at org.jasig.cas.ticket.registry.MemCacheTicketRegistry.addTicket_aroundBody0(MemCacheTicketRegistry.java:131) [cas-server-integration-memcached-4.2.4.jar:4.2.4]
    at org.jasig.cas.ticket.registry.MemCacheTicketRegistry$AjcClosure1.run(MemCacheTicketRegistry.java:1) [cas-server-integration-memcached-4.2.4.jar:4.2.4]
`

For more information, please see this post in the mailing list: https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/xYh0z6S9eV4

**Comment by mmoayyed** [comment]
Wait for about 15 mins. Then switch to 4.2.5-SNAPSHOT in your pom for cas server version and rebuild using the -U command to force an update and get the new snapshot. Report back please.

**Comment by mmoayyed** [comment]
The fix should be in. Go ahead and try at your earliest convenience

**Comment by johnmichaelbradley** [comment]
Well done! It's fixed. Thanks, Misagh!

**Comment by mmoayyed** [comment]
Pleasure
