### ISSUE TITLE
OIDC support: discovery endpoint is producing wrong field names

### ISSUE THREAD

**Issue by leleuj** [apereo/cas#1945]
When using the OpenID Connect server support, the discovery url does not return the `subject_types_supported` field.
In the spec, it says it SHOULD and not MUST so it doesn't seem to be mandatory, though there is an ambiguity which leads implementations to require it or not.

In the pac4j `OidcClient` (based on the Nimbus SDK), it fails due to this missing field.

After some discussion with his creator, the recommendation would be to add this field, while the spec is fixed.

**Comment by mmoayyed** [comment]
Isnt this what you're after? 
https://github.com/apereo/cas/blob/master/cas-server-support-oidc/src/main/java/org/apereo/cas/web/controllers/OidcWellKnownEndpointController.java#L47

**Comment by leleuj** [comment]
Here is the metadata returned by the CAS discovery url:

```json
{  
   "supportedScopes":[  
      "openid",
      "profile",
      "email",
      "address",
      "phone",
      "offline_access"
   ],
   "supportedResponseTypes":[  
      "code",
      "token"
   ],
   "supportedSubjectTypes":[  
      "public",
      "pairwise"
   ],
   "supportedClaimTypes":[  
      "normal"
   ],
   "supportedClaims":[  
      "sub",
      "name",
      "preferred_username",
      "family_name",
      "given_name",
      "middle_name",
      "given_name",
      "profile",
      "picture",
      "nickname",
      "website",
      "zoneinfo",
      "locale",
      "updated_at",
      "birthdate",
      "email",
      "email_verified",
      "phone_number",
      "phone_number_verified",
      "address"
   ],
   "supportedGrantTypes":[  
      "authorization_code",
      "password",
      "implicit"
   ],
   "issuer":"http://localhost:8080/cas/oidc",
   "authorizationEndpoint":"https://cas.example.org:8443/cas/oauth2.0/authorize",
   "tokenEndpoint":"https://cas.example.org:8443/cas/oauth2.0/accessToken",
   "userinfoEndpoint":"https://cas.example.org:8443/cas/oauth2.0/profile",
   "jwksEndpoint":"https://cas.example.org:8443/cas/oidc/jwks",
   "registrationEndpoint":"https://cas.example.org:8443/cas/oidc/register",
   "introspectionEndpoint":"https://cas.example.org:8443/cas/oidc/introspect",
   "revocationEndpoint":"https://cas.example.org:8443/cas/oidc/revocation"
}
```

Reading the spec (http://openid.net/specs/openid-connect-discovery-1_0-17.html), I see: `subject_types_supported` for example and this is what I get with IdentityServer4 for example.

With the Nimbus SDK, I get the error:

```java
Exception in thread "main" org.pac4j.core.exception.TechnicalException: com.nimbusds.oauth2.sdk.ParseException: Missing JSON object member with key "subject_types_supported"
```

I think there is an issue with the attribute names in the metadata.

**Comment by mmoayyed** [comment]
You're right. The claims are wrong. Here is the correct version done for shibboleth: https://shibboleth-oidc.herokuapp.com/idp/.well-known

**Comment by mmoayyed** [comment]
@leleuj RC1 is coming up tomorrow. Given this is a known bug we can fix it post RC but I want to ask you if you think it possible to get a patch in before Monday?

**Comment by leleuj** [comment]
Did you test the OIDC support already?

Because I have found several problems (apart from the discovery url) which I'm working on, but I'm not sure to be able to fix everything before Monday.

I have already checked the OAuth support and updated the pac4j `CasOAuthWrapperClient` to accommodate the changes (new JSON format response).

**Comment by mmoayyed** [comment]
Which client are you using? I ran tests against this https://github.com/mitreid-connect/simple-web-app and it worked fine though I understand yours might be more vigilant. 

If possible, I'd like to fix the discovery endpoint first. That's a known bug we can address right now. If there are other things you have found, we can do them post RC.

**Comment by mmoayyed** [comment]
Another option would be to just punt this for RC2.

**Comment by leleuj** [comment]
I'm surprised it worked with mitreid with the current discovery url. I will do more tests today and at worst submit the changes I have: we'll decide then.

**Comment by leleuj** [comment]
I'm using the `OidcClient` which has been tested with Google, IdentityServer, Azure... based on the nimbus SDK.

**Comment by mmoayyed** [comment]
Interesting. Might be more robust perhaps, or I may have been careless. Though I admit I didnt test discovery all that much. Mostly just the endpoints. 

What other things you have found and fixed?

**Comment by leleuj** [comment]
The metadata returns that the OIDC authorize endpoint is /oauth2.0/authorize for example. Which is strange and does not work because the AccessTokenResponseGenerator is the OAuth 2 one and not the OIDC one and thus, the ID token is missing.

Going down that road, `@Controller` is missing for most OIDC endpoints and the `oauthSecConfig` cannot be used (different callback url)...

**Comment by leleuj** [comment]
Do we agree that you developed the OIDC support to have its own urls: `/oidc/authorize` for example or am I missing something?

**Comment by mmoayyed** [comment]
Yes, all OIDC endpoints are mapped to `/oidc/*`, yet they attempt to delegate to the OAuth 2.0 endpoints and override behavior where necessary. In reality, only the discovery endpoint and the JWKS endpoint are OIDC specific. Everything else is delegated, and overridden in certain cases. Much less code.

**Comment by leleuj** [comment]
The delegation to the OAuth 2.0 endpoints (internally right?) is a good idea, but the callback url depends on the url: how can it work except by having a second callback url dedicated to OIDC?

**Comment by mmoayyed** [comment]
Reviewed. Few notes:

1. Controller annotations that are missing are intentional. They inherit from a base controller that has that configured. That is sufficient.
2. OIDC defines its own callbackAuthorizeViewResolver

**Comment by leleuj** [comment]
1. Sure. That was I was thinking, but it doesn't work for me. These endpoints are never mapped (404 error page + nothing in spring mvc logs)

2. What about the `OAuthCallbackAuthorizeService` defined on `/oauth2.0/callbackAuthorize` versus `/oidc/callbackAuthorize`?

**Comment by mmoayyed** [comment]
1. Cool. Lets add them then. 
2. The flow as far as I remember should be that when the user is redirected back to the `/oauth2.0/callbackAuthorize`, the view resolver that is defined by OIDC and conditionally injected into the context takes over and handles that.

See

```java
@RequestMapping(path = OAuthConstants.BASE_OAUTH20_URL + '/' + OAuthConstants.CALLBACK_AUTHORIZE_URL)
    public ModelAndView handleRequestInternal(final HttpServletRequest request, final HttpServletResponse response) throws Exception {
        this.callbackController.callback(request, response);
        final String url = StringUtils.remove(response.getHeader("Location"), "redirect:");
        final J2EContext ctx = new J2EContext(request, response);
        final ProfileManager manager = new ProfileManager(ctx);
        return oAuth20CallbackAuthorizeViewResolver.resolve(ctx, manager, url); //this is the important part.
    }
```

Then in the OIDC configuration, see:

```
public OAuth20CallbackAuthorizeViewResolver callbackAuthorizeViewResolver() {}
```

**Comment by mmoayyed** [comment]
So the OIDC callbackAuthorizeViewResolver basically does the same thing as the original OAuth one did, except it handles some specific OIDC parameters.

**Comment by leleuj** [comment]
I have found a way and fixed another issue (missing "token_type" for the "access_token"), but I won't have time to finish before Monday. I'll keep you posted next week.

**Comment by mmoayyed** [comment]
No problem. What might be reasonable timeline? Shall we delay the RC for about 2-3 extra days?

**Comment by leleuj** [comment]
One week, to be sure I can finish next week.

**Comment by mmoayyed** [comment]
Sounds good.

**Comment by leleuj** [comment]
I've fixed the latest issue with this missing parameter in the discovery url:

```
id_token_signing_alg_values_supported
REQUIRED. JSON array containing a list of the JWS signing algorithms (alg values) supported by the OP for the ID Token to encode the Claims in a JWT [JWT]. The algorithm RS256 MUST be included. The value none MAY be supported, but MUST NOT be used unless the Response Type used returns no ID Token from the Authorization Endpoint (such as when using the Authorization Code Flow).
```

Now fighting with the Checkstyle rules...

**Comment by leleuj** [comment]
Here is the required changes in CAS to make OIDC support work: https://github.com/apereo/cas/pull/1961

The CAS OIDC support was updated on pac4j as well: https://github.com/pac4j/pac4j/pull/634

The OAuth support has been re-tested and the `CasOAuthWrapperClient` updated in pac4j to accommodate the changes (the new JSON response format).
