### ISSUE TITLE
RememberMeMaxAge being applied when not requested

### ISSUE THREAD

**Issue by tsschmidt** [apereo/cas#1949]
Found this issue when setting up a CAS 5.0.0 server from master.  The TGC max age was always being set for two weeks.  Traced it to CookieRetrievingCookieGenerator line 64.  Looks like the if() here should be changed to StringUtils.isBlank instead of StringUtils.isNotBlank,  The rememberMeMax age is being applied even though it is commented out in the webflow and not requested.

**Comment by mmoayyed** [comment]
Sounds reasonable. Would you want to handle this and send along a patch?

**Comment by tsschmidt** [comment]
I am still waiting on my employer to sign the release.  So right now I can
not submit a pull request.

**Comment by mmoayyed** [comment]
This is taken care of.
