### ISSUE TITLE
AbstractMultifactorAuthenticationProvider implementations need to be @Autowired

### ISSUE THREAD

**Issue by tsschmidt** [apereo/cas#1958]
Found this setting up Duo MFA with the latest CAS 5.0.0 master.  I was getting a null pointer exception when getOrder() of DuoMultifactorAuthenticaionProvider was being called during start up.   AbstractMultifactorAuthenticationProvider has CasConfigurationProperties marked as being @Autowired.  In DuoConfiguration though the implementation class was being created by calling new DuoMultifactorAuthenticationProvider() and bypassing spring Autowiring.  

Adding DuoMultifactorAuthenticationProvider as an @Autowired member of DuoConfiguration and changing the getter method to this:

    @Bean
    @RefreshScope
    public MultifactorAuthenticationProvider duoAuthenticationProvider() {
        provider.setDuoAuthenticationService(duoAuthenticationService());
        return provider;
    }

made the problem go away.  I am assuming similar changes would need to be made to all MFAProvider implementations, or find a different way to inject CasConfigurationProperties to the base class.

**Comment by mmoayyed** [comment]
Is this already done https://github.com/apereo/cas/blob/master/cas-server-support-duo/src/main/java/org/apereo/cas/adaptors/duo/config/DuoConfiguration.java#L151 ?

**Comment by tsschmidt** [comment]
Doesn't appear to be.  The object is being created by calling the new().  Unless their is some other Spring Boot magic that is supposed to be happening here that I am not aware of.

**Comment by mmoayyed** [comment]
I'll take a look. Ignore new. Boot magic.

**Comment by mmoayyed** [comment]
Cant duplicate. Declared duo module, declared settings. No errors. I most observed start-up behavior as you noted. No NPEs.

**Comment by mmoayyed** [comment]
![image](https://cloud.githubusercontent.com/assets/1205228/17784518/a2d40a1e-6531-11e6-9f50-6d08b12ad869.png)

And this worked fine too.

**Comment by tsschmidt** [comment]
OK, I think I see my problem.  I am not 100% up on Boot yet.  I was using the same build command for previous versions.  I think adding "bootRun" to the build command will fix my issue.  

Thanks for taking a look.

**Comment by mmoayyed** [comment]
Pleasure. Thank you for testing!

**Comment by tsschmidt** [comment]
Just to document the solution.  I was running the build script without this
option "-DskipAspectJ=true".  And the NPE was being hit in code generated
by AspectJ.  Running clean and building without AspectJ cleared the issue.
