### ISSUE TITLE
Build support for Kotlin

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#1959]
This is a placeholder for discussing the possibility of allowing CAS to support Kotlin as a language for source files. This should reduce much of Java-induced noise and would potentially allow us to remove boilerplate code in favor of Kotlin idioms.

**Comment by dima767** [comment]
+1 on exploring the Kotlin route

**Comment by robertoschwald** [comment]
Why not Groovy?

**Comment by dima767** [comment]
It could be anything really ;-) Kotlin seems like getting a lot of traction and would be a good candidate to try out. No 1 lang vs another lang flame wars here ;-)

**Comment by mmoayyed** [comment]
No preference here really. This is a very good read: http://melix.github.io/blog/2016/05/gradle-kotlin.html

Most differentiating factor to me seems to be that Kotlin is an instantiation of Groovy+Scala with a static type system and compilation. I would consider that a safer choice, given that it's built into the language.

**Comment by robertoschwald** [comment]
I was just asking because Kotlin is cutting edge and currently has some drawbacks (like static logger workarounds, etc.) and Groovy can be compiled statically as well.

**Comment by dima767** [comment]
In any case, this is here just to try it out and see what comes out of it...

**Comment by mmoayyed** [comment]
Handled in 5.1 RC2
