### ISSUE TITLE
Setting spring.jmx.default-domain To Unique Values For cas-server-webapp and cas-management-webapp For CAS 5

### ISSUE THREAD

**Issue by wcrowell** [apereo/cas#1962]
This is not a bug.

cas-server-webapp and cas-management-webapp are deployed on the same server which are both Spring Boot applications in CAS 5.  I know this is not typical when deploying these applications as they usually are on different servers.

This results in the following exception:

`...
2016-08-19 17:37:08,442 ERROR [org.springframework.boot.SpringApplication] - <Application startup failed>
org.springframework.jmx.export.UnableToRegisterMBeanException: Unable to register MBean [org.springframework.cloud.context.environment.EnvironmentManager@19480877] with key 'environmentManager'; nested exception is javax.management.InstanceAlreadyExistsException: org.springframework.cloud.context.environment:name=environmentManager,type=EnvironmentManager
        at org.springframework.jmx.export.MBeanExporter.registerBeanNameOrInstance(MBeanExporter.java:625) ~[spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
        at org.springframework.jmx.export.MBeanExporter.registerBeans(MBeanExporter.java:550) ~[spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
...
`

In src/main/resources/bootstrap.properties in both cas-server-webapp and cas-management-webapp, the spring.jmx.default-domain is not set.  

Could I suggest setting this value uniquely for both applications in bootstrap.properties?

Environment details:

- CAS server version
- Tomcat 8.0.32
- Deploy cas-server-webapp and cas-management-webapp on the same server.

**Comment by mmoayyed** [comment]
Feel free to submit a patch.

**Comment by wcrowell** [comment]
Will do.  Thanks!
