### ISSUE TITLE
Statistic view on ST 

### ISSUE THREAD

**Issue by M4t3o** [apereo/cas#1964]
Hi 

My context : 
- CAS 4.2.4 (Maven Overlay install)
- Tomcat 7
- ServicesRegistry : **json**
- TicketRegistry : **ehcache**

After some hours, everything seems to work as expected.
I can see active TGTs on /cas/statistics with  ehcacheMonitor enabled.

But there is nothing about STs ?
Is it possible to get something like : 
`<alias name="ticketServiceCache" alias="ehcacheMonitorCache" />`
?

Thanks for your great work :)

**Comment by M4t3o** [comment]
Hi
from the mailing list (http://goo.gl/4tFNKy) : 
"Looks like expired STs were always fixed to 0 on the stats page. File an issue please."

More informations about the problem : 
t seems very strange, i explain :

- on /cas/statistics/ssosessions, i can see the usage count increment and what services are using
- on cas/statistics, the gauge on Unexpired & Expireds STs are always null

I think the feature is already present but the gauge doesn't use the right counter maybe.

**Comment by mmoayyed** [comment]
Try with 4.2.5-SNAPSHOT.

**Comment by M4t3o** [comment]
This is the same problem with : 

******************** Welcome to CAS *******************
CAS Version: 4.2.5-SNAPSHOT
Build Date/Time: 2016-08-26T06:38:28.000+02:00
Java Home: /usr/lib/jvm/j2sdk1.7-oracle/jre
Java Vendor: Oracle Corporation
Java Version: 1.7.0_72
OS Architecture: amd64
OS Name: Linux
OS Version: 3.2.0-4-amd64
*******************************************************

Screenshots added.
![ssoview](https://cloud.githubusercontent.com/assets/12034566/18005373/e1bb22b2-6b99-11e6-99e4-13e1c72d5030.png)
![statview](https://cloud.githubusercontent.com/assets/12034566/18005378/e4e463b8-6b99-11e6-9465-cfbcb186fba3.png)

The page /cas/statistics should display "Unexpired Tickets  2" i guess.

**Comment by mmoayyed** [comment]
No that's irrelevant. Usage count is different

**Comment by M4t3o** [comment]
Really ?
The usage of TGT is directly mapped to ST (with SSO enabled) count in my context.
Maybe it's not relevant for everyone...
What counter is represented by "Statistics View" about STs ?
Why do they stay null ?

**Comment by mmoayyed** [comment]
It's not a question of to whom it's irrelevant. What I was trying to get at was, you're mixing usage count with something else.
