### ISSUE TITLE
Proxy Tickets Are Already Used/Expired Immediately After Being Issued

### ISSUE THREAD

**Issue by wcrowell** [apereo/cas#1966]
I have included the following in my report:

- CAS server version: 5.0.0.RC1-SNAPSHOT
- Container/environment type/version: Tomcat 8.0.32 on MacOSX
- Steps to duplicate the problem:

1) Post a user name and password to /cas/v1/tickets and get a Ticket Granting Ticket.

2) Post the Ticket Granting Ticket and registered service you want to access (in this case "/protected-web-app") to "/cas/v1/tickets/<TGT>" where TGT is the Ticket Granting Ticket and obtain a Service Ticket.

3) Send a GET request to "/cas/serviceValidate" containing the service to access, the Service Ticket, and the proxy URL of the service (in this case "/protected-web-app/proxyUrl" which is the CAS client).  A Proxy Granting Ticket IOU will be issued.

4) Send a GET request to the proxy URL of the service (in this case "/protected-web-app/proxyUrl" which is the CAS client) and get a Proxy Granting Ticket.

5) Send a GET request to "/cas/proxy" containing the Proxy Granting Ticket and get a one-time use Proxy Ticket.

6) Send a GET request to "/cas/proxyValidate" containing the service to access (in this case "/protected-web-app"), the Proxy Ticket, and the proxy URL (in this case "/protected-web-app/proxyUrl" which is the CAS client).  You should get the corresponding Proxy Granting Ticket and proxy URL that was issued for this Proxy Ticket.

Step 6 is where it fails and says the Proxy Ticket was already used.  

- Stacktraces and CAS logs where appropriate: Link to the log: [https://raw.githubusercontent.com/wcrowell/cas-functional-tests/5.0.x/logs/catalina.out](https://raw.githubusercontent.com/wcrowell/cas-functional-tests/5.0.x/logs/catalina.out)

Look at the 2 lines around 4:04:44pm:
`
2016-08-22 16:06:44,605 DEBUG [org.apereo.cas.ticket.support.MultiTimeUseOrTimeoutExpirationPolicy] - <Ticket usage count 1 is greater than or equal to 1>
2016-08-22 16:06:44,606 DEBUG [org.apereo.cas.ticket.registry.DefaultTicketRegistry] - <Removing ticket [ST-1-pbhtA5brbBiYabVpygfn-192] from the registry.>
`

**Comment by mmoayyed** [comment]
The 2 lines you outlined are fine. I am lots more concerned about this:

```
WARN [org.apereo.cas.web.ProxyValidateController] - <Service ticket [PT-2-f96UqRibdLcYREKZhh9N-192] does not satisfy validation specification.>
```

Find this line:
https://github.com/apereo/cas/blob/master/cas-server-support-validation/src/main/java/org/apereo/cas/web/config/CasValidationConfiguration.java#L198

Change it to:

```
c.setValidationSpecification(cas20ProtocolValidationSpecification);
```

Rerun tests.

**Comment by mmoayyed** [comment]
Needless to say, if that works submit a PR please :)

**Comment by wcrowell** [comment]
Will do.  No problem.

**Comment by wcrowell** [comment]
That appears to have fixed it.  Running more tests.
