### ISSUE TITLE
OIDC: Add new field for signing algorithm to management app

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#1976]

**Comment by leleuj** [comment]
@mmoayyed Just to be sure:

Currently, we decide whether idToken must be signed or not at the OIDC service level. Then, we expect the JWKS to be a RSA key and use the `RSA_USING_SHA256` algorithm.

Generally, we can set the `cas.authn.oidc.idTokenSigningAlgs` property to `none` if no OIDC services sign the idTokens, `RS256` if all OIDC services sign the idTokens and maybe `none,RS256` if some OIDC services require signing and others don't.

What do we want to change? Add the ability to choose between `RSA_USING_SHA256`, `RSA_USING_SHA384` and `RSA_USING_SHA512` at the OIDC service level via the management web app?

**Comment by mmoayyed** [comment]
Yes. Since JWKS can be service-specific, the algorithm type used may also be service-specific. 

Also we need to take into account that property when we actually sign the token. It's not used anywhere else today other than discovery. Quick search shows that `getIdTokenSigningAlgs` is not used at all other than in discovery?

**Comment by leleuj** [comment]
In fact, the `idTokenSigningAlgs` is the sum of all available algorithms. It could be somehow computed by looping through all OIDC services.

**Comment by mmoayyed** [comment]
I am not sure that would work. `idTokenSigningAlgs` is only used in the discovery endpoint. You cannot expect services to exist in order to compute that value for discovery. That will cause breakage in the future. A better usage of that field would be to: remove the property altogether and compute the supported algorithms based on what "the system" actually can support. Look into JCE and other relevant areas to figure out what algs are supported by default. 

Also, just because `idTokenSigningAlgs` is set to `none` that does not mean that id tokens will not be signed. That's just an advertisement. If that field says "none RS256" that means that the IdP supports unsigned tokens, as  well as signed tokens by RS256. How we do make a decision when to sign things? That is predicated on the fact that whether a JWKS exists for the service or not. If it does, tokens are signed. If not, they are not.

In our implementation, "none" will always exist as a supported alg. The rest of the algs as I thought before MAY be calculated based on what the system supports.

I had a look at the OIDC service defn: looks like algorithm support on a per-service isnt even there yet. So this issue is just void. We could turn it into a feature request for later.

**Comment by mmoayyed** [comment]
PS We can let the use choose what algs can be supported via discovery, but I am almost sure nobody would be inclined to set that property for the time being. Maybe a future enhancement to allow overrides...and that's a big maybe.

**Comment by leleuj** [comment]
This is how I compute the signing algorithms:

```java
        final Set<String> signingAlgorithms = new HashSet<>();
        final Collection<RegisteredService> services = servicesManager.getAllServices();
        for (final RegisteredService service : services) {
            if (service instanceof OidcRegisteredService) {
                final OidcRegisteredService oidcService = (OidcRegisteredService) service;
                if (!oidcService.isSignIdToken()) {
                    signingAlgorithms.add(AlgorithmIdentifiers.NONE);
                } else {
                    signingAlgorithms.add(oidcService.getSigningAlgorithm()); // or add("RS256");
                }
            }
        }
        discoveryProperties.setIdTokenSigningAlgValuesSupported(signingAlgorithms);
```

That make sense to me, but we can just have a static value: `none,RS256` (or `none,RS256,RS384,RS512`).

About the webapp UI update to be able to define signing algorithm, you want to do that later?

**Comment by mmoayyed** [comment]
The problem we that snippet is, if there are no services available the discovery endpoint would produce nothing for the alg values which is invalid. That doesn't seem correct to me.

> id_token_signing_alg_values_supported
REQUIRED. JSON array containing a list of the JWS signing algorithms (alg values) supported by the OP for the ID Token to encode the Claims in a JWT [JWT]. The algorithm RS256 MUST be included. The value none MAY be supported, but MUST NOT be used unless the Response Type used returns no ID Token from the Authorization Endpoint (such as when using the Authorization Code Flow).

I like the static option better as `none,RS256` (and perhaps we can let that be controlled by the current property). 

And yes, lets do the webapp UI later.

**Comment by leleuj** [comment]
OK.

When doing some tests, I found out a strange behaviour since RC1. Specific service definitions seems lost (with the JSON services rgistry):

```
2016-09-12 12:14:46,365 INFO [org.apereo.cas.services.DefaultServicesManagerImpl] - <Loaded 5 services from JsonServiceRegistryDao.>
2016-09-12 12:14:46,369 INFO [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <Beginning ticket cleanup...>
2016-09-12 12:14:46,370 INFO [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <0 expired tickets removed.>
2016-09-12 12:14:46,370 INFO [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <Finished ticket cleanup.>
2016-09-12 12:15:02,033 INFO [org.apereo.cas.services.DefaultServicesManagerImpl] - <Loaded 2 services from JsonServiceRegistryDao.>
```

5 becomes 2. Have you encountered that issue?

**Comment by mmoayyed** [comment]
Cant say I have. It's possible the auto-loading behavior of the registry is interfering with tests. I typically would use the InMemory service manager for tests. 

Which test is that by the way?

**Comment by leleuj** [comment]
I'm talking about manual tests and I use my default overlay-demo: https://github.com/leleuj/cas-overlay-demo

**Comment by mmoayyed** [comment]
Gotcha. Yes, I think that's what causing that behavior (the autoloading the service definitions perhaps) but as far as I know, the registry is only auto-loaded if it's empty.

**Comment by mmoayyed** [comment]
Closing in favor of #2068
