### ISSUE TITLE
STs counter on statistic view

### ISSUE THREAD

**Issue by M4t3o** [apereo/cas#1977]
Hello
This is my context : 
    CAS 4.2.5 (Maven Overlay install)
    Tomcat 7
    ServicesRegistry : json
    TicketRegistry : ehcache
    Authentification LDAP ActiveDirectory
    Attributes settings with SAML

(I try with memcached TicketRegistry too, same problem)

In both cases, the STs counter (expired ot not) always stay null.
How to reproduce : 
- auth --> TGT
- go to services SSO enabled --> ST

The /cas/statistics page seems unable to show ST statistic.
(No relevant errors in CAS log.)
I don't understand how "Expired ST" can be count because there is not expiration date on these.
But for active ones, it should be possible ?

**Comment by mmoayyed** [comment]
Lets try to clarify one thing first: There is no such thing as 4.2.5 yet. So are you sure you're on the correct SNAPSHOT release?

**Comment by mmoayyed** [comment]
> I don't understand how "Expired ST" can be count because there is not expiration date on these.

There is always an expiration policy associated with STs. Unless you have disabled it.

**Comment by mmoayyed** [comment]
> go to services SSO enabled --> ST

This will immediately invalidate the ST and remove it from the registry. Your ST count will remain as 0.

**Comment by mmoayyed** [comment]
And if you turn up CAS DEBUG logs and observe, you will notice that ST is removed from the registry.
