### ISSUE TITLE
servlet-api-2.4.jar gets included when building overlay with maven and SPNEGO

### ISSUE THREAD

**Issue by bplessis** [apereo/cas#1990]
Hi,

I have experienced a few 500 errors with SPNEGO/CAS 4.2.4 (not tested 4.2.5 but the root cause seem to be still there).

The error was found in the "localhost." log file of the tomcat servlet engine, something like:
The method getDispatcherType() is undefined for the type HttpServletRequest"

This error led me to inspecting the war file in search for servlet-api jar and i found out that the servlet-api-2.4.jar was added in the project when adding spnego dependency, apparently ultimately due to jcifs package.

A friend helping me with CAS provided the following block for maven dependency:

```
        <dependency>
            <groupId>org.jasig.cas</groupId>
            <artifactId>cas-server-support-spnego-webflow</artifactId>
            <version>${cas.version}</version>
            <!-- Sinon inclu la lib servlet 2.4 dans le war -->
            <exclusions>
                <exclusion>
                    <groupId>javax.servlet</groupId>
                    <artifactId>servlet-api</artifactId>
                </exclusion>
            </exclusions>
       </dependency>
```

And this fixed the issue that appeared on the servlet in some weird conditions.

**Comment by mmoayyed** [comment]
This should be handled via 4.2.6-SNAPSHOT.
