### ISSUE TITLE
Request for customizable validation URLs in Yubikey Authentication Handler

### ISSUE THREAD

**Issue by pmarasse** [apereo/cas#1998]
We will use Yubikeys with customized cryptographic keys, so Yubico's public servers will not be able to validate our tokens.

So I need to customize yubikey's validation URLs, but unfortunately there's no CAS property to achieve that, yet.

It seems that Yubico client is already aware of this possibility via `YubicoClient.setWsapiUrls(String[] wsapi)` method.

Can this parameter be added to CAS ?

**Comment by mmoayyed** [comment]
This should be handled now in RC2.
