### ISSUE TITLE
Webflow Redirection not working with LDAP password policy and Google Apps

### ISSUE THREAD

**Issue by petracvv** [apereo/cas#2002]
CAS Version: 4.2.5
Container: Tomcat 8.0.37

We recently did an upgrade from 4.2.0 to 4.2.5 and encountered an unusual issue related to password expiration and Google Apps integration. When someone has a password that expires within our warning limit ( password.policy.warningDays=15 ) and they try to log into our google apps instance, they are presented with the warning screen telling them how many days left they have before expiration. On this screen there is a continue link but when that link is clicked, they are presented with a blank page or a browser error ( ERR_EMPTY_RESPONSE in Google Chrome).

Looking at the request logs, I am seeing the webflow execution request from the continue button but the application is returning a 400 code instead of the 302. Other applications or services that are using CAS redirect just fine when used with an account within our warning limit.

Example access log entry:
https://gist.github.com/petracvv/cff0715781bc5eb8a4ebc7eba7f0fcb3

The authentication does succeed (the ticket is granted to the client) and if you go to the Gmail login for your domain or any other CAS site you will be logged in. The redirection is all that seems to fail.

Steps to reproduce:
1) Have an LDAP account with a password that expires within the configured warning period
2) Have a Google Apps domain configured to use your CAS server
3) Attempt to log in with the LDAP account to the Google Apps domain using the appropriate username
4) Enter your credentials on the CAS login page after being redirected from the Google login
5) See the password expiration warning page and click the continue link.
6) See a blank page instead of a redirection to the google service you logged in to.

I will be pushing an overlay with credentials removed to the cas-issues project shortly

----------------------------------------------
I have included the following in my report:

- [x] CAS server version
- [x] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
- [x] Steps to duplicate the problem
- [x] Stacktraces and CAS logs where appropriate.
- [x] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

**Comment by mmoayyed** [comment]
Thank you for the bug report. While I am almost sure this is a bug, it would be helpful if you actually provide CAS logs. Not access logs.

**Comment by petracvv** [comment]
Sorry about that. I did not see any error or traceback in the logs even with debug on. Here is a session with logon and a failed redirection: https://gist.github.com/petracvv/c01b27f3ac784f9d06d812153767ebcd

**Comment by mmoayyed** [comment]
There wouldn't be an error. Is there anything in the logs after you see the warning page? cause the flow sort of stops at: `View resolved: /WEB-INF/view/jsp/default/ui/casLoginMessageView.jsp`

**Comment by petracvv** [comment]
Yeah I noticed that. The only entries after that relate to the service reloading job.

The next few lines:

```
2016-09-20 09:04:34,901 DEBUG [org.jasig.cas.web.support.TGCCookieRetrievingCookieGenerator] - Added cookie with name [TGC] and value [eyJhbGciOiJIUzUxMiJ9.WlhsS2FHSkhZMmxQYVVwcllWaEphVXhEU214aWJVMXBUMmxLUWsxVVNUUlJNRXBFVEZWb1ZFMXFWVEpKYmpBdUxqaGFlR2xTZVVkcWRXODJMVE5TTTJwRGFYSllTRUV1VjFseVlTMURSR2xXZFRGNVRGZG5WR0ZCTW5kT09HWXhkM1J4ZFVSRVdYaE1ZVTlpWkd0UGJHczRWREZQTFZSblZVdFhPR2xPTUhGS01IWlFaSGxNVkVKWE9XNUJjVUpxUVhOUWFUaHlVWGRRZDB0ek0wRk9ja2x0YWtaWVkxOHhVVWw1TjNGeVZFcHpaM2RmVURaamNrWjJkakZNVDJ3NGIxZzJSVUZYTlVkaVVuVlhjbXBzZWs4NFIwSnJRV2wxTjBkSWIxQjNjbWd0UVc1NUxWTktNVlJuYUhaQ2EwdFljbFpEZEZOU05YRktRMU56TjJSYWNHUjJTRkZxTlhCUE1XcGhVR3RxTjE5MmRuVmxlbkZMWkUxYU1sZDZSRmQyT0RKUFRuVmFhak5UZDNoNmNXZHpTR041VURrMFNGWk1WamhMV1dGNVFuUk9RMnM1TTBOS1JHTkhkV2c0VkRSVWQxOU5PRWxCVVVKT2QwbG5OMUV1UlhKVU1YcEpkMU5YZGpSdlptbGpjVlJFUW5wM1FRPT0.Gce85QWkwuMOxRIYukBtuFDIzxiChlwenoCxwJPGiqIfl1NsSkrcgwxEBhVQ8C0xRq9J8N-XTqHMaHgEmwITFg]
2016-09-20 09:04:34,912 DEBUG [org.jasig.cas.services.web.RegisteredServiceThemeBasedViewResolver] - View resolved: /WEB-INF/view/jsp/default/ui/casLoginMessageView.jsp
2016-09-20 09:05:05,517 DEBUG [org.jasig.cas.util.CasSpringBeanJobFactory] - Created job org.jasig.cas.services.DefaultServicesManagerImpl$ServiceRegistryReloaderJob@141279e0 for bundle org.quartz.spi.TriggerFiredBundle@7c0a1c0
2016-09-20 09:05:05,517 DEBUG [org.jasig.cas.util.CasSpringBeanJobFactory] - Autowired job per the application context
2016-09-20 09:05:05,517 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - Reloading registered services.
2016-09-20 09:05:05,519 DEBUG [org.jasig.cas.services.DefaultServicesManagerImpl] - Adding registered service ^https://.*wiu\.edu/.*
```

The 2nd line there is the casLoginMessageView.jsp call that you mentioned.

**Comment by mmoayyed** [comment]
Interesting; I am going to theorize that because google apps wants a POST done after the authentication, somehow the warning page interferes with that flow. If we produce a patch, would you be able to test this by switching to 4.2.6-SNAPSHOT?

**Comment by mmoayyed** [comment]
One other thing; could I ask you to reproduce logs by first turning up the spring webflow logging to DEBUG?

**Comment by petracvv** [comment]
Yes I could test a snapshot build. I have a testing CAS server I can use. 

The logs w/webflow DEBUG logging: https://gist.github.com/petracvv/d6334b9110cb3a880a64e47dfddea194

**Comment by mmoayyed** [comment]
I can't duplicate this, as I see the final POST message go out after clicking continue. You will need to capture the 400 error message at the web server and see what it might be telling you. Look at tomcat logs, trace the request, try to upgrade tomcat and increase maximum http-header-size & http-post-size.

**Comment by petracvv** [comment]
Hmm. So there is supposed to be another POST after clicking continue in the password warning screen? I am still learning about SAML2. Authentication to Google seems to succeed (if I go back and try to login again I don't get redirected to CAS for login). It just isn't redirecting me after the continue button is pressed. 

Example: https://gist.github.com/petracvv/22dda7aeffa1ec8e5b6f5d468f3b3a49

The second line there with the POST is before I click continue. 

I will try to trace the request some more.

**Comment by petracvv** [comment]
Gah. I feel a bit stupid now. It was the httpMaxHeaderSize; the default size is 8K and with the giant execution string + CAS cookies it was over the limit. Don't know how I didn't see it, the tomcat logs did mention it now that I look at them again. 

Thanks for pointing me in the right direction!
