### ISSUE TITLE
NullPointerException in GatewayServicesManagementCheck

### ISSUE THREAD

**Issue by marcinroman** [apereo/cas#2011]
It seems that in 
src/main/java/org/apereo/cas/web/config/CasSupportActionsConfiguration.java
the argument is missing in the constructor of GatewayServicesManagementCheck.
Currently:
```
    public Action gatewayServicesManagementCheck() {
        return new GatewayServicesManagementCheck();
    }
```
I think it should be:
```
    public Action gatewayServicesManagementCheck() {
        return new GatewayServicesManagementCheck(this.servicesManager);
    }
```

Without it there is a bug in line 43 of GatewayServicesManagementCheck.java

**Comment by mmoayyed** [comment]
Good one. Do submit a PR plz.
