### ISSUE TITLE
MFA with non interactive authentication issue with CAS 5.0.0-RC3

### ISSUE THREAD

**Issue by pmarasse** [apereo/cas#2018]
MFA authentication with SPNEGO then Yubikey works oddly : MFA is not triggered first time, ending with "Authentication failure" on client application. If I click try again, MFA is triggered and I'm correctly authenticated.

I suspect that transition on success after SPNEGO to be incorrect. It's actually hardcoded to CasWebflowConstants.TRANSITION_ID_SEND_TICKET_GRANTING_TICKET.

**Comment by mmoayyed** [comment]
@pmarasse could you try with RC3 SNAPSHOT? force an upgrade with -U

**Comment by pmarasse** [comment]
Hello,

Unfortunately, this is worse than before, I'm getting error code 500 with text : `Error: No transition was matched on the event(s) signaled by the [1] action(s) that executed in this action state 'spnego' of flow 'login'; transitions must be defined to handle action result outcomes -- possible flow configuration error? Note: the eventIds signaled were: 'array<String>['authenticationFailure']', while the supported set of transitional criteria for this action state is 'array<TransitionCriteria>[success, error]'`

Although I've ported back modification from RC3 to my customized login-webflow :

```xml
    <action-state id="startSpnegoAuthenticate">
    	<evaluate expression="negociateSpnego" />
    	<transition on="success" to="spnego" />
    	<transition on="negotiate" to="casSpnegoNegotiateView" />
    	<transition on="error" to="casSpnegoErrorView" />
    </action-state>
    
    <action-state id="spnego">
    	<evaluate expression="spnego" />
    	<transition on="success" to="sendTicketGrantingTicket" />
    	<transition on="error" to="casSpnegoErrorView" />
    	<on-exit>
    		<evaluate expression="clearWebflowCredentialsAction" />
    	</on-exit>
    </action-state>

	<end-state id="casSpnegoNegotiateView" view="casSpnegoNegotiateView" />

	<end-state id="casSpnegoErrorView" view="casSpnegoErrorView"  />
```

There's the full catalina log : 
[catalina.out](https://github.com/apereo/cas/files/495559/spnego.txt)


Regards.

**Comment by mmoayyed** [comment]
If you have manually modified the login flow to make changes, then everything else (including adding other transitions and states) is also on you to handle.

**Comment by mmoayyed** [comment]
I also recommend you avoid modifying the login webflow directly, and think about how "your custom changes" can become part of CAS either directly or via a pluggable strategy. Changing this sort of thing ad-hoc is only going to break you later on.

**Comment by pmarasse** [comment]
Indeed.
If needed, I can test a more "vanilla" CAS SPNEGO authentication.

**Comment by mmoayyed** [comment]
That would be very helpful. Thank you.

**Comment by pmarasse** [comment]
My first try on vanilla configuration was not a success, spnego was not triggered. the documentation tells to `Replace instances of initializeLoginForm with startSpnegoAuthenticate, if any.` 

If I change every transitions to `initializeLoginForm` with `startSpnegoAuthenticate`: it does not work.
If I change the onSuccess transition of `initializeLoginForm` state from `viewloginForm` to `startSpnegoAuthenticate` : it works.

So when spnego is correctly triggered, yubikey follows this time.

**Comment by mmoayyed** [comment]
Thanks for the feedback. Sounds like we need to adjust the docs a little bit. Could you handle that with a PR plz?

**Comment by pmarasse** [comment]
Done PR #2021
