### ISSUE TITLE
CAS v5 PM, AD Server needs encoded password sent

### ISSUE THREAD

**Issue by JasonEverling** [apereo/cas#2019]
When using CAS v5 RC3 the password management feature does not seem to be working for AD servers. I checked some of the code and it seems that in order for it to work with AD it has to be encoded using UTF-16LE. I did not see any references to it currently unless I missed it somewhere. Trying to change a password results in LdapErr: DSID-0C090C7D, comment: Unknown extended request OID, data 0

I have included the following in my report:

- CAS server version : v5 RC3
- Container/environment type/version : Tomcat/Java 8 , Windows
- Steps to duplicate the problem : Try to change password where LDAP server is AD

**Comment by mmoayyed** [comment]
Thanks for the feedback. Looks like CAS just does a `PasswordModifyOperation` with Ldaptive. Have you tried posting your question  to ldaptive forums and see if there is something else the code should do? The type of thing you're describing should be handled by ldaptive, it seems.

https://groups.google.com/forum/#!forum/ldaptive

Ping @dfish3r

**Comment by JasonEverling** [comment]
I didn't see anything in ldaptive for it but I did see examples for unboundid sdk using UTF-16LE

I also looked at the way Unicon implemented it for their addon they made years ago, and they also had to use the unicodePwd attribute and encode as UTF-16LE if the server type was active directory

[https://github.com/Unicon/cas-password-manager/blob/master/src/main/java/net/unicon/cas/passwordmanager/ldap/ActiveDirectoryLdapServer.java]

**Comment by mmoayyed** [comment]
Cool, I am happy to accommodate the change (or if you want to post a PR, that's perfectly better since you can confirm it works) but it might be a change better suited for ldaptive native. Please post to their forums and short of nothing else, we can always manually encode it.

**Comment by JasonEverling** [comment]
I did find it in ldapative's code already, not sure how to translate all that though

[https://github.com/vt-middleware/ldaptive/blob/7fe131b85cd4e399abed92203af5e10c68163070/core/src/main/java/org/ldaptive/ad/io/UnicodePwdValueTranscoder.java](url)

**Comment by mmoayyed** [comment]
Cool. We probably need Daniel's help here. Not sure if that needs to be plugged in somewhere, or whether it's something that CAS should invoke.

**Comment by JasonEverling** [comment]
Ok, I will see what I can come up with but I am not a java developers so I will get lost pretty quickly probably but we can see what Daniel says,

Thanks!

**Comment by mmoayyed** [comment]
No worries. We are here to help you out. Post back when you find more plz.

**Comment by dfish3r** [comment]
To change the unicodePwd attribute do this:
```
ModifyOperation modify = new ModifyOperation(conn);
modify.execute(
  new ModifyRequest(
    "dn-of-entry-to-modify",
    new AttributeModification(
      AttributeModificationType.REPLACE,
      new UnicodePwdAttribute("password"))));
```

Be aware of the caveats surrounding AD password changes:
https://msdn.microsoft.com/en-us/library/cc223247.aspx

**Comment by JasonEverling** [comment]
Sweet! Thanks!!! It is working now, I just tried the latest snapshot at 5.0.0.RC3-20160928.104306 and it worked, I was able to successfully change the password.

**Comment by mmoayyed** [comment]
Thanks @dfish3r
