### ISSUE TITLE
SAML authentication delegation is broken

### ISSUE THREAD

**Issue by leleuj** [apereo/cas#2020]
The `resource:` or `classpath:` prefix cannot be used and I've updated the warning about it: https://github.com/apereo/cas/commit/1a77b24956dd3a07736361e689f3ca863f8cde20#diff-6fb367a9c97b816b0c1991fcbde08088

I have made various fixes on pac4j v1.9.3 to make it work: https://github.com/pac4j/pac4j/pull/691

Though, the SAML support cannot still work because of the fact we use the redirection URL (https://github.com/apereo/cas/blob/master/support/cas-server-support-pac4j/src/main/java/org/apereo/cas/support/pac4j/web/flow/ClientAction.java#L161) while by default, it's a form POST. And there is no property to change that.

Using an intermediate controller or switch to HTTP REDIRECT binding would be a solution.

**Comment by mmoayyed** [comment]
@leleuj Is this something you're working on? Or shall we schedule it for RC4 or later?

**Comment by leleuj** [comment]
Yes, as soon as we agree on the solution: "an intermediate controller or switch to HTTP REDIRECT binding". The latter being the easiest.

**Comment by mmoayyed** [comment]
Could you describe the pros/cons of each approach? I am ok with the latter solution given that it's less stuff for us to maintain, but what are the consequences, if any?

**Comment by leleuj** [comment]
"intermediate controller" solution:
It's more work, but it solves this problem and the performance issue for OAuth 1.0 and OpenID Connect (when the client needs to call the identity provider to compute the redirection URL). It allows us to let users set the binding type if ever the SAML IdP has an issue with one binding versus another.

"redirect binding" solution:
It's easy: it should be one line of configuration to set up the HTTP redirect binding. Though this does not fix the performance issue, nor offer the ability to set the binding type if ever the SAML IdP does not support it correctly.

We can do the latter first and track the first one as an improvement.

**Comment by mmoayyed** [comment]
I admit the first solution sounds infinitely better; but how much more work are we talking about? 2 days? 2 weeks? 

The current plan is to cut RC3 by early next week, and then allow about 1-2 weeks after for the GA. Think that might be enough time to handle the 1st option given your schedule? If not, we can always do the easy one first and track the other later.

**Comment by mmoayyed** [comment]
I moved this to 5.0.0 to allow us a couple of more weeks to see what the better solution might be.

**Comment by leleuj** [comment]
Working on this...

**Comment by leleuj** [comment]
I just realized that, in the `SAML2ServiceProviderMetadataResolver`, the SP entity ID is the callback URL without the `client_name` if it was null. Since version 1.8.x.

In most cases, it does not matter as we set the entityID to the callback URL, but for CAS, we don't so I need a somehow confusing configuration to make it work.

@mmoayyed what's the rationale behind this sp entity identifier computation? Should we change it for 2.0?

The good point is that SAML2 authentication delegation works now with pac4j 1.9.3-SNAPSHOT.

**Comment by mmoayyed** [comment]
Reviewing.

**Comment by leleuj** [comment]
See: https://github.com/pac4j/pac4j/blob/master/pac4j-saml/src/main/java/org/pac4j/saml/metadata/SAML2ServiceProviderMetadataResolver.java#L85

**Comment by leleuj** [comment]
Here is my Okta configuration:

| Setting | Value |
|--------|-------|
| Single Sign On URL | http://localhost:8080/cas/login?client_name=SAML2Client |
| Recipient URL | http://localhost:8080/cas/login?client_name=SAML2Client |
| Destination URL | http://localhost:8080/cas/login?client_name=SAML2Client |
| Audience Restriction | http://localhost:8080/cas/login |
| Default Relay State | http://localhost:8080/cas/login?client_name=SAML2Client |

**Comment by leleuj** [comment]
Or spEntityID may not have a query string in some SAML providers, like ADFS maybe...

**Comment by mmoayyed** [comment]
Yes the entity id is not always a URL, but in our case since CAS is the SP and the CAS SP entity ID is always a URL, I think we might be able to add the client_name parameter to its entityId. 

Is that something pac4j should handle? or should we provide a minor CAS extension to handle metadata constructions correctly? Or perhaps just document the nuance?

**Comment by leleuj** [comment]
In fact, we already can in the `Pac4jconfiguration`: I see:

```java
properties.put(PropertiesConfigFactory.SAML_SERVICE_PROVIDER_ENTITY_ID,
       casProperties.getAuthn().getPac4j().getSaml().getServiceProviderEntityId());
````

So `cas.authn.pac4j.saml.serviceProviderEntityId` is available.

This makes me spot another strange thing. See this line (just below):

```java
properties.put(PropertiesConfigFactory.SAML_SERVICE_PROVIDER_METADATA_PATH,
        casProperties.getAuthn().getPac4j().getSaml().getServiceProviderEntityId());
```

Why is the SP entity ID set in the SP metadata path?

**Comment by leleuj** [comment]
To answer your question, I think we should document it properly. I will handle that in this PR.

**Comment by leleuj** [comment]
I will add a `serviceProviderMetadataPath`, I'm not sure why it was removed.

**Comment by leleuj** [comment]
I have still one issue with the webflow: in case of an error (bad scope for Facebook for example), I fixed the returned event to `stop` event instead of `stopWebflow` (https://github.com/apereo/cas/pull/2035/files#diff-75afcf8c2ce4cc369aa2c9c049680e7cR113),  but the `casPac4jStopWebflow` view is never displayed and I haven't been able to find out why. Any idea?

**Comment by mmoayyed** [comment]
Can you step into `Pac4jErrorViewResolver`?

**Comment by leleuj** [comment]
No, the `Pac4jErrorViewResolver` is not called.

**Comment by leleuj** [comment]
I released pac4j v1.9.3 and spring-webmvc-pac4j v1.1.3: I'll submit a PR to upgrade CAS unless you do it before me.

**Comment by mmoayyed** [comment]
This should already be done. I switched when I saw your announcement! Great work.

**Comment by mmoayyed** [comment]
Also, oh, the webflow stop event should also be functional now.

**Comment by leleuj** [comment]
Thanks. Perfect.
