### ISSUE TITLE
REST API Is Not Loading In CAS 4.2.6

### ISSUE THREAD

**Issue by wcrowell** [apereo/cas#2027]
- CAS server version: 4.2.6.  The REST API works fine in 4.2.4 and 4.2.5.
- Servers: Jetty and Tomcat 8
- Include cas-server-support-rest in cas-server-webapp's build.gradle.
- The only line in the log showing an issue is: 
`2016-09-30 08:47:24,203 WARN [org.springframework.web.servlet.PageNotFound] - <No mapping found for HTTP request with URI [/cas/v1/tickets] in DispatcherServlet with name 'cas'>`

Please note I will take ownership of this issue and submit a fix.

**Comment by wcrowell** [comment]
This is not a bug.  The cas-server-support-rest jar was not being included in the packaged cas-server-webapp.war even though it was listed as a dependency.

**Comment by mmoayyed** [comment]
Got confirmation from @wcrowell that this is now resolved in 4.2.7-SNAPSHOT.
