### ISSUE TITLE
pac4j delegate authentication does not support PrincipalResolver

### ISSUE THREAD

**Issue by clegallic** [apereo/cas#2030]
CAS server version : 4.2.5

pac4j ClientAuthenticationHandler is currently registered without being associated to a PrincipalResolver.
([for example in 4.2.x](https://github.com/apereo/cas/blob/4.2.x/cas-server-support-pac4j/src/main/java/org/jasig/cas/support/pac4j/Pac4jServletContextListener.java#L32))

Thus, it's not possible to add additional attributes to the user CAS principal once the user has been successfully authenticated through the OIDC authentication sequence.

It will be nice to be able to associate an optional PrincipalResolver to the ClientAuthenticationHandler, and then be able to use a PersonDirectory implementation to retrieve additional attributes.

**Comment by mmoayyed** [comment]
Closed via https://github.com/apereo/cas/commit/334b343af2e58b81fae0395e47ecd0543f5aec4a
