### ISSUE TITLE
Support for Login Images to Protect Against Phishing Attacks

### ISSUE THREAD

**Issue by rdev5** [apereo/cas#2031]
Putting in my request now for Login Image Support to mitigate phishing attacks :)

Thanks!

**Comment by mmoayyed** [comment]
And what exactly is login images??

**Comment by mmoayyed** [comment]
reCaptcha is already supported which is what I think you meant.

**Comment by rdev5** [comment]
Not really...

> reCAPTCHA is a [Google service](https://developers.google.com/recaptcha) that protects your CAS deployment from spam and abuse.

"Login images" are another form of post-login verification (i.e. second factor) where a site presents the user with an image previously selected by the user at the time the account is created. It is an "account secret" (i.e. [Active Directory attribute](http://www3.ca.com/us/support/ca-support-online/product-content/knowledgebase-articles/tec478758.aspx)) tied to their username that should not be easily reproduced by a phishing campaign attempting to impersonate a legitimate website.

In practice, the website prompts the user for only their username and responds with a page displaying what should be the user's pre-selected image along with a password field to complete their authentication. The user in turn is to be trained to refuse submitting the rest of their login credentials to the site posing to be legitimate if it fails to present the **correct** image.

It's 2012 technology, I'll give you that.  But when used correctly and with the proper training, it addresses a problem that a lot of security companies still to this day struggle to incorporate into their most expensive security solutions from an integration standpoint (they would basically have to own your authentication system to do this for you).

> Some of the most important networks and systems today are woefully outdated. And that isn't always a bad thing. (http://zd.net/1WWshaJ)

And no, this is not something I find current 2-factor solutions to have addressed either because by the time you get your verification code via SMS or authentication app, you've already submitted both username AND password. Hence, these are two different problems. reCAPTCHA solves another distinct, yet unrelated problem: spam.

**Comment by mmoayyed** [comment]
Cool. Thanks for clarifying.

**Comment by mmoayyed** [comment]
This should now be available. Note that support and range of range of options are rather limited and focused today and may grow over time. You are encouraged to review and provide feedback 

Thank you for the suggestion :)

**Comment by mmoayyed** [comment]
Sweet. Sorry, forgot to pass along the actual link to the docs https://apereo.github.io/cas/development/installation/GUA-Authentication.html
