### ISSUE TITLE
SPNEGO workflow partly broken in 5.0.0.RC3

### ISSUE THREAD

**Issue by FSchumacher** [apereo/cas#2032]
With 5.0.0RC3 the SPNEGO workflow breaks, when the browser delivers an invalid kerberos ticket via the Negotiate header. The other possible flows, where a valid kerberos ticket is send or the browser doesn't understand the Negotiate protocol, are working as expected.

The broken workflow looks for a transition `authenticationFailure` in the state `spnego`, but finds only `error` and `success`.

The error message is:
```
Error: No transition was matched on the event(s) signaled by the [1]
action(s) that executed in this action state 'spnego' of flow 'login';
transitions must be defined to handle action result outcomes -- possible
flow configuration error? Note: the eventIds signaled were:
'array<String>['authenticationFailure']', while the supported set of
transitional criteria for this action state is
'array<TransitionCriteria>[success, error]' 
```

As discussed on the mailing list I had to adapt `SpengoWebflowConfigurer` and add the transition
```
+        spnego.getTransitionSet().add(createTransition(CasWebflowConstants.TRANSITION_ID_AUTHENTICATION_FAILURE,
+                CasWebflowConstants.STATE_ID_VIEW_LOGIN_FORM));
```

With this fix, the workflow works as expected and the login view gets shown.

**Comment by mmoayyed** [comment]
This is already fixed. Please update your snapshot and try again.

**Comment by FSchumacher** [comment]
Works in 5.0.0.RC4-SNAPSHOT.

Thanks for fixing and support.
