### ISSUE TITLE
mod_auth_cas Sign Out feature

### ISSUE THREAD

**Issue by pouriam** [apereo/cas#2034]
I would like to ask for the Single Sign out feature to be added in cas client module ( mod_auth_cas )
I know it is a KNOWN LIMITATIONS to cas client. 
Or if that can not be happen in a short and reasonable time, then I have a suggestion to add another feature to force apache to validate the ticket via CAS Server for each request. I know this might have performance hit, so by default it could be turned off and people can turn it On if they need it.

CAS Client : mod_auth_cas version 1.1
Environment: Linux ( SUSE, CentOS )

Thank you.

**Comment by mmoayyed** [comment]
This project deals with the server. Not the clients.

**Comment by mmoayyed** [comment]
Use https://github.com/Jasig/mod_auth_cas

**Comment by pouriam** [comment]
@mmoayyed 
Yes I am using mod_auth_cas which is dealing with server. Sorry for confusion.
And in the README file inside the mod_auth_cas source, there is a section called: 
"KNOWN LIMITATIONS"
and Single Sign Out is one of them. I was wondering if that is possible to add a feature to the mod_auth_cas to be able to validate each request agains CAS server. 
I know I can set timeout for invalidating the cookie, but that is not remedy for my case. I need every single request to the server, being validated agains CAS server.

Thanks

**Comment by mmoayyed** [comment]
I understand. I was pointing out that this is something you need to discuss with mod-auth-cas, linked above. This is a project about the server, not the clients.

**Comment by pouriam** [comment]
@mmoayyed Thanks
