### ISSUE TITLE
OAuth provider redirect broken in CAS 4.2.5 (and possibly 4.2.6)

### ISSUE THREAD

**Issue by jabbrwcky** [apereo/cas#2037]
Hi,

I am experiencing problems using CAS as an OAuth server. Tested with 4.2.5 on Jetty built via Maven overlay. 

(Tried 4.2.6, but there it may fail already due to the fact that 4.2.6 is not able to find the (defined) metrics registry)

Discussion on cas-user: [[cas-user] Oauth2.0 not redirecting back to app](https://groups.google.com/d/topic/jasig-cas-user/anwDz34C5mk/discussion)

Here is the list of services registered:

[STDOUT] 2016-10-04 13:29:54,461 DEBUG [org.jasig.cas.services.DefaultServicesManagerImpl] - <Adding registered service localhost:8443/cas/oauth2.0/callbackAuthorize>
[STDOUT] 2016-10-04 13:29:54,462 DEBUG [org.jasig.cas.services.DefaultServicesManagerImpl] - <Adding registered service ^https?://localhost:\d+/callback>
[STDOUT] 2016-10-04 13:29:54,462 DEBUG [org.jasig.cas.services.DefaultServicesManagerImpl] - <Adding registered service https?://localhost:5000/.*>
[STDOUT] 2016-10-04 13:29:54,462 DEBUG [org.jasig.cas.services.DefaultServicesManagerImpl] - <Adding registered service localhost:8443/cas/oauth2.0/callbackAuthorize>
[STDOUT] 2016-10-04 13:29:54,462 DEBUG [org.jasig.cas.services.DefaultServicesManagerImpl] - <Adding registered service https://localhost:8443/cas/oauth2.0/callbackAuthorize>

There are two service definitions for the OAuth2.0 callbackAuthorize servce. 
The first one seems to be registered by default by the oauth plugin and has a serviceId w/o a protocol. 

The second one in the list (at the end) is the manual service registration I posted here already:

{
  "@class": "org.jasig.cas.support.oauth.services.OAuthCallbackAuthorizeService",
  "serviceId": "https://localhost:8443/cas/oauth2.0/callbackAuthorize",
  "name": "OAuth Callback url",
  "id": 49918310095849,
  "description": "OAuth Wrapper Callback Url",
  "logoutType": "BACK_CHANNEL",
  "accessStrategy": {
    "@class": "org.jasig.cas.services.DefaultRegisteredServiceAccessStrategy",
    "enabled": true,
    "ssoEnabled": true,
    "requireAllAttributes": true,
    "caseInsensitive": false
  }
}

First issue: I get this (broken) URL in the Location header in the 302 response returned by /oauth2.0/authorize:

localhost:8443/cas/login?service=https%3A%2F%2Flocalhost%3A8443%2Fcas%2Foauth2.0%2FcallbackAuthorize

When I copy the Location and add a proper protocol (https://...) I continue to the next step.

Without my own service definition I run into the error page that my application is not authorized.

When I add my custom service definition for the OAuth service, I am finally redirected to the calling application.

The main culprit seems to be the (automatically generated?) service for the OauthAuthorize callback service which produces a broken redirect URL.

I have included the following in my report:

- [x] CAS server version
- [x] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
- [] Steps to duplicate the problem
- [x] Stacktraces and CAS logs where appropriate.
- [] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

**Comment by mmoayyed** [comment]
Why would you consider that url to be broken?

**Comment by mmoayyed** [comment]
Ah, let me clarify: by broken you mean the actual host name. Not the service parameter which is what I was going for.

This is a problem with your configuration. You need specify the proper cas name and prefix.

**Comment by jabbrwcky** [comment]
@mmoayyed, @leleuj asked me to create an issue as the outcome of our discussion on cas-user. So just shrugging it off as pilot error does not fix the issue.

This is the manual one I built (in src/main/resources/services in the overlay project):
```
{
  "@class": "org.jasig.cas.support.oauth.services.OAuthCallbackAuthorizeService",
  "serviceId": "https://localhost:8443/cas/oauth2.0/callbackAuthorize",
  "name": "OAuth Callback url",
  "id": 49918310095849,
  "description": "OAuth Wrapper Callback Url",
  "logoutType": "BACK_CHANNEL",
  "accessStrategy": {
    "@class": "org.jasig.cas.services.DefaultRegisteredServiceAccessStrategy",
    "enabled": true,
    "ssoEnabled": true,
    "requireAllAttributes": true,
    "caseInsensitive": false
  }
}
```

I think this service definition should work.

BUT I also find in the target classes folder this additional service definition which I did not create and which seemingly appears out of nowhere:
```
  @class: org.jasig.cas.support.oauth.services.OAuthCallbackAuthorizeService
  serviceId: localhost:8443/cas/oauth2.0/callbackAuthorize
  name: OAuth Callback url
  id: 181929053279567
  description: OAuth Wrapper Callback Url
  logoutType: BACK_CHANNEL
  accessStrategy:
  {
    @class: org.jasig.cas.services.DefaultRegisteredServiceAccessStrategy
    enabled: true
    ssoEnabled: true
    requireAllAttributes: true
    caseInsensitive: false
  }
}
```
The service Id here is broken and I frankly have not found yet where it comes from.

Getting rid of this second definition would solve this problem - if I had the slightest idea where it came from.

**Comment by jabbrwcky** [comment]
It might only affect CAS if the service definitions are not read from files but from the classpath - but it is annoying nonetheless

**Comment by mmoayyed** [comment]
I didn't shrug it off. I provided an explanation. Whether or not you like that explanation is up to you. 

The service is created by CAS automatically based on your settings. Evaluate those and see where that might come from.

**Comment by mmoayyed** [comment]
Easiest way to diagnose this, would to provide an overlay as the issue template suggested so we can try to duplicate the issue.

**Comment by jabbrwcky** [comment]
Which setting would then cause the missing protocol prefix to the generated ServiceId?

Because the rest (web application path, hostname and port) are generated correctly.

**Comment by mmoayyed** [comment]
Could you paste a copy of your cas.properties file?

**Comment by jabbrwcky** [comment]
```
server.name=localhost:8443
server.prefix=${server.name}/cas

cas.securityContext.adminpages.ip=127\.0\.0\.1|0:0:0:0:0:0:0:1

host.name=localhost

ticketreg.database.ddl.auto=create-drop
ticketreg.database.dialect=org.hibernate.dialect.MySQLInnoDBDialect
ticketreg.database.batchSize=10
ticketreg.database.driverClass=org.mysql.jdbcDriver
ticketreg.database.url=jdbc:mysqldb:cas-ticket-registry
ticketreg.database.user=root
ticketreg.database.password=
ticketreg.database.pool.minSize=6
ticketreg.database.pool.maxSize=18
ticketreg.database.pool.maxWait=10000
ticketreg.database.pool.maxIdleTime=120
ticketreg.database.pool.acquireIncrement=6
ticketreg.database.pool.idleConnectionTestPeriod=30
ticketreg.database.pool.connectionHealthQuery=select 1
ticketreg.database.pool.acquireRetryAttempts=5
ticketreg.database.pool.acquireRetryDelay=2000
ticketreg.database.pool.connectionHealthQuery=select 1

svcreg.database.ddl.auto=create-drop
svcreg.database.hibernate.dialect=org.hibernate.dialect.MySQLInnoDBDialect
svcreg.database.hibernate.batchSize=10
svcreg.database.driverClass=org.mysql.jdbcDriver
svcreg.database.url=jdbc:mysql:cas-ticket-registry
svcreg.database.user=root
svcreg.database.password=
svcreg.database.pool.minSize=6
svcreg.database.pool.maxSize=18
svcreg.database.pool.maxWait=10000
svcreg.database.pool.maxIdleTime=120
svcreg.database.pool.acquireIncrement=6
svcreg.database.pool.idleConnectionTestPeriod=30
svcreg.database.pool.connectionHealthQuery=select 1
svcreg.database.pool.acquireRetryAttempts=5
svcreg.database.pool.acquireRetryDelay=2000
svcreg.database.pool.connectionHealthQuery=select 1

tgc.encryption.key=[...]
tgc.signing.key=[...]
okie should be created only under secure connections.
tgc.secure=true

webflow.encryption.key=[...]
webflow.signing.key=[...]

ldap.url=[...]
ldap.useStartTLS=[...]
ldap.use.ssl=[...]
ldap.rootDn=[...]
ldap.baseDn=[...]
ldap.connectTimeout=[...]
ldap.managerDn=[...]
ldap.managerPassword=[...]

ldap.pool.blockWaitTime=500
ldap.pool.idleTime=100
ldap.pool.maxSize=5
ldap.pool.minSize=2
ldap.pool.validateOnCheckout=true
ldap.pool.validatePeriodically=true
ldap.pool.validatePeriod=1000
ldap.pool.prunePeriod=3000

ldap.authn.searchFilter=SAMAccountName={user}

ldap.allowMultipleDns=false

ldap.subtree.search=true

accept.authn.users=casuser::Mellon

memcached.servers=localhost:11211
memcached.hashAlgorithm=FNV1_64_HASH
memcached.protocol=BINARY
memcached.locatorType=ARRAY_MOD
memcached.failureMode=Redistribute

cache.monitor.warn.free.threshold=10
cache.monitor.eviction.threshold=0
```

Added cas-issues PR: https://github.com/cas-projects/cas-issues/pull/19

I could reproduce the problem as well with the version deployed on tomcat (tomcat 7).

```
2016-10-13 12:56:24,734 DEBUG [org.jasig.cas.services.DefaultServicesManagerImpl] - Adding registered service sso.xing.hh:443/oauth2.0/callbackAuthorize
2016-10-13 12:56:24,734 INFO [org.jasig.cas.services.DefaultServicesManagerImpl] - Loaded 6 services from JsonServiceRegistryDao.
2016-10-13 12:56:26,133 DEBUG [org.jasig.cas.support.oauth.web.OAuth20WrapperController] - method : authorize
2016-10-13 12:56:26,134 DEBUG [org.jasig.cas.support.oauth.web.OAuth20AuthorizeController] - method : authorize
2016-10-13 12:56:26,134 DEBUG [org.jasig.cas.support.oauth.web.OAuth20AuthorizeController] - client_id : 30ceed1c0a94bf4fad35f53e6e0b0442
2016-10-13 12:56:26,135 DEBUG [org.jasig.cas.support.oauth.web.OAuth20AuthorizeController] - redirect_uri : https://localhost:3000/callback
2016-10-13 12:56:26,135 DEBUG [org.jasig.cas.support.oauth.web.OAuth20AuthorizeController] - state : 3(#0/!~
2016-10-13 12:56:26,136 DEBUG [org.jasig.cas.support.oauth.web.OAuth20AuthorizeController] - callbackAuthorize : https://sso.xing.hh/oauth2.0/callbackAuthorize
2016-10-13 12:56:26,137 DEBUG [org.jasig.cas.support.oauth.web.OAuth20AuthorizeController] - loginUrlWithService : sso.xing.hh:443/login?service=https%3A%2F%2Fsso.xing.hh%2Foauth2.0%2FcallbackAuthorize
```

**Comment by jabbrwcky** [comment]
@mmoayyed I had a look at the template cas.properties and found there that the server.name in cas.properties actually includes the protocol prefix. In mine it is missing, so I admit that it actually seems to be pilot error. My bad. Thanks for looking into it.

**Comment by mmoayyed** [comment]
No worries. Glad you were able to figure this out and thanks for following up.
