### ISSUE TITLE
runtime ClassNotFoundException: org.opensaml.saml.metadata.resolver.impl.AbstractMetadataResolver for cas-server-support-saml-idp

### ISSUE THREAD

**Issue by ernestojanus** [apereo/cas#2038]
CAS server version: 5.0.0.RC3

Reproduction: include  cas-server-support-saml-idp in the overlay and start CAS.

I will include a pull-request with my overlay that includes a workaround for the issue (lines 82-113 in the pom.xml).

The stacktrace from stdout/cas.log is included as a file to this issue.
[stacktrace_saml_idp_classnotfound.txt](https://github.com/apereo/cas/files/524622/stacktrace_saml_idp_classnotfound.txt)

**Comment by ernestojanus** [comment]
pull-request added for cas-issues

**Comment by mmoayyed** [comment]
You should not have to add any of those extra dependencies at all. Can you try with RC4?

**Comment by ernestojanus** [comment]
I tried a clean package with 5.0.0.RC4-SNAPSHOT just now. It still does the ClassNotFoundException on startup.

**Comment by mmoayyed** [comment]
ok, one other test: what happens if you set the scope of your cas dependencies to compile?

**Comment by ernestojanus** [comment]
If I change the scope on line 69 to compile instead of runtime it still happens when lines 82-113 are commented out. I didn't try the other cas-dependencies as default scope for maven dependencies is compile.

**Comment by mmoayyed** [comment]
Thanks very much for the followup. Seems like a legitimate issue. Stay on RC4 to receive the fix.

**Comment by mmoayyed** [comment]
Cant duplicate the problem with your overlay. No issues whatsoever if I remove the extra dependencies.

**Comment by ernestojanus** [comment]
That's weird.... You checked during runtime? I start up with java -jar cas.war when testing. Also, I have to do a 'mvn clean package' between builds to get the difference.

**Comment by mmoayyed** [comment]
Yes. No other changes, and didnt change scopes at all.

Force an update of the snapshot with -U. Then try again.

**Comment by mmoayyed** [comment]
If that still fails, provide a listing of all CAS dependencies in the final war under web-inf/lib. Or do a dependency tree via maven and paste back the output please.

**Comment by ernestojanus** [comment]
I tried 'mvn -U clean package' but it didn't help. Included are the dependency-trees. there's definitely stuff missing from the tree-without-workaround (e.g. net.shibboleth.idp:idp-saml-api:jar).
[with_workaround.txt](https://github.com/apereo/cas/files/525165/with_workaround.txt)
[without_workaround.txt](https://github.com/apereo/cas/files/525166/without_workaround.txt)

**Comment by mmoayyed** [comment]
The class that you are missing is not part of the idp. Its part of opensaml-saml-impl, which somehow is ignored. I'll take a look. It's odd that you get everything except that one.

**Comment by mmoayyed** [comment]
It looks like CAS is not explicitly producing opensaml-saml-impl as a dependency. I'll see if I can produce a new snapshot in about an hour and will post back when it's ready.

**Comment by mmoayyed** [comment]
Run the build with -U once more, and see if you get the same error.

**Comment by mmoayyed** [comment]
Status check: does the new snapshot fix this issue for you, @ernestojanus ?

**Comment by ernestojanus** [comment]
the ClassNotFoundException now changed to net.shibboleth.idp.saml.xmlobject.DelegationPolicy, see [stacktrace.txt](https://github.com/apereo/cas/files/527620/stacktrace.txt)

If I do a dependency-tree I still see 
net.shibboleth.idp:idp-saml-api:jar:3.2.1:runtime
net.shibboleth.liberty:idwsfconsumer:jar:1.0.0:runtime
net.shibboleth.idp:idp-attribute-api:jar:3.2.1:runtime

missing from the RC4-SNAPSHOT build without workaround. These were really needed when I created the workaround as I added them step by step until I got no more ClassNotFound exceptions.

**Comment by mmoayyed** [comment]
Cool. We are going to have to add them as well; one at a time perhaps. I sense a new snapshot version coming up shortly :)

**Comment by mmoayyed** [comment]
Give it yet another shot with the new snapshot. All those dependencies should now be there hopefully.

**Comment by ernestojanus** [comment]
I did a build with a fresh RC4-SNAPSHOT and the startup errors are gone, however I still can't do successful SAML IDP (see issue #2023 for a reproduction scenario, replacing : with _ of course :).
The weird thing is it complains about 'Cannot find entity https://sp.testshib.org/shibboleth-sp in metadata provider', but the service definition is right there and it works fine in my RC3 build (with the workaround).
[stacktrace_cantfindentity.txt](https://github.com/apereo/cas/files/529102/stacktrace_cantfindentity.txt)
Also, the actual SP I want to reach (SURF) doesn't work either but with a totally different message (500: no message) and stacktrace 
[stacktrace_surf.txt](https://github.com/apereo/cas/files/529133/stacktrace_surf.txt)

again, works ok with RC3-build with the workaround.

I understand I might be pulling in some other changes as well with RC4-SNAPSHOT...

**Comment by mmoayyed** [comment]
Cool. So next, attach a copy of your surfnet metadata. Also attach a local copy of your http://www.testshib.org/metadata/testshib-providers.xml.

**Comment by mmoayyed** [comment]
Or better yet, post another PR to the issues project that allows us to duplicate this :) (but the metadata here should also do)

**Comment by mmoayyed** [comment]
Also, we do need to see your service defns as well. Thanks.

**Comment by ernestojanus** [comment]
both use a URL to get the SP metadata

`surf_sp_debug-10000004.json`
```json
{
  "@class" : "org.apereo.cas.support.saml.services.SamlRegisteredService",
  "serviceId" : "https://engine.connect.surfconext.nl/authentication/sp/metadata",
  "name" : "SURF SP debug",
  "id" : 10000004,
  "evaluationOrder" : 11,
  "metadataLocation":"https://engine.connect.surfconext.nl/authentication/sp/metadata",
  "attributeReleasePolicy" : {
    "@class" : "org.apereo.cas.services.ReturnMappedAttributeReleasePolicy" ,
    "allowedAttributes" : {
      "@class" : "java.util.TreeMap",
      "uid" : "urn_mace_dir_attribute-def_uid",
      "displayName" : "urn_mace_dir_attribute-def_displayName",
      "mail" : "urn_mace_dir_attribute-def_mail"
    }
  }
}
```
`testshib-10000003.json`
```json
{
  "@class" : "org.apereo.cas.support.saml.services.SamlRegisteredService",
  "serviceId" : "https://sp.testshib.org/shibboleth-sp",
  "name" : "SAMLService",
  "id" : 10000003,
  "evaluationOrder" : 10,
  "metadataLocation" : "http://www.testshib.org/metadata/testshib-providers.xml",
  "attributeReleasePolicy" : {
    "@class" : "org.apereo.cas.services.ReturnMappedAttributeReleasePolicy" ,
    "allowedAttributes" : {
      "@class" : "java.util.TreeMap",
      "uid" : "uid",
      "displayName" : "urn_mace_dir_attribute-def_displayName"
    }
  }
}
```

**Comment by mmoayyed** [comment]
Perfect. I did find one small issue with entity id detection. Not sure yet if that affects your case  here, but I'll post back shortly.

**Comment by mmoayyed** [comment]
Quick update: thanks for catching this. This is definitely a bug. We recently added support for entity-role filters, and the bug is that CAS incorrectly filters all entity descriptors from the metadata rather than those that need explicit filtering. This will be fixed shortly. As for the issue with "_" vs ":", I believe that is already taken care of as part of the other issue now closed, so you should be good there. My initial tests show that I can successfully log into test shib, etc without having to do that manual transformation.

I'll post back when the metadata fix is available.

**Comment by mmoayyed** [comment]
This should be resolved.

**Comment by ernestojanus** [comment]
The RC4-SNAPSHOT actually logs in to the SP now! But there's still a regression from RC3-with-workaround...
After login CAS only seems to pass the _last_ attribute mapped in the AttributeReleasePolicy now.

For reproducing on testshib I added another mapped attribute (mail) to the service-def for easy visualization (otherwise you have to dig in the shibd.log):
 
```json
{
  "@class" : "org.apereo.cas.support.saml.services.SamlRegisteredService",
  "serviceId" : "https://sp.testshib.org/shibboleth-sp",
  "name" : "SAMLService",
  "id" : 10000003,
  "evaluationOrder" : 10,
  "metadataLocation" : "http://www.testshib.org/metadata/testshib-providers.xml",
  "attributeReleasePolicy" : {
    "@class" : "org.apereo.cas.services.ReturnMappedAttributeReleasePolicy" ,
    "allowedAttributes" : {
      "@class" : "java.util.TreeMap",
      "uid" : "uid",
      "displayName" : "urn_mace_dir_attribute-def_displayName",
      "mail" : "urn_mace_dir_attribute-def_mail"
    }
  }
}
```
The result with RC3-with-workaround: after login to testshib-SP you will actually see your displayName and mail.
The result with RC4-SNAPSHOT: you will only see the mail attribute.

I can confirm from the 
```
DEBUG [org.jasig.cas.client.validation.Cas30ServiceTicketValidator] - <Server response: <cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    <cas:authenticationSuccess>
....
``` 
message in cas.log that the xml contains only 1 of the mapped attributes for RC4-SNAPSHOT, but all attributes for RC3.

**Comment by mmoayyed** [comment]
How r u resolving attributes?

**Comment by ernestojanus** [comment]
through [LDAP](https://github.com/apereo/cas/blob/master/docs/cas-server-documentation/installation/Configuration-Properties.md#ldap-authentication) and then using the mapped [Authentication Attributes](https://github.com/apereo/cas/blob/master/docs/cas-server-documentation/installation/Configuration-Properties.md#authentication-attributes) as per the docs.
The only added attribute to the defaults in the Authentication Attributes is
```
cas.authn.attributeRepository.attributes.mail=mail
```

**Comment by mmoayyed** [comment]
Remove the attribute repository. If you are resolving attributes from ldap, the attribute repository won't be taken into account .

**Comment by ernestojanus** [comment]
wait, are
```
# cas.authn.attributeRepository.attributes.displayName=displayName
# cas.authn.attributeRepository.attributes.cn=commonName
# cas.authn.attributeRepository.attributes.affiliation=groupMembership
```
not resolved by default anymore in RC4 when you define an extra attribute (e.g. the mail-one I just mentioned)?
I just realized that the only attribute that comes through seems to be the one I added myself in both cases (which also happens to be the last one in both release mappings).

**Comment by ernestojanus** [comment]
Sorry for the confusion, I'm only doing authentication (type AUTHENTICATED) using LDAP, not explicit attribute resolving.

**Comment by mmoayyed** [comment]
Not anymore. The static attribute repository is only consulted if you have no other repository sources defined for attributes and if you are not retrieving attributes from ldap as part of authn. Even then you must define the attributes yourself as defaults no longer are there. They caused more confusion than anything else.

**Comment by ernestojanus** [comment]
OK, I just added the previous defaults explicitly and stuff works again! Thanks for the help, feel free to close the issue :)

**Comment by mmoayyed** [comment]
Always a pleasure.
