### ISSUE TITLE
MFA-Duo /samlValidate: Error generating SAML response

### ISSUE THREAD

**Issue by bifyu** [apereo/cas#2039]
- CAS server version: RC4-SNAPSHOT
- Container/environment type/version: Tomcat 8.0.37

Using a service definition that includes
`  "multifactorPolicy" : {
    "@class" : "org.apereo.cas.services.DefaultRegisteredServiceMultifactorPolicy",
    "multifactorAuthenticationProviders" : [ "java.util.LinkedHashSet", [ "mfa-duo" ] ],
    "failureMode" : "OPEN"
  }`

After providing my username and password to the app that uses the Java CAS client (v3.4.2), Duo is invoked. However, after providing the Duo factor it successfully validates the ticket but throws an exception generating the SAML response:

`DEBUG [org.apereo.cas.support.saml.web.SamlValidateController] - <Successfully validated service ticket AAE***Cq2 for service [https://example.edu/app]>
ERROR [org.apereo.cas.support.saml.web.view.Saml10SuccessResponseView] - <Error generating SAML response for service example.edu.>
java.lang.ClassCastException: java.util.HashSet cannot be cast to java.lang.String
        at org.apereo.cas.support.saml.web.view.Saml10SuccessResponseView.prepareResponse(Saml10SuccessResponseView.java:60) ~[cas-server-support-saml-5.0.0.RC4-SNAPSHOT.jar:5.0.0.RC4-SNAPSHOT]
        at org.apereo.cas.support.saml.web.view.AbstractSaml10ResponseView.renderMergedOutputModel(AbstractSaml10ResponseView.java:104) ~[cas-server-support-saml-5.0.0.RC4-SNAPSHOT.jar:5.0.0.RC4-SNAPSHOT]
        ...`

**Comment by mmoayyed** [comment]
Have you tried running with the latest RC4 snapshot?

**Comment by bifyu** [comment]
fixed
