### ISSUE TITLE
Contracts for ExpirationPolicy and MultiTimeUseOrTimeoutExpirationPolicy differ in used time units

### ISSUE THREAD

**Issue by FSchumacher** [apereo/cas#2043]
In CAS 5.0.0.RC4-snapshot (probably earlier too) the contracts for `ExpirationPolicy#getTimeToLive` and `MultiTimeUseOrTimeoutExpirationPolicy#getTimeToLive` seem to differ in their time-resolution.

`MultiTimeUseOrTimeoutExpirationPolicy` gets initialized with values in units of milliseconds (and returns them without conversion), while `ExpirationPolicy#getTimeToLive` states, that it returns values in units of seconds.

That leads to a rather long timeout for tickets.

**Comment by mmoayyed** [comment]
Thanks. This is more of a javadocs issue; all ticket expiration policies should do proper conversions. If you find an instance that is not handled, please post back.

**Comment by FSchumacher** [comment]
Well, I was hit by it with `HazelcastTicketRegistry#addTicket`, where it uses the value as seconds.

**Comment by mmoayyed** [comment]
Good point. You're right. This should be fixed.

**Comment by mmoayyed** [comment]
I double checked. 

CAS consistently uses SECONDS for all expiration policies. We don't instantiate `MultiTimeUseOrTimeoutExpirationPolicy` at all. Rather, there are child classes for STs, PTs whose conversion is handled directly in Configuration classes. Same goes for all policies that deal with TGTs. So any registry that attempts to put a value inside a ticket registry acts one a timeout that is in seconds, and `ticket.getExpirationPolicy().getTimeToLive()` should always return the converted value in seconds. If you want this to be false somehow, please attach an overlay project so we can observe and duplicate the issue. 

Unless you create your own expiration policies, in which case, you're sort of on your own.

**Comment by FSchumacher** [comment]
Have a look at `CasCoreTicketsConfiguration#serviceTicketExpirationPolicy`. In there the config value for `timeToKillInSeconds` is converted to milliseconds and used for construction of the `ExpirationPolicy`, that value will then be used as seconds in the `HazelcastTicketRegistry`.

**Comment by mmoayyed** [comment]
You are right. Thanks for the pointer. I'll take a pass at this; turns out same is true for PTs actually.

**Comment by mmoayyed** [comment]
This should be done.
