### ISSUE TITLE
Cassandra ticket registry: Jackson annotations in interfaces

### ISSUE THREAD

**Issue by pampelix** [apereo/cas#2045]
Hi, 

we're planning to run CAS5 with a Cassandra cluster as ticket store, and we'd like to store tickets as serialized json objects. This serialization / deserialization is currently not possible because of missing Jackson annotations in interfaces. 
Can you add the following annotations: 

AbstractTicket: 
@JsonIdentityInfo(generator=ObjectIdGenerators.IntSequenceGenerator.class)

Authentication, Principal, ExpirationPolicy, CredentialMetaData
@JsonTypeInfo(use=JsonTypeInfo.Id.MINIMAL_CLASS, include= JsonTypeInfo.As.PROPERTY)

Thanks

**Comment by mmoayyed** [comment]
You are welcome to submit a pull request, once you have tested the change. Please do that.
