### ISSUE TITLE
Unable to use the LDAP authenticator with version 5.0.0-RC3

### ISSUE THREAD

**Issue by akraxx** [apereo/cas#2047]
Hi,

I am trying to use the LDAP authenticator for an OpenLdap, but I'm not able to contact it, I followed this : https://apereo.github.io/cas/development/installation/LDAP-Authentication.html

And I tried with this configuration :

```
##
# CAS Authentication Credentials
#
cas.authn.accept.users=

##
# CAS Authentication Attributes
#

cas.authn.ldap[0].ldapUrl=ldap://localhost:389
cas.authn.ldap[0].useSsl=false
cas.authn.ldap[0].useStartTls=false
cas.authn.ldap[0].connectTimeout=5000
cas.authn.ldap[0].bindDn=cn=admin,dc=example,dc=org
cas.authn.ldap[0].bindCredential=admin
cas.authn.ldap[0].usePasswordPolicy=false
cas.authn.ldap[0].dnFormat=uid=%s,dc=example,dc=org
cas.authn.ldap[0].type=DIRECT
```

I have nothing in the cas logs related to the LDAP authenticator, neither in my ldap logs

Did I miss something?

- CAS server version : 5.0.0-RC3
- Container/environment type/version : tomcat / windows

**Comment by mmoayyed** [comment]
BaseDN?

**Comment by akraxx** [comment]
Exactly, thank you!

**Comment by mmoayyed** [comment]
This speaks to a larger issue, which is that CAS should have prompted you about the missing setting as a WARN entry in the logs. Invisibly failing is never the right thing to do, so we'll account for that. Thank you for the feedback!
