### ISSUE TITLE
Ehcache config load / delete error in 5.x

### ISSUE THREAD

**Issue by rfrovarp** [apereo/cas#2054]
Running against CAS 5.x RC3, with Ehcache configuration.

Not changing any configuration values in the properties file.

I'm getting a stacktrace upon a cold / clean startup about not being able to delete a file out of a directory:

```
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: File does not exist: /tmp/cas/ehcache-replicated.xml
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at org.apereo.cas.util.ResourceUtils.prepareClasspathResourceIfNeeded(ResourceUtils.java:138)
	at org.apereo.cas.util.ResourceUtils.prepareClasspathResourceIfNeeded(ResourceUtils.java:79)
	at org.apereo.cas.config.EhcacheTicketRegistryConfiguration.cacheManager(EhcacheTicketRegistryConfiguration.java:60)
	at org.apereo.cas.config.EhcacheTicketRegistryConfiguration$$EnhancerBySpringCGLIB$$b55fdc4b.CGLIB$cacheManager$2(<generated>)
	at org.apereo.cas.config.EhcacheTicketRegistryConfiguration$$EnhancerBySpringCGLIB$$b55fdc4b$$FastClassBySpringCGLIB$$ed1ea947.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at org.apereo.cas.config.EhcacheTicketRegistryConfiguration$$EnhancerBySpringCGLIB$$b55fdc4b.cacheManager(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 64 more
Caused by: java.io.FileNotFoundException: File does not exist: /tmp/cas/ehcache-replicated.xml
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2377)
	at org.apereo.cas.util.ResourceUtils.prepareClasspathResourceIfNeeded(ResourceUtils.java:114)
```

Yes, the file does not exist. Default configuration pulls from the classpath, which is working as I misplaced it and it complained about that. If I simply touch a file at the specified path, it will delete it and replace it with the one from the classpath.

Looking at master, it is still calling a forceDelete, which fails when the item isn't there. That doesn't seem ideal.

**Comment by mmoayyed** [comment]
You cannot not modify the settings. Change settings to point to a valid file either in classpath or elsewhere. If you find that doesn't work, please submit your overlay so we can duplicate it.

**Comment by rfrovarp** [comment]
It is pointing to a valid file in the classpath. But something goes through and eventually calls FileUtils.forceDelete().
http://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/FileUtils.html#forceDelete(java.io.File)

Throws:
NullPointerException - if the directory is null
FileNotFoundException - if the file was not found
IOException - in case deletion is unsuccessful

So if the file doesn't exist, it throws an exception, and kill it, at least running under java -jar cas.war.

I'm trying to figure out why you are forcing that a file exists in a temp directory for the system to start. I'm guessing that this impacts other configurations than just EHcache. If I touch the file in the temp directory, Commons IO can then delete the file, and then replaces it with the file from the classpath. So the issue only arises when you have an empty temp directory. Forcing content to be in a temp directory prior to startup doesn't seem like the right design choice.

**Comment by mmoayyed** [comment]
The issue has to do with loading classpath resources inside a jar in an embedded environment where we need to physically realize a stream and turn it into a file so it can consumed by something else. Admittedly, that's not the best approach but I'd have to see an overlay to reproduce this, or instructions on how to reproduce this exactly before proceeding further.

**Comment by mmoayyed** [comment]
And you shouldn't be running RC3 anyway.

**Comment by rfrovarp** [comment]
There isn't a RC4 yet, so I'm on RC3. I know that I will run into already
fixed errors, but the offending line is still in master.

The reproducible step is to use EHcache or anything else that does the copy
from the classpath to temp, but make sure that the temp directory is empty.
forceDelete requires that the file exists to delete, otherwise it throws a
exception.

The code that does the steps you describe on line 114 of ResourceUtils
throws an exception if the file doesn't exist in the temp location upon a
delete. If that exception is thrown, it skips all of the code that copies
it out of the war to the temp location, lands in a catch, which is then
rethrown as an unchecked exception.

If line 114 is a regular delete that doesn't enforce that the file exists
prior to the delete, this all works as expected.

**Comment by mmoayyed** [comment]
>The reproducible step is to use EHcache or anything else that does the copy
from the classpath to temp, but make sure that the temp directory is empty.
forceDelete requires that the file exists to delete, otherwise it throws a
exception.

Thanks, but that's not quite what I am looking for. What would be better is:

1. I added this module into X
2. I set this setting to Y
3. here is a copy of Y
4. I see this exception, error in my logs (as above)

Once you can do that, we can spend time to review. Or, as the issue template suggests `When and where appropriate, please submit your CAS configuration/overlay to this project in form of a pull request so we could easily evaluate your deployment configuration to reproduce the issue.`

Or provide a unit test that causes a failure. Otherwise, all I can tell you personally is that I can't duplicate it.

Or pause the discussion, and provide a PR with a test :)

Thanks.

**Comment by mmoayyed** [comment]
Also, just to show you what I have done so far to diagnose this:

1. I added the ehcache module into an overlay.
2. I didnt change any of the settings.
3. Started up via the embedded tomcat.

Received this error:

```
Caused by: java.io.FileNotFoundException: class path resource [ehcache-replicated.xml] cannot be resolved to URL because it does not exist
        at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
        at org.apereo.cas.util.ResourceUtils.prepareClasspathResourceIfNeeded(ResourceUtils.java:101)
        ... 73 more
```

Fine. 

So then I added:

```
cas.ticket.registry.ehcache.configLocation=file:/etc/cas/ehcache-replicated.xml
```

In the properties and the file was read correctly. Is there a step I am missing?

**Comment by rfrovarp** [comment]
That's not coming from the classpath in the war.

cas.ticket.registry.ehcache.configLocation=classpath://
ehcache-replicated.xml

Or just don't specify anything and use the default configuration. Then
stick the file in src/main/resources

rm -rf /tmp/cas

mvn package
java -jar target/cas.war

On Oct 19, 2016 6:54 AM, "Misagh Moayyed" <notifications@github.com> wrote:

Also, just to show you what I have done so far to diagnose this:

   1. I added the ehcache module into an overlay.
   2. I didnt change any of the settings.
   3. Started up via the embedded tomcat.

Received this error:

Caused by: java.io.FileNotFoundException: class path resource
[ehcache-replicated.xml] cannot be resolved to URL because it does not
exist
        at org.springframework.core.io.ClassPathResource.getURL(ClassPathResource.java:187)
        at org.apereo.cas.util.ResourceUtils.prepareClasspathResourceIfNeeded(ResourceUtils.java:101)
        ... 73 more

Fine.

So then I added:

cas.ticket.registry.ehcache.configLocation=file:/etc/cas/ehcache-replicated.xml

In the properties and the file was read correctly. Is there a step I am
missing?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/apereo/cas/issues/2054#issuecomment-254790932>, or mute
the thread

**Comment by mmoayyed** [comment]
Sure. See the update to my last comment. Did that as well and still no failures :(

**Comment by mmoayyed** [comment]
Guess I can remove the /tmp/cas and try again. Hang on.

**Comment by mmoayyed** [comment]
No difference.

**Comment by rfrovarp** [comment]
I'll try to put something together tonight. Are you testing on Linux or
macOS? I have seen differences in IO exceptions on Linux vs macOS. I'm
experiencing the problem on Linux.

**Comment by mmoayyed** [comment]
Excellent. I look forward to it.

I am testing this on MacOS El Capitan and Windows 10 Pro. Both in embedded Tomcat/Jetty/Undertow and external instances just to be safe.

**Comment by rfrovarp** [comment]
So it isn't platform specific. Testing commons-io 2.5 on my desktop (Ubuntu) and VM (Windows 7) both running Oracle JDK, it throws the exception. Here is the minimal full project I was able to put together. Most of it comes from leleuj's overlay demo. It is pointing it at your snapshot repo and replicated with 5.0.0.RC4-SNAPSHOT on Linux and Windows. If you remove src/main/resources/ehcache-replicated.xml, it complains about the file not being found in the classpath, which is what I would expect. Have it there and it complains that it can't delete out of the temp directory.

If you 
  touch /tmp/cas/ehcache-replicated.xml

then start, it works as the file exists so that it can delete it to replace it.

[startup-bug.tar.gz](https://github.com/apereo/cas/files/539268/startup-bug.tar.gz)

**Comment by mmoayyed** [comment]
Nice. Let me look into this then.

**Comment by mmoayyed** [comment]
All hail. Finally! I can see the failure. Thanks. I'll look into this a bit more.

**Comment by mmoayyed** [comment]
Try the new RC4 snapshot with -U and report back please.

**Comment by rfrovarp** [comment]
My Nexus isn't picking up the latest snapshot. Looking at the change, it certainly looks correct.
