### ISSUE TITLE
Bad JWT expiration date for OIDC

### ISSUE THREAD

**Issue by akraxx** [apereo/cas#2056]
Hi,

I think there is a problem with the JWT expiration date, the timeout is specified in seconds but when you look at : https://github.com/apereo/cas/blob/1b36169b89fa9f30469f4a22a372e4e1cbe8e010/support/cas-server-support-oidc/src/main/java/org/apereo/cas/web/OidcAccessTokenResponseGenerator.java#L100

The timeout is added in minutes :

```java
claims.setExpirationTimeMinutesInTheFuture(timeout);
```

By default the timeout is 7200 seconds for 2 hours, but after JWT crafting it's 5 days (7200 minutes)

CAS version : 5.0.0-RC3

**Comment by mmoayyed** [comment]
You are absolutely right. Would you rather submit a PR to get this fixed? Maybe convert `casProperties.getTicket().getTgt().getTimeToKillInSeconds()` to MINUTES via TimeUnit?

**Comment by akraxx** [comment]
Yes, or i can do something like :

```
setExpirationTime(NumericDate.now().addSeconds(timeout));
```

With this we can keep all the timeout in seconds in the properties (refresh token, access token ...)

**Comment by mmoayyed** [comment]
Sounds perfect. Please do.
