### ISSUE TITLE
application.properties: Attribute repositories should be lists

### ISSUE THREAD

**Issue by Erdou** [apereo/cas#2059]
As using multiple attributes repositories (like LDAP + JDBC) automatically creates the merger DAO, one may want to merge multiple same type repos (especially 2x JDBC, for merging one multi-row and one single-row).

It will be nice to have lists in the same way as it's done for authentication handlers. I.e.:

> cas.authn.attributeRepository.jdbc**[0]**.singleRow=false
> ...

Environment:
- CAS server: 5.0.0-RC4-SNAPSHOT
- Embedded Tomcat
- Linux
- Built with Maven Overlays

**Comment by mmoayyed** [comment]
You can do this already:

cas.authn.attributeRepository.jdbc[1].singleRow=false

cas.authn.attributeRepository.jdbc[2].singleRow=true

etc.

**Comment by Erdou** [comment]
Yes, that was what I meant but it doesn't seem to work:

`2016-10-19 17:36:54,766 WARN [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.ryantenney.metrics.spring.MetricsBeanPostProcessorFactory#4': Cannot resolve reference to bean 'metrics' while setting constructor argument; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'casMetricsConfiguration': Unsatisfied dependency expressed through field 'casProperties'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cas-org.apereo.cas.configuration.CasConfigurationProperties': Could not bind properties to CasConfigurationProperties (prefix=cas, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.beans.InvalidPropertyException: Invalid property 'authn.attributeRepository.jdbc[0][dialect]' of bean class [org.apereo.cas.configuration.model.core.authentication.AuthenticationProperties]: Illegal attempt to get property 'jdbc' threw exception; nested exception is org.springframework.beans.InvalidPropertyException: Invalid property 'authn.attributeRepository.jdbc[0][dialect]' of bean class [org.apereo.cas.configuration.model.core.authentication.AuthenticationProperties]: Property referenced in indexed property path 'jdbc[0][dialect]' is neither an array nor a List nor a Set nor a Map; returned value was [org.apereo.cas.configuration.model.core.authentication.PrincipalAttributesProperties$Jdbc@607fbe09]>`

With the configuration:

```
##
# JDBC attribute repository 1
#
cas.authn.attributeRepository.jdbc[0].singleRow=false
cas.authn.attributeRepository.jdbc[0].requireAllAttributes=false
cas.authn.attributeRepository.jdbc[0].caseCanonicalization=NONE
cas.authn.attributeRepository.jdbc[0].columnMappings.name=value

cas.authn.attributeRepository.jdbc[0].sql=SELECT u.login AS sAMAccountName, f.name AS name, f.`type` AS `type`, m.value AS value FROM user AS u JOIN metadata AS m ON u.id = m.user_id JOIN field AS f ON m.field_id = f.id WHERE f.application_id = 1 AND {0}
cas.authn.attributeRepository.jdbc[0].username=login
cas.authn.attributeRepository.jdbc[0].healthQuery=SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
cas.authn.attributeRepository.jdbc[0].url=jdbc:mysql://localhost/db
cas.authn.attributeRepository.jdbc[0].failFast=false
cas.authn.attributeRepository.jdbc[0].isolationLevelName=ISOLATION_READ_COMMITTED
cas.authn.attributeRepository.jdbc[0].dialect=org.hibernate.dialect.MySQLDialect
cas.authn.attributeRepository.jdbc[0].leakThreshold=10
cas.authn.attributeRepository.jdbc[0].propagationBehaviorName=PROPAGATION_REQUIRED
cas.authn.attributeRepository.jdbc[0].batchSize=1
cas.authn.attributeRepository.jdbc[0].user=mysqlUser
cas.authn.attributeRepository.jdbc[0].ddlAuto=create-drop
cas.authn.attributeRepository.jdbc[0].password=secret
cas.authn.attributeRepository.jdbc[0].autocommit=false
cas.authn.attributeRepository.jdbc[0].driverClass=com.mysql.jdbc.Driver
cas.authn.attributeRepository.jdbc[0].idleTimeout=5000
cas.authn.attributeRepository.jdbc[0].pool.suspension=false
cas.authn.attributeRepository.jdbc[0].pool.minSize=6
cas.authn.attributeRepository.jdbc[0].pool.maxSize=18
cas.authn.attributeRepository.jdbc[0].pool.maxIdleTime=1000
cas.authn.attributeRepository.jdbc[0].pool.maxWait=2000


##
# JDBC attribute repository 2
#
cas.authn.attributeRepository.jdbc[1].singleRow=true
cas.authn.attributeRepository.jdbc[1].requireAllAttributes=false
cas.authn.attributeRepository.jdbc[1].caseCanonicalization=NONE

# Used only when there is a mapping of many rows to one user
# cas.authn.attributeRepository.jdbc[1].columnMappings.columnAttrName1=columnAttrValue1
# cas.authn.attributeRepository.jdbc[1].columnMappings.columnAttrName2=columnAttrValue2
# cas.authn.attributeRepository.jdbc[1].columnMappings.columnAttrName3=columnAttrValue3
# cas.authn.attributeRepository.jdbc[1].columnMappings.name=value

#cas.authn.attributeRepository.jdbc[1].sql=SELECT * FROM user WHERE {0}
cas.authn.attributeRepository.jdbc[1].sql=SELECT login AS sAMAccountName FROM user WHERE {0}
cas.authn.attributeRepository.jdbc[1].username=login
cas.authn.attributeRepository.jdbc[1].healthQuery=SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
# cas.authn.attributeRepository.jdbc[1].isolateInternalQueries=false
cas.authn.attributeRepository.jdbc[1].url=jdbc:mysql://localhost/db
cas.authn.attributeRepository.jdbc[1].failFast=false
cas.authn.attributeRepository.jdbc[1].isolationLevelName=ISOLATION_READ_COMMITTED
cas.authn.attributeRepository.jdbc[1].dialect=org.hibernate.dialect.MySQLDialect
cas.authn.attributeRepository.jdbc[1].leakThreshold=10
cas.authn.attributeRepository.jdbc[1].propagationBehaviorName=PROPAGATION_REQUIRED
cas.authn.attributeRepository.jdbc[1].batchSize=1
cas.authn.attributeRepository.jdbc[1].user=mysqlUser
cas.authn.attributeRepository.jdbc[1].ddlAuto=create-drop
cas.authn.attributeRepository.jdbc[1].password=secret
cas.authn.attributeRepository.jdbc[1].autocommit=false
cas.authn.attributeRepository.jdbc[1].driverClass=com.mysql.jdbc.Driver
cas.authn.attributeRepository.jdbc[1].idleTimeout=5000
cas.authn.attributeRepository.jdbc[1].pool.suspension=false
cas.authn.attributeRepository.jdbc[1].pool.minSize=6
cas.authn.attributeRepository.jdbc[1].pool.maxSize=18
cas.authn.attributeRepository.jdbc[1].pool.maxIdleTime=1000
cas.authn.attributeRepository.jdbc[1].pool.maxWait=2000
```

Note that the documentation does'nt show the list way (indices). But that's the easy part to change :)

**Comment by mmoayyed** [comment]
Ah you are so very right. I don't know why I thought repositories can be lists. They certainly are not designed to handle this. Going to mark this for 5.1, as this is not a bug per se. 

Good reporting.

**Comment by mmoayyed** [comment]
This is handled in 5.1.0-SNAPSHOT
