### ISSUE TITLE
Additional attribute repositories should be merged with attributes resolved in LDAP authentication

### ISSUE THREAD

**Issue by Erdou** [apereo/cas#2061]
Currently, in CAS 5.0.0, one cannot use attributes gotten in LDAP authentication because that will make additional attribute repositories ignored. I.e. when those are not empty or commented:

```
cas.authn.ldap[0].principalAttributeId=
cas.authn.ldap[0].principalAttributeList=
```

That's a pity, because if you want an LDAP authentication with subsequent LDAP attributes + SQL attributes fetched by JDBC attribute repository, you'll have to declare an LDAP attribute repository over the LDAP authentication handler.

I would be nice and "logic" to simply merge additional repositories with attributes given by authentication handlers.

**Comment by mmoayyed** [comment]
Hey @Erdou are you available to test this issue if a patch was produced?

**Comment by mmoayyed** [comment]
This is now done in 5.1 SNAPSHOTs. (Docs updated) When you can a chance it would be great if you could try it and report back any and all issues.

**Comment by Erdou** [comment]
Hi Misagh!

Sorry I've just read this message,
Yes sure! I'm waiting for it :)



*Erdal.*

2016-11-23 0:28 GMT+01:00 Misagh Moayyed <notifications@github.com>:

**Comment by mmoayyed** [comment]
Hey there, you should be able to test this with snapshots going out. LMK if you run into any issues. Tnx!
