### ISSUE TITLE
CAS User Interface Enhancements

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#2068]
Improve the following shortcomings of the admin user interfaces:
- [X] Allow the configuration screen to edit CAS properties in place. Update/Refresh and notify.
- [X] Allow reporting back of the refreshed properties when done manually.
- [X] Add new field for signing algorithm to management app
- [x] Allow configuration of log levels.
- [] Allow successful/failed authn attempts into the stats page as a chart

Working with @mindblender on this one.

**Comment by leleuj** [comment]
Includes: https://github.com/apereo/cas/issues/1976

**Comment by mmoayyed** [comment]
@mindblender how are we doing on this issue?

**Comment by mmoayyed** [comment]
Reported back the following issues to @mindblender  with the current management webapp:

Service Type: should be WS Federation Client

OpenID Client type: 
- extra scopes: OAuth2 Client, SAML2 Service Provider, OpenID Connect Client (Should be removed)
- Attribute release tab should be removed/hidden
SAML2 Service Provider: 
- Attribute Release Return Allowed/Mapped/PatternMatcing disabled?! They seem to be disabled for all types.
Multifactor Authentication Providers: Change into dropdown (with the ability to type). List of options are: https://apereo.github.io/cas/development/installation/Configuring-Multifactor-Authentication.html#supported-providers. Use the ID column (without Custom)
- Username attribute: Anonymous: Add option for "Principal Attribute". Text field.
- Access Strategy: Required attributes: unable to add/remove attributes. No buttons? 

Server work is still expected to be verified.

**Comment by mmoayyed** [comment]
Closing to move the conversation into the PR directly.
