### ISSUE TITLE
Attribute repositories with own mappings / released attributes list

### ISSUE THREAD

**Issue by Erdou** [apereo/cas#2083]
Currently, attribute repositories share:
- The same mappings through: `cas.authn.attributeRepository.attributes.*`
- The same bundled releases through: `cas.authn.attributeRepository.defaultAttributesToRelease=`

It would be nice and more useful if those settings weren't global but per attribute repository, as:
- One may want to map differently (ex. mapping "uid" to "login" from LDAP and "uid" to "userId" from JDBC)
- One may want to release everything from a repo but only some attributes from another one (ex. all from DB but only a few from the messy Active Directory. See issue #2078).

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.
