### ISSUE TITLE
How can a CAS client determine a user's authentication status without redirecting the browser to the CAS login page?

### ISSUE THREAD

**Issue by timotgl** [apereo/cas#2086]
This is kind of a high-level, conceptual question, since I couldn't find an answer on the mailing list. Apologies if this is not the right place to ask.

From what I understand, the CAS client (webapp) needs to maintain a session with the user. What happens if the user logs out of CAS in a new browser tab, but remains on the webapp in another tab? Is there any way for the CAS client to simply check on the user's authentication status **without** redirecting through CAS?

Our scenario is that we don't have "normal" session management (we use encrypted cookies with a limited lifespan) and now have the requirement to find out wether a user is still authenticated with CAS **without** doing the normal redirect flow.

I was told that it should be possible to use proxy granting tickets, saved in the client's browser cookies, to accomplish that. But I can't really wrap my head around the concept.

From my understanding of CAS, it is simply not possible to find out wether a user is still authenticated without following the normal workflow which includes redirects. Is this correct?

**Comment by mmoayyed** [comment]
Your understanding is correct, so as long as you are excluding `gateway=true` (which does involve a redirect). There is no heartbeat mechanism, yet.

**Comment by mmoayyed** [comment]
This question has been asked several times by the way, and I wonder if we could perhaps provide a protocol extension to support a heartbeat without involving the browser and `gateway`. Do post on the mailing list and see if there are any takers.
