### ISSUE TITLE
docker pull  error

### ISSUE THREAD

**Issue by zhongtianxie** [apereo/cas#2094]
test$ docker pull apereo/cas:v4.2.6
v4.2.6: Pulling from apereo/cas
bb59160dd3ff: Downloading [===============================>                   ]   116 MB/185 MB
c87a3e7ac7b0: Download complete 
......
......
e62faf404001: Already exists 
86b37a0f27c3: Already exists 
Pulling repository apereo/cas
**FATA[3086] Tag v4.2.6 not found in repository apereo/cas**

**Comment by mmoayyed** [comment]
```
>  docker pull apereo/cas:v4.2.6
v4.2.6: Pulling from apereo/cas

a3ed95caeb02: Pull complete
05346a7282e1: Pull complete
c033fe5f15e1: Pull complete
f1060f95f756: Pull complete
f7b2fa50d41e: Pull complete
245e4c8c867a: Pull complete
9faafbcd273e: Pull complete
0ab89b4c6d0a: Pull complete
d8eb7019d7da: Pull complete
068fe81c68c0: Pull complete
Digest: sha256:9a730038826b51d38be477d5e48f74e4e5a71d852ddc2f0e4a89893331220efd
Status: Downloaded newer image for apereo/cas:v4.2.6
```
