### ISSUE TITLE
AddOns add duplicate jars.

### ISSUE THREAD

**Issue by CobraFlow** [apereo/cas#2095]
Version 5.0.0.RC4

I have noticed duplicate jars appearing in my CAS war file when I add Add Ons.

When I add the following I get duplicates the same three jars...
cas-server-support-jdbc, cas-server-support-pac4j-webflow, cas-server-support-pac4j-webflow (there may be others)
- classmate
- commons-beanutils
- httpcore

**Comment by mmoayyed** [comment]
Can you produce an overlay that duplicates the problem?

**Comment by CobraFlow** [comment]
Yes.
I have a [github](https://github.com/CobraFlow/security-test-area) project that I use to try to get OAuth2 and CAS delegate working.

It shows this issue in the cas-server-2 module.

With the dependencyManagement section commented, you see the issue.

**Comment by mmoayyed** [comment]
Thanks. This should be fixed in about 30 minutes once the new snapshot goes out. Please try again and report back if you still see similar issues.

**Comment by CobraFlow** [comment]
Excellent. Fixed.

Thank you!

**Comment by mmoayyed** [comment]
Always a pleasure.
