### ISSUE TITLE
OIDC Delegated AuthN: Allow configuring scope

### ISSUE THREAD

**Issue by aanli** [apereo/cas#2096]
Allow configuring Oidc scope.
It will be useful to retrieve values other than the defaults (profile, mail, openid).

In cas.properties, we can have: "cas.pac4j.oidc.scope="

CAS 4.2

**Comment by mmoayyed** [comment]
I don't follow. Can't you put your own values as scopes in the same properly?

**Comment by aanli** [comment]
It's doesn't work.
This property is ignored.

**Comment by mmoayyed** [comment]
Thanks for the update. This is really an issue with pac4j. Once it starts to add support for scopes, we can certainly add it here. Feel free to open up an issue for the pac4j project. 

cc: @leleuj

**Comment by aanli** [comment]
pac4j supports scopes.
http://www.pac4j.org/1.9.x/docs/clients/openid-connect.html

You can define the scope to use with the _setScope_ method:
`config.setScope("openid email profile phone");`

**Comment by mmoayyed** [comment]
It needs to support it here https://github.com/pac4j/pac4j/blob/master/pac4j-config/src/main/java/org/pac4j/config/client/PropertiesConfigFactory.java

**Comment by mmoayyed** [comment]
If you want to submit a PR to pac4j, I am sure @leleuj  and others would be happy to merge it for you, and we can then build support for it here as well.

**Comment by mmoayyed** [comment]
This feature requires pac4j 1.9.4, not-currently released.

**Comment by mmoayyed** [comment]
Should be solved in the latest snapshot. CAS builds on pac4j 2.0.0 SNAPSHOT.
