### ISSUE TITLE
[5.0.0.RC4] Infinispan ticket registry not working for Service Tickets

### ISSUE THREAD

**Issue by rfrovarp** [apereo/cas#2097]
I'm not having any luck with the Infinispan ticket registry with respect to Service Tickets. I'm getting back that the ticket is invalid. I'm having Infinispan dump to disk, and I can see that the ST string is in the file. It just isn't validating it. From testing, the SSO ticket is working and persisting through restarts, it's just the ST that isn't working.

I've been digging through the code, trying to figure out how it works. There appears to be potentially some inconsistency with the expiration policy, and that may be the issue. I'm trying to figure out intent to better understand where the bug may be.

ExpirationPolicy.getTimeToLive() and ExpirationPolicy.getTimeToIdle() both say that a zero value indicates the time duration is not supported or is inactive.

CasCoreTicketsConfiguration shows in serviceTicketExpirationPolicy() that it is most likely using MultiTimeUseOrTimeoutExpirationPolicy, which returns a zero for getTimeToIdle(). InfinispanTicketRegistry.addTicket() uses both the live and idle times without examination. However, I think Infinispan might have issues with the zero second idle value. https://docs.jboss.org/infinispan/8.2/apidocs/org/infinispan/commons/api/BasicCache.html#put-K-V-long-java.util.concurrent.TimeUnit-long-java.util.concurrent.TimeUnit-

I see that the Infinispan unit tests are using NeverExpiresExpirationPolicy, which returns max int for idle, so the test isn't necessarily correct for what I think standard STs are going to be, assuming that my understanding of how this is supposed to work is correct.

The other oddity I noticed when trying to track this all down is that EhCacheTicketRegistry is using the ExpirationPolicy.getTimeToIdle() as both the idle and live time when interacting with EHcache. If I'm understanding this all correctly, that means that both of those values would be 0 for standard ST, and the EHcach documentation states that a zero means forever. So I think there is a bug there as well.

Both couchbase and memcache seem to be using the live time instead of the idle time. The to live time makes more sense.

**Comment by mmoayyed** [comment]
Can you try with the latest snapshot? RC5-SNAPSHOT that is.

**Comment by rfrovarp** [comment]
That worked for Infinispan.

**Comment by mmoayyed** [comment]
Very nice. Thanks for the update.
