### ISSUE TITLE
getOrder()  in YubiKeyMultifactorAuthenticationProvider

### ISSUE THREAD

**Issue by John-Chan** [apereo/cas#2099]
[YubiKeyMultifactorAuthenticationProvider](https://github.com/apereo/cas/blob/v5.0.0.RC4/support/cas-server-support-yubikey/src/main/java/org/apereo/cas/adaptors/yubikey/YubiKeyMultifactorAuthenticationProvider.java#L39)

should be 
`
return casProperties.getAuthn().getMfa().getYubikey().getRank();
`

**Comment by mmoayyed** [comment]
great catch. wanna submit a pull request to correct this?

**Comment by mmoayyed** [comment]
Handled via https://github.com/apereo/cas/commit/bd766cbe2681aadbe10db0fce3d57113cd8d0cef
