### ISSUE TITLE
CAS 5.x Infinispan doesn't remove from cache stores

### ISSUE THREAD

**Issue by rfrovarp** [apereo/cas#2100]
Using latest 5.0.0.RC5-SNAPSHOT, STs are now validated against Infinispan. The issue I'm seeing now is that TGTs aren't cleaned up against a persistent store. 

InfinispanTicketRegistry.deleteSingleTicket() calls cache.evict(). However, that simply removes it from memory, and not a persistent store or cluster:

https://docs.jboss.org/infinispan/8.2/apidocs/org/infinispan/Cache.html#evict-K-

cache.remove() should be called instead.
https://docs.jboss.org/infinispan/8.2/apidocs/org/infinispan/commons/api/BasicCache.html#remove-java.lang.Object-

[infinispan.patch.txt](https://github.com/apereo/cas/files/562539/infinispan.patch.txt)

**Comment by mmoayyed** [comment]
Excellent. Thanks. Could you turn the patch into a PR, or would you rather we apply it directly?

**Comment by rfrovarp** [comment]
Go ahead and apply the patch directly. I'm still learning GitHub and patches are way easier for me. Especially given the current repo size for CAS.

**Comment by mmoayyed** [comment]
Cool, thanks.

If you want to, you can easily get a much faster clone with `--depth 1` and if you only care about master, you can get away with `--single-branch --branch master`.

**Comment by mmoayyed** [comment]
via https://github.com/apereo/cas/commit/42705df0866bb1e40b491e4ef5796076a1fdb919
