### ISSUE TITLE
Delegated Authentication for LinkedIn using Pac4j

### ISSUE THREAD

**Issue by kripalsingh** [apereo/cas#2101]
Would like to request CAS5(for 5.0.0.RC4-SNAPSHOT) Delegated Authentication for linkedin . 
Please see below 
https://groups.google.com/a/apereo.org/forum/#!searchin/cas-user/linkedin/cas-user/tNRb1fkOUVY/Wz5JEoVGAgAJ

**Comment by mmoayyed** [comment]
This feature requires pac4j 1.9.4, not-currently released.

**Comment by leleuj** [comment]
In fact, it will be the 1.9.5 version (after the backport).

**Comment by mmoayyed** [comment]
Should be solved in the latest snapshot. CAS builds on pac4j 2.0.0 SNAPSHOT.

**Comment by kripalsingh** [comment]
thanks!

**Comment by leleuj** [comment]
@mmoayyed Upgrading to pac4j 2.0.0-SNAPSHOT is not a good idea: the development of this new version has just started. Things will be broken over and over again. And pac4j 2.0 is not to be expected before next year. I foresee CAS 5.1 will be ready earlier.

**Comment by mmoayyed** [comment]
Our timeline is around May 2017.

**Comment by mmoayyed** [comment]
Of course there will be plenty of RCs and such before that, and patch released if/when needed for 5.0.x..and we can push back the deadline.

**Comment by leleuj** [comment]
OK. So pac4j 2.0 will certainly be ready for that date. Just be prepared for some breaking changes ;-)

**Comment by mmoayyed** [comment]
No worries; ample opportunity to yell at you [and myself] :) and also good to see how changes can be applied in practice en masse.

**Comment by mmoayyed** [comment]
Speaking of which, [perhaps something to discuss on the pac4j list], release scheduled should be published on github [or somewhere] for pac4j even if dates are tentative.

**Comment by leleuj** [comment]
It makes sense. Let's target the same date for pac4j 2.0 and something before the end of the year (mid-December) for 1.9.5.

**Comment by yellowcola** [comment]
@mmoayyed Is there any plan to make a patch for 5.0.2? I'm currently looking into upgrade to 5.0.2 and LinkedIn Authentication is a requirement. Thanks!

**Comment by mmoayyed** [comment]
CAS is on 5.0.3 now; so no I have no plans to make patches. If you like, you can prepare a patch, post a PR to the 5.0.x branch and that will get included in the next patch release, 5.0.4.

**Comment by dima767** [comment]
Just a correction: `5.0.3` is not yet released

**Comment by mmoayyed** [comment]
Thanks dima. My bad!
