### ISSUE TITLE
Duo Security - Ability to specify integration keys to individual services

### ISSUE THREAD

**Issue by ericallen** [apereo/cas#2104]
Feature Request to Duo Security MFA Integration 

Currently the Duo Security integration, has one global integration key location set in the config file.  Using the attributes `cas.authn.mfa.duo.duoSecretKey`, `cas.authn.mfa.duo.duoApplicationKey`, `cas.authn.mfa.duo.duoIntegrationKey`, and `cas.authn.mfa.duo.duoApiHost`.  These settings apply to all services, making the same duo policy to apply to all services.  

Requesting to have the ability to override the global duo settings on a per service bases.  Allows applications to have different duo policies applied.  A use case for this is that we have a service that contains sensitive data or requires a different policy for compliance reasons than the default policy that applies to more general applications and data.

**Comment by jdbeutel** [comment]
I am interested in the same or similar feature.  I thought of it in terms of configuring another mfa-duo provider with a separate id and config params, so services that need a different duo policy could specify it to CAS via, e.g., authn_method=mfa-duo-different.  Could it be implemented in a general way, to allow such duplicates for any MFA provider?

**Comment by mmoayyed** [comment]
You can definitely build your own mfa provider, but you then also need to accompany that with all other components that deal with MFA. It's not a task for the faint hearted. 
What might be easier to implement as an option would be to allow services to define their duo config as properties to override the global. That's much easier to handle than a whole new MFA provider

**Comment by jdbeutel** [comment]
That would be fine, whatever is easier.  The apps do not need to specify the policy themselves, e.g., to upgrade the user's authentication level within the same app.

**Comment by mmoayyed** [comment]
This should now be supported in today's 5.1 snapshot.
