### ISSUE TITLE
CAS 5.x request to audit MFA start

### ISSUE THREAD

**Issue by rfrovarp** [apereo/cas#2105]
New feature request to audit the start / trigger of a MFA workflow. Duo in particular won't record MFA failures or abandons. All failures happen between the browser and Duo, and so CAS will never see them.

If triggering MFA would result in an audit event being thrown, any event that isn't followed by a MFA success message is either a failure or an abandon. 

So this is logged in the end:

```
2016-11-02 13:45:07,120 INFO [org.apereo.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN
WHO: richard.frovarp
WHAT: Supplied credentials: [org.apereo.cas.adaptors.duo.authn.web.DuoCredential@7f1152c8[username=richard.frovarp,signedDuoResponse=AUTH|<bunch of stuff>]]
ACTION: AUTHENTICATION_SUCCESS
APPLICATION: CAS
WHEN: Wed Nov 02 13:45:07 CDT 2016
CLIENT IP ADDRESS: 127.0.0.1
SERVER IP ADDRESS: 127.0.0.1
```

But nothing is logged before it, other than the AUTHENTICATION_SUCCESS from LDAP in my case. There isn't anything indicating the Duo was triggered, and that's what I would like to see.

**Comment by mmoayyed** [comment]
This is done in 5.1 now.
