### ISSUE TITLE
Couchbase Ticket Service not converting expiration policy correctly

### ISSUE THREAD

**Issue by ericallen** [apereo/cas#2106]
The couchbase ticket service is not converting the ticket expiration policy correctly.  It is treating the policy as minutes.  So the default of 28800 in seconds to 28800000 as minutes which is longer than the couchbase ticket service can handle so the tickets are immediately removed.  

From Misagh on chat
Any expiration time larger than 30 days in seconds is considered absolute (as in a Unix time stamp), anything smaller is considered relative in seconds.
the value that is passed is too big, or larger than 30 days in seconds but let me confirm.
yup that is issue. CAS is not doing conversions; the expiration value that is passed by default is in milli seconds, and CAS is not converting it to seconds, which means couchbase treats that value, 28800000, in minutes which is > 30 days in seconds
so the value gets treated as a Unix timestamp; thus all the weirdness

**Comment by mmoayyed** [comment]
This should be fixed in the latest snapshot. Updated docs as well.
