### ISSUE TITLE
CAS 5.x Management App doesn't honor server.port

### ISSUE THREAD

**Issue by rfrovarp** [apereo/cas#2107]
Using RC4 and RC5-SNAPSHOT, I can't get the management application to honor the server.port setting in application.properties upon startup via the embedded Tomcat using the java -jar method. 

I've also tried --server.port as the docs in the source indicate might work, and that too doesn't work. 

It also doesn't honor changing the server.context-path. So I'm not quite sure is needed. Luckily the embedded Tomcat container for the main CAS application does honor the server.port setting so I can switch that over to 8081 and let the management application live on 8080 for development purposes.

There's nothing of use in the logs, it does start, and other values in the config file for configuration are being honored, such as the service registry location.
[pom.txt](https://github.com/apereo/cas/files/569362/pom.txt)
[application.properties.txt](https://github.com/apereo/cas/files/569363/application.properties.txt)

**Comment by mmoayyed** [comment]
You likely need to set the spring-boot and tomcat logs to DEBUG to see what's happening but I'll take a pass.

**Comment by mmoayyed** [comment]
Here is what I did:

1. Downloaded your pom
2. Created src/main/resources and put your application.properties file in there
3. built via clean package
4. Ran the embedded container

http://localhost:8081/cas-mgmt came up just fine and redirected me to CAS. 

Check your config. I don't know what exactly you are seeing, but it's not possible to speculate without receiving an overlay
