### ISSUE TITLE
QueryDatabaseAuthenticationHandler not using passwordEncoder

### ISSUE THREAD

**Issue by rohajda** [apereo/cas#2112]
- [5.0.0] CAS server version
- Embedded Tomcat on OSx
- Configure cas.authn.jdbc.query[0].passwordEncoder.type=BCRYPT and use DatabaseAuthentication query. Authentication is not successful due code in **QueryDatabaseAuthenticationHandler** class

` if(!StringUtils.equals(password, e))` because that is not right way to check if there is match. Instead passwordEncoder.matches should be used where first argument is raw password as provided by user. Reason is that BCryptPasswordEncoder will not encode same password to same string so comparing them is irrelevant.

**Comment by mmoayyed** [comment]
Cool. Would you be willing to submit a pull request to get this fixed?

**Comment by rohajda** [comment]
Sure, just want your approval on my solution.

Step1)
 Into class **AbstractUsernamePasswordAuthenticationHandler** add new method (reason is that only this abstract class has passwordEncoder)

```
public boolean matches(final CharSequence rawPassword,final String password){
    return this.passwordEncoder.matches(rawPassword,password);
}
```

Step2)
 Modify **QueryDatabaseAuthenticationHandler** particular if statement to

```
if (!this.matches(password, dbPassword)) {
                throw new FailedLoginException("Password does not match value on record.");
            }
```

 I am working with CAS just over a week and trying to use just database authentication so I have not check if such issue is with other types of authentication.


 If you are ok with proposal i will create pull request

Regards
  Robert

**Comment by mmoayyed** [comment]
Sure. I'm okay with your suggestion. Thanks!

**Comment by rohajda** [comment]
Pull request #2114 created

**Comment by rohajda** [comment]
build failed as I have not fixed tests - i am working on it

**Comment by rohajda** [comment]
fixed. All green

**Comment by rohajda** [comment]
changes done as you suggested, test is green.

**Comment by rohajda** [comment]
having issue with internet, i will continue tomorrow

**Comment by mmoayyed** [comment]
No rush. Thanks!

**Comment by rohajda** [comment]
i am not yet familiar with gradle and master branch has issues

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':core:cas-server-core-configuration-cloud-vault:compileClasspath'.
> A conflict was found between the following modules:
   - org.apache.httpcomponents:httpcore:4.4.5
   - org.apache.httpcomponents:httpcore:4.4.4

```

is it something I am doing wrong or it is really an issue there?

**Comment by mmoayyed** [comment]
Are you on the latest commit?

**Comment by mmoayyed** [comment]
Accordingly to latest travis builds, there are no issues:
https://travis-ci.org/apereo/cas/builds

Make sure you're on the latest commit. If not, let me know what command you're using to build, etc.

**Comment by rohajda** [comment]
i synch this morning my fork. I can try again tomorrow.

**Comment by rohajda** [comment]
i will try to check out tomorrow whole project again and let you know if i have issues - i feel something wrong on my side - i saw travis ci is ok too.

**Comment by rohajda** [comment]
i have commited changes but travis ci build failed #4802 failed - it is part not modified by me.

```
:core:cas-server-core-authentication:test
org.apereo.cas.CentralAuthenticationServiceImplWithMockitoTests > verifyChainedAuthenticationsOnValidation FAILED
    java.lang.NullPointerException
        at org.apereo.cas.CentralAuthenticationServiceImpl.grantServiceTicket(CentralAuthenticationServiceImpl.java:168)
        at org.apereo.cas.CentralAuthenticationServiceImplWithMockitoTests.verifyChainedAuthenticationsOnValidation(CentralAuthenticationServiceImplWithMockitoTests.java:211)
```

please advice.

**Comment by gabedwrds** [comment]
I'm still seeing problems in 5.0.1. It looks like both Credentials in `AbstractUsernamePasswordAuthenticationHandler.doAuthenticate()` point to the same object so the original password isn't being kept intact to pass to `authenticateUsernamePasswordInternal()`. The bcrypt matching function gets a new hash instead of the raw password and authentication fails.

IMO, AbstractUsernamePasswordAuthenticationHandler shouldn't be encoding passwords at all when the encoder is a BCryptPasswordEncoder. Bcrypt hashes are way too CPU-intensive to waste.

I can work on fixing this if no one's currently on it. Let me know if you'd rather have this on a separate issue.

**Comment by mmoayyed** [comment]
Yes do a separate issue please, and by all means, do submit a PR at your convenience.
