### ISSUE TITLE
Change properties involving time values to Durations

### ISSUE THREAD

**Issue by tsschmidt** [apereo/cas#2115]
Found an issue in CAS 5.0.x in Beans.java where newDuration(long time) is coded to use Duration.ofSeconds() for all time values that are in the properties.  Problem is some properties are defaulted to values that represent milliseconds and some are in seconds.  AbstractLdapProperties.java has connectTimeout and blockWaitTime that are being set to well over an hour because their default values are set in units of milliseconds.

It would be clearer if we changed the properties to accept Strings and values could be set like PT5S so no one has to guess or lookup what the time units are supposed to be.

**Comment by mmoayyed** [comment]
We should in theory be accepting everything in seconds. I agree durations likely would be clearer. For the time being, what are the exact number of settings that are classified as milliseconds? Let's get those fixed and converted into seconds and we'll worry about durations later.

**Comment by tsschmidt** [comment]
Only ones I see that are way off are:
The ldap.connectTimeout is set to 5000 which is ~ 1 hour 20 mins .  
The blockWaitTime is set to 6000 which is ~ 1 hr 40 mins.
The prunePeriod is set to 10000 which is ~ 2 hr 45 mins.

**Comment by mmoayyed** [comment]
I am going to take a pass at this today.

**Comment by mmoayyed** [comment]
Resolved with help. Thanks everyone! Do test master or 5.1 SNAPSHOT and report back issues/findings please.
