### ISSUE TITLE
Services using Callback URL not displaying correct UI

### ISSUE THREAD

**Issue by rkorn86** [apereo/cas#2120]
I have included the following in my report:

- [X] CAS server version: 5.0.0
- [X] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc): Tomcat
- [X] Steps to duplicate the problem: enable saml idp and add a sp
- [X] Stacktraces and CAS logs where appropriate:
When the user tries to access the SP, he gets redirected the IDP Login via SAML mechanism. This could be either `/idp/profile/SAML2/Redirect/SSO` or `/idp/profile/SAML2/POST/SSO`. `SSOPostProfileHandlerController` handles this and will redirect the user to CAS Login page with appended Callback Service ID (for checking the service) and entityId (for displaying). Same thing happens when integrating shibboleth and using mdui, see here: https://apereo.github.io/cas/5.0.x/integration/Shibboleth.html
Problem for callback service/display service and SAML is here: https://github.com/apereo/cas/blob/v5.0.0/support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/AbstractSamlProfileHandlerController.java#L353. `final URLBuilder builder = new URLBuilder(this.callbackService.getId());` for example will just use the predefined regex of the saml callback service (which is added automatically when using saml-idp plugin). So the service URL is just the same regex. Afterwards the entityId is appended to that regex. That all wont be a problem at all, if the whole redirect URL wont be URLencoded in https://github.com/apereo/cas/blob/v5.0.0/support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/AbstractSamlProfileHandlerController.java#L302.
SamlMetadataUIParserAction cant handle the encoded url in https://github.com/apereo/cas/blob/a1ccfe90993a7fe93908716aa7f8cc3af8744ecd/support/cas-server-support-saml-mdui/src/main/java/org/apereo/cas/support/saml/web/flow/SamlMetadataUIParserAction.java#L84, because the the url here will be sth like `https://cas.example.org/login?service=https%3A%2F%2Fcas.example.org%2Fidp%2Fprofile%2FSAML2%2FPOST%2FSSO%2FCallback.%2B%3FentityId%3Dhttps%253A%252F%252Fsp.example.org%252Fshibboleth%26SAMLRequest%3DPD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c2FtbHA6QXV0aG5SZXF1ZXN0IHhtbG5zOnNhbWxwPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6cHJvdG9jb2wiIEFzc2VydGlvbkNvbnN1bWVyU2VydmljZVVSTD0iaHR0cHM6Ly9rb3JuaS5nZnotcG90c2RhbS5kZS9TaGliYm9sZXRoLnNzby9TQU1MMi9QT1NUIiBEZXN0aW5hdGlvbj0iaHR0cHM6Ly9pZHAtZGV2Lmdmei1wb3RzZGFtLmRlL2Nhcy9pZHAvcHJvZmlsZS9TQU1MMi9SZWRpcmVjdC9TU08iIElEPSJfMDc4NDAwYzRhMTAyYjc3NTljODExMmZjMjQ4Y2Y0NDEiIElzc3VlSW5zdGFudD0iMjAxNi0xMS0xNVQxMTo0NTo0MVoiIFByb3RvY29sQmluZGluZz0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmJpbmRpbmdzOkhUVFAtUE9TVCIgVmVyc2lvbj0iMi4wIj48c2FtbDpJc3N1ZXIgeG1sbnM6c2FtbD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiI%252BaHR0cHM6Ly9rb3JuaS5nZnotcG90c2RhbS5kZS9zaGliYm9sZXRoPC9zYW1sOklzc3Vlcj48c2FtbHA6TmFtZUlEUG9saWN5IEFsbG93Q3JlYXRlPSIxIi8%252BPC9zYW1scDpBdXRoblJlcXVlc3Q%252B`

The whole process is hard to describe, but I hope you get me.
PS: The same thing can be seen on oAuth services as well.

**Comment by dima767** [comment]
Yeah, this needs to be fixed. If you have a well unit tested fix/patch for this, do not hesitate to open up a pull request

**Comment by rkorn86** [comment]
Im unsure which side is wrong. Is it the building of the redirection url or just the extracting part later, which should be fixed?

**Comment by dima767** [comment]
Let's see what @mmoayyed has to say...

**Comment by mmoayyed** [comment]
All CAS component that need to deal with request parameters such as service or entityID MUST be prepared to handle handle encoded parameters and decode appropriately. If you find this to be false anywhere, consider that bug (which sounds like MDUI is actually prone to this issue).

**Comment by rkorn86** [comment]
The problem is, that the encoded URL to parse is already a request 
parameter (service).


Am 15. November 2016 5:29:53 nachm. schrieb Misagh Moayyed 
<notifications@github.com>:

**Comment by mmoayyed** [comment]
OK lets do a little digging and reproduce this. Stay tuned

**Comment by mmoayyed** [comment]
You did list that to reproduce this, SAML IdP and a SP must be added but it also sounds like you have MDUI enabled?

**Comment by rkorn86** [comment]
Mdui is not needed. It was just for comparison, how it should look like.


Am 15. November 2016 10:42:58 nachm. schrieb Misagh Moayyed 
<notifications@github.com>:

**Comment by mmoayyed** [comment]
OK so then let me ask, when you say `not displaying correct UI` what does that actually refer to? My understanding is that you are referring to the UI that is displayed on the login page which outlines logo, description and such for the registered service, right? We are basically showing info about the callback service rather than the actual which in your case happens to be entityID, or in the OAuth/OIDC case might be something else. Does that make sense?

**Comment by rkorn86** [comment]
Yes, Im referring to the UI that is displayed on the login page which outlines logo, description and such for the registered service.  
Correct, you are showing info about the callback service, rather than the actual one from the entityID. I recognized this behaviour for SAML and oAuth. For a better user expierience the original requested service should be displayed.  
I only picked the `saml` one, as i debugged the construction of the callback url and saw the wrong encoding/decoding of the service URL.

**Comment by mmoayyed** [comment]
Excellent, now we are getting somewhere. This is an easy problem to solve. Thanks!

**Comment by mmoayyed** [comment]
I have solved this issue for saml2 and snapshots should contain fixes. I'll continue to apply the same fix for oauth and oidc.

**Comment by mmoayyed** [comment]
This should be handled for all now.
