### ISSUE TITLE
CAS 5.1.0-SNAP MFA yubikey not trigerred

### ISSUE THREAD

**Issue by pmarasse** [apereo/cas#2127]
Environment :
  - CAS server version 5.1.0-SNAP
  - Apache Tomcat 8.5.8 on Debian Jessie 32 bits
  - Maven overlay : LDAP + Yubikey (with custom registry) + SAML (for SAMLv11 ST validation)

MFA yubikey is not triggered, and I noticed in the log 
`[org.apereo.cas.web.flow.resolver.impl.RegisteredServiceAuthenticationPolicyProviderResolver] - <Could not locate [mfa-yubikey] bean id in the application context as
an authentication provider.>`

Just upgrading from 5.0.0 to 5.1.0-SNAP :
  - [5.1.0-SNAP log](https://github.com/apereo/cas/files/597965/no-spnego-yubi5.1.0.txt)
  - [5.0.0 log](https://github.com/apereo/cas/files/597967/no-spnego-yubi5.0.0.txt) as a reference.

5.0.0 runs fine, and 5.1.0-SNAP bypass yubikey, and shows an ugly exception because of a wrong ldap password. On client side, I'm authenticated (ldap only of course).

**Comment by mmoayyed** [comment]
This should be fixed now.
