### ISSUE TITLE
MFA for SAML2 SP based on CAS Service Registry EntityID

### ISSUE THREAD

**Issue by kripalsingh** [apereo/cas#2128]
Would like MFA triggered for a specific SAML2 SP inside the CAS service registry.  would like to do it using entityID in SAML2 SP service registry JSON.
https://groups.google.com/a/apereo.org/forum/?utm_medium=email&utm_source=footer#!msg/cas-user/j8zJ_t2-u9s/KcLlJSM5BwAJ
- [] CAS server version 5.0
- [] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc) . tomcat 8

**Comment by mmoayyed** [comment]
This is now handled in 5.1 SNAPSHOTs

**Comment by kripalsingh** [comment]
thanks!
