### ISSUE TITLE
Proposal DefaultServicesManagerImpl improvement

### ISSUE THREAD

**Issue by DavidRG13** [apereo/cas#2133]
convertToTreeSet method is called every time findServiceBy method is called (not by id).

Then a stream is created from this TreeSet and looped over finding a service that matches.

Is this intermediate TreeSet useful?

**Comment by mmoayyed** [comment]
You probably should take this to the dev list, but I'll take a first jab: The treeset I think provides ordering for services that are packaged by the evaluation order setting. So I believe it is important to keep it around. Of course, if you can find a more efficient way of handling the collection and preserving the order, by all means.

**Comment by mmoayyed** [comment]
Of course, be careful with breaking API changes. If backward compatibility cannot be preserved specially for modules/components in the "api" category, the change likely is going to be met with some hesitation. So for all improvements really, attempt to either isolate changes down to the impl level or take advantage of `default` and such to help with BC issues.

**Comment by DavidRG13** [comment]
I think no one (outside this class) is using the public method that return the Tree, so I couldn't see any API compatibility problems.

Anyway, as a first approach we can create the Tree at the same same level that the Map, and update the Tree on every Map update

**Comment by mmoayyed** [comment]
Cool.
