### ISSUE TITLE
Revise codebase checkstyle rules

### ISSUE THREAD

**Issue by dima767** [apereo/cas#2134]
This is a generic issue to track a task and discussion of revising, relaxing, refactoring codebase checkstyle rules to be more flexible, in-line with modern programming style and Java language features, and be an easier barrier to entry for contributors.

**Comment by DavidRG13** [comment]
I think this is the best for asking, why are you using Equals and HashCode builders? Note the extended recommendation of not creating objects on that methods

**Comment by mmoayyed** [comment]
I don't think this is enforced by checkstyle rules, is it? If not we might be able to revisit.

I don't care either way to be honest; what I care about is 2 things:

1. Consistency, everywhere
2. Rules that can be enforced automatically without having to review everything manually. As an example, if we are saying that you should use approach A for doing functionality B across the codebase, that should happen everywhere...and if I decide to suddenly use approach A2, the rules should catch that and the build should probably fail. 

So if you find anything that you can pass through those 2 filters, by all means.

**Comment by mmoayyed** [comment]
I did update my comment above, but I am not sure notifications are sent; mostly the gist is that we of course have to be practical and there may be cases where exceptions need to be made to violate rules conditionally. That's perfectly fine. We just need to automate those too. Less work all around for long-term longevity.

**Comment by mmoayyed** [comment]
Oh on other thing to help out with this stuff: IDEA does have a very good checkstyle plugin that can be configured with CAS rules and suppression filters. Letting the plugin scan changed files only prior to a push is very very helpful.

**Comment by DavidRG13** [comment]
As far as I can see the only rule suggesting to use Guava instead of Java is:
`<module name="RegexpSingleline">
        <metadata name="net.sf.eclipsecs.core.comment" value="Arrays.asList() method call"/>
        <property name="severity" value="error"/>
        <property name="format" value="Arrays\.asList\(.+"/>
        <property name="message" value="Use Lists.newArrayList() instead."/>
    </module>`

I would suggest to move to Java collections, as they have been improved in Java 8 and 9

As I said, I would be glad to contribute with this change 

Apart from this I can't see any limiting checkstyle rule

**Comment by mmoayyed** [comment]
Please do. Thanks!

**Comment by DavidRG13** [comment]
Are you OK removing that rule? as the first commit

**Comment by mmoayyed** [comment]
Yes please. I'd suggest you ultimately replace it with a rule that also enforces your suggestion.

Little background: you do also need to make sure replacements are serialization friendly.

**Comment by DavidRG13** [comment]
Hey, 
as you can see I created a PR for Java collecions, could you please point any other library that can be replaced by Java?
- JodaTime is required by Saml, could we limit its usage with a rule?

**Comment by mmoayyed** [comment]
You can't remove them. You may be able to limit usage. I am not sure you can limit usage without causing more pain to be honest.

**Comment by mmoayyed** [comment]
This seems done with a series of PRs posted to clean up the codebase.
