### ISSUE TITLE
Consider turning on the Security Filter by default

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#2135]
Consider adjusting default CAS settings to turn on the following security options by default. 

Content Security Policy		-	Content Security Policy (CSP) header not implemented	
Cross-origin Resource Sharing			Content is not visible via cross-origin resource sharing (CORS) files or headers	
HTTP Strict Transport Security		-	HTTP Strict Transport Security (HSTS) header not implemented	
Referrer Policy		-	Referrer-Policy header not implemented (optional)	
X-Content-Type-Options		-	X-Content-Type-Options header not implemented	
X-Frame-Options		-	X-Frame-Options (XFO) header not implemented	
X-XSS-Protection		- X-XSS-Protection header not implemented

**Comment by pmarasse** [comment]
IMHO CORS implementation would be a great feature. Actually we have issues when CAS enabled applications are accessed via XHR/Ajax requests : imagine when the application wants to re-auth the user... XHR request tries CORS pre-flight, and fails, silently. The user has no choice but reloading the entire page/application.

**Comment by mmoayyed** [comment]
This is now done, including CORS.
