### ISSUE TITLE
CAS integration with JIRA - redirection issue

### ISSUE THREAD

**Issue by nchantrennne** [apereo/cas#2140]
Hello, 

we have an issue with CAS integration with JIRA. CAS server version is 3.4.11. CAS Client integration is 3.4.1.

Everything works as expected except for one thing:

When we try to access this kind of URL without being logged in:

https://ourjiraserver/browse/ST-110

it is transformed as:

https://ourjiraserver/browse/ST-10?ticket=ST-12667-kNfKk2e2ckrcpOrjhMFK-cas

This address throws a 404 error.

We believe that we are facing https://issues.jasig.org/browse/CAS-1338, but as the tickets were migrated to GitHub we do not see any fix for this issue.

Thanks and Regards,
Nathan

**Comment by mmoayyed** [comment]
This solution is documented here by the way https://apereo.github.io/cas/5.0.x/installation/User-Interface-Customization-CSSJS.html#preserving-anchor-fragments 
You may find it useful to apply to 3.4.x as well. 
If you run into issues, please report back.
