### ISSUE TITLE
CAS Management webapp authorization controls

### ISSUE THREAD

**Issue by rfrovarp** [apereo/cas#2153]
With CAS 5.0.0 and the management webapp, the authorization controls split the cas.mgmt.adminRoles provided value by a comma, using the StringUtils helper from Spring. Despite the fact that the Javadoc for the method makes reference to CSV, it doesn't honor quoted strings (like a CSV library would), and instead just does a simple split based off of the provided character, and in the case of this application it is just a comma. 

This makes it impossible to use AD groups as those are full LDAP DNs, with lots of commas. The part from that will never match the whole being compared to.

Perhaps the simplest solution would be to add another configuration value to specify the splitter value. Anyone using AD groups can override the default to a tilde or pipe, and everyone else can stick with the default of comma.

**Comment by mmoayyed** [comment]
I appreciate the use case but I don't think exposing options for delimiters and such is the better solution. What we likely should do is eliminate parsing altogether and get out of that game. Less is more.  

So rather than having:

```
cas.adminPagesSecurity.adminRoles=ROLE_ADMIN|ROLE,WHATEVER
cas.adminPagesSecurity.adminRolesDelimiter=|
```

We should do:

```
cas.adminPagesSecurity.adminRoles[0]=ROLE_ADMIN
cas.adminPagesSecurity.adminRoles[0]=ROLE_ADMIN,WHATEVER|ANYTHING GOES
```

Such that you don't have to worry about splitting.

**Comment by mmoayyed** [comment]
The advantage of the 2nd option is that it's something offered natively by Spring Boot, it is the recommended approach and requires less of a learning curve from the deployer given things simply just and should work.

**Comment by mmoayyed** [comment]
This should now be handled in 5.1 snapshots. Docs updated
