### ISSUE TITLE
Infinispan can't load config via path

### ISSUE THREAD

**Issue by rfrovarp** [apereo/cas#2155]
In CAS 5.0.0 I'm using the Infinispan ticket registry. It is unable to load its configuration file from the file system path.

cas/support/cas-server-support-infinispan-ticket-registry/src/main/java/org/apereo/cas/ticket/registry/config/

final Resource loc = casProperties.getTicket().getRegistry().getInfinispan().getConfigLocation();
return new DefaultCacheManager(loc.getFilename());

loc.getFilename() only returns the name of the file, not the path. Constructor for DefaultCacheManager will treat it as something on the classpath, but if it can't find it, the value will be treated as an absolute path.

**Comment by mmoayyed** [comment]
Thanks for the report. Definitely an issue. Sounds like we need to make sure the full path is loaded whether it's a classpath resource or an external file. 

Is this something you intend to fix and patch up, or is this something we should take a look?

**Comment by rfrovarp** [comment]
I can take a look at it and generate a patch. It might be a week or so before I have time to dedicate to it, but I can get it done.

**Comment by mmoayyed** [comment]
Excellent. Look forward to it.

Target your destination branch to be master, and we can backport it to 5.0.x (Or you can issue two patches for either branch if you are ambitious)

**Comment by mmoayyed** [comment]
I ended up applying the patch to use input stream instead. Feel free to try and report back with the current snapshots.
