### ISSUE TITLE
when createTicketGrantingTicket, the log says that WHO: audit:unknown

### ISSUE THREAD

**Issue by lhcalibur** [apereo/cas#2159]
I have included the following in my report:

- [4.2.7] CAS server version
- [Jetty] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)

In CentralAuthenticationServiceImpl such as method"public TicketGrantingTicket createTicketGrantingTicket(final AuthenticationContext context) throws AuthenticationException, AbstractTicketException", the auditing resolver TicketOrCredentialPrincipalResolver's method resolveArgument can not resolve AuthenticationContext, so the audit log says that WHO is audit:unknown:

```
=============================================================
WHO: audit:unknown
WHAT: TGT-**********************************************xGEjNqYzor-cas01.example.org
ACTION: TICKET_GRANTING_TICKET_CREATED
APPLICATION: CAS
WHEN: Mon Dec 05 10:44:27 CST 2016
CLIENT IP ADDRESS: 127.0.0.1
SERVER IP ADDRESS: 127.0.0.1
=============================================================
```

**Comment by mmoayyed** [comment]
We verified that this is fixed in 5. Might be something for you to try, or shall we try and backport this behavior when we/you get around to it?

**Comment by lhcalibur** [comment]
Thank you very much. And I will try to use release 5~

**Comment by mmoayyed** [comment]
Excellent! I'll go ahead and close this issue for now.
