### ISSUE TITLE
Changes to json file in JSONServiceRegistry are not dynamically loaded into CAS Server

### ISSUE THREAD

**Issue by tsschmidt** [apereo/cas#2166]
Working with 5.1.0-SNAPSHOT builds from master, I noticed that changes made in either the Management App or directly to a file in the JSONServiceRegistry directory location, do not get loaded into CAS without a server restart.  Log shows that the file is reloaded immediately after editing, but changes are not reflected when logging into CAS for the changed service.

**Comment by mmoayyed** [comment]
Could you share logs please? and what sort of changes are we talking about? things like changing name, description or something more significant like adding mfa? I am basically trying to figure out if this is a basic resource loading issue, or if there is an underlying component that is affected by a specific change.

**Comment by tsschmidt** [comment]
Logs I mentioned were just the normal "Loaded services" message after 
the file has been changed.  I first noticed it with altering attribute 
release policies.  I also tried just changing the enabled flag in access 
strategy and it was also ignored until a full restart.

**Comment by tsschmidt** [comment]
Looks like changes committed on 11/20 for issue #2136 are what caused this error to appear.  The change was to use a ConcurrentSkipList to store the orderedServices.  The set works by using the compareTo method of the Object being added to determine if the object is absent from the set and only adds it if it is not found.  Here is the compareTo for AbstractRegisteredService

  @Override
    public int compareTo(final RegisteredService other) {
        return new CompareToBuilder()
                  .append(this.getEvaluationOrder(), other.getEvaluationOrder())
                  .append(this.getName().toLowerCase(), other.getName().toLowerCase())
                  .append(this.getServiceId(), other.getServiceId())
                  .append(this.getId(), other.getId())
                  .toComparison();
    }

So if any of these fields are changed then it would be inserted into the the set.  Changes made all fields, but the ones in the compare will cause the updated service to not be inserted into the new list.

**Comment by mmoayyed** [comment]
Your analysis is perfect correct. @DavidRG13 ideas on how to fix this issue?

**Comment by DavidRG13** [comment]
Ohhh I see.

Could you please have a look into https://github.com/William-Hill-Online/cas/tree/CAS-2166? I have created a couple of test to reproduce this but I'm not able to, what am I missing?

**Comment by tsschmidt** [comment]
In your test the service  id is not the same as the one that is loaded in
the @Before so it is added as a new service and not replacing an existing
service.  You need a test that has the same fields as the pre-loaded test
in the setup and then change some field like description that is not coded
in the compareTo() method in AbstractRegisteredService.

Travis

**Comment by DavidRG13** [comment]
Cool!! Thx

I managed to make the test fail, and the issue is fixed (I'll create a PR)

FYI, the solution applied was to recreate the Set, instead of changing the compareTo method. Performance wise if worse than before, but better than the first version, so we are fine :)
I think it's better to maintain an ordered copy of the services as they are queried much more than updated (at least that is our case)
