### ISSUE TITLE
Clean "uses unchecked or unsafe operations." warnings

### ISSUE THREAD

**Issue by DavidRG13** [apereo/cas#2168]
There are lot of messages like ```Note: /home/travis/build/apereo/cas/support/cas-server-support-gauth/src/main/java/org/apereo/cas/config/GoogleAuthenticatorConfiguration.java uses unchecked or unsafe operations.``` in the build logs.

Would you mind if I try to clean the most I can?

**Comment by mmoayyed** [comment]
Of course not. Please do!!

**Comment by mmoayyed** [comment]
@DavidRG13 is there still work to be done in this area? Is it safe to get this closed?

**Comment by DavidRG13** [comment]
Hi, 

I think we can close it and revisit when we can deprecate the usage of some libs
