### ISSUE TITLE
Issue with characher encode for default password encoder in CAS 5.0.0

### ISSUE THREAD

**Issue by mhgs** [apereo/cas#2169]
For JDBC / database authentication I've configured a character encode (ISO_8859_1) for the passwords. The logfiles show that this character encoding used, however debugging, shows that the default password decoder always uses the UTF_8 encoding.

Line in the default password encoder:
`return new String(DigestUtils.getDigest(this.encodingAlgorithm).digest(password.toString().getBytes(StandardCharsets.UTF_8)), StandardCharsets.UTF_8);`

Configuration:
`cas.authn.jdbc.query[0].passwordEncoder.characterEncoding=ISO_8859_1`

In my setup this always results in a authentication failed message because the passwords could not be matched (are not equal)

Note: in previous versions of CAS (4.x) the password compared in the database was a hex value of, in my case, the SHA-256 encoded password. I did not find a way to configure this in CAS 5.0.x. If this is possible, I would like to know how because then the above issue is not relevant.

**Comment by mmoayyed** [comment]
Have you tried running this with 5.1 SNAPSHOT?

**Comment by mhgs** [comment]
No, I am using the maven war overlay with 5.0.0. I tried moving to 5.1.0 but I noticed this version is not available yet?

**Comment by mmoayyed** [comment]
5.1.0-SNAPSHOT.

**Comment by mmoayyed** [comment]
Specifically, you'd be receiving patches from here for CAS modules:
https://oss.sonatype.org/content/repositories/snapshots/org/apereo/cas/

Trying snapshots is the preferred way to get an early build going and experiment with bug fixes, etc.

**Comment by mhgs** [comment]
Ok, I will try this later today. Thanks for the quick response.

**Comment by mhgs** [comment]
The issue is indeed resolved using the 5.1.0 snapshot. Thanks for the feedback
