### ISSUE TITLE
Clean deprecated methods

### ISSUE THREAD

**Issue by DavidRG13** [apereo/cas#2170]
As you hay have noticed, ```Throwables.propagate``` is deprecated.
The documentation said:

```
Use {@code throw e} or {@code throw new RuntimeException(e)} directly, or use a
   *     combination of {@link #throwIfUnchecked} and {@code throw new RuntimeException(e)}. This
   *     method is scheduled to be removed in July 2018.```
```

Do you have any suggestion on how to replace it? Maybe we can just inline it

**Comment by mmoayyed** [comment]
No particular suggestions just yet; it's way too early to be making that kind of change just yet. By 2018, you'll have come up with 2-3 better options possibly :) So I am not sure it's worth your time just yet, but if you prefer inlining, that's fine too. Just make sure the changeset, if you end up making them, are consistent everywhere and possibly the new "style" is accounted for in the style guidelines, checkstyle and such. 

Thanks!

**Comment by DavidRG13** [comment]
Ok, so I'll submit a PR for the rest of deprecated

Cheers!
