### ISSUE TITLE
MFA Gauth JPA not using my (custom) configuration

### ISSUE THREAD

**Issue by mhgs** [apereo/cas#2173]
I've configured CAS 5.1.0 as a overlay project and in my bootstrap.properties I've configured Google Authenticator as a MFA method. This works fine, but when I want to configure the JPA settings for the mfa.gauth it seems like these settings are not respected. instead it looks like some default settings are used.

**My configuration:**

`
cas.authn.mfa.gauth.jpa.healthQuery=SELECT 1 FROM connection_test
cas.authn.mfa.gauth.jpa.url=jdbc:mysql://127.0.0.1/DV_SSO
cas.authn.mfa.gauth.jpa.dialect=org.hibernate.dialect.MySQLDialect
cas.authn.mfa.gauth.jpa.user=xxxxxx
cas.authn.mfa.gauth.jpa.password=xxxxxx
cas.authn.mfa.gauth.jpa.ddlAuto=update
`

However on startup I see the following logs suggesting a ddlAuto setting create or create-drop is set.

`
Hibernate: alter table scratch_codes drop constraint FK9uwqjfu3f5rfbufio8d8j45ha
Hibernate: drop table GoogleAuthenticatorRegistrationRecord if exists
Hibernate: drop table scratch_codes if exists
Hibernate: drop sequence hibernate_sequence if exists
Hibernate: create sequence hibernate_sequence start with 1 increment by 1
Hibernate: create table GoogleAuthenticatorRegistrationRecord (id bigint not null, secretKey varchar(2147483647) not null, username varchar(2147483647) not null, validationCode integer not null, primary key (id))
Hibernate: create table scratch_codes (username bigint not null, scratchCodes integer not null)
Hibernate: alter table scratch_codes add constraint FK9uwqjfu3f5rfbufio8d8j45ha foreign key (username) references GoogleAuthenticatorRegistrationRecord
`

On shutdown the following logs are displayed, suggesting the ddlAuto create-drop is set.

`
Hibernate: alter table scratch_codes drop constraint FK9uwqjfu3f5rfbufio8d8j45ha
Hibernate: drop table GoogleAuthenticatorRegistrationRecord if exists
Hibernate: drop table scratch_codes if exists
Hibernate: drop sequence hibernate_sequence if exists
`

Of course I've tried other settings for dllAuto, all with the same results in the logs. Also I did not see the table structure in my configured DB.

Is there something I'm missing or is this unintended behaviour of CAS

**Comment by mmoayyed** [comment]
Try:

```
# cas.authn.mfa.gauth.jpa.database.xyz=...
```

Updated the docs. Thanks for the report!
