### ISSUE TITLE
support for custom password encoder in 5.0

### ISSUE THREAD

**Issue by stenflo** [apereo/cas#2174]
In CAS 4.2.1 it was possible to have a custom password encoder class to change the behavior of DefaultPasswordEncoder. For example it could be recognized in `deployerConfigContext.xml` with spring bean configuration:

```
<bean id="passwordEncoder" class="my.own.custom.PasswordEncoder" />
```

After migrating to 5.0.0 there seems to be no equivalent configuration as the classes corresponding to the choices `NONE|DEFAULT|STANDARD|BCRYPT` are not configurable via spring beans anymore.

WANT: Some way to keep using "my.own.custom.PasswordEncoder" with CAS 5.0.0 and having it assigned to different authentication handlers. I've updated my custom encoder to implement the spring PasswordEncoder interface instead of the old jasig one, but there seems to be no clean way to inject it via configuration anymore. - Surely you are discouraging this but there must still be good use cases for it.

related issue: [https://github.com/apereo/cas/issues/1913](url)

**Comment by mmoayyed** [comment]
PasswordEncoders are directly applied to authN handlers. So you can create your own handler, or extend/locate and existing one and set its encoder directly in your own configuration class. As you sort of alluded to, I'd suggest you evaluate your requirements and try to come up with a solution that can be contributed back to CAS so you just end up configuring it based on a new type, or a new variation of an existing type.
