### ISSUE TITLE
Use constructor-injection where possible for classes

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#2184]
Avoid doing things like:

```java
    public Action logoutAction() {
        final LogoutAction a = new LogoutAction();
        a.setWebApplicationServiceFactory(webApplicationServiceFactory);
        a.setFollowServiceRedirects(casProperties.getLogout().isFollowServiceRedirects());
        a.setServicesManager(this.servicesManager);
        return a;
    }
```

Remove setters and switch to constructor injection:

```java
    public Action logoutAction() {
        return new LogoutAction(webApplicationServiceFactory, ...);
    }
```

Possibly, also add checkstyle rules to enforce this behavior. 

@DavidRG13 wanna take this one? [If so, I recommend you introduce changes in batches via multiple pull requests]

**Comment by dima767** [comment]
+1 on atomic, more laser-focused change sets

**Comment by DavidRG13** [comment]
Of course I can!! Finally having constructor based injection make me happy :)

Will do tiny PR ;)

**Comment by mmoayyed** [comment]
Excellent!

**Comment by mmoayyed** [comment]
I imagine this is going to take us a LONG time. Wanted to clarify that the issue at hand here isnt just about Configuration classes, but all components where it makes sense.

**Comment by DavidRG13** [comment]
Hi everyone, 
Could you please have a quick look and see if there is anything missing.

Of course still you can see setter methods, but removing them it's a nightmare. For me, extension is good when a complete hierarchy exists (Car -> Vehicle, car ALWAYS has the same attributes than vehicle), this is not happening in the code, maybe a person with more experience in the domain could refactor it.

**Comment by mmoayyed** [comment]
Hi David, thanks very much for your work on this issue thus far. I think it's safe to say that further work on this changeset needs to be continuous and done sort of on demand as we all run into areas that need improvement. You're more than welcome to continue posting pull requests to fix areas you run into. It's evident that this changeset is going to take a while. We can keep the issue open and link PRs to it as you and others fix things or we can get it closed if you feel the work done so far is sufficient. It's your call. 

I've also taken a pass and fixed a few of the ctor injections related to MFA work. There's still plenty to get fixed, and we'll eventually get there.

**Comment by mmoayyed** [comment]
Closing on good-enough merits for now. Can revisit later.
