### ISSUE TITLE
Swap out @RequestMapping instances with the equivalent Spring annotations

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#2189]
Go through all RequestMapping annotations and make sure the appropriate Get/Post equivalent is used. Keep it all consistent and add relevant checkstyle rules. Related to #2161 

@DavidRG13 another one for you perhaps.

**Comment by DavidRG13** [comment]
Sure! 
I didn't change that because I did not know which http method we should use. Any ideas? Get by default?

**Comment by mmoayyed** [comment]
Yup. Get by default. POSTs should always be specified explicitly, and I think you got that covered already! thanks.

**Comment by DavidRG13** [comment]
As I said in the PR, there are classes annotated with ```@RequestMapping``` , what should we do with them? 
We can merge the PR, and do another one if needed

**Comment by mmoayyed** [comment]
They are probably on as they are. We could either relax checkstyle to make an exception for those or did deeper and turn them into method-level annotations. I am fine with the exception in the rules but it's your call.
