### ISSUE TITLE
CAS 5.0.0: EhCacheTicketRegistry uses timeToKillInSeconds instead of maxTimeToLiveInSeconds

### ISSUE THREAD

**Issue by yauheni-sidarenka** [apereo/cas#2198]
It seems to me that there is a problem with tickets expiration in `org.apereo.cas.ticket.registry.EhCacheTicketRegistry`. I configured CAS to expire ticket granting ticket after 10 seconds of inactivity or expire it after 60 seconds regardless of activity. Then I logged in successfully and tried to open login page several times after that (to emulate activity) but suddenly CAS showed me login page again in about 10 seconds after successful login, I mean CAS used value of `timeToKillInSeconds` property as value for `maxTimeToLiveInSeconds` property.

I have included the following in my report:

- CAS server version: 5.0.0, Gradle overlay
- Container/environment type/version: external Tomcat 8.0.30, Oracle JDK 8u60, Windows 7 Pro OS
- Steps to duplicate the problem:
1. Set TGT expiration properties as following: 
```
cas.ticket.tgt.timeToKillInSeconds=10
cas.ticket.tgt.maxTimeToLiveInSeconds=60
```
2. Add EhCache ticket registry to the overlay and build the project
3. Put resulted `cas.war` file into `CATALINA_HOME/webapps` directory and start the container
4. Go to https://<cas_host>:<cas_port>/cas/login -> login page appears
5. Enter default credentials casuser/Mellon -> CAS' generic success view appears
6. Wait 5 seconds and go again to https://<cas_host>:<cas_port>/cas/login -> CAS' generic success view appears
7. Wait 6 seconds (5+6=11>timeToKillInSeconds) and go again to https://<cas_host>:<cas_port>/cas/login -> unexpectedly login page appears instead of CAS' generic success view 
- cas.log says:
```
2016-12-13 15:38:03,113 INFO [org.apereo.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN
=============================================================
WHO: casuser
WHAT: TGT-**********************************************abAhZwO5NB-key-man1
ACTION: TICKET_GRANTING_TICKET_CREATED
APPLICATION: CAS
WHEN: Tue Dec 13 15:38:03 MSK 2016
CLIENT IP ADDRESS: 192.168.56.1
SERVER IP ADDRESS: 192.168.56.1
=============================================================

>
2016-12-13 15:38:13,268 INFO [org.apereo.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN
=============================================================
WHO: audit:unknown
WHAT: TGT-**********************************************abAhZwO5NB-key-man1
ACTION: TICKET_GRANTING_TICKET_DESTROYED
APPLICATION: CAS
WHEN: Tue Dec 13 15:38:13 MSK 2016
CLIENT IP ADDRESS: 192.168.56.1
SERVER IP ADDRESS: 192.168.56.1
=============================================================

>
```

**Comment by mmoayyed** [comment]
https://github.com/cas-projects/cas-issues/pull/29

**Comment by mmoayyed** [comment]
This is indeed a bug, yes. Thanks for the report.

**Comment by yauheni-sidarenka** [comment]
@mmoayyed, you are welcome! By the way, I am preparing another issue with locale change interceptor.

**Comment by yauheni-sidarenka** [comment]
Well... Actually, the issue still exists. But this time it can be another issue. I mean it looks like the issue is deeper and wider than I expected it to be. Let me explain a little bit.

I have just tried with the latest 5.0.2-SNAPSHOT using steps mentioned in my first post. Fail, TGT expires accurately in 10 seconds, log says.

Ok, I doubled TTI setting it to 20 seconds. Fail again, TGT expires accurately in 20 seconds, log says.

Let it be. I excluded EhCache ticket registry dependency and removed `ehcache-replicated.xml` from overlay project. That means I tried to reproduce with default ticket registry implementation. And the issue is still reproducible (with both TTI=10 sec and TTI=20 sec)!

Then I changed workflow a bit on steps 4, 6 and 7. I used `service` parameter with URL to a non-existent service `https://my.service`, so I had 
```
https://<cas_host>:<cas_port>/cas/login?service=https://my.service
```
instead of 
```
https://<cas_host>:<cas_port>/cas/login
```

This time everything worked as expected for both default and EhCache ticket registries. Although in very rare cases EhCache was not precise enough in expiration (see logs attached for details, but sorry, I was too lazy to configure additivity properly in default logger configuration XML file)


[cas.log_TTL=60_TTI=20_attempt_1.txt](https://github.com/apereo/cas/files/661441/cas.log_TTL.60_TTI.20_attempt_1.txt)
[cas.log_TTL=60_TTI=20_attempt_3.txt](https://github.com/apereo/cas/files/661442/cas.log_TTL.60_TTI.20_attempt_3.txt)
[cas.log_TTL=60_TTI=20_attempt_4.txt](https://github.com/apereo/cas/files/661440/cas.log_TTL.60_TTI.20_attempt_4.txt)

Also I did one more test. I tried to log in in my service which accepts default user `casuser` and after successful login I opened another tab in browser and went to `https://<cas_host>:<cas_port>/cas/login` - TGT expired in 3 seconds after successful creation, log says. I did it two times (see log attached), configuration: EhCache ticket registry, TTL=28800 seconds, TTI=28800 seconds, service pattern for default HTTPS and IMAPS service=`^(https?|imaps)(:|%3a)(%2f|/){2}.*`.

[cas.log_TTL=28800_TTI=28800_real_service_then_login.txt](https://github.com/apereo/cas/files/661463/cas.log_TTL.28800_TTI.28800_real_service_then_login.txt)

The last but not least thing. There are two versions of `spring-boot-*`, `spring-data-*` and `spring-integration-*` libraries in `/WEB-INF/lib` directory.

Regards, Yauheni.

**Comment by mmoayyed** [comment]
> The last but not least thing. There are two versions of spring-boot-*, spring-data-* and spring-integration-* libraries in /WEB-INF/lib directory.

This is a separate issue. For this, you'll need to submit an overlay and create a separate issue so it can individually tracked. Thanks. 

> Fail again, TGT expires accurately in 20 seconds, log says.

You'll need to attach DEBUG logs.

**Comment by yauheni-sidarenka** [comment]
> This is a separate issue. For this, you'll need to submit an overlay and create a separate issue so it can individually tracked. Thanks.

I have just created https://github.com/apereo/cas/issues/2241

**Comment by yauheni-sidarenka** [comment]
> You'll need to attach DEBUG logs.

@mmoayyed, could you specify, please, which loggers I should switch to debug level? All org.apereo.* loggers or only some specific of them? Shall I touch Spring's loggers and other 3rd-party ones?

**Comment by mmoayyed** [comment]
In this case you need org.apereo.cas and the packages related to ehcache at least so we can observe the eviction policy activity in the logs. Attachs logs from startup so we can see how CAS creates expiration policies.

**Comment by mmoayyed** [comment]
Do we have updates on this? Can this be closed?

**Comment by yauheni-sidarenka** [comment]
I do apologize for delay.
So I used this configuration for loggers:
[log4j2_eh_debug.zip](https://github.com/apereo/cas/files/668798/log4j2_eh_debug.zip)
Log files:
- scenario from first post (login -> wait 5 sec -> login -> wait 6 sec -> login)
[cas.log_TTL=60_TTI=10_debug.txt](https://github.com/apereo/cas/files/668802/cas.log_TTL.60_TTI.10_debug.txt)
- scenario from additional test with real service (real service login -> login)
[cas.log_TTL=28800_TTI=28800_real_service_then_login_debug.txt](https://github.com/apereo/cas/files/668807/cas.log_TTL.28800_TTI.28800_real_service_then_login_debug.txt)

**Comment by mmoayyed** [comment]
You need to "Attach logs from startup so we can see how CAS creates expiration policies."

**Comment by mmoayyed** [comment]
I'll run through this one more time. Hang on.

**Comment by mmoayyed** [comment]
So I set up:

```
cas.ticket.tgt.timeToKillInSeconds=10
cas.ticket.tgt.maxTimeToLiveInSeconds=60
```

And ran through this. What I observe is that when I log in after 10 seconds of inactivity the TGT is removed from the cache and expired. However if I actually start USING that TGT to issue service tickets and so it is only then removed after a minute. It seems like your difficulty has more to do with the concept of "ticket usage", etc. If you just sit on the login page idly, or if you just keep refreshing the page that does not constitute TGT usage.

**Comment by yauheni-sidarenka** [comment]
> You need to "Attach logs from startup so we can see how CAS creates expiration policies."

Oh, I am so sorry for that. I did test several times and chose improper file to attach. Although [this one](https://github.com/apereo/cas/files/668807/cas.log_TTL.28800_TTI.28800_real_service_then_login_debug.txt) has the necessary information from startup.

> If you just sit on the login page idly, or if you just keep refreshing the page that does not constitute TGT usage.

Thanks a lot. I've got it. But what about scenario with a real service and following login page? There were both TTI=28800 and TTL=28800, but TGT was expired in 8 seconds.

**Comment by mmoayyed** [comment]
Thanks very much. Not a problem about logs; it's always the VERY FIRST thing I ask for :)

> But what about scenario with a real service and following login page? There were both TTI=28800 and TTL=28800, but TGT was expired in 8 seconds.

I shall look into it.

**Comment by mmoayyed** [comment]
> what about scenario with a real service and following login page? There were both TTI=28800 and TTL=28800, but TGT was expired in 8 seconds.

Also unable to duplicate this.

**Comment by yauheni-sidarenka** [comment]
Hi!

> Also unable to duplicate this.

I have resolved this issue using property
```
cas.ticket.registry.ehcache.persistence=LOCALTEMPSWAP
```
instead of default one
```
cas.ticket.registry.ehcache.persistence=NONE
```
Thanks.
