### ISSUE TITLE
Login loop with renew=true

### ISSUE THREAD

**Issue by bifyu** [apereo/cas#2209]
Users experience a login loop when renew=true is used with expired TGT.
Note: _**renew=true** is required to trigger this behavior._

- CAS server version
  - 5.0.0 (AuthN using LDAP, JSON service registry)
- Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
  - Tomcat 8.0.39, Java 1.8.0_112
- Steps to duplicate the problem
1. set `cas.ticket.tgt.timeToKillInSeconds=300` (to facilitate testing)
2. define registered service for testing purposes (JSON)
`{
  "name" : "Login_Loop_Test_No_MFA",
  "serviceId" : "^https://example\\.edu/loop",
  "description" : "Stub registration to test login loop problem - no MFA",
  "id" : 20161114102217,
  "evaluationOrder" : 99999999,
  "@class" : "org.apereo.cas.services.RegexRegisteredService",
}`
3. use a new private/incognito browser window for test service URL (the renew=true parameter is required)
`https://cas.example.edu/cas/login?renew=true&service=https%3A%2F%2Fexample%2Eedu%2Floop`
4. authenticate
5. wait for interval longer than cas.ticket.tgt.timeToKillInSeconds (e.g 5+ min)
6. reload test service URL
`https://cas.example.edu/cas/login?renew=true&service=https%3A%2F%2Fexample%2Eedu%2Floop`

The authentication should fail, and the user is returned to the login page with the username field pre-filled. Despite entering the correct username/password, the logins fail, and the user is returned to the login page each time as described.

The debug logs show that when the user sees the login loop, CAS tries to issue a service ticket (ST), but fails because it is trying to use an invalid/expired ticket granting ticket (TGT)

Each time through the loop, the CAS logs show that it's still trying to use the same expired TGT. We hypothesize the expired TGT may be stored in a hidden form input in the cas login page:

`<input type="hidden" name="lt" value="${loginTicket}" /><input type="hidden" name="execution" value="(Base64 encoded data)"`

Each time through the loop, the value of the hidden ${loginTicket} input changes.

Note: we also see this behavior when MFA-Duo is enabled for the service, although the debug logs then additionally show that the TGC is cleared. e.g.:

2016-12-14 09:25:56,457 DEBUG [org.apereo.cas.CentralAuthenticationServiceImpl] - <Ticket [TGT-**********************************************WKGulczcJU-cas] has expired and is now deleted from the ticket registry.>
2016-12-14 09:25:56,458 DEBUG [org.apereo.cas.CentralAuthenticationServiceImpl] - <Removing ticket [TGT-**********************************************WKGulczcJU-cas] from registry...>
2016-12-14 09:25:56,459 DEBUG [org.apereo.cas.web.support.TGCCookieRetrievingCookieGenerator] - <Removed cookie with name [TGC]>

Looping ceases once the browser gets a TGC.

- CAS debug logs
  - [CAS5-login-loop.log](https://gist.github.com/bifyu/126a90ada2b0dd62fa25d689a7669e1e#file-cas5-login-loop-log)

**Comment by mmoayyed** [comment]
> Each time through the loop, the value of the hidden ${loginTicket} input changes.

I don't know if this is the root cause of this issue as I have yet to run through this, but please note that there is no such thing as a loginTicket in CAS 5. If this shows up on your page, it must be specific to your UI changes.

**Comment by bifyu** [comment]
Hmm, I wasn't involved with the UI customizations other than to deploy them, so unfortunately I can't speak to the source of the loginTicket content. I can confirm though that if either the value for that hidden field is not specified (e.g. ```<input type="hidden" name="lt" />```) or if that hidden input is completely commented out, that the login loop behavior still occurs. Would it be helpful to include the overlay for the UI customizations?

**Comment by mmoayyed** [comment]
Yes a full overlay is always helpful as a PR to the issues project. 

I'd also recommend you simply try with 5.0.2-SNAPSHOT and see what happens. If there is an issue for which a fix should be added, it would be on top of that version anyway so you might as well be on it to begin with, before further diagnostics can resume.

**Comment by bifyu** [comment]
5.0.2-SNAPSHOT seems to have solved the problem

**Comment by mmoayyed** [comment]
Excellent.
