### ISSUE TITLE
MFA-Duo not invoked when renew=true, Duo "remember me…" not selected

### ISSUE THREAD

**Issue by bifyu** [apereo/cas#2224]
Users are not prompted for Duo MFA factor after reauthentication with primary credentials with renew=true and Duo "remember me for …" not selected.
Note: _**renew=true** is required to trigger this behavior._

- CAS server version
  - 5.0.0 (AuthN using LDAP/MFA-Duo, JSON service registry)
- Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
  - Tomcat 8.0.39, Java 1.8.0_112
- Steps to duplicate the problem
1. define registered service for testing purposes (JSON)
`{
  "name" : "Duo_Renew_True_Test",
  "serviceId" : "^https://example\\.edu/duorenew",
  "description" : "Stub registration to test login loop problem - no MFA",
  "id" : 20161115100000,
  "evaluationOrder" : 99999999,
  "multifactorPolicy" : {
    "@class" : "org.apereo.cas.services.DefaultRegisteredServiceMultifactorPolicy",
    "multifactorAuthenticationProviders" : [ "java.util.LinkedHashSet", [ "mfa-duo" ] ],
    "failureMode" : "OPEN"
  }
  "@class" : "org.apereo.cas.services.RegexRegisteredService",
}`
3. use a new private/incognito browser window for test service URL (the renew=true parameter is required)
`https://cas.example.edu/cas/login?renew=true&service=https%3A%2F%2Fexample%2Eedu%2Fduorenew`
4. authenticate
  a. provide primary LDAP credentials
  b. provide MFA-Duo factor (do not select "remember me for…" for Duo)
6. reload test service URL
`https://cas.example.edu/cas/login?renew=true&service=https%3A%2F%2Fexample%2Eedu%2Fduorenew`

This second time, after providing, primary credentials, the MFA step is skipped and the user is redirected to the registered service.

- CAS debug logs
  - [CAS5-missing-duo.log](https://gist.github.com/bifyu/126a90ada2b0dd62fa25d689a7669e1e#file-cas5-missing-duo-log)

**Comment by mmoayyed** [comment]
Likely related to https://github.com/apereo/cas/issues/2209

**Comment by mmoayyed** [comment]
Resolved in 5.0.2 SNAPSHOT

**Comment by bifyu** [comment]
not sure what feedback is requested?

**Comment by bifyu** [comment]
confirmed fixed in latest published 5.0.2-SNAPSHOT
