### ISSUE TITLE
JDBC authentication provider fails to validate encoded passwords

### ISSUE THREAD

**Issue by gabedwrds** [apereo/cas#2229]
Setup:
CAS version: 5.0.1
Running in Tomcat 8.0.28 on RHEL 7
Configuration: JDBC authentication provider with encoding set to BCRYPT
Database contains a user "uniform" with password "papa", stored as bcrypt hash `$2a$10$/Xbe7FI94Pfkpa.iKqh.BOrqTy6fLknVkhkA385O.M1InLNBJE5.C`

Expected behaviour: CAS accepts user login with the password "papa". To validate correctly, `BCryptPasswordEncoder.matches(CharSequence rawPassword, String encodedPassword)` should be passed the raw password entered by the user, and the encoded password from the database.

Actual behaviour: Login fails. AbstractUsernamePasswordAuthenticationHandler replaces the original password in the Credential object with a new hash, which the matching function can't validate.

The current approach (part of #2114) is to let AbstractUsernamePasswordAuthenticationHandler pre-encode all passwords but keep a copy of the original in case it's needed (i.e. for BCRYPT). The code to keep the original isn't working quite right - debugging shows that the `credential` object meant to hold the original password actually references the same object as `userPass` which gets its password replaced with the hash. Encoding hashes that won't be used is also really CPU-intensive, wasting about 9 seconds per login on my system with the default 16 rounds of bcrypt.

I propose modifying AbstractUsernamePasswordAuthenticationHandler to skip encoding passwords if the encoder is a BCryptPasswordEncoder. Will work on a PR for 5.0.x.

**Comment by mmoayyed** [comment]
> I propose modifying AbstractUsernamePasswordAuthenticationHandler to skip encoding passwords if the encoder is a BCryptPasswordEncoder. Will work on a PR for 5.0.x.

Quick heads up: the handler at that level needs to handle encoding for all credentials. Any type of "if this encoder is bcrypt then don't encode otherwise move on" logic will likely be looked at with a bit of suspicion. My suggestion is to perhaps try to solve the problem with more specific bcrypt encoder types that know what and when to ignore the credential, and make the abstract handler completely agnostic of the encoder type directly.

**Comment by mmoayyed** [comment]
Also, as a first task and to help everyone else understand the issue better: please demonstrate failures with a test case first as part of your upcoming PR.

**Comment by gabedwrds** [comment]
Thinking about this further and testing some things, the problems actually go deeper. Possibly all non-noop encoders are broken with JDBC.

Assume we have providers LDAP, JDBC configured with DefaultPasswordEncoder using MD5, and Accept Users with no encoder. User inputs credentials that are valid in the last provider.
1. LDAP works normally and rejects the user
2. JDBC+MD5 hashes the password, _stores the transformed password in the original credential object_, and rejects the user
3. Accept Users gets the same credential object which still holds the MD5 transformed by the JDBC provider (see screenshot). The user list holds plaintext, not a hash, so this rejects the valid user!

![screen shot 2016-12-16 at 14 21 26](https://cloud.githubusercontent.com/assets/1580619/21275470/fa0ae07e-c39a-11e6-98ce-6d11acdfd80e.png)

Basic quick fix: Each authentication provider should copy the credential object coming in and never modify the original. This will at least fix my bcrypt problem and the problem above where JDBC breaks other providers.

Maybe after dealing with that we can talk about optimizing the rest, like avoiding that unnecessary bcrypt generation. There also seem to be some issues with DefaultPasswordEncoder itself that should be looked at.

**Comment by mmoayyed** [comment]
>Basic quick fix: Each authentication provider should copy the credential object coming in and never modify the original. This will at least fix my bcrypt problem and the problem above where JDBC breaks other providers.

Sounds good to me. Excellent analysis. Look forward to your patch.

> Maybe after dealing with that we can talk about optimizing the rest, like avoiding that unnecessary bcrypt generation. There also seem to be some issues with DefaultPasswordEncoder itself that should be looked at.

Certainly. We can create a separate issue to track that optimization task more accurately.

**Comment by mmoayyed** [comment]
btw, you're welcome [as a suggestion] to target your patch to the master branch first. Depending on feasibility and relevance,  we [or better you] can backport to 5.0.x. This probably is a better route I believe because it sounds like your proposal does include a few breaking IMPL changes, and switching to 5.1.0-SNAPSHOT to get this behavior is very cheap in terms of upgrade effort.

**Comment by gabedwrds** [comment]
I think I'd like to target the quick fix to 5.0.x at first since I'm focused there at the moment (building our own project that works with it), and haven't even looked at master yet. It should be very simple to copy over though. PR coming shortly...

I agree the rest of the work would probably be better suited to master.

**Comment by mmoayyed** [comment]
That's fine; sure. Just be careful and avoid breaking changes when you can.
