### ISSUE TITLE
IgniteTicketRegistry servicesCache cache name mismatched!

### ISSUE THREAD

**Issue by j1nsh1** [apereo/cas#2234]
I have included the following in my report:

- [] CAS server version
4.2.x
- [] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
- [] Steps to duplicate the problem
- [] Stacktraces and CAS logs where appropriate.
- [] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

org.jasig.cas.ticket.registry.IgniteTicketRegistry
line 57
```@Autowired
    @NotNull
    @Value("${ignite.ticketsCache.name:serviceTicketsCache}")
    private String servicesCacheName;
```
should be
```@Autowired
    @NotNull
    @Value("${ignite.servicesCache.name:serviceTicketsCache}")
    private String servicesCacheName;
```

**Comment by mmoayyed** [comment]
https://github.com/apereo/cas/commit/add4dd3bd3d980f23b39725fc89c85a9b1c65337
