### ISSUE TITLE
NullPointerException in Resource CRL check

### ISSUE THREAD

**Issue by hdeadman** [apereo/cas#2238]
CAS 5.0.1, Tomcat Spring Boot, X509

ResourceCRLRevocationChecker - Line 204 can return a singleton collection with single null value (haven't tracked down why, but probably b/c i am testing with dummy cert, or bad config)
```
    @Override
    protected Collection<X509CRL> getCRLs(final X509Certificate cert) {
        return Collections.singleton(this.crlIssuerMap.get(cert.getIssuerX500Principal()));
    }
```
AbstractCRLRevocationChecker  - Line 65 - crls list is not null or empty so it makes it through this block: 
```
        final Collection<X509CRL> crls = getCRLs(cert);

        if (crls == null || crls.isEmpty()) {
            logger.warn("CRL data is not available for {}", CertUtils.toString(cert));
            this.unavailableCRLPolicy.apply(null);
            return;
        }
```

The crls collection contains a single null value so there is NPE in CertUtils.isExpired() when the following block executes:
```
        crls.stream().filter(CertUtils::isExpired).forEach(crl -> {
            logger.warn("CRL data expired on {}", crl.getNextUpdate());
            expiredCrls.add(crl);
        });
```

ResourceCRLRevocationChecker.getCRLs() should probably return null if this.crlIssuerMap.get(cert.getIssuerX500Principal()) returns null.

**Comment by hdeadman** [comment]
The root mis-configuration is that I have one CRL configured but it's not for the issuer of the certificate I am using.  There should probably be message logged with the cert issuer if this.crlIssuerMap.get(cert.getIssuerX500Principal()) returns null (in addition to the whole method returning null if that happens.

**Comment by mmoayyed** [comment]
This is now solved in newer snapshots, once they become available.
