### ISSUE TITLE
Configure Hibernate/JPA catalog and schema

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2239]
Since the switch from Spring xml to Java config in CAS 5 it has become increasingly more difficult to specify additional JPA properties for Hibernate.

Would it be possible to add the following CAS properties:
- `cas.*.jdbc.catalog`
- `cas.*.jdbc.schema`

to configure the JPA properties:
- `hibernate.default_catalog`
- `hibernate.default_schema`

**Comment by mmoayyed** [comment]
Absolutely. Piece of cake actually now with the Java config.

**Comment by Condor70** [comment]
Thanks for the quick response.

Indeed, it only requires adding the properties to org.apereo.cas.configuration.model.support.jpa.AbstractJpaProperties and modifying org.apereo.cas.configuration.support.Beans.newEntityManagerFactoryBean.
(which I now temporarily do in the src directory of our cas-5.0.1 project)

**Comment by mmoayyed** [comment]
Do you know what the default values are for those two properties in hibernate?

**Comment by mmoayyed** [comment]
This will be available in the next batch of snapshots.
