### ISSUE TITLE
Feature request - make it easier for principal resolution failure to be fatal

### ISSUE THREAD

**Issue by hdeadman** [apereo/cas#2251]
In the case where AbstractAuthenticationManager.resolvePrincipal() returns null (e.g. x509 authentication is configured to get principal from ldap attribute repository and user is not found in ldap), it should be easier (ideally configurable, but calling protected method isPrincipalResolutionFailureFatal() would help) to have a PreventedException thrown rather than always falling back to principal name from authentication handler. 
```
            principal = resolvePrincipal(handler.getName(), resolver, credential);
            if (principal == null) {
                logger.warn("Principal resolution handled by {} produced a null principal. "
                        + "This is likely due to misconfiguration or missing attributes; CAS will attempt to use the principal "
                        + "produced by the authentication handler, if any.", resolver.getClass().getSimpleName());
                principal = result.getPrincipal();
            }
```
Something along these lines would allow the PolicyBasedAuthenticationManager to be extended to make that login fail. 
```
            principal = resolvePrincipal(handler.getName(), resolver, credential);
            if (principal == null) {
                if (isPrincipalResolutionFailureFatal()) {
                	logger.debug("Principal resolution handled by {} produced a null principal for: {}" 
                                 , resolver.getClass().getSimpleName(), result.getPrincipal());
                	throw new GeneralSecurityException("Unable to resolve principal");
                }
            	logger.warn("Principal resolution handled by {} produced a null principal. "
                        + "This is likely due to misconfiguration or missing attributes; CAS will attempt to use the principal "
                        + "produced by the authentication handler, if any.", resolver.getClass().getSimpleName());
            }

```

The resolvePrincipal method is abstract but the PreventedException and GeneralSecurityException are checked so it can't throw them. It is also not possible to throw those exceptions from authenticationPolicy.isSatisfiedBy() in a custom authentication policy.

**Comment by mmoayyed** [comment]
This should be done based on newer snapshots of 5.1. See https://apereo.github.io/cas/development/installation/Configuration-Properties.html#principal-resolution
