### ISSUE TITLE
NPE if registered service doesn't have an access strategy

### ISSUE THREAD

**Issue by hdeadman** [apereo/cas#2256]
CAS 5.0.1

Not sure if access strategies are required or not, but I had some services without them and got the following NPE in org.apereo.cas.web.flow.GenerateServiceTicketAction: 

```
Caused by: java.lang.NullPointerException
	at org.apereo.cas.web.flow.GenerateServiceTicketAction.doExecute(GenerateServiceTicketAction.java:74)
	at org.springframework.webflow.action.AbstractAction.execute(AbstractAction.java:188)
	at org.springframework.webflow.execution.ActionExecutor.execute(ActionExecutor.java:51)
	... 115 more
```

Code is (registeredService.getAccessStrategy() is returning null):
```
            WebUtils.putUnauthorizedRedirectUrlIntoFlowScope(context,
                    registeredService.getAccessStrategy().getUnauthorizedRedirectUrl());
```

If access strategies are required they should be defaulted or something should be logged when they are loaded without one.

**Comment by mmoayyed** [comment]
How are you saving/loading services? What is your service registry type?

**Comment by hdeadman** [comment]
I am loading them from JSON files (cas-server-support-json-service-registry) using the following config:

cas:
  serviceRegistry:
    watcherEnabled: false
    initFromJson: true
    config:
      location: file:${config.dir}/cas/config/services

**Comment by mmoayyed** [comment]
Very good. Could you paste the JSON definition that is at fault here? I sort of have an idea what it looks like but just need to be sure so I can add test cases to catch this behavior for good.

**Comment by hdeadman** [comment]
Here it is with some things changed to xyz. 
```
{
  "@class" : "org.apereo.cas.services.RegexRegisteredService",
  "serviceId" : "^https://xyz.*",
  "name" : "XYZ",
  "id" : "20161214"
}
```

**Comment by mmoayyed** [comment]
Excellent. Thanks!

**Comment by mmoayyed** [comment]
Somehow I am unable to dup this. This test for instance passes just fine:

```java
    @Test
    public void checkNullability() {
        final RegisteredServiceJsonSerializer zer = new RegisteredServiceJsonSerializer();
        final String json = "    {\n" +
                "        \"@class\" : \"org.apereo.cas.services.RegexRegisteredService\",\n" +
                "            \"serviceId\" : \"^https://xyz.*\",\n" +
                "            \"name\" : \"XYZ\",\n" +
                "            \"id\" : \"20161214\"\n" +
                "    }";

        final RegisteredService s = zer.from(json);
        assertNotNull(s);
        assertNotNull(s.getAccessStrategy());
        assertNotNull(s.getAttributeReleasePolicy());
        assertNotNull(s.getProxyPolicy());
        assertNotNull(s.getUsernameAttributeProvider());
    }
```

There are defaults. It's unclear why you're getting that NPE. Are you sure it's the access strategy that is null and not the service itself?

**Comment by hdeadman** [comment]
Sorry I didn't debug (to see which is null) and I misread the code thinking that the service couldn't be null, I will try to re-create tomorrow to determine which variable was null. On the other hand, after I got the error I added an access strategy to the service and I think I got by the error (but who knows, I might have fixed a regex for the service url as well).

**Comment by hdeadman** [comment]
I tried several different things and was not able to recreate this. One thing I remember is that the exception was dumped out to the browser and I was unable to find it in any of the log files so I guess it was handled by a default Tomcat/Spring boot error handler? If a default access strategy is created for all services, I suppose servicesManager.findServiceBy(service) must have returned null. 

My un-tested theory is that I had a stale browser open long enough that the session died so the call to: 

```
final Service service = WebUtils.getService(context);
```
returned null b/c the session underlying the flow scope expired. 

I didn't try it but I think:
```
final RegisteredService registeredService = servicesManager.findServiceBy(service);
```
would return null if it was passed a null service. 

If the session did time-out then I blame gitter chat.

**Comment by mmoayyed** [comment]
I very much doubt it's a session timeout issue, because by default session data is backed by the client and there is nothing tracked by the server in the session to affect that. If you can find a way to consistently duplicate this, please report back and we shall investigate. Thanks!
