### ISSUE TITLE
Wrong OAuthRefreshTokenExpirationPolicy expiry calculations

### ISSUE THREAD

**Issue by rduboveckij** [apereo/cas#2265]
Hello Guys,

I have a problem with a wrong time format. A name of a property show seconds, but an implementation expected milliseconds. Example below.
cas.authn.oauth.refreshToken.timeToKillInSeconds=2592000

```
 private ExpirationPolicy refreshTokenExpirationPolicy() {
        return new OAuthRefreshTokenExpirationPolicy(casProperties.getAuthn().getOauth().getRefreshToken().**getTimeToKillInSeconds()**);
    }
```

https://github.com/apereo/cas/blob/v5.0.1/support/cas-server-support-oauth/src/main/java/org/apereo/cas/config/CasOAuthConfiguration.java#L378

```
public boolean isExpired(final TicketState ticketState) {
        return ticketState == null || ticketState.getCreationTime()
                .plus(this.timeToKillInMilliSeconds, **ChronoUnit.MILLIS**).isBefore(ZonedDateTime.now(ZoneOffset.UTC));
}
```

https://github.com/apereo/cas/blob/v5.0.1/support/cas-server-support-oauth/src/main/java/org/apereo/cas/ticket/refreshtoken/OAuthRefreshTokenExpirationPolicy.java#L39

Please change ChronoUnit.MILLIS to ChronoUnit.SECONDS and rename timeToKillInMilliSeconds to timeToKillInSeconds to be more consistent with an access token implementation. 

I hope you will fix it soon.

Thanks, Ruslan

**Comment by mmoayyed** [comment]
Pleas submit a pull request with the change you have in mind. Thanks!

**Comment by mmoayyed** [comment]
Handled in RC2 SNAPSHOT

**Comment by mmoayyed** [comment]
Handled in RC2 SNAPSHOT
