### ISSUE TITLE
LdapAuthorizationGenerator role search

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2268]
The CAS 5.x javadoc for LdapAuthorizationGenerator states that it does 2 separate searches, one for the user and one for the roles.

LdapAuthorizationGenerator in the 4.2 branch actually does this, but LdapAuthorizationGenerator in the 5.0.x and 5.1.x branches only does a single search for the user and evaluates an attribute for the roles.

Our LDAP does indeed contain a separate branch with roles, so i need the 4.2 implementation instead of the 5.x one.

Can the code be modified to support both kind of searches?

**Comment by mmoayyed** [comment]
Handled in the latest snapshot.

**Comment by Condor70** [comment]
The problem with this implementation is that I still need to specify a roleAttribute for this to work, even though I don't actually have a roleAttribute. Otherwise I get an IllegalStateException because the attribute doesn't exist.

Retrieving and validating the attribute specified by the roleAttribute should be moved from LdapUserAttributesToRolesAuthorizationGenerator.generate to addProfileRoles.
