### ISSUE TITLE
DEFAULT CURRENT_TIMESTAMP not valid SQL

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2270]
org.apereo.cas.audit.entity.AuditTrailEntity and org.apereo.cas.trusted.authentication.api.MultifactorAuthenticationTrustRecord both contain the following column definition:
`@Column(columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")`

This is not valid SQL on the DB2 database I'm using (on DB2 it would be "TIMESTAMP WITH DEFAULT").

Why do these 2 entities even contain a default value? CAS never inserts into these tables without specifying the timestamp, so "DEFAULT CURRENT_TIMESTAMP" could just as well be omitted.

**Comment by mmoayyed** [comment]
Handled in the latest snapshot.
