### ISSUE TITLE
Default catalog/schema for audit

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2271]
For issue CAS-2239 you added default catalog and schema support (thanks!), but these only work for JPA based database interaction.

The JdbcAuditTrailManager inserts into the database with an SQL statement instead of using JPA, so the default catalog and schema are ignored.

I've currently modified CasSupportJdbcAuditConfiguration to add catalog and schema support:
```
    @Bean(name = {"jdbcAuditTrailManager", "auditTrailManager"})
    public DelegatingAuditTrailManager jdbcAuditTrailManager() {
        final JdbcAuditTrailManager t = new JdbcAuditTrailManager(inspektrAuditTransactionTemplate());
        t.setCleanupCriteria(auditCleanupCriteria());
        t.setDataSource(inspektrAuditTrailDataSource());
        // -->
        String tableName = "COM_AUDIT_TRAIL";
        if (!StringUtils.isBlank(casProperties.getAudit().getJdbc().getDefaultSchema())) {
        	tableName = casProperties.getAudit().getJdbc().getDefaultSchema() + "." + tableName;
        }
        if (!StringUtils.isBlank(casProperties.getAudit().getJdbc().getDefaultCatalog())) {
        	tableName = casProperties.getAudit().getJdbc().getDefaultCatalog() + "." + tableName;
        }
        t.setTableName(tableName);
        // <--
        return new DefaultDelegatingAuditTrailManager(t);
    }
```
but it might be cleaner to modify JdbcAuditTrailManager to have defaultSchema and defaultCatalog properties and move the concatenation to JdbcAuditTrailManager.LoggingTask.run().

**Comment by mmoayyed** [comment]
Handled in the latest snapshot.
