### ISSUE TITLE
GAuth QR code broken

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2274]
The GAuth QR code no longer works and results in a 404 error.

This is because GoogleAuthenticatorQRGeneratorController is no longer loaded by the @ComponentScan in CasWebApplication (which was removed in the "create spring.factories for autoconfig modules" commit).

I recommend adding googleAuthenticatorQRGeneratorController as a @Bean to GoogleAuthenticatorConfiguration.

**Comment by mmoayyed** [comment]
> I recommend adding googleAuthenticatorQRGeneratorController as a @Bean to GoogleAuthenticatorConfiguration.

Yup. We should do that. Thanks for the catch!

**Comment by mmoayyed** [comment]
This should be fixed in the latest snapshot.
