### ISSUE TITLE
CAS management app error page

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2282]
If, for some reason, the CAS management application needs to show an error page, it will show a stack trace instead.

There are 2 things wrong with AbstractManagementController.resolveException():
1. The view is called "error" and not "errors".
2. Tomcat will show its own error page instead of the nice CAS error page when using sendError.
I recommend removing:
`response.sendError(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);`

**Comment by mmoayyed** [comment]
In your case, what might be an "error" case where the page would show? Is that like an error where something in the app goes wrong, or authz fails, etc? How might you reproduce an error?

**Comment by Condor70** [comment]
I was still suffering from issue #2284 (CAS validation returns error 500).

Under normal circumstances you would probably never see the error page.

**Comment by mmoayyed** [comment]
Cool, well that's good. Easy way to duplicate the problem and kill 2 birds with one stone. Thanks! Shall review.

**Comment by Condor70** [comment]
Quote from the [sendError API docs](http://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletResponse.html#sendError-int-):
> After using this method, the response should be considered to be committed and should not be written to.

So you either use sendError and don't provide your own content or use setStatus and provide your own error page, but not both.

**Comment by mmoayyed** [comment]
Now that https://github.com/apereo/cas/issues/2284 is fixed, can you try once more to see if this issue persists? Or is this now a general enhancement to fix the error processing?

**Comment by Condor70** [comment]
Now #2284 is fixed, I no longer have a way to check this.

But during yesterdays testing I still had to remove the sendError() call, because the response stream is closed by sendError and the CAS error page wouldn't get rendered (you get the default Tomcat error page).

**Comment by mmoayyed** [comment]
This should be fixed in later snapshots. Please try again and report back.
