### ISSUE TITLE
NullPointerException in Cas30ResponseView

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2284]
Version: 5.1.0-RC2-SNAPSHOT

Validating a ticket using both Ldap and GAuth authentication generates a NullPointerException in  Cas30ResponseView.putCasResponseAttributesIntoModel, which results in an error 500 response.

My CAS validation response contained the following attributes:

```
isFromNewLogin: [true]
bypassMultifactorAuthentication: [false]
authenticationDate: [2017-01-06T15:18:06.621+01:00[Europe/Berlin]]
authenticationMethod: [LdapAuthenticationHandler, GoogleAuthenticatorAuthenticationHandler]
authnContextClass: [mfa-gauth]
successfulAuthenticationHandlers: [null, GoogleAuthenticatorAuthenticationHandler]
longTermAuthenticationRequestTokenUsed: [false]
```

The problem is that successfulAuthenticationHandlers contains a null (is that a bug or is that normal?).

If it's a bug, then it should be fixed in the appropriate place.

If it's normal, then putCasResponseAttributesIntoModel should be fixed so it ignores null values, e.g.
```
    protected void putCasResponseAttributesIntoModel(final Map<String, Object> model,
                                                     final Map<String, Object> attributes,
                                                     final RegisteredService registeredService) {
        final Map<String, Object> encodedAttributes = this.protocolAttributeEncoder.encodeAttributes(attributes, registeredService);
        super.putIntoModel(model, CasProtocolConstants.VALIDATION_CAS_MODEL_ATTRIBUTE_NAME_ATTRIBUTES, encodedAttributes);

        final List<String> formattedAttributes = new ArrayList<>(encodedAttributes.size());
        encodedAttributes.forEach((k, v) -> {
            final Set<Object> values = CollectionUtils.toCollection(v);
            values.forEach(value -> {
// -->
            	if (value != null) {
// <--
	                final StringBuilder builder = new StringBuilder();
	                builder.append("<cas:".concat(k).concat(">"));
	               	builder.append(StringEscapeUtils.escapeXml10(value.toString().trim()));
	                builder.append("</cas:".concat(k).concat(">"));
	                formattedAttributes.add(builder.toString());
// -->
            	}
// <--
            });
        });
        super.putIntoModel(model, CasProtocolConstants.VALIDATION_CAS_MODEL_ATTRIBUTE_NAME_FORMATTED_ATTRIBUTES, formattedAttributes);
    }
```

ps. I don't know if you monitor comments on closed issues, but the fix for #2268 is not completely correct IMHO.

**Comment by mmoayyed** [comment]
> If it's a bug, then it should be fixed in the appropriate place.

This is a bug yes. 

For https://github.com/apereo/cas/issues/2268 you are welcome to provide additional feedback on the issue, or better yet submit the fix for what you consider broken. That would be ideal.

**Comment by mmoayyed** [comment]
Could you attach debug logs please? It would be good to trace the error.

**Comment by Condor70** [comment]
Any particular packages you want a debug log from or do you want a complete log (database access makes the log huge)?

**Comment by mmoayyed** [comment]
org.apereo.cas  (or org.apereo) should be good enough: 
https://apereo.github.io/cas/development/installation/Troubleshooting-Guide.html#review-logs

Thanks.

**Comment by Condor70** [comment]
I updated to the latest 5.1.0-RC2-SNAPSHOT and the error changed from a NullPointerException to a ClassCastException, but the underlying cause seems to be unchanged.

Here is the log: [log.txt](https://github.com/apereo/cas/files/693465/log.txt)

It looks like issue #2293 has exactly the same cause (attribute value = null).

**Comment by mmoayyed** [comment]
In your logs, it's unclear exactly what version of CAS you're running. You have taken out the banner that shows the actual build date/time. Please repost logs. 

I am simply unable to duplicate this based on your description so either you are not running the latest, or snapshots are not going out.

**Comment by mmoayyed** [comment]
And travis shows snapshots are successfully going out.

**Comment by Condor70** [comment]
The banner is only written to console and not to the log file.

Here it is:
  __  ____     _     ____  __
 / / / ___|   / \   / ___| \ \
| | | |      / _ \  \___ \  | |
| | | |___  / ___ \  ___) | | |
| |  \____|/_/   \_\|____/  | |
 \_\                       /_/

CAS Version: 5.1.0-RC2-SNAPSHOT
CAS Commit Id: e44590ff094b91f17dab3143668f770f2ff5b67f
CAS Build Date/Time: 2017-01-10T06:52:35.123Z
Spring Boot Version: 1.4.3.RELEASE
Apache Tomcat Version: Apache Tomcat/8.5.5
---------------------------------------------
System Date/Time: 2017-01-10T07:52:45.112+01:00[Europe/Berlin]
System Temp Directory: C:\Users\User\AppData\Local\Temp\
---------------------------------------------
Java Home: C:\Program Files\Java\jre8
Java Vendor: Oracle Corporation
Java Version: 1.8.0_101
JCE Installed: yes
---------------------------------------------
OS Architecture: amd64
OS Name: Windows 7
OS Version: 6.1

**Comment by mmoayyed** [comment]
Thanks for the update. I'll run through this once more to see if I can duplicate this. Logs seem to indicate that CAS is looking for an attribute in the authentication object that indicates the satisfied context (mfa-gauth) and for some reason it bombs to retrieve it due a type mismatch. It's puzzling why I can't duplicate this with your setup though. Lets compare notes: what do you have turned on in your overlay? The LDAP and the GAuth module? Anything else?

**Comment by mmoayyed** [comment]
Also lets try to isolate this: what happens if you disable the Ldap authentication piece (or whatever you use today) and simply fall back onto the native casuser:Mellon business? Does that error show itself again?

**Comment by Condor70** [comment]
I have a lot of stuff enabled:
- support-ldap
- support-jpa-service-registry
- support-jpa-ticket-registry
- support-gauth
- support-gauth-jpa
- support-trusted-mfa
- support-trusted-mfa-jdbc
- support-audit-jdbc

I played with this a little more and I found which setting causes the issue:
If I enable mfa-gauth globally with cas.authn.mfa.globalProviderId it works, but if I enable mfa-gauth in the service (by setting Multifactor Authentication Policy -> Providers to mfa-gauth using the management app) it fails.

**Comment by mmoayyed** [comment]
Thanks. I tracked this down and was able to duplicate it. Update snapshots and try once more.

**Comment by Condor70** [comment]
Yes, that fixed it. Thanks!!!
