### ISSUE TITLE
It is possible to log in with a username followed (postfixed) by an additional @.

### ISSUE THREAD

**Issue by sla23** [apereo/cas#2287]
Version: 4.2.7

Container/environment type/version: Tomcat version  8.5.8, Java version 1.8.0_111, Linux Ubuntu version 14.04.4 LTS

It is possible to log into the CAS server with a username followed (postfixed) by an additional @.

=============================================================
WHO: [username: test123@]
WHAT: supplied credentials: [username: test123@]
ACTION: AUTHENTICATION_SUCCESS
APPLICATION: CAS
WHEN: Tue Jan 03 12:27:25 GMT 2017
CLIENT IP ADDRESS: xx.xx.xx.xx
SERVER IP ADDRESS: xx.xx.xx.xx
=============================================================

To reproduce the issue login with the username followed (postfixed) by an additional @ and the same password you would normally use.

This is an issue for us as we are using the CAS server as a RemoteUser login handler for our Shibboleth server. In the case highlighted above, the CAS server logs you in, but the Shibboleth server does not pull in any attributes from the LDAP server, as user "test123@" does not exist.

In the latest CAS server, it's possible to trim any white spaces before or after the username (this works as we have tested it already), but it's not possible to trim any other character, such as the additional @ that is affecting our service.

**Comment by mmoayyed** [comment]
If you are asking how you might pre-process the userid on CAS before it's submitted over to shib, one easy solution is trap the submit event on the page and mod the username on the JS callback.
