### ISSUE TITLE
CAS 5.1.0-SNAP NPE with SPNEGO+MFA + bypass

### ISSUE THREAD

**Issue by pmarasse** [apereo/cas#2293]
Environment
- CAS server version 5.1.0-SNAP (this morning update)
- Container : Tomcat/8.5.8 Java 8u111 Debian Jessie 32bits

We have 2 auth schemes : SPNEGO & Login/password + Yubikey if needed. I'm using MFA bypass if SPNEGO is triggered.
Tests are done with phpCAS client and 2 apps :
  - 1st SPNEGO or Login/PWD - SAMLv11 validation
  - 2nd SPNEGO or ( Login/PWD + Yubikey ) - CASv3 Validation

With latest snapshot :
  - SPNEGO works on 2 apps
  - Login/PWD fails on 2 apps

Full log since server start (2 first auth are OK with spnego, the last one fails on MFA, CASv3 protocol) :
[npe.txt](https://github.com/apereo/cas/files/693068/npe.txt)

NPE with SAMLv11 :
[npe2.txt](https://github.com/apereo/cas/files/693085/npe2.txt)

**Comment by mmoayyed** [comment]
Could you try again with the updated snapshot and repost logs? Saml1 example might be best to try first. The snapshot doesn't contain a fix but has enough logs in it to hopefully pinpoint the issue.

**Comment by pmarasse** [comment]
updated this morning, SAMLv11 only (1st exception due to bad password... a bit ugly btw), NPE is at the bottom of file : [npe3.txt](https://github.com/apereo/cas/files/695571/npe3.txt)

**Comment by mmoayyed** [comment]
See if the latest snapshot helps.

**Comment by mmoayyed** [comment]
You are definitely not running a recent snapshot. Your banner does not show what git commit id the released is based on. U sure maven is downloading the snapshot dependencies correctly?

**Comment by mmoayyed** [comment]
Your banner also shows your build is at least 4 days old:

```
CAS Build Date/Time: 2017-01-06T09:43:28Z
```

You need to be running `5.1.0-RC2-SNAPSHOT` and then you'd see:

```
CAS Version: 5.1.0-RC2-SNAPSHOT
CAS Commit Id: 0b75fabbb0f865c497327695e30ecf08b6f15e63
CAS Build Date/Time: xyz
Spring Boot Version: 1.4.3.RELEASE
Apache Tomcat Version: Apache Tomcat/8.5.9
```

**Comment by pmarasse** [comment]
Oh sorry, I was not aware that I had to change version from 5.1.0-SNAP to 5.1.0-RC2-SNAP. With this new version, no more NPE but no more attributes release !

now I have :
```
CAS Version: 5.1.0-RC2-SNAPSHOT
CAS Commit Id: b54409b3c5fa6ef22ee3c368b45ca54879e2f5fd
CAS Build Date/Time: 2017-01-11T11:09:06Z
Spring Boot Version: 1.4.3.RELEASE
Apache Tomcat Version: Apache Tomcat/8.5.8
```

new log file : [noattrib.txt](https://github.com/apereo/cas/files/698631/noattrib.txt)

**Comment by mmoayyed** [comment]
Cool. Now we are getting somewhere; I am assuming the service defn does allow for the release of various attributes?

**Comment by pmarasse** [comment]
Of course, If I'm not mistaken :
```
 attributeReleasePolicy:
  {
    @class: org.apereo.cas.services.ReturnAllAttributeReleasePolicy
    principalAttributesRepository:
    {
      @class: org.apereo.cas.authentication.principal.DefaultPrincipalAttributesRepository
      expiration: 2
      timeUnit: HOURS
    }
    authorizedToReleaseCredentialPassword: false
    authorizedToReleaseProxyGrantingTicket: true
  }
```

Before the update that showed up NPE, attributes were released.

**Comment by mmoayyed** [comment]
Excellent. Bound to be something minor I may have missed. Let me review and I'll post back shortly. Sorry for the trouble

**Comment by mmoayyed** [comment]
See this:

```
2017-01-11 12:13:45,311 WARN [org.apereo.cas.authentication.LdapAuthenticationHandler] - <The principal id attribute [uid] is not found. CAS cannot construct the final authenticated principal if it's unable to locate the attribute that is designated as the principal id. Attributes available on the LDAP entry are [[]]. Since principal id attribute is not available, CAS will fallback to construct the principal based on the provided user id: casuser>
2017-01-11 12:13:45,312 DEBUG [org.apereo.cas.authentication.LdapAuthenticationHandler] - <Recording principal DN attribute as LdapAuthenticationHandler.casuser>
```

Your logs show that CAS is not retrieving any attributes from LDAP. How did you define attributes for retrieval?

**Comment by mmoayyed** [comment]
Also in the future (unless the issue deals with SWF) Only turn on DEBUG logs for org.apereo. Reduces the noise quite a bit.

**Comment by mmoayyed** [comment]
This should be fixed in later snapshots. Please try again and report back.

**Comment by pmarasse** [comment]
It does not start this morning :
```
  __  ____     _     ____  __
 / / / ___|   / \   / ___| \ \
| | | |      / _ \  \___ \  | |
| | | |___  / ___ \  ___) | | |
| |  \____|/_/   \_\|____/  | |
 \_\                       /_/

CAS Version: 5.1.0-RC2-SNAPSHOT
CAS Commit Id: a3bd4bcbc4303bf36a906255a4e181ce48f73389
CAS Build Date/Time: 2017-01-16T08:41:28Z
Spring Boot Version: 1.4.3.RELEASE
Apache Tomcat Version: Apache Tomcat/8.5.8
------------------------------------------------------------
System Date/Time: 2017-01-16T09:43:19.270
System Temp Directory: /var/tomcat/inst2/temp
------------------------------------------------------------
Java Home: /usr/java/jdk1.8.0_111/jre
Java Vendor: Oracle Corporation
Java Version: 1.8.0_111
JCE Installed: yes
------------------------------------------------------------
OS Architecture: i386
OS Name: Linux
OS Version: 3.16.0-4-686-pae
------------------------------------------------------------


2017-01-16 09:43:19,809 INFO [org.apereo.cas.web.CasWebApplicationServletInitializer] - <The following profiles are active: native>
2017-01-16 09:43:20,006 WARN [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [org.apereo.cas.web.CasWebApplication]; nested exception is java.lang.IllegalStateException: java.io.FileNotFoundException: class path resource [org/apereo/cas/config/SpnegoConfiguration  .class] cannot be opened because it does not exist>
```
It seems related to spnego, especially this file which contains two spaces at the end of line :
```
support/cas-server-support-spnego-webflow/src/main/resources/META-INF/spring.factories
```

**Comment by mmoayyed** [comment]
Yuck. Thanks for the update. Trimmed the file.

**Comment by pmarasse** [comment]
Yesterday I had weird exception about MFA duo (which I do not use), This morning things seems to be correct :
  * SPNEGO + ByPass : OK
  * SPNEGO only : OK
  * Login/password + MFA : OK
  * Login/password only : OK

Each time, attribute release is done successfully. Thank you !
