### ISSUE TITLE
CAS management app displaying an error message on load and none of the buttons working.

### ISSUE THREAD

**Issue by s757b304** [apereo/cas#2294]
I have included the following in my report:

-  CAS server version - [5.0.0]
-  Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc) -[Tomat 8.0.32] 
- Steps to duplicate the problem
Login to CAS management app using an url similar to https://localhost:8443/cas-management
-  Stacktraces and CAS logs where appropriate.
The following message gets displayed on top of the screen after logging into the cas-management app and none of the button functionalities seem to be working as well.(screen shot attached). No other error in the logs.

 {{ serviceTableCtrl.alert.data.name }} has been successfully deleted. A problem has occurred while trying to delete the service. Be aware that the default service can not be deleted. Unable to retrieve service listing. The service evaluation order can not be updated.

I had been working with Dima on this and we found another user who had a similar experiance
https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/NB6voQHdxp4
![cas-managementapp-error](https://cloud.githubusercontent.com/assets/8258878/21782965/f213131c-d67a-11e6-8b94-33d0d17c5fb8.GIF)

**Comment by mmoayyed** [comment]
Look at your browser console and locate the script errors. Something likely is blocking connections on your end.

**Comment by mmoayyed** [comment]
Also please make sure to take out the comments in the issue template when you submit.

**Comment by s757b304** [comment]
Hello Misagh

I do see some script errors related to angular.js, attaching the screen shot.

![cas-managementapp-error-scripterror](https://cloud.githubusercontent.com/assets/8258878/21783647/fbfa22be-d67d-11e6-9beb-5f209de2d8df.GIF)

**Comment by mmoayyed** [comment]
Have u tried upgrading to the latest 5.0.2 snapshot?

**Comment by s757b304** [comment]
Thanks Misagh. CAS management app seems to work fine with  5.0.2-SNAPSHOT .


I have another issue going on tomcat startup , I do see the following exceptions related to the log4j appenders(log file attached). Do i need to create an overlay for the log4j2.xml without the following?

        <CasAppender name="casAudit">
            <AppenderRef ref="auditlogfile" />
        </CasAppender>
        <CasAppender name="casFile">
            <AppenderRef ref="file" />
        </CasAppender>
        <CasAppender name="casConsole">
            <AppenderRef ref="console" />
        </CasAppender>
        <CasAppender name="casPerf">
            <AppenderRef ref="perfFileAppender" />
        </CasAppender>







________________________________
