### ISSUE TITLE
CAS status page displaying an error message for HazelcastMonitor

### ISSUE THREAD

**Issue by ITassas** [apereo/cas#2295]
Version: 5.0.1

Using Hazelcast ticket registry, the /cas/status page throws the following error  :

> 
> Health: ERROR
> 
> 	1.HazelcastMonitor: ERROR - Error fetching cache status: NullPointerException::null

**cas-server-support-hazelcast-monitor** library is present

With DEBUG mode enabled for com.hazelcast and org.apereo , no more details

**Comment by mmoayyed** [comment]
As I said, you will need to attach full DEBUG logs.

**Comment by ITassas** [comment]
Here's the DEBUG logs while browsing the status page : [hazelcast_monitor.txt](https://github.com/apereo/cas/files/695864/hazelcast_monitor.txt)

**Comment by mmoayyed** [comment]
Fixed in 5.0.2 SNAPSHOT
