### ISSUE TITLE
Adding oauth breaks REST authentication

### ISSUE THREAD

**Issue by ergo70** [apereo/cas#2299]
Hello,

in CAS 5.0.1, adding oauth seems to break REST authentication.

CAS 5.0.1
Tomcat 8.5.9 with Oracle 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14
Ubuntu 16.04 LTS

Steps to duplicate:

1.) Build from cas-overlay-template 5.0.1 with REST enabled:

```
<dependency>
    <groupId>org.apereo.cas</groupId>
    <artifactId>cas-server-support-rest-authentication</artifactId>
    <version>${cas.version}</version>
</dependency>
```

in pom.xml.

Authenticate against REST works.

2.) Build from cas-overlay with oauth added:

```
<dependency>
  <groupId>org.apereo.cas</groupId>
  <artifactId>cas-server-support-oauth-webflow</artifactId>
  <version>${cas.version}</version>
</dependency>
```

in pom.xml.

3.) Authenticate against REST now fails when requesting a service ticket.

The TGT is issued fine - but then, when you try to get a ST:

HTTP 500
Unauthorized Service Access. Service [someservice] is not found in service registry.

4.) Remove oauth dependency from pom.xml. Build again. REST works again.

best regards,

Ernst-Georg

**Comment by mmoayyed** [comment]
Could you also attach DEBUG logs that might explain why `Service [someservice] is not found in service registry` shows up? 
https://apereo.github.io/cas/5.0.x/installation/Troubleshooting-Guide.html

**Comment by ergo70** [comment]
I'll try my best. But I can say that logging in via the default login page works fine and that REST also works fine with [someservice] when the oauth dependency is not present during the build.

**Comment by mmoayyed** [comment]
Thanks. I might have an idea or two, but logs would simply save time to troubleshoot this. Please post back.

**Comment by ergo70** [comment]
This is my cas.log and cas_audit.log with debug on:

[cas.log.txt](https://github.com/apereo/cas/files/697324/cas.log.txt)
[cas_audit.log.txt](https://github.com/apereo/cas/files/697323/cas_audit.log.txt)

I hope that helps...

**Comment by ergo70** [comment]
And now without oauth with debug on - no stacktraces:

[cas.log.txt](https://github.com/apereo/cas/files/697459/cas.log.txt)
[cas_audit.log.txt](https://github.com/apereo/cas/files/697460/cas_audit.log.txt)

**Comment by mmoayyed** [comment]
Excellent. Thanks. I'll review shortly

**Comment by ergo70** [comment]
I think I found it. I now have activated the JSON service registry by adding:

```
<dependency>
    <groupId>org.apereo.cas</groupId>
    <artifactId>cas-server-support-json-service-registry</artifactId>
    <version>${cas.version}</version>
</dependency>
```

to pom.xml and explicitly pointed it to a directory with the service registry files:

`cas.serviceRegistry.config.location: file:/etc/cas/services`

in cas.properties, instead of relying on the implicit service definitions in classpath:/services.

And now it works as expected. However i don't know _why_ it works with explicit, but not with the implicit definitions?

Anyway, it looks like a quirk but not a real bug to me now.

**Comment by mmoayyed** [comment]
You absolutely must not point the registry to embedded files. If you want to use those and you own files at the same time set the registry to auto initialize. 

Thanks for the update.
