### ISSUE TITLE
No feedback on invalid GAuth code

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2304]
Version: 5.1.0-RC2-SNAPSHOT

When an invalid GAuth code is entered the screen is refreshed, but no error message is shown.

Also, #{screen.welcome.label.password} is used in both loginform.html and casGoogleAuthenticatorLoginView.html, so the user has no indication that he has to enter a GAuth code instead of re-entering his original login password.
(I can easily fix this by providing my own casGoogleAuthenticatorLoginView.html, but I feel this should be in the repository too)

**Comment by mmoayyed** [comment]
Should be fixed in later snapshots.
