### ISSUE TITLE
No principal resolution is configured

### ISSUE THREAD

**Issue by tsschmidt** [apereo/cas#2308]
Working with the latest commits in "master" for `5.1.0-RC2-SNAPSHOT`.  I pulled in latest changes to test yesterday and found that CAS was no longer resolving attributes from an LDAP source configured using 
```
cas.authn.attributeRepository.ldap[0]
```
Traced the problem down to the change of "authenticationHandlersResolvers" being switched to a TreeMap to try and order the resolvers.  Switching the Map back to just HashMap in CasCoreAuthenticationConfiguration restores the functionality, but obviously removes the attempted change.

When debugged it seemed that `compareTo` for `AbstractAuthenticationHandler` was called once and a returned 1 and then it just returned null to the get() call.  In the map I believe I had a `DuoAuthenticationHandler` in my first entry, an HttpsBasedHandler in the second entry, and then the PersonDirectoryResolver in the third entry.

Let me know if you need any more info to help resolve this.
Travis

**Comment by mmoayyed** [comment]
Thanks Travis. So in order to for one to duplicate this, one would need to add the duo and ldap modules? anything else? Have you defined more than one block of LDAP settings? Would be good to share maybe the build script and the collection of settings.

**Comment by mmoayyed** [comment]
I must admit it sounds like the issue @pmarasse  experienced as well.

**Comment by mmoayyed** [comment]
Related issue https://github.com/apereo/cas/issues/2293

**Comment by mmoayyed** [comment]
This should be fixed in later snapshots. Please try again and report back.

**Comment by mmoayyed** [comment]
Confirmed via #2293

**Comment by tsschmidt** [comment]
Yes, this has been fixed now.
