### ISSUE TITLE
JPA Ticket Registry (PostgreSQL 9.5.5)

### ISSUE THREAD

**Issue by diogo-cvs** [apereo/cas#2312]
I am in a new deployment **CAS 5.0.2** and am experiencing difficulties in integrating with **Postgresql 9.5.5**.

 **JPA Ticket Registry** feature error: [log.txt](https://github.com/apereo/cas/files/708787/log.txt)

`ERROR: cannot execute SELECT FOR UPDATE in a read-only transaction`

cas.properties:
```
## JPA Ticket Registry
cas.ticket.registry.jpa.jpaLockingTimeout=3600
cas.ticket.registry.jpa.healthQuery=SELECT 1
cas.ticket.registry.jpa.isolateInternalQueries=false
cas.ticket.registry.jpa.url=jdbc:postgresql://localhost/datatraffic
cas.ticket.registry.jpa.failFast=true
cas.ticket.registry.jpa.dialect=org.hibernate.dialect.PostgreSQL95Dialect
cas.ticket.registry.jpa.leakThreshold=10
cas.ticket.registry.jpa.jpaLockingTgtEnabled=true
cas.ticket.registry.jpa.batchSize=1
#cas.ticket.registry.jpa.defaultCatalog=
cas.ticket.registry.jpa.defaultSchema=cas
cas.ticket.registry.jpa.user=cas
cas.ticket.registry.jpa.ddlAuto=validate
cas.ticket.registry.jpa.password=cas
cas.ticket.registry.jpa.autocommit=false
cas.ticket.registry.jpa.driverClass=org.postgresql.Driver
cas.ticket.registry.jpa.idleTimeout=5000
cas.ticket.registry.jpa.pool.suspension=false
cas.ticket.registry.jpa.pool.minSize=1
cas.ticket.registry.jpa.pool.maxSize=5
cas.ticket.registry.jpa.pool.maxIdleTime=1000
cas.ticket.registry.jpa.pool.maxWait=2000
#cas.ticket.registry.jpa.crypto.signing.key=
#cas.ticket.registry.jpa.crypto.signing.keySize=512
#cas.ticket.registry.jpa.crypto.encryption.key=
#cas.ticket.registry.jpa.crypto.encryption.keySize=16
#cas.ticket.registry.jpa.crypto.alg=AES
```

**Comment by mrcasablr** [comment]
I remember running into this while using JDBC backed. Here is my configuration with PostgreSQL 9.6.1 that works for my JDBC authentication and storing audit data. Might work for JPA too -

Here is my JDBC config for audit - 

cas.audit.jdbc.healthQuery=SELECT 1
cas.audit.jdbc.isolateInternalQueries=false
cas.audit.jdbc.url=jdbc:postgresql://localhost:5432/dev_cas_audit
cas.audit.jdbc.failFast=true
cas.audit.jdbc.isolationLevelName=ISOLATION_READ_COMMITTED
cas.audit.jdbc.dialect=org.hibernate.dialect.PostgreSQL92Dialect
cas.audit.jdbc.leakThreshold=10
cas.audit.jdbc.propagationBehaviorName=PROPAGATION_REQUIRED
cas.audit.jdbc.batchSize=1
cas.audit.jdbc.user=<password>
cas.audit.jdbc.ddlAuto=create-drop
cas.audit.jdbc.maxAgeDays=180
cas.audit.jdbc.password=<password>
cas.audit.jdbc.autocommit=false
cas.audit.jdbc.driverClass=org.postgresql.Driver
cas.audit.jdbc.idleTimeout=5000
cas.audit.jdbc.pool.suspension=false
cas.audit.jdbc.pool.minSize=6
cas.audit.jdbc.pool.maxSize=18
cas.audit.jdbc.pool.maxIdleTime=1000
cas.audit.jdbc.pool.maxWait=2000

You probably should change the dialect to `org.hibernate.dialect.PostgreSQL92Dialect` as I read that hibernate 5 and above needs it.

**Comment by mmoayyed** [comment]
Turn off locking and try again.

**Comment by mrcasablr** [comment]
I had the same issue on postgres 9.6.1 and `cas.ticket.registry.jpa.jpaLockingTgtEnabled=false` fixed it
