### ISSUE TITLE
Application Not Authorized to Use CAS

### ISSUE THREAD

**Issue by luotianwen** [apereo/cas#2313]
Application Not Authorized to Use CAS
The application you attempted to authenticate to is not authorized to use CAS.

 

- [4.2.7] CAS server version
- [Java] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
- [] Steps to duplicate the problem
- [] Stacktraces and CAS logs where appropriate.
- [] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

**Comment by luotianwen** [comment]
where  i don't find it

**Comment by luotianwen** [comment]
give me a link

**Comment by hmissi** [comment]
Hello, you have to add a service definition to yopur cas 
i guess that you use http like service ? and by default there is just HTTPS and IMAPS
https://apereo.github.io/cas/4.2.x/installation/Service-Management.html
