### ISSUE TITLE
NPE in GoogleAuthenticatorAuthenticationHandler

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2314]
CAS Version: 5.1.0-RC2-SNAPSHOT
CAS Commit Id: ed48739a3a97d4ceaeabef13fb14355a3ddeacf3
CAS Build Date/Time: 2017-01-18T07:44:14.101Z
Spring Boot Version: 1.5.0.RC1
Apache Tomcat Version: Apache Tomcat/8.5.5

After providing either a valid or an invalid GAuth token I get an NPE in GoogleAuthenticatorAuthenticationHandler.

[Log file](https://github.com/apereo/cas/files/713346/cas.txt)

Nb. I get the NPE error as a dialog error instead of as an error page (probably because of #2304)

**Comment by mmoayyed** [comment]
Give it another shot please. I should have fixed this. Ran through the set up a few times and I believe it should be gone now.
