### ISSUE TITLE
Multiple instances of LDAP pool ?

### ISSUE THREAD

**Issue by maelstr** [apereo/cas#2315]
Configuring LDAP auth with a pool of minPoolSize 2 but 6 connections are opened on the server (according to CAS logs **3** pools are created ?)

CAS server version : 5.0.2 
Container : Tomcat 8.0

```
cas.authn.ldap[0].type=ANONYMOUS
cas.authn.ldap[0].ldapUrl=ldaps://ldap.univ.fr
cas.authn.ldap[0].useSsl=true
cas.authn.ldap[0].baseDn=ou=people,dc=univ,dc=fr
cas.authn.ldap[0].userFilter=(|(supannAliasLogin={user})(mail={user}))
cas.authn.ldap[0].subtreeSearch=false
cas.authn.ldap[0].principalAttributeId=uid
cas.authn.ldap[0].principalAttributeList=sn,cn,givenName,mail
cas.authn.ldap[0].minPoolSize=2
cas.authn.ldap[0].maxPoolSize=10
```

**Comment by mmoayyed** [comment]
Logs are?

**Comment by maelstr** [comment]
Log attached
[cas.log.txt](https://github.com/apereo/cas/files/713914/cas.log.txt)

**Comment by mmoayyed** [comment]
So I am confused here; Your settings say create a connection pool with a minimum size of 2 and maximum size of 10, and then there are 10 connection well within the limits of those parameters. What is the issue?

**Comment by maelstr** [comment]
The 6 connections are created at startup, before any login attempt. I think the minPoolSize indicates that we only want 2 idle connections actives when nothing is going on.. Why 3 initializations of LDAP pool in the log (INFO [org.ldaptive.pool.BlockingConnectionPool] - pool initialized) ?

**Comment by mmoayyed** [comment]
What happens when you set `enhanceWithEntryResolver=false`?

**Comment by mmoayyed** [comment]
I think I know what is happening though and your analysis is right on the spot. Here is the deal:

This happens when creating an anonymous/authenticated authenticator:

```java
        final PooledSearchDnResolver resolver = new PooledSearchDnResolver();
        resolver.setBaseDn(l.getBaseDn());
        resolver.setSubtreeSearch(l.isSubtreeSearch());
        resolver.setAllowMultipleDns(l.isAllowMultipleDns());
        resolver.setConnectionFactory(Beans.newPooledConnectionFactory(l)); //first pool
        resolver.setUserFilter(l.getUserFilter());

        final Authenticator auth;
        if (StringUtils.isBlank(l.getPrincipalAttributePassword())) {
            auth = new Authenticator(resolver, getPooledBindAuthenticationHandler(l)); //second pool
        } else {
            auth = new Authenticator(resolver, getPooledCompareAuthenticationHandler(l));
        }
        if (l.isEnhanceWithEntryResolver()) {
            auth.setEntryResolver(Beans.newSearchEntryResolver(l)); //third pool
        }
```

This should be fixed.

**Comment by maelstr** [comment]
With `enhanceWithEntryResolver=false` only 2 pools are created (and 4 connections opened)
Do I need this property at true ? I can't find what it does in the documentation

**Comment by mmoayyed** [comment]
You do not need it; that was just me testing a theory (which turned out to be true) if you see the code snippet above where I have highlighted the 3 connection pools that get created.

**Comment by mmoayyed** [comment]
Fixed in RC2. This something you would like to see in 5.0.3?

**Comment by maelstr** [comment]
I can wait for the 5.1 release. Thank you for the (quick !) fixes

**Comment by mmoayyed** [comment]
Cool. You should be able to start testing changes with RC2-SNAPSHOT if you are eager!

**Comment by maelstr** [comment]
5.1.0-RC2-SNAPSHOT still creates 2 pools (org/apereo/cas/config/LdapAuthenticationConfiguration.java
line 268 should use previously declared `factory` ?)

As a side node the snapshot I tried has failed to resolve the principal : [cas.log.txt](https://github.com/apereo/cas/files/722807/cas.log.txt)
