### ISSUE TITLE
LDAP returned attributes repeated in request ?

### ISSUE THREAD

**Issue by maelstr** [apereo/cas#2317]
When requesting attributes on an LDAP server the CAS application request contains the attributes repeated

```
cas.authn.ldap[0].type=ANONYMOUS
cas.authn.ldap[0].ldapUrl=ldaps://ldap.univ.fr
cas.authn.ldap[0].useSsl=true
cas.authn.ldap[0].baseDn=ou=people,dc=univ,dc=fr
cas.authn.ldap[0].userFilter=(|(supannAliasLogin={user})(mail={user}))
cas.authn.ldap[0].subtreeSearch=false
cas.authn.ldap[0].principalAttributeId=uid
cas.authn.ldap[0].principalAttributeList=sn,cn,givenName,mail
```

LDAP server log :

```
conn=1168 op=0 SRCH attr=uid mail givenName sn cn mail givenName sn cn
```

CAS log :

```
DEBUG [org.ldaptive.auth.PooledBindAuthenticationHandler] - authenticate criteria=[org.ldaptive.auth.AuthenticationCriteria@743842752::dn=uid=cotest,ou=people,dc=univ,dc=fr, authenticationRequest=[org.ldaptive.auth.AuthenticationRequest@1653527421::user=[org.ldaptive.auth.User@1921357008::identifier=cotest, context=null], returnAttributes=[uid, mail, givenName, sn, cn, mail, givenName, sn, cn]]]
```

- Cas server version : 5.0.2

**Comment by mmoayyed** [comment]
Could you attach full DEBUG logs from startup?

**Comment by maelstr** [comment]
I should have added that this is totally minor, everything is working as expected, but I've just found curious the duplication of attributes while monitoring the log on the LDAP server. The repetition only appears in ldaptive logs so I'm not sure if it's an incorrect use of the library by CAS or a minor bug in ldaptive itself
[cas.log.txt](https://github.com/apereo/cas/files/715927/cas.log.txt)

**Comment by mmoayyed** [comment]
Thanks for the logs but this won't do. I actually do need the full "startup" logs to determine what CAS is doing to construct requirements for attributes. Start from DEBUG and start from the very very beginning.

**Comment by maelstr** [comment]
Full debug logs are really huge.. I suspect the issue is that ldaptive concatenates the return attributes from the `Authenticator`, with the return attributes from the `AuthenticationRequest` during the `authenticate()` call :

```
org/apereo/cas/config/LdapAuthenticationConfiguration.java

authenticator.setReturnAttributes(attributes.keySet().toArray(new String[]{}));

org/apereo/cas/authentication/LdapAuthenticationHandler.java

final AuthenticationRequest request = new AuthenticationRequest(upc.getUsername(),
                    new org.ldaptive.Credential(upc.getPassword()),
                    this.authenticatedEntryAttributes);
response = this.authenticator.authenticate(request);
```

**Comment by mmoayyed** [comment]
That's very likely. Thanks for the diagnosis.

**Comment by mmoayyed** [comment]
Should be fixed in RC2.
