### ISSUE TITLE
Can't use PooledSearchDnResolver in Active Directory type

### ISSUE THREAD

**Issue by leebake** [apereo/cas#2318]
Why I can't use PooledSearchDnResolver in ActiveDirectory type? I found the code, that when I use ActiveDirectory type LdapAuthenticationConfiguration himself resolve resolver to FormatDnResolver. 

https://github.com/apereo/cas/blob/master/support/cas-server-support-ldap/src/main/java/org/apereo/cas/config/LdapAuthenticationConfiguration.java#L274

**Comment by mmoayyed** [comment]
You may also want to discuss this with ldaptive.

**Comment by leebake** [comment]
Ldaptive provides API (especially `org.ldaptive.auth.Authenticator` constructor), that allows you to pass different implementations of DnResolver in constructor. This is exemplified at creating Authenticator of `SASL` type -> https://github.com/apereo/cas/blob/master/support/cas-server-support-ldap/src/main/java/org/apereo/cas/config/LdapAuthenticationConfiguration.java#L243
