### ISSUE TITLE
can‘t more AttributePrincipal 3.4.2

### ISSUE THREAD

**Issue by luotianwen** [apereo/cas#2319]
I have included the following in my report:

- [4.2.7] CAS server version
- [Tomcat] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
- [10] Steps to duplicate the problem
- [] Stacktraces and CAS logs where appropriate.
- [] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

client 3.4.2

can‘t more AttributePrincipal 3.4.2
<bean id="attributeRepository"
    class="org.jasig.services.persondir.support.jdbc.SingleRowJdbcPersonAttributeDao">
    <constructor-arg index="0" ref="dataSource" />
    <constructor-arg index="1" value="SELECT * FROM users WHERE {0}" />
    <property name="queryAttributeMapping">
        <map>
            <entry key="username" value="uName" />
        </map>
    </property>
    <property name="resultAttributeMapping">
        <map>
            <entry key="uName" value="uName" />
            <entry key="uEmail" value="uEmail" />
			<entry key="u_id" value="u_id" />
			<entry key="uPhone" value="uPhone" />
        </map>
    </property>
</bean>
 
<%
AttributePrincipal principal = (AttributePrincipal) request.getUserPrincipal();
// AttributePrincipal principal = AssertionHolder.getAssertion().getPrincipal();
String loginName = principal.getName();
out.println("loginName:" + loginName);
Map<String, Object> attributes = principal.getAttributes();
out.println("
");
if (attributes != null)
{
for (String key:attributes.keySet()
) {
out.println("key= "+ key + " and value= " + attributes.get(key));
}
}
%>

**Comment by dima767** [comment]
Not clear what the issue is

**Comment by luotianwen** [comment]
attributes  is null

**Comment by luotianwen** [comment]
it's ok 
<filter>
    <filter-name>CAS Validation Filter</filter-name>
    <filter-class>
        org.jasig.cas.client.validation.Cas30ProxyReceivingTicketValidationFilter</filter-class>
    <init-param>
        <param-name>casServerUrlPrefix</param-name>
        <param-value>https://127.0.0.1:8443/</param-value>
    </init-param>
    <init-param>
        <param-name>serverName</param-name>
        <param-value>http://127.0.0.1:8081</param-value>
    </init-param>
</filter>
