### ISSUE TITLE
Can't use DirectBindAuthenticator with an EntryResolver

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2327]
Version: 5.1.0-RC2-SNAPSHOT

org.apereo.cas.config.LdapAuthenticationConfiguration.getDirectBindAuthenticator is using the **baseDn** property for the FormatDnResolver instead of the **dnFormat** property (like getActiveDirectoryAuthenticator does).

This works just fine, but if you also set enhanceWithEntryResolver=true, then an entryResolver is created with the specified baseDn, which in this case contains a format string an not a proper base DN,

Fix:
```
    private static Authenticator getDirectBindAuthenticator(final LdapAuthenticationProperties l) {
        if (StringUtils.isBlank(l.getDnFormat())) {
            throw new IllegalArgumentException("Dn format cannot be empty/blank for direct bind authentication");
        }
        final PooledConnectionFactory factory = Beans.newPooledConnectionFactory(l);
        final FormatDnResolver resolver = new FormatDnResolver(l.getDnFormat());
        final Authenticator authenticator = new Authenticator(resolver, getPooledBindAuthenticationHandler(l, factory));

        if (l.isEnhanceWithEntryResolver()) {
            authenticator.setEntryResolver(Beans.newSearchEntryResolver(l, factory));
        }
        return authenticator;
    }
```

**Comment by mmoayyed** [comment]
Fixed in more recent snapshots. Thanks very much for testing and reporting this!
