### ISSUE TITLE
cas.adminPagesSecurity.adminRoles

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2329]
Version: 5.1.0-RC2-SNAPSHOT

The manual states I should be using:
cas.adminPagesSecurity.adminRoles[0]=MYROLE

But adminRoles in org.apereo.cas.configuration.model.core.web.security.AdminPagesSecurityProperties is a Set and can't be specified using the adminRoles[n] syntax (only List can).

**Comment by mmoayyed** [comment]
Fixed in more recent snapshots. Thanks very much for testing and reporting this!
