### ISSUE TITLE
Parameterize content of generated SAML2 idp metadata

### ISSUE THREAD

**Issue by dima767** [apereo/cas#2330]
Currently, seems like CAS auto-generates `idp-metadata.xml` with some assumed static content like root `/idp` context under which CAS is deployed as well as static port of `8443`.

In order to make the generation of the metadata flexible and not to require manual "massaging" of the xml file afterwords to match current environmental settings, come up with a way to parameterize values for generated metadata. At least `root context` and `port`. Perhaps do so via regular CAS property source machinery

**Comment by mmoayyed** [comment]
This is now done. 

You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.
