### ISSUE TITLE
ClientIPAddress must not be null exception when auto registering the OAuth Callback service

### ISSUE THREAD

**Issue by johnlister** [apereo/cas#2333]
This issue was introduced in CAS 5.0.2 and the CAS 5.1 RC1 builds.

If the OAuth webflow is enabled the new event auditing code throws an exception that the clientIPAddress must not be null when the OAuth code tries to self register its own callback service.  It appears that clientIPAddress has been made compulsory for audit events and as the event is triggered internally no valid address is passed.

To replicate, use the gradle overlay template, set the version to 5.0.2, add a dependency on the oauth webflow and run. CAS will terminate with an exception

**Comment by mmoayyed** [comment]
Fixed in 5.0.3
