### ISSUE TITLE
Feature request: LDAP authorization for /cas/status

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2335]
Would it be possible to refactor cas-management-webapp-support-ldap so it is suitable for both the CAS management application en de CAS status page?

**Comment by mmoayyed** [comment]
This is already possible via different ways. The status endpoints can be protected by CAS itself and not via an IP address, which means you can register the endpoint as a service and add access strategy rules based on attributes resolved from LDAP.

**Comment by mmoayyed** [comment]
But of course, if you have something else in mind by all means lets discuss and re-open the case.

**Comment by Condor70** [comment]
I hadn't considered using a service attribute based access strategy. 

But in our LDAP the user roles are stored as group memberships in a different LDAP tree than the users.
I would have to test if is even possible to retrieve  this info as attributes.
And even if this works, is the service attribute based access strategy able to allow access if one of the values of a multivalued attribute (a user can be a member of several groups) equals a certain value?

**Comment by mmoayyed** [comment]
> And even if this works, is the service attribute based access strategy able to allow access if one of the values of a multivalued attribute (a user can be a member of several groups) equals a certain value?

Yes, or that would be a bug.

**Comment by Condor70** [comment]
I tried, but I can't seem to retrieve a roles attribute.

Our LDAP contains the classic people/groups hierarchy:
```
ou=people,dc=domain
  uid={user},objectclass=inetOrgPerson
    attributes: uid, cn, sn, email, telephoneNumber, mobile, manager
ou=groups,dc=domain
  cn={role},objectclass=groupOfUniqueNames
    attributes: uniquemember={dn}
```

I configured a direct bind authenticator for retrieving the user attributes.

I looked at the brand new cas.authn.ldap[0].searchEntryHandlers[0] config, but it looks like there is no searchEntryHandler.type that would perform a group search (PRIMARY_GROUP and RECURSIVE_ENTRY do something completely different).

Next, I tried to configure cas.authn.attributeRepository.ldap[0].
1. I can only use {user} in userFilter (and I would need to use the dn).
2. The search would return a "cn" attribute with a list of roles, which I would have liked to rename to "roles". Unfortunately, configuring "cas.authn.attributeRepository.attributes.cn=roles" will also make the LDAP authenticator retrieve the "cn" attribute from the user!
3. I think i'm missing something. I can see the attributeResolver being created in the debug log, but it is never used during a login.

**Comment by mmoayyed** [comment]
I see your difficulty. I re-opened the case so that we can begin to consider additional authZ rules for accessing status and the CAS dashboard. Thanks for the submission.

**Comment by Condor70** [comment]
Issues 1 and 2 still stand, but issue 3 is already resolved (issue #2348).

Besides these two issues i also ran into another problem, which i logged in the person-directory project: https://github.com/apereo/person-directory/issues/14

**Comment by mmoayyed** [comment]
For 1, you may want to discuss that with ldaptive and/or @dfish3r. I suspect there is a way to use DN in user filters  but I am not privy to it without further research. Daniel would know for sure.

**Comment by Condor70** [comment]
Ldaptive already has a DnAttributeEntryHandler to add the DN as an attribute.

The problem is LdaptivePersonAttributeDao, which only supports a {user} attribute. I will add a feature request for this to the person-directory project.

That only leaves issue 2, for which i would recommend adding a "returnAttributes" config option to cas.authn.attributeRepository.ldap[] (which would work the same as cas.authn.ldap[].principalAttributeList).

**Comment by mmoayyed** [comment]
> That only leaves issue 2, for which i would recommend adding a "returnAttributes" config option to cas.authn.attributeRepository.ldap[] (which would work the same as cas.authn.ldap[].principalAttributeList).

Help me understand this better. Why couldn't you do the same with attribute repositories?

**Comment by mmoayyed** [comment]
Also, if I have not stressed this already I strongly recommend you take a pass at the PDIR issues yourself. Would be much easier to work up the changeset if you already have the environment that can test them quickly.

**Comment by mmoayyed** [comment]
Also what might be easier here is, we can use boot's assistance with spring security to protect the status endpoints and all other actuators. With Spring Sec, it's easy to build support for basic authN backed by ldap/jdbc. Also supports roles.

**Comment by Condor70** [comment]
Issue 2:
The problem is that there is only one set of cas.authn.attributeRepository.attributes which are used by both LdapAuthenticationHandler and all attribute repositories.

When one ore more of these attribute sources contain an attribute with the same name, but a different meaning (in my case the "cn" attribute in user and in group are completely different), specifying a mapping with cas.authn.attributeRepository.attributes (e.g. cas.authn.attributeRepository.attributes.cn=roles) will affect them both.

LdapAuthenticationHandler already has the ability to rename attributes (using cas.authn.ldap[].principalAttributeList). I need the same mapping functionality for the attribute repositories defined in CasPersonDirectoryConfiguration.

**Comment by mmoayyed** [comment]
Thanks for explaining. Sounds like #2083 We'll probably tackle that in 5.2 or later.

**Comment by Condor70** [comment]
Hadn't seen that request before. That would indeed cover this issue completely.

**Comment by mmoayyed** [comment]
This is now handled via Spring Security and the new module to handle webapp security config. See docs for more info. We'll tackle the attribute repository issue later, but please post back if the present functionality added addresses your concerns here.
