### ISSUE TITLE
Wrong implementation of DEFAULT_ERROR_LIST in AuthenticationExceptionHandler 

### ISSUE THREAD

**Issue by leebake** [apereo/cas#2341]
Hi,

I have a little suggestion of `AuthenticationExceptionHandler ` implementation.  As you can see at https://github.com/apereo/cas/blob/master/core/cas-server-core-authentication/src/main/java/org/apereo/cas/web/flow/AuthenticationExceptionHandler.java#L55 

order of `DEFAULT_ERROR_LIST` is very important, so the question is why you have used `HashSet`. From the java doc:

>Class HashSet<E>
 This class implements the Set interface, backed by a hash table (actually a HashMap instance). It makes no guarantees as to the iteration order of the set; in particular, it does not guarantee that the order will remain constant over time.

**Comment by mmoayyed** [comment]
You're right. That's an oversight. Turn your suggestion to a PR and we can merge it. Thanks.
