### ISSUE TITLE
RFE : Skip security questions on password reset

### ISSUE THREAD

**Issue by johnlister** [apereo/cas#2343]
I'm currently using the new Password Management functionality in CAS 5.1 (for a JDBC backend) and cannot use the security questions as these are currently not present in the database. The current implementation assumes that there is at least one security question and throws an error if none are present.

I've successfully replaced the pswdreset-webflow.xml in CAS 5.0.1 (with my own tweaks to get password management working over JDBC) however with 5.1 RC2 spring doesn't pick up my new webflow when applied to an overlay project. The file is in src/main/resources/webflow/pswdreset. 

Is it possible without writing my own webflow configuration java classes to have the xml files replace the base ones when using an overlay?

An alternative is to update the flow to not ask security questions (or always succeed) if none are present instead of throwing an error

**Comment by mmoayyed** [comment]
> Is it possible without writing my own webflow configuration java classes to have the xml files replace the base ones when using an overlay?

Note the big yellow box:
https://apereo.github.io/cas/5.0.x/installation/Webflow-Customization.html#webflow-auto-configuration

> An alternative is to update the flow to not ask security questions (or always succeed) if none are present instead of throwing an error

This is a much better alternative, according to the big yellow box :)

**Comment by johnlister** [comment]
I would agree, the better way would be to modify the code :) Slightly easier to initially update the webflow document though...

**Comment by mmoayyed** [comment]
This is now done. You can try to disable support for security questions.
