### ISSUE TITLE
BUG : JDBC Password management passes String.class as a parameter to jdbcTemplate.queryForMap

### ISSUE THREAD

**Issue by johnlister** [apereo/cas#2344]
queryForMap doesn't require a type specifier and so treats the String.class param as a binary query parameter in JDBC.

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.

**Comment by mmoayyed** [comment]
Also, while the title in this case is rather helpful please remember to use the issue template provided in the future.
