### ISSUE TITLE
NPE in OidcAuthenticationContextWebflowEventEventResolver

### ISSUE THREAD

**Issue by tsschmidt** [apereo/cas#2347]
Working with 5.1.0 SNAPSHOT built from latest in master.  

The exception is raised when logging into a new service with SSO and entering credentials are bypassed.

line 61 in OidcAuthenticationContextWebflowEventEventResolver.java attempts to get the FlowExecutionURL.  With this being a SSO login no FlowExecution key is present when this is executed.  
The behavior is that the login page is presented after the exception occurs.

I fixed the issue on my end for now by doing this:

 `   final URIBuilder builderContext = new URIBuilder(StringUtils.trimToEmpty(context.getFlowExecutionUrl()));`

**Comment by mmoayyed** [comment]
Thanks @tsschmidt I applied the suggested change.
