### ISSUE TITLE
PersonDirectoryPrincipalResolver is ignored when not using JDBCResolver

### ISSUE THREAD

**Issue by tsschmidt** [apereo/cas#2348]
Working with 5.1.0-SNAPSHOT-RC2 latest in master.

In LdapAuthenticationConfiguration.java, there is a method defined as this:

`        private boolean isAttributeRepositorySourceDefined() {
            return personDirectoryPrincipalResolver.getAttributeRepository() != null
                    && personDirectoryPrincipalResolver.getAttributeRepository().getAvailableQueryAttributes() != null
                    && !personDirectoryPrincipalResolver.getAttributeRepository().getAvailableQueryAttributes().isEmpty();
        }
`

Only JDBC resolvers in CasPersonDircetoryConfiguration have any  AvailableQueryAttributes set when they are created.  So all other types of resolvers like Ldaptive resolver have empty set of attributes and are ignored by this configuration.

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.
