### ISSUE TITLE
Bcrypt should only require passwordEncoder.type 

### ISSUE THREAD

**Issue by densik** [apereo/cas#2349]
Bcrypt should not require any properties other than passwordEncoder.type, as it does not require a predefined secret or other attributes. No errors occur when secret is set to an empty/null value.

CAS Version: 5.0.2
Environment: Docker, Ubuntu 16.04, AWS

Steps: 
1) Create cas.properties with JDBC properties set as desired and only `cas.authn.jdbc.query[0].passwordEncoder.type=BCRYPT` (no other passwordEncoder properties set).
2) Docker/overlay build runs fine.
3) Null pointer is returned when CAS is started.

[Stacktrace](https://gist.github.com/densik/3b80f7b1fc47c1a83056408085ce2486)
[properties.cas](https://gist.github.com/densik/3b80f7b1fc47c1a83056408085ce2486)

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.
