### ISSUE TITLE
OAuth authorize endpoint generates a FlowExecutionException

### ISSUE THREAD

**Issue by johnlister** [apereo/cas#2351]
Using the 5.1 RC2 snapshot generates a FlowExecutionException (stack track attached) when calling the authorize oauth 2 method. The code is injecting an AuditTrailManagementAspect into the flow attributes which cannot be serialized resulting in the error. I cannot see in the code where this is happening, but my understanding of spring flow is currently limited.

Using CAS-5.1.0-RC2-SNAPSHOT and running Under Windows 10 or Linux, using either Tomcat 8.0.39 or as standalone app

To reproduce, add dependencies for oauth to overlay project, build and then navigate to /cas/oauth2.0/authorize endpoint. Exception is thrown in viewLoginForm state

Debug trace and exception:
[log+exc-dump.txt](https://github.com/apereo/cas/files/738889/log.exc-dump.txt)

local properties
[cas.properties.txt](https://github.com/apereo/cas/files/738897/cas.properties.txt)

The above file has some additional custom properties, but for the sake of repeatability a clean overlay build was used.

**Update:** Line 45 of OAuth20RegisteredServiceUIAction adds a new inner class of type BaseRegisteredServiceUserInterfaceInfo to the attribute map. Because this is an inner class the compiler automatically inserts a hidden reference to the parent class. When the normal java serialization logic is called it tries to serialize the parent and fails. This pattern is also in the Oidc service, which presumably would fail in a similar manner.  The Saml service declares an actual Metadata class that is passed into the map. Duplicating this pattern for the OAuth service seems to solve the problem

**Comment by mmoayyed** [comment]
Thanks for the info. Are you comfortable with sending a pull request that applies that same pattern for OAuth and OIDC modules?

**Comment by johnlister** [comment]
Sure, wasn't sure if you had a "design" preference. I've got a few other tweaks as well, which i'll finalise and make a pull request.

**Comment by mmoayyed** [comment]
Excellent. Look forward to them.

**Comment by johnlister** [comment]
Fixed by commit [#d93e905](https://github.com/apereo/cas/commit/d93e905db744eb36af4d6e79051e4572a5ca94d8)
