### ISSUE TITLE
Default JPA property values

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2352]
Version: 5.1.0-RC2-SNAPSHOT

I'm trying to reduce the number of warnings issued during CAS startup. A few of these warnings could be avoided by changing some defaults in AbstractJpaProperties:

1. healthQuery = "SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS" -> StringUtils.EMPTY
Hikari uses JDBC4 validation when no connectionTestQuery is specified. I think this should be preferred over using the default healthQuery, which only works on HSQLDB.

2. idleTimeout = "PT5S" -> "PT10M"
Hikari doesn't accept idleTimeout values below 10 sec. A warning will be logged and idleTimeout will be set to 10 min (which should be the default value IMHO).

3. leakThreshold = 10 -> 0
Hikari doesn't accept leakDetectionThreshold values below 2000 ms. A warning will be logged and leak detection will be disabled (leakDetectionThreshold = 0). The default value for leakThreshold should be set to 0 or a value larger than 2000.

**Comment by mmoayyed** [comment]
Thanks very much! All seem perfectly reasonable.

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.
