### ISSUE TITLE
Documentation is messy and not clear

### ISSUE THREAD

**Issue by dragonalvaro** [apereo/cas#2354]
I think that the documentation need and entire revision. The index is confusing and I can't find what I'm looking for.

I'm very new to CAS, but with version 5.0 I can't figure out how to start the server working with a JDBC connection. Tried to import the project to my eclipse to run some test but can't figure out either (docs aren't clear if I have to use maven or gradle). Even using the search function in docs, it takes me to and old version documentation (4.x) and so, useless in 5.0 (took me a time realise that the version was wrongm so I was wasting my time).

Even tried to use a mongo db. But connectors are only for 4.0.

Please, review the documentation.

**Comment by mmoayyed** [comment]
Find areas that need improvement. Submit pull requests to fix.

**Comment by dragonalvaro** [comment]
For example, the jdbc is not clear. I have to put only these properties? add to deployer xml? It's not clear

**Comment by mmoayyed** [comment]
Which "only these properties"? Which steps have you followed in the docs? Happy to answer questions

**Comment by dima767** [comment]
There is no deployer XML requirement in CAS 5. The basic config pattern in version 5 is this:

1) Declare dependency on modules in question for features desired e.g. LDAP, JDBC, etc. 

2) Confogure respective properties in cas.properties

That is pretty much it. 

Yes, the description of the properties could be a little more detailed, and that is something that the dev. team would be improving over time, but of course as @mmoayyed mentioned, all contributions are always welcomed.

**Comment by dima767** [comment]
I would move this discussion to mailing list
