### ISSUE TITLE
REST Authentication discards Principal attributes

### ISSUE THREAD

**Issue by jaantark** [apereo/cas#2362]
https://github.com/apereo/cas/blob/v5.0.2/support/cas-server-support-rest-authentication/src/main/java/org/apereo/cas/adaptors/rest/RestAuthenticationHandler.java#L48

... here, the createPrincipal(String) discards the Attributes from principalFromRest, shouldn't this be createPrincipal(principalFromRest.getId(), principalFromRest.getAttributes()) instead?

**Comment by mmoayyed** [comment]
It certainly should! Good catch. Would you want to send a pull request to fix this ?

**Comment by mmoayyed** [comment]
ported patch over to 5.0.x
