### ISSUE TITLE
CAS Maven overlay - Spring boot application context doesn't see my beans

### ISSUE THREAD

**Issue by leebake** [apereo/cas#2363]
Hi,

I want to overwrite login webflow with my custom action state. I have a problem with beans defined in `src/main/java`

<action-state id="handleAuthenticationFailure">
        
        <transition on="AccountPasswordMustChangeException" to="prepareMustChangePassword" />
        <transition on="CredentialExpiredException" to="prepareMustChangePassword" />
        
    </action-state>

    <action-state id="prepareMustChangePassword">
        <evaluate expression="changePasswordAction.prepare(messageContext)" />
        <transition on="PREPARED" to="viewMustChangePasswordForm" />
    </action-state>`

Spring context doesn't see and doesn't create my config and bean classes:

```
package com.company.cas.config;

import com.company.cas.flow.ChangePasswordAction;
import com.company.cas.service.PasswordChangeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class CasConfig {

    @Autowired
    private PasswordChangeService passwordChangeService;

    @Bean("changePasswordAction")
    public ChangePasswordAction changePasswordAction() {
        return null;
    }

}

```
- CAS server version: 5.1.0-RC2
- Container/environment type/version Tomcat, Windows 7

**Comment by mmoayyed** [comment]
You need to register your configuration with boot first. See spring boot docs on how to create your own auto configuration components.

**Comment by mmoayyed** [comment]
Also please only create issues that are genuine bugs. General purpose questions are not issues.
