### ISSUE TITLE
RFE: Support making missing principal attribute fatal (for ldap authentication handler)

### ISSUE THREAD

**Issue by hdeadman** [apereo/cas#2366]
When using LDAP authentication against Active Directory you can authenticate with a name like my.name (where dnFormat is %s@domain.com) even if that user is located outside of the baseDn. If the "my.name" user is not in the folder or OU specified by the baseDn then no attributes will be found when the user is searched for (after authentication). If you have a principalAttributeId specified then it won't be found but the code just logs that as a warning and continues (using the username). In my case the username happens to be the sAMAccountName which is what I am using for principalAttributeId but I would rather not authenticate users outside the baseDn. 

In LdapAuthenticationHandler.getLdapPrincipalIdentifier(...) there is already a flag for allowMultiplePrincipalAttributeValues and it throws a LoginException if that flag is violated. A similar flag like allowMissingPrincipalAttributeValue (default true) could be used to throw a LoginException if the principalAttributeId is not found. This would essentially restrict logins to users in or under the baseDn (depending on subtreeSearch flag).

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.
