### ISSUE TITLE
REST authentication dropping Principal Attributes via Resolver

### ISSUE THREAD

**Issue by jaantark** [apereo/cas#2371]
https://github.com/apereo/cas/blob/fefdfd647ed822de7a9e7c0ca0f92c5742e02761/core/cas-server-core-authentication/src/main/java/org/apereo/cas/authentication/AbstractAuthenticationManager.java#L222

This is causes Principal Attribute dropping on 5.0.x since the original REST result is not passed to the resolver, that in turn will have no access to the Attributes.

Did not test it - but looks to me, this has been addressed in master:
https://github.com/apereo/cas/commit/0b136a6f7dffc39bfe780d66af682cd465356b1c#diff-f92b26bc4f36cb1e871dc9cc8ba235b6

Shouldn't this be backported to 5.0.x ... as was #2362 ?

**Comment by mmoayyed** [comment]
If it works on master, stay on master please. If you want it backported, by all means shoot over a pull request.
