### ISSUE TITLE
SAML assertion encryption does not use certificate defined in metadata for service

### ISSUE THREAD

**Issue by todd-pratt** [apereo/cas#2372]
I found an issue when I enabled assertion encryption.  When encrypting the assertion it would use the IdP public certificate instead of the one I had defined in the metadata file for the service.  The resolveSingle method call in SamlObjectEncrypter wouldn't return the correct public certificate.  The signing of the response worked so I figured my metadata file was correct.  For simplicity I just loaded the public certificate from the same keystore I was using on my client, so I could test the rest of the encryption which worked after that.  I included a link to the line in SamlObjectEncrypter on github and the change I made to SamlObjectEncrypter code along with my metadata file and json config file.  

Cas Version:  5.0.1
Environment: Tomcat 8 / Java 8 - Linux

[https://github.com/apereo/cas/blob/6f30a825e9fb3dbc3fc75e794e17373746edb48a/support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/enc/SamlObjectEncrypter.java#L227](url)

[SamlObjectEncrypter.java.txt](https://github.com/apereo/cas/files/750967/SamlObjectEncrypter.java.txt
[saml_test2.xml.txt](https://github.com/apereo/cas/files/750980/saml_test2.xml.txt)
[SAMLTest-3032504042888199.json.txt](https://github.com/apereo/cas/files/750984/SAMLTest-3032504042888199.json.txt)

)

**Comment by todd-pratt** [comment]
Corrected the link to github.

https://github.com/apereo/cas/blob/6f30a825e9fb3dbc3fc75e794e17373746edb48a/support/cas-server-support-saml-idp/src/main/java/org/apereo/cas/support/saml/web/idp/profile/builders/enc/SamlObjectEncrypter.java#L227

**Comment by mmoayyed** [comment]
Could I ask, what sort of SP is this that requires encryption? Home-grown app? commercial?

**Comment by mmoayyed** [comment]
Also, do you have some sort of unit test that shows both the correct and incorrect behaviors?

**Comment by todd-pratt** [comment]
I don't have a unit test for this.  Yes it's a home grown app, we are looking for a single sign-on solution for the company I work for and are very interested in CAS.  We plan to use OAuth but would like to know that SAML is also available in case we need it in the future.

**Comment by mmoayyed** [comment]
Cool. Well thanks for raising this issue to the project's attention. This will be reviewed and looked at in the coming days. Seems like certainly a bug in CAS' use of the resolver that should be trivial to fix. Stay tuned.

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.
