### ISSUE TITLE
roleAttribute required for LdapUserGroupsToRolesAuthorizationGenerator

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2376]
Version: 5.1.0-RC2-SNAPSHOT

LdapUserGroupsToRolesAuthorizationGenerator is supposed to retrieve roles based on a groupFilter and a groupAttribute.

The problem is that LdapUserGroupsToRolesAuthorizationGenerator inherits from LdapUserAttributesToRolesAuthorizationGenerator which throws an IllegalStateException when the roleAttribute is not found.

Our LDAP doens't have a roleAttribute, so I can't specify one.

I recommend moving the roleAttribute code from LdapUserAttributesToRolesAuthorizationGenerator.generate() to addProfileRoles(), so it is overridden by LdapUserGroupsToRolesAuthorizationGenerator.addProfileRoles().

Also:
CasWebApplicationSecurityConfiguration.init() checks roleAttribute to see if it has a valid configuration. This will need to be changed, because now either roleAttribute or groupFilter+groupAttribute are valid.

Other minor issues:
1. The baseDn for our groups is different from the one for people. Would it be possible to add a groupBaseDn property to LdapAuthorizationProperties (defaults to baseDn when not specified)?
2. CasLdapUserDetailsManagerConfigurer.ldapAuthorizationGeneratorGroupSearchExecutor creates a SearchExecutor with returnAttributes set to ALL. Could this be changed to only return the groupAttribute (otherwise it will also retrieve all 1000+ group members)?

**Comment by mmoayyed** [comment]
As was suggested, did you try setting your groupAttribute into CAS' roleAttribute and leaving all else empty? You'll need to activate LdapUserAttributesToRolesAuthorizationGenerator, right? 

1. Yes. All things are possible in open source :) You are probably asking if it's probable. That depends. 
2. Good suggestions, sure.

**Comment by Condor70** [comment]
Nope. Setting the roleAttribute to my groupAttribute will fail, because a user doesn't have that attribute.

roleAttribute can only be set to an existing user attribute. And if I use a random user attribute (e.g. "uid"), it will also be evaluated as a role, which could be a security risk (e.g. naming a user "FULL_ACCESS" would give him full access even though he doesn't have that role).

**Comment by mmoayyed** [comment]
If you set it to a random user attribute, it should be evaluated as a role because `LdapUserGroupsToRolesAuthorizationGenerator` overrides that functionality to only add group attributes, right?

**Comment by mmoayyed** [comment]
Correction: not.

Don't get me wrong. This is a legitimate issue; I am merely trying to solve the problem without code changes.

**Comment by Condor70** [comment]
I hadn't looked at it that way. If I set roleAttribute=uid it does indeed not interpret the uid as a role (I read that wrong).

So this is not really an error, just an inconsistency.

**Comment by mmoayyed** [comment]
Excellent. Thanks for double checking. I'll see if I can take a pass at the other suggestions and fix this consistency issue. Keep testing.

**Comment by mmoayyed** [comment]
This is now done. 
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.
