### ISSUE TITLE
Explore integration options with Sentry; tracking and monitoring

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#2379]
https://sentry.io/welcome/

As an addon, it would be great to able to register deployments automatically with the sentry server, hosted by Apereo perhaps or CAS directly. Helps us put together a "who uses CAS" sort of page, and improves community relationship and growth. We'd want the integration to be on by default, but of course configurable easily to turn off. 

Have discussed this option with @jtgasper3 in the past; perhaps we could deploy the server-component via docker somewhere and let CAS talk to it. 

More modestly, a simple http header that can be tracked via `shodan.io` [or other easier means] may be in order here.

**Comment by jtgasper3** [comment]
See: 
- https://hub.docker.com/_/sentry/
- https://store.docker.com/images/788f45b7-2701-4244-90e4-3f85aef116d8?tab=description

**Comment by mmoayyed** [comment]
Changes should be available in 5.1 RC2
