### ISSUE TITLE
Need to set an LDAP response timeout on 5.0.x

### ISSUE THREAD

**Issue by gabedwrds** [apereo/cas#2387]
I'm running into a problem with LDAP on 5.0.2 where CAS doesn't set a response timeout which can cause authentication to hang for 15-16 minutes under certain conditions.

On 5.0.2, with LDAP set up as follows:

```
cas.authn.ldap[0].connectTimeout=5
cas.authn.ldap[0].validateOnCheckout=false
# basically same problem with validateOnCheckout=true
cas.authn.ldap[0].type=AUTHENTICATED
cas.authn.ldap[0].ldapUrl=ldap://ldap.example.com
cas.authn.ldap[0].baseDn=ou=People,dc=jboss,dc=org
cas.authn.ldap[0].userFilter=uid={user}
cas.authn.ldap[0].bindDn=cn=Root,dc=jboss,dc=org
cas.authn.ldap[0].bindCredential=secret1
cas.authn.ldap[0].dnFormat=uid=%s,ou=People,dc=jboss,dc=org
cas.authn.ldap[0].principalAttributeId=uid
cas.authn.ldap[0].useSsl=false
cas.authn.ldap[0].useStartTls=false
cas.authn.ldap[0].usePasswordPolicy=false
```

Problem scenario:
- The connection pool already has a connection open and available
- The LDAP server becomes unreachable (iptables -A INPUT -s ldap.example.com -j DROP)
- Next authentication attempt goes to use the existing connection (or validate it before use), so connectTimeout doesn't apply, will wait for responseTimeout
- responseTimeout defaulted to -1 so it'll wait forever (actually gives up after 15-16 minutes)

In master I see that commit dfc0320c6cd3c980f6fcdb66bca243881848067f added responseTimeout to the LDAP ConnectionConfig which solves this problem. I'm running on 5.0.x and waiting for 5.1.0 isn't an option at this point so I'd like to fix in 5.0.x.

I tested a quick fix by doing cc.setResponseTimeout(newDuration(l.getConnectTimeout())) at the same time that [connectTimeout gets set](https://github.com/apereo/cas/blob/v5.0.2/core/cas-server-core-configuration/src/main/java/org/apereo/cas/configuration/support/Beans.java#L277).

Could also pick another default or port the responseTimeout property from master to make it configurable.

**Comment by mmoayyed** [comment]
Cool. Feel free to submit a pull request to the 5.0.x branch. No need for an issue this case.
