### ISSUE TITLE
SAML2 IdP Unsolicited/Initiated broken

### ISSUE THREAD

**Issue by jribette** [apereo/cas#2390]
I'm trying to use CAS 5.0.2 as a SAML IDP with a simple SAML SP (springboot with spring-security, https://github.com/vdenotaris/spring-boot-security-saml-sample).

It works nice in SP initiated SSO mode.
I have 2 problems in IDP initiated SSO mode, with the following URL :

https://central.local.fr:8443/cas/idp/profile/SAML2/Unsolicited/SSO?providerId=com:vdenotaris:spring:sp&target=http://localhost:9000
CAS server is on port 8443 on localhost.
SP is on port 9000 on locahost.

First problem is in AbstractSamlProfileHandlerController.initiateAuthenticationRequest.initiateAuthenticationRequest
It calls SAMLBindingSupport.isMessageSigned but there is no message in the context in IDP initiated SSO and an ConstraintViolationException with message "SAML message was not present in message context" is thrown.
[stack1.txt](https://github.com/apereo/cas/files/779752/stack1.txt)
If works if an "if" is added arround the "SAMLBindingSupport.isMessageSigned" test.

Second problem is in IdPInitiatedProfileHandlerController.handleIdPInitiatedSsoRequest.
The lines "authnRequest.setID(...)" adds an ID to the SAML request, and later CAS generates and send to the SP an SAML response with "InResponseTo" set. However the SP hasn't send any SAML request in IDP initiated SSO and rejects the SAML response.
[stack2.txt](https://github.com/apereo/cas/files/779792/stack2.txt)
It works if I remove the "authnRequest.setID(...)".

My fixes can be seen here (master branch) : https://github.com/jribette/cas/commit/cf2d666312755f14c9e276885a7db9a2f9b97b0b
They may not be the right ones has I know little about SAML request and reponse.

**Comment by mmoayyed** [comment]
Thank you very much. This is fixed in master, but if you want to submit a pull request for the 5.0.x branch, that would be great.
