### ISSUE TITLE
Can we have clear documentation on how to setup CAS 5.0.X using maven

### ISSUE THREAD

**Issue by allw1994** [apereo/cas#2393]
Please please please can we have some clearer docs on how to setup CAS - especially around DB authentication. The older versions have some really great and detailed ways of setting these things up but sadly all of the methods I have found do not work with the newest version!

**Comment by dima767** [comment]
First point out exactly the spots in the current docs where things are not clear. Second, what details excactly you would like to see. Third, contributions are welcomed.

**Comment by allw1994** [comment]
Right, so starting with databases because that is where the majority of my issues currently lie.

The databases authentication page says please use this dependency  - fine but then anything else is on a different page. Clicking "learn how to configure database drivers" it take you to a page that now disagrees with the previous dependency (when you try to compile it) and says you have automatic support for a bunch of databases but no instructions on how to actually use this support.

 As for configuration of the database page (back again at where I started) you click relevant list of cas properties and although I can see why an exhaustive list of properties is useful it doesn't actually say anything about which properties are relevant for databases (even looking at those with JDBC in the name narrows it down to about 4 different sections) and again the docs tell you nothing on how to actually use the properties - it just gives you what I presume is default settings. 

Also under one of the sections is a link to learn more about this topic taking you back to the original page effectively creating a loop.

I realise why you have the pages as you do but step by step instructions are all I am asking for  - and yes after I have managed to do what I want if i can contribute I will.

**Comment by dima767** [comment]
All legitimate points.

**Comment by lidonghe** [comment]
I'm also very confused by the document, just give you a bunch of configurations but no instruction at all
