### ISSUE TITLE
Duplicate createViewState in PasswordManagementWebflowConfigurer

### ISSUE THREAD

**Issue by FSchumacher** [apereo/cas#2397]
In current trunk (and 5.0.x) there seems to be a duplicate call of createViewState in line 57,58.

`createViewState(flow, "casAccountDisabledView", "casAccountDisabledView");`

As all other states are created only once, I believe this is a typo.

**Comment by mmoayyed** [comment]
Thank you very much for the report. This is fixed in trunk. If you want to backport this to 5.0.x that would be great!
