### ISSUE TITLE
LDAP authentication against AD ignores baseDn/userFilter and requires dnFormat

### ISSUE THREAD

**Issue by jhitt25** [apereo/cas#2402]
We are setting up CAS v5.0.2 running on embedded Tomcat.  We are setting up SPNEGO auth with LDAP form-based fallback (against Active Directory).  With both SPNEGO and LDAP we find that we cannot restrict authentication to users in a specific OU (the baseDn is completely ignored).

Our configuration:
```
cas.authn.spnego.kerberosConf=/etc/cas/krb5.conf
cas.authn.spnego.jcifsServicePrincipal=HTTP/authtest.mydomain.com@MYDOMAIN.COM
cas.authn.spnego.mixedModeAuthentication=true
cas.authn.spnego.send401OnAuthenticationFailure=false
cas.authn.spnego.ldap.baseDn=ou=MyDept,dc=mydomain,dc=com
cas.authn.spnego.ldap.userFilter=(memberOf=cn=MyGroup,ou=Groups,dc=mydomain,dc=com)

cas.authn.ldap[0].type=AD
cas.authn.ldap[0].ldapUrl=ldaps://mydomain.com
cas.authn.ldap[0].usePasswordPolicy=false
cas.authn.ldap[0].dnFormat=%s@mydomain.com
cas.authn.ldap[0].userFilter=(memberOf=cn=MyGroup,ou=Groups,dc=mydomain,dc=com)
cas.authn.ldap[0].baseDn=dc=ou=MyDept,dc=mydomain,dc=com
```

Since i've specifically targetted LDAP with the subject line, i'll focus on that, but the problem exists for both SPNEGO and LDAP.  Using credentials that are neither in MyDept OU or belonging to MyGroup group, authentication is successful.  Further, the userFilter can be set to 'x', and the baseDn to 'x' as well, and authentication still succeeds, with no errors in the logs.

If dnFormat were not required for LDAP type=AD, one would image the userFilter could be modified appropriately to accomodate this need, but even with dnFormat, we may not want to include all users in the directory as viable authentication candidates.

**Comment by mmoayyed** [comment]
Switch to `AUTHENTICATED`

**Comment by jhitt25** [comment]
Switching to `AUTHENTICATED` causes LDAP "NO_OBJECT" errors, which is why i opted to try `AD` instead.  No matter how simple i make the userFilter, or how broad the baseDn, it will not locate users.  Additionally, 'baseDn' is required for `AD`, yet is completely unused.

```
ERROR [org.apereo.cas.authentication.PolicyBasedAuthenticationManager] - <LdapAuthenticationHandler: Unexpected LDAP error  (Details: javax.naming.NameNotFoundException: [LDAP: error code 32 - 0000208D: NameErr: DSID-0315270B, problem 2001 (NO_OBJECT), data 0, best match of:
        'DC=mydomain,DC=com'
]; remaining name 'OU=MyDept,DC=mydomain,DC=com')>
```

**Comment by mmoayyed** [comment]
Just for a bit of background, the AD authentication scheme is modeled after this guide:
https://apereo.github.io/cas/4.1.x/installation/LDAP-Authentication.html#active-directory-authentication

You may want to check this issue with @dfish3r, then post to ldaptive https://github.com/vt-middleware/ldaptive and then analyze the CAS configuration/source to see what improvements may be made, and accompany that with a pull request.
