### ISSUE TITLE
cas 5.1.0-RC1 artifacts (cas-server-webapp war and other modules) depend on SNAPSHOT versions of pac4j

### ISSUE THREAD

**Issue by snakebyte85** [apereo/cas#2405]
I'm trying to develop my custom cas using maven overlay pattern, described on the documentation.

I'm using the 5.1.0-RC1 version in order to use the correct spring-boot autoconfiguration feature (in previous versions the @Configuration classes were loaded with component scan)

But this version depends on SNAPSHOT versions of pac4j artifacts that are not present on maven central repository.

**Comment by mmoayyed** [comment]
It's been almost 2 months since that release. You might have better luck with 5.1 RC2 SNAPSHOTs which build on more recent versions of pac4j [and that's what you should be testing/trying anyway]
