### ISSUE TITLE
openid 2.0 identifier_select doesn't return username

### ISSUE THREAD

**Issue by icukeng** [apereo/cas#2406]
Hello,
I have some weird behavior with openid 2 in CAS.
RP correctly redirects through yadis to OP with identifier_select
```
openid.ns:"http://specs.openid.net/auth/2.0"
openid.mode:"checkid_setup"
openid.return_to:"http://localhost:8080/"
openid.realm:"http://localhost:8080"
openid.ns.ax:"http://openid.net/srv/ax/1.0"
openid.ax.mode:"fetch_request"
openid.ax.type.namePerson:"http://axschema.org/namePerson"
openid.ax.required:"namePerson"
openid.ns.sreg:"http://openid.net/extensions/sreg/1.1"
openid.sreg.required:"fullname"
openid.claimed_id:"http://specs.openid.net/auth/2.0/identifier_select"
openid.identity:"http://specs.openid.net/auth/2.0/identifier_select"
```
I can enter both username and password (so I suppose identifier_select was understood).
But redirect back  does not provide correct identity
```
openid.return_to:"http://localhost:8080/"
openid.identity:"http://specs.openid.net/auth/2.0/identifier_select"
openid.op_endpoint:"https://cas.example.org:8443/cas/login"
openid.assoc_handle:"1486724928189-12"
openid.mode:"id_res"
openid.signed:"op_endpoint,claimed_id,identity,return_to,response_nonce,assoc_handle"
openid.sig:"P5CeYGbXNsA4K7VNNUyurn6fZZ93gXZiXTpOQJJWuHo="
openid.claimed_id:"http://specs.openid.net/auth/2.0/identifier_select"
openid.response_nonce:"2017-02-22T19:22:44Z0"
openid.ns:"http://specs.openid.net/auth/2.0"
```
claimed_id and identity both have no useful informatiln about user.
However  if I send url with user  - everything working like a charm.

I've tried to investigate the situation.
https://github.com/apereo/cas/blob/061ee6686b008f84ec7c37f0e4d15714426fa981/support/cas-server-support-openid/src/main/java/org/apereo/cas/support/openid/web/flow/OpenIdSingleSignOnAction.java
Seems like in getOpenIdSelectedIdentifier function there is condition for valid username url substitution for IDENTIFIER_SELECT mode.
```
if (OpenIdProtocolConstants.OPENID_IDENTIFIERSELECT.equals(openidIdentityParameter)) {
       ......
       final Principal p = ticketRegistrySupport.getAuthenticatedPrincipalFrom(ticketGrantingTicketId);
       if (p != null) {
             return p.getId();
       }
       return OpenIdProtocolConstants.OPENID_IDENTIFIERSELECT;
}
```
I think that "p" is null here for some reason.

**Comment by mmoayyed** [comment]
Are you able to step into the code, debug and figure out if p is in fact null?

**Comment by mmoayyed** [comment]
Do you have client that can be used to test this? Have you looked at DEBUG logs? Do you know what CAS version you're using? What config?!

It would be very useful if you could follow the issue template provided.

**Comment by icukeng** [comment]
We use cas overlay template master from dec 13 2016.
It's very basic configured
```
[root@62203d4d7561 cas-overlay]# git diff
diff --git a/etc/cas/config/log4j2.xml b/etc/cas/config/log4j2.xml
index a093ff7..ca3b74d 100644
--- a/etc/cas/config/log4j2.xml
+++ b/etc/cas/config/log4j2.xml
@@ -53,7 +53,7 @@
             <AppenderRef ref="casConsole"/>
             <AppenderRef ref="casFile"/>
         </AsyncLogger>
-        <AsyncLogger name="org.apereo" level="warn" additivity="false" includeLocation="true">
+        <AsyncLogger name="org.apereo" level="debug" additivity="false" includeLocation="true">
             <AppenderRef ref="casConsole"/>
             <AppenderRef ref="casFile"/>
         </AsyncLogger>
@@ -148,7 +148,7 @@
             <AppenderRef ref="casConsole"/>
             <AppenderRef ref="casFile"/>
         </AsyncLogger>
-        <AsyncLogger name="org.openid4java" level="warn" additivity="false">
+        <AsyncLogger name="org.openid4java" level="debug" additivity="false">
             <AppenderRef ref="casConsole"/>
             <AppenderRef ref="casFile"/>
         </AsyncLogger>
diff --git a/pom.xml b/pom.xml
index 5c126f1..2e6b77d 100755
--- a/pom.xml
+++ b/pom.xml
@@ -66,6 +66,11 @@
             <type>war</type>
             <scope>runtime</scope>
         </dependency>
+        <dependency>
+           <groupId>org.apereo.cas</groupId>
+           <artifactId>cas-server-support-openid-webflow</artifactId>
+           <version>${cas.version}</version>
+        </dependency>
     </dependencies>
 
     <properties>
```
I can't debug it right now, i'm not as good in java.
My colleagues traverse the code in GH. 
The most relevant debug mesage was 
```
DEBUG [org.apereo.cas.support.openid.authentication.principal.OpenIdServiceResponseBuilder] - <Responding to non-associated mode. Service ticket ST-15-nsUUIaGdRifw3F2QVpcM-62203d4d7561 must be validated by the RP>
``` 
Which according to colleagues makes them pretty sure to the point.
Maybe we find enough time for debugging later. 

Actually same behavior we meet at version 4. But found issue 930 and tryed fresh wersion.

As client we use lightopenid for php with some tuning. I attach our example. You need to rewrite endpoint url (we have html with xrds metatag at this url). Run it using "php -S localhost:8080 example.php"
[cas-openid.zip](https://github.com/apereo/cas/files/794754/cas-openid.zip)

I hope this helps.

**Comment by mmoayyed** [comment]
Unfortunately I can't run php client to diagnose this. My suggestion would be for you to debug and step into th code to figure out how by this behavior is happening. If you find an issue please accompany that with a patch with the help of someone who understands Java better.
