### ISSUE TITLE
Issue with spnego, could not find dependencies

### ISSUE THREAD

**Issue by cifren** [apereo/cas#2408]
Hi,

I am trying to use https://apereo.github.io/cas/5.0.x/installation/SPNEGO-Authentication.html, but the dependency "org.samba.jcifs:jcifs-ext:0.9.4" could not be found.

## To reproduce the issue

Add into project/cas/build.gradle

    dependencies {
        compile "org.apereo.cas:cas-server-webapp:${project.'cas.version'}@war"
        compile "org.apereo.cas:cas-server-support-ldap:${project.'cas.version'}"
        compile "org.apereo.cas:cas-server-support-pac4j-webflow:${project.'cas.version'}"
        compile "org.apereo.cas:cas-server-support-spnego-webflow:${project.'cas.version'}"
    }

**Run sudo -E ./gradlew clean build; sudo -E java -jar cas/build/libs/cas.war**

It sends :
```
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_vp0xuc2fc2zpq6so40g7bsd1$_run_closure1.doCall(/projects/cas-gradle-overlay-template/build.gradle:16)
Copying configuration to /etc/cas/config

FAILURE: Build failed with an exception.

* Where:
Build file '/projects/cas-gradle-overlay-template/cas/build.gradle' line: 58

* What went wrong:
A problem occurred evaluating project ':cas'.
> Could not resolve all dependencies for configuration 'detachedConfiguration4'.
   > Could not find org.samba.jcifs:jcifs-ext:0.9.4.
     Searched in the following locations:
         file:/root/.m2/repository/org/samba/jcifs/jcifs-ext/0.9.4/jcifs-ext-0.9.4.pom
         file:/root/.m2/repository/org/samba/jcifs/jcifs-ext/0.9.4/jcifs-ext-0.9.4.jar
         https://jcenter.bintray.com/org/samba/jcifs/jcifs-ext/0.9.4/jcifs-ext-0.9.4.pom
         https://jcenter.bintray.com/org/samba/jcifs/jcifs-ext/0.9.4/jcifs-ext-0.9.4.jar
         https://oss.sonatype.org/content/repositories/snapshots/org/samba/jcifs/jcifs-ext/0.9.4/jcifs-ext-0.9.4.pom
         https://oss.sonatype.org/content/repositories/snapshots/org/samba/jcifs/jcifs-ext/0.9.4/jcifs-ext-0.9.4.jar
         https://build.shibboleth.net/nexus/content/repositories/releases/org/samba/jcifs/jcifs-ext/0.9.4/jcifs-ext-0.9.4.pom
         https://build.shibboleth.net/nexus/content/repositories/releases/org/samba/jcifs/jcifs-ext/0.9.4/jcifs-ext-0.9.4.jar
     Required by:
         project :cas > org.apereo.cas:cas-server-support-spnego-webflow:5.0.2 > org.apereo.cas:cas-server-support-spnego:5.0.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

## Config details

- 5.0 CAS server version
CAS Version: 5.0.2
Apache Tomcat Version: Apache Tomcat/8.5.9
Build Date/Time: 2017-02-23T13:40:32Z
System Temp Directory: /tmp
Java Home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.121-0.b13.el7_3.x86_64/jre
Java Vendor: Oracle Corporation
Java Version: 1.8.0_121
JCE Installed: yes
OS Architecture: amd64
OS Name: Linux
OS Version: 4.4.0-64-generic
Gradle

My cas.properties

    cas.server.name=http://localhost-cas
    cas.server.prefix=http://localhost-cas/cas

    cas.server.ajp.enabled=true

    cas.adminPagesSecurity.ip=.*

    logging.config=file:/etc/cas/config/log4j2.xml

    ####### config simple par defaut
    # Cookie
    cas.tgc.cipherEnabled=false

    # SSL
    server.ssl.enabled=false

    # webflow
    cas.webflow.signing.key=2H1YLO-_8HYK505D8Ty78_cIW3Hn9BTCGJ8QB8vI1n9jhvD4ONAL-LtjoKwohFPWhmLa-aoaPhpP7Yb0GUAh0w
    cas.webflow.encryption.key=UGIUmxYrRXPqgMiL
    ####### config simple par defaut

Thank you for your help.

**Comment by mmoayyed** [comment]
Thank you for a most excellent bug report!

Can you try adding `maven { url "http://developer.jasig.org/repo/content/groups/m2-legacy/" }` to the build?

**Comment by cifren** [comment]
I have placed "http://maven.novamens.com/jcifs/jcifs-ext/0.9.4/" pom and jar into "file:/root/.m2/repository/org/samba/jcifs/jcifs-ext/0.9.4/" like it was asking, I had to replace the group id from jcifs-ext-0.9.4.pom like it 'asked'.

It resolved my problem.

I will try your solution.

**Comment by cifren** [comment]
Your solution is way better lol

Thank you for the really fast answer :)

**Comment by cifren** [comment]
Should I propose a change into the documentation ?

**Comment by mmoayyed** [comment]
Yes please. That would be terrific. Target your change to the 5.0.x branch.

**Comment by cifren** [comment]
I am sorry but I am not sure how to change the doc, the part we need to edit would be the javascript part... in order to add the new repository

And I am not even sure if Maven reacts the same way...

I could add :
    ``You need to add a new repository "http://developer.jasig.org/repo/content/groups/m2-legacy/" into your cas/build.gradle``

**Comment by mmoayyed** [comment]
What you want to do is:

See this page first:
https://github.com/apereo/cas/blob/master/docs/cas-server-documentation/installation/SPNEGO-Authentication.md#components

Notice how it has that block for the repository configuration? Copy that block.

Then go here:
https://apereo.github.io/cas/5.0.x/installation/SPNEGO-Authentication.html

- Click that pencil in the toolbar.
- Paste the change in the appropriate spot, once the repo is forked, etc.
- Turn the change into a pull request.

LMK if you still have trouble. You should also read through this doc https://apereo.github.io/cas/developer/Contributor-Guidelines.html

**Comment by cifren** [comment]
https://github.com/apereo/cas/pull/2412
