### ISSUE TITLE
Unify connection pools

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2417]
CAS creates separate JDBC and LDAP connection pool instances in several places.

If these connection pools are for the same database/ldap server then it would be a lot more effective if only one connection pool was created and used everywhere.

Most JDBC datasources are created as separate beans (dataSourceService, dataSourceTicket, inspektrAuditTrailDataSource, dataSourceMfaTrustedAuthn, dataSourceEvent, dataSourceGoogleAuthenticator, monitorDataSource) which means I could replace them with a single aliased datasource if they would have been marked with @ConditionalOnMissingBean.

Other JDBC datasources are created inside other code (PasswordManagementConfiguration, CasJdbcUserDetailsManagerConfigurer, CasJdbcAuthenticationConfiguration and CasPersonDirectoryConfiguration) and aren't easy to replace.

LDAP connection pools are currently always created inside the Beans utility class, which means that it is almost impossible to create a single LDAP connection pool that is used in multiple places.

Could all instances of JDBC and LDAP connection pools be created as @Beans, marked with @ConditionalOnMissingBean?

**Comment by mmoayyed** [comment]
See https://github.com/apereo/cas/pull/2400

**Comment by mmoayyed** [comment]
You may want to discuss this with @leebake as well.

**Comment by mmoayyed** [comment]
> Could all instances of JDBC and LDAP connection pools be created as @Beans, marked with @ConditionalOnMissingBean?

Sure thing. Shoot over a pull request please.

**Comment by Condor70** [comment]
#2400 is definitely not a duplicate. Was that the reason you closed this?

I could create a pull request for JDBC datasources, but a solution for LDAP connection pools would be rather invasive. Do you still want me to create a pull request for that?

**Comment by mmoayyed** [comment]
Yes. Your request seemed to advocate that there is need for unification of [LDAP specially] connection pools. I pointed out the recent discussion on that regard. Not a duplicate; just a conflict. But, feature enhancements and such need to usually and mostly be accompanied by pull requests. That is effectively the "issue". 

As for your question, yes to both. Changes should be targeted to master, and be separate PRs if possible.

Thanks very much.
