### ISSUE TITLE
absolute path question for windows7

### ISSUE THREAD

**Issue by liuchang666** [apereo/cas#2422]
ServletContext resource [/D:/etc/cas/log4j2.xml] cannot be resolved to URL because it does not exist

**Comment by liuchang666** [comment]
##
# CAS Log4j Configuration
#
logging.config=D:\\etc\\cas\\log4j2.xml
server.context-parameters.isLog4jAutoInitializationDisabled=true

**Comment by mmoayyed** [comment]
Please discuss and review this issue with spring boot.
