### ISSUE TITLE
CAS 5.0.x: Dashboard bug

### ISSUE THREAD

**Issue by nstylianides** [apereo/cas#2427]
CAS server version: 5.0.x
Container/environment type/version: Tomcat 8
Steps to duplicate the problem: access /status/dashboard

Hi there, 
I am not sure if this is a Core problem but i found a bug: 

In WEB-INF/classes/templates/monitoring/viewDashboard.hml: line 78

Fix th:action value from "/status/dashboard" to "@{/status/dashboard}"

**Comment by mmoayyed** [comment]
Great. Can you turn this into a pull request please?

**Comment by mmoayyed** [comment]
Reviewed. The `viewDashboard.hml` page has no reference to /status/dashboard. Please review and confirm again.
