### ISSUE TITLE
SessionIndex attribute is missing in SAML authentication response

### ISSUE THREAD

**Issue by dima767** [apereo/cas#2429]
WebAdvisor SAML2 integration fails due to a theory of missing `SessionIndex` attribute of `AuthnStatemnt` element of SAML2 authentication response sent by CAS. Similar Shibboleth Idp authentication response is examined and it does contain this attribute. The Shib Idp integration succeeds while CAS integration fails with WebAdvisor complaining that it cannot create session/token. While there are no detailed logs available from WebAdvisor side pointing exactly that the missing session index is the problem, it is however a theory.

Issue here exists for discussion/tracking/estimate of what would it take to add that session index attribute to CAS implementation.

Here's how Shibboleth authn stmt element in the response looks like:

```xml
<saml2:AuthnStatement AuthnInstant="2017-03-03T00:16:27.844Z" SessionIndex="_xxx...”>
```

and here's CAS':

```xml
<saml2:AuthnStatement AuthnInstant="2017-03-02T17:53:04.868Z”>
```

**Comment by mmoayyed** [comment]
> what would it take to add that session index attribute to CAS implementation.

Very simply, a pull request that looks at the authn statement generation process and builds the session index.
