### ISSUE TITLE
enabling LDAP or SAML support downgrades built-in Tomcat

### ISSUE THREAD

**Issue by ernestojanus** [apereo/cas#2432]
# CAS version
5.0.3

# Container 
built-in Tomcat

# Reproduction
1. using a maven war-overlay, start with no extra dependencies and confirm on startup that CAS uses Tomcat 8.5.9
2. include a dependency on <tt>cas-server-support-ldap</tt>. If you start CAS now, it will use Tomcat 8.5.6

# Analysis
The observed behavior also happens when including e.g. <tt>cas-server-support-saml-idp</tt>. The culprit seems to be a dependency on <tt>org.apereo.cas:cas-server-core-authentication</tt>, which places an 8.5.6 version of Tomcat in the <tt>/lib</tt> dir of the war. This overrides the Tomcat 8.5.9 version in <tt>/lib-provided</tt> during startup.

Here is a truncated output of <tt>mvn dependency:tree</tt>
<pre>
[INFO] nl.uva:cas5:war:1.0.0-SNAPSHOT
[INFO] +- org.apereo.cas:cas-server-webapp:war:5.0.3:compile
[INFO] +- org.apereo.cas:cas-server-support-ldap:jar:5.0.3:compile
[INFO] |  +- org.apereo.cas:cas-server-core-authentication:jar:5.0.3:compile
..
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-web:jar:1.4.2.RELEASE:compile
[INFO] |  |  |  \- org.springframework.boot:spring-boot-starter-tomcat:jar:1.4.2.RELEASE:compile
[INFO] |  |  |     +- org.apache.tomcat.embed:tomcat-embed-core:jar:8.5.6:compile
[INFO] |  |  |     +- org.apache.tomcat.embed:tomcat-embed-el:jar:8.5.6:compile
[INFO] |  |  |     \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:8.5.6:compile
</pre>

I currently use exclusion of <tt>spring-boot-starter-web</tt> as a temporary workaround in my war-overlay

```xml
..
        <dependency>
            <groupId>org.apereo.cas</groupId>
            <artifactId>cas-server-support-ldap</artifactId>
            <version>${cas.version}</version>
            <exclusions>
                <!-- TODO report to Apereo -->
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-web</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
..
```

**Comment by mmoayyed** [comment]
I believe this is fixed in 5.0.4 SNAPSHOTs. Feel free to switch and try. Thank you for the bug report and your excellent analysis of the issue!
