### ISSUE TITLE
CAS SAML2 IdP failed to locate the right service metadata when processing LogoutRequest

### ISSUE THREAD

**Issue by gangyang7** [apereo/cas#2439]
When there are more than one SAML services defined, CAS IdP failed to locate the right service metadata when processing SAML2 LogoutRequest.

The CAS tested were 5.1.0-RC1 and RC2 deployed in external Tomcat 8 on Windows 2008 R2.

To reproduce the problem:
- Build CAS SAML2 IdP with 5.1.0-RC2 using CAS War overlay
- Deploy the war into an external Tomcat 8
- Define two SAML2 services in CAS SAML2 IdP. The ones used were all using HTTP POST bindings for both SSO and SLO.
- Login to one of the SAML2 services via CAS SAML2 IdP
- Logout from the SAML2 service, which will trigger a SAML2 LogoutRequest sent to CAS SAML2 IdP via HTTP POST.
- Observe Tomcat console for error: java.lang.RuntimeException: Cannot find entity https://ts3.security.army.mil/TS3WebApp in metadata provider.

A Tomcat console log is attached with CAS debug turned on for org.aperos. It seemed to have shown that when locating the service metadata, CAS did find the right metadata [C:/temp/cas/sp/TS3WebApp.xml] for the logged-in service, https://ts3.security.army.mil/TS3WebApp. But somehow it did not stop searching and ended up using the metadata for the other service, TS3WebAppWSClient.

Look for "!!! Start of SLO" when viewing the log. 

[TomcatConsoleLog.txt](https://github.com/apereo/cas/files/828297/TomcatConsoleLog.txt)

**Comment by mmoayyed** [comment]
Could you also attach your SAML service defn please?

**Comment by gangyang7** [comment]
Attached together with metadata.

Gang

**Comment by mmoayyed** [comment]
Sorry, I don't see anything. Did you attach the files to your email message? Those wont show up here, I don't think.

**Comment by gangyang7** [comment]
Sorry, yes, I responded from email and attached the files to the email not realizing where the email came from. Here they are.
[TS3WebApp-10000003.json.txt](https://github.com/apereo/cas/files/829151/TS3WebApp-10000003.json.txt)
[TS3WebAppWSClient-10000004.json.txt](https://github.com/apereo/cas/files/829152/TS3WebAppWSClient-10000004.json.txt)
[TS3WebApp.xml.txt](https://github.com/apereo/cas/files/829154/TS3WebApp.xml.txt)
[TS3WebAppWSClient.xml.txt](https://github.com/apereo/cas/files/829155/TS3WebAppWSClient.xml.txt)

**Comment by mmoayyed** [comment]
Same as the other issue; I tried to run through this sequence under RC3 SNAPSHOT and could not duplicate. Please try again and report back. We can further investigate.
