### ISSUE TITLE
acceptable use NPE in 5.1.0-rc2 with DefaultAcceptableUsagePolicyRepository

### ISSUE THREAD

**Issue by hdeadman** [apereo/cas#2441]
CAS 5.1.0-rc2, config was working in 5.0.3.1 (updated CAS and removed customized login flow) - 

In CasSupportActionsAcceptableUsagePolicyConfiguration it creates a DefaultAcceptableUsagePolicyRepository without calling the setter with the ticketRegistrySupport so I get an NPE due to ticketRegistrySupport (I confirmed it is null in debugger although it is only thing that could be null)

```
Caused by: java.lang.NullPointerException
	at org.apereo.cas.web.support.WebUtils.getPrincipalFromRequestContext(WebUtils.java:534)
	at org.apereo.cas.web.flow.DefaultAcceptableUsagePolicyRepository.verify(DefaultAcceptableUsagePolicyRepository.java:26)
	at org.apereo.cas.web.flow.AcceptableUsagePolicyFormAction.verify(AcceptableUsagePolicyFormAction.java:51)
```

The code in question is in CasSupportActionsAcceptableUsagePolicyConfiguration (needs to call setter or call a constructor that doesn't exist):
```java
    @ConditionalOnMissingBean(name = "acceptableUsagePolicyRepository")
    @Bean
    public AcceptableUsagePolicyRepository acceptableUsagePolicyRepository() {
        return new DefaultAcceptableUsagePolicyRepository();
    }
```

I am not using an acceptableUsagePolicyRepository (e.g. LDAP) 

I am trying to upgrade to see if x509 and acceptable use webflows can work together in 5.1. In 5.0 I don't get an acceptable use page if authenticating with x509 credentials.  This error occurs when I cancel out of the x509 auth and use username/password. I get a different webflow error if I provide x509 credentials in 5.1 but I haven't tracked that down yet. 
```
[Request processing failed; nested exception is org.springframework.webflow.engine.NoMatchingTransitionException: No transition was matched on the event(s) signaled by the [1] action(s) that executed in this action state 'startX509Authenticate' of flow 'login'; transitions must be defined to handle action result outcomes -- possible flow configuration error? Note: the eventIds signaled were: 'array<String>['authenticationFailure']', while the supported set of transitional criteria for this action state is 'array<TransitionCriteria>[success, warn, error]'] with root cause>
```

**Comment by mmoayyed** [comment]
Excellent analysis. Thank you.

Could you put together a PR for the first issue? Seems very trivial. For the second, lets track that separately.

**Comment by mmoayyed** [comment]
> I am not using an acceptableUsagePolicyRepository (e.g. LDAP)

What option are you using to store and check for user decisions?

**Comment by hdeadman** [comment]
I am not storing their decision, they just have to agree to the acceptable use verbiage every time they authenticate. That is sort of the requirement where I am at. 

I will try to do a patch shortly.

**Comment by mmoayyed** [comment]
Interesting, and thank you!

**Comment by mmoayyed** [comment]
PR https://github.com/apereo/cas/pull/2442
