### ISSUE TITLE
bindDN not reused when rebinding to LDAP connection

### ISSUE THREAD

**Issue by bifyu** [apereo/cas#2443]
The bindDN specified by the property `cas.authn.ldap[0].bindDn` is not always re-used when rebinding to a closed LDAP pool connection. Instead, it may rebind with the DN of the CAS user. Depending on the LDAP's ACI configuration, the CAS user may not have sufficient privileges to search for any subsequent user and/or retrieve their attributes.

- CAS server version
  - 5.0.3.1 (AuthN using LDAP, JSON service registry)
- Container/environment type/version
  - Tomcat 8.0.41, Java 1.8.0_112, Red Hat Linux 6.8

We are able to induce bug with a stress test that rapidly loops through login/validate repeatedly with multiple users. The problem surfaces quickly.

Example of one LDAP connection from CAS:

A brand new LDAP connection binds as the special DN cn=cas-authn-ldap-bindDN. It's able to search for any username and get back attributes:
```
Mar05 14:37:28 conn=3593818 14:37:28 - dn="cn=cas-authn-ldap-bindDN" BIND dn="cn=cas-authn-ldap-bindDN" method=128 version=3      RESULT err=0 tag=97 nentries=0 etime=0 dn="cn=cas-authn-ldap-bindDN"
Mar05 14:37:28 conn=3593818 14:37:28 - dn="cn=cas-authn-ldap-bindDN" SRCH base="" scope=0 filter="(objectClass=*)" attrs="1.1"       RESULT err=0 tag=101 nentries=1 etime=0
Mar05 14:37:28 conn=3593818 14:37:28 - dn="cn=cas-authn-ldap-bindDN" SRCH base="dc=hawaii, scope=2 filter="(uid=user1)" attrs="labeledURI physicalDeliveryOfficeName telep        RESULT err=0 tag=101 nentries=1 etime=0
```
A few minutes later, it BINDs as an end-user and it keeps doing that for several other users until 16:25
```
Mar05 14:40:52 conn=3593818 14:37:28 - dn="cn=cas-authn-ldap-bindDN" BIND dn="uhEntry=193..." method=128 version=3      RESULT err=0 tag=97 nentries=0 etime=0 dn="uhentry=193..."
Mar05 14:40:55 conn=3593818 14:37:28 - dn="cn=cas-authn-ldap-bindDN" SRCH base="" scope=0 filter="(objectClass=*)" attrs="1.1"       RESULT err=0 tag=101 nentries=1 etime=0
...
Mar05 16:25:28 conn=3593818 14:37:28 - dn="cn=cas-authn-ldap-bindDN" BIND dn="uhEntry=1a3.." method=128 version=3      RESULT err=0 tag=97 nentries=0 etime=0 dn="uhentry=1a3..."
Mar05 16:25:28 conn=3593818 14:37:28 - dn="cn=cas-authn-ldap-bindDN" SRCH base="" scope=0 filter="(objectClass=*)" attrs="1.1"       RESULT err=0 tag=101 nentries=1 etime=0
```
Since we are still bound as the last end-user above, we cannot search for any username and retrieve attributes (that requires the connection to BIND again as the special DN cn=cas-authn-ldap-bindDN). The query returns 0 entries:
```
Mar05 16:25:28 conn=3593818 14:37:28 - dn="cn=cas-authn-ldap-bindDN" SRCH base="dc=hawaii, scope=2 filter="(uid=user4)" attrs="labeledURI physicalDeliveryOfficeName telep         RESULT err=0 tag=101 nentries=0 etime=0
Mar05 16:25:29 conn=3593818 14:37:28 - dn="cn=cas-authn-ldap-bindDN" SRCH base="" scope=0 filter="(objectClass=*)" attrs="1.1"       RESULT err=0 tag=101 nentries=1 etime=1
```
This results in a "short" CAS log entry like the following that is missing attributes
```
INFO [org.apereo.cas.authentication.PolicyBasedAuthenticationManager] - <Authenticated principal [user1] and attributes {LdapAuthenticationHandler.dn=uhEntry=1a3...,} with credentials [user4].>
```
Rather than the expected
```
INFO [org.apereo.cas.authentication.PolicyBasedAuthenticationManager] - <Authenticated principal [user1] and attributes {cn=Firstname Lastname, eduPersonAffiliation=student, eduPersonOrgDN=uhm, eduPersonPrincipalName=user4@hawaii.edu, givenName=Firstname, LdapAuthenticationHandler.dn=uhEntry=1a3..., mail=user4@hawaii.edu, sn=Lastname, uhEmail=user4@hawaii.edu, uhOrgAffiliation=eduPersonOrgDN=uhm,eduPersonAffiliation=student, uhUuid=12345678, uid=user4} with credentials [user4].>
```
Applications using CAS that expect to receive attributes consequently fail.

**Comment by hdeadman** [comment]
My guess is 7eb97d31879694f2d24b393a2c21687b0fc6533a on the 5.0 branch. "Let ldap authentication reuse existing connection pool".

**Comment by mmoayyed** [comment]
That https://github.com/apereo/cas/commit/7eb97d31879694f2d24b393a2c21687b0fc6533a seem like the culprit. I remember this is a PR that got merged into master, and we backported to 5.0.x, and then was reverted in master but not from 5.0.x. @bifyu Could you reverse that commit and see if it fixes that issue?

**Comment by dfish3r** [comment]
@mmoayyed just wanted to confirm this is an issue in the CAS code base and not a regression in the ldaptive spring schema parsing.

**Comment by hdeadman** [comment]
It's been fixed on the 5.0.x branch, or at least an attempt to fix was made. Did anyone try a snapshot build to confirm the fix? I assume there are snapshot builds of the 5.0.x branch but I don't know for sure.

**Comment by mmoayyed** [comment]
Thanks @dfish3r Appreciate the update. 

In 5.0.x, there now exists configuration that allows one to define the passivator as ldaptive provides. I just ran into this issue with a deployment, and the passivator took care of it. I am going to mark this as fixed/closed but if we can always circle back to reopen if this pops up again. 

@hdeadman yes SNAPSHOTs are available for all branches.

**Comment by dfish3r** [comment]
@mmoayyed, I should have been clearer. I wasn't stating a fact, but asking a question. Is there a regression/bug in ldaptive that I should take a look at?

**Comment by mmoayyed** [comment]
Gotcha. No I don't think so. I think this all started with this thread:
https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/PyGTeFXU_-U

Which of course you beautifully took care of here:
https://groups.google.com/forum/#!topic/ldaptive/6pF-36w2gyI

In summary, I think we should be good for the time being. I do wonder if CAS should just attempt to set that passivator component to do binds for connection configs that do a bind-and-search, so "things just work" without having to dig deep into this issue and the config. Is that something you would recommend? Right now the default is what ldaptive does of course. 

Thanks for following up.

**Comment by dfish3r** [comment]
> Is that something you would recommend?

Adding the passivator does introduce some latency into the authentication process. Deployers that need the highest level of performance may notice. But in terms of your support costs you may be better off documenting how to disable that feature rather than enable it.

**Comment by mmoayyed** [comment]
Great. Thanks for the tip. Will do.
