### ISSUE TITLE
Make TicketGrantingTicketImpl.getRoot method recursive

### ISSUE THREAD

**Issue by DavidRG13** [apereo/cas#2445]
Hi everyone,

Just noticed that:
```
public TicketGrantingTicket getRoot() {
        TicketGrantingTicket current = this;
        TicketGrantingTicket parent = current.getGrantingTicket();
        while (parent != null) {
            current = parent;
            parent = current.getGrantingTicket();
        }
        return current;
    }
```

could be:
```
TicketGrantingTicket parent = this.getGrantingTicket();
if (parent == null) {
    return this;
}
return parent.getRoot();
```

Am I right? missing something?

**Comment by mmoayyed** [comment]
I think that's fine. I admit the original version is a bit confusing, but I think it's trying to travel up the tree to find the root. You're welcome to clean that up as long you meet the same end goal, but please make sure you accompany the change with [many] test cases. This is a tricky area. 

And thank you for catching this.
