### ISSUE TITLE
Suggestion on TicketGrantingTicketImpl

### ISSUE THREAD

**Issue by DavidRG13** [apereo/cas#2447]
I continue having a look into TicketGrantingTicketImpl, trackServiceSession method:

```
final List<Authentication> authentications = getChainedAuthentications();
service.setPrincipal(authentications.get(authentications.size() - 1).getPrincipal());
```

as far as I can see, getChainedAuthentications() return a list where the root authentication is the last element.
So, the previous 2 lines could be replace by getRoot().getAuthentication(). Am I right?

**Comment by mmoayyed** [comment]
I believe so, yes. If you end up changing and improving this bit, please accompany the patch with a few test cases, specially those perhaps that exercise proxy authn.

**Comment by DavidRG13** [comment]
Could you please point me to that test cases/classes?

**Comment by mmoayyed** [comment]
Sure. Look into `CentralAuthenticationServiceImplTests`
