### ISSUE TITLE
Investigate the use of long instead of ZonedDateTime in Ticket classes

### ISSUE THREAD

**Issue by DavidRG13** [apereo/cas#2448]
With memory footprint in mind, it's not optimal to use ZonedDateTime for creation and lastTimeUsed dates.

But Is there any reason behind this decision? Where is this human format needed?

**Comment by mmoayyed** [comment]
If I remember right, the dates are used in audit logs and reports, events and report, CAS validation payload, various UI gadgets for display purposes, etc. If you are serious about changing the types, consider that we can't quite make the change until CAS 6, and you're going to want to provide some evidence, with numbers, that demonstrates and compares performance improvements.

You may also want to carry this sort of discussion on the mailing list as it's the more appropriate place.
