### ISSUE TITLE
New Feature: Support x509 over REST

### ISSUE THREAD

**Issue by fedon** [apereo/cas#2449]
Currently CAS supports only Username/Password over REST. X509 support is desired to accept public certificate as well.

I have included the following in my report:

- [] CAS server version 5.1-RC2
- [] Container any

**Comment by mmoayyed** [comment]
Thanks for the request. Feel free to submit a pull request to handle this case.

**Comment by PetrGasparik** [comment]
Hi!

PR is shining bright, checkstyle is smiling, Travis is happy, when we can expect this to land in master, master? 🙏

**Comment by dima767** [comment]
Looks 👍 to me

**Comment by mmoayyed** [comment]
Sweet. As soon as you update the docs as well to explain the module, feature, behavior and caveats.
