### ISSUE TITLE
NotSerializableException Exception thrown in state 'getSecurityQuestionsView' of flow 'pswdreset'

### ISSUE THREAD

**Issue by ramostiago** [apereo/cas#2455]
- CAS server version: 5.1.0-RC2
- Tomcat, Java 8, Linux
- After click on link to reset password i have this error:
Link example:
https://localhost:9443/cas/pswdreset?t=eyJhbGciOiJIUzUxMiJ9.WlhsS05tRllRV2xQYVVwRlVsVlphVXhEU21oaVIyTnBUMmxLYTJGWVNXbE1RMHBzWW0xTmFVOXBTa0pOVkVrMFVUQktSRXhWYUZSTmFsVXlTVzR3TGk0NVEwTm5lRzg0Wlc1MlRWRk1WV1pLYUUwM1VGVkJMbTk0ZW5kT1oxOTJjRFV6TkhKeVYySkVOMDFXUkVGeWVHeGpSbE5UYmt3NU1raE5kWEpoWTFKTFExVm9la0YwZDBSRFYwSXdMVFZhTTIxNWFURnBOamg0Tmt4aGFXZEZWMEZIWWtjM0xWZHhRWFF4WVhKVk5FSTRWWEJOWlVWcmJHWktSV040YUdGQ1NISjVTVUp2VkVsNWFUZzFNSGxuVHpNMFlXMTBiM0JzZG05a1lrOHhaV1pzYzJOUU5VMU5hVlZDYW1oelZIbDVUa2t5Um10b05XNHhhVFEzYmt4Q2JWVlhiWGd3WW1vdFpsOHhjV1pIZUVaaWVHTkVjazVETXk1NFIwZE9VRk14VDFCWWRYUjZlWGN0Tms1VGVrMVI.mEgMDNm1ErmJpYqZNqeFkPoGAXZr6-qlv7KLdW3bsi7zqLoFxmd02EXxT5F7eAUpjcjY9nJtO0o8pLPEOpquVw

**Comment by mmoayyed** [comment]
Can you attach full logs please and not just the stacktrace? This doesn't contain enough information to diagnose the issue; it's not clear how you're getting security questions and what operations have led you to this error. Thanks!

**Comment by ramostiago** [comment]
@mmoayyed ,

I am sending my log, cas.properties and a email.

![email](https://cloud.githubusercontent.com/assets/4801901/23996076/f12300aa-0a2a-11e7-9026-33b3847de7dc.png)
[cas.properties.txt](https://github.com/apereo/cas/files/847639/cas.properties.txt)
[cas-2017-03-14-16-4.log.txt](https://github.com/apereo/cas/files/847640/cas-2017-03-14-16-4.log.txt)

**Comment by mmoayyed** [comment]
Thank you, but you may have to redo the logs once more. Please turn on DEBUG logs, run through the sequence and attach again.

**Comment by mmoayyed** [comment]
https://apereo.github.io/cas/development/installation/Troubleshooting-Guide.html#review-logs

**Comment by mmoayyed** [comment]
Though I think I know what the issue is, and I believe I tracked this down and fixed it in master. Should be available in the next snapshot, once Travis picks it up. 
https://travis-ci.org/apereo/cas/builds
