### ISSUE TITLE
Connection pool property is using idle time instead of idle connection count 

### ISSUE THREAD

**Issue by hdeadman** [apereo/cas#2459]
CAS 5.1 -

This line from org.apereo.cas.configuration.support.Beans.java newHickariDataSource method appears wrong:
```
bean.setMinimumIdle(Long.valueOf(jpaProperties.getPool().getMaxIdleTime()).intValue());
```

The javadoc for bean.setMiniumumIdle() is:

"The property controls the minimum number of idle connections that HikariCP tries to maintain in the pool, including both idle and in-use connections. If the idle connections dip below this value, HikariCP will make a best effort to restore them quickly and efficiently. "

The value being passed in is an idle time Duration. It seems like CAS is opening a lot more connections than it needs to and this may be why. There is a another call to bean.setIdleTimeout() which uses a different non-"Duration" property. 

This is unrelated, but another nice property to have on the pool would be bean.setConnectionInitSql(...) b/c it would allow the schema owner and the login user to be different, which some security people like to enforce since schema owners typically have rights to drop all their tables. 

In oracle the init sql might be "alter session set current_schema=cas"
In postgresql the init sql might be "SET search_path TO cas;"

Then CAS could login as cas_user and tables would be found as though they logged in as the schema owner (i.e. cas), assuming they had the correct CRUD privileges. In this case tables would need to be pre-created since cas_user wouldn't have rights to do so.

**Comment by mmoayyed** [comment]
Is this something you can provide a pull request to fix and handle?
