### ISSUE TITLE
SAML2 Attribute Release is inconsistent and uses SAML1 XML tags

### ISSUE THREAD

**Issue by ledermueller** [apereo/cas#2460]
Hi,

I was trying the CAS 5.1.0-RC2 Release to be able to use the fixed RelayState.
After configuring CAS SAML 2 IdP and testing with an ADFS 2.0 as SAML Service Provider there were XML issues.
After some debugging and a lot of configuration changes I found that CAS atm returns Attributes like this:

```
<saml2:Attribute FriendlyName="uid" Name="uid">
    <saml1:AttributeValue xmlns:saml1="urn:oasis:names:tc:SAML:1.0:assertion"
                          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xsd:string">
        user@email
    </saml1:AttributeValue>
</saml2:Attribute>
```

I checked back with CAS 5.0.3.1 and Shibboleth and there I found that attributes are provided this way:
```
<saml2:Attribute Name="uid" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
    <saml2:AttributeValue
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">user@email</saml2:AttributeValue>
</saml2:Attribute>
```

The difference is `<saml1:AttributeValue>` and `<saml2:AttributeValue>`.
ADFS seems really picky with with XML structure and names and won't accept this.

After some code diving I found the following in `AbstractSaml20ObjectBuilder.java` in CAS 5.0.x branch.

```
    /**
     * New attribute statement.
     *
     * @param attributes      the attributes
     * @param setFriendlyName the set friendly name
     * @return the attribute statement
     */
    public AttributeStatement newAttributeStatement(final Map<String, Object> attributes, final boolean setFriendlyName) {

        final AttributeStatement attrStatement = newSamlObject(AttributeStatement.class);
        for (final Map.Entry<String, Object> e : attributes.entrySet()) {
            if (e.getValue() instanceof Collection<?> && ((Collection<?>) e.getValue()).isEmpty()) {
                logger.info("Skipping attribute {} because it does not have any values.", e.getKey());
                continue;
            }
            final Attribute attribute = newSamlObject(Attribute.class);
            attribute.setName(e.getKey());
            
            if (setFriendlyName) {
                attribute.setFriendlyName(e.getKey());
            } 
            
            if (e.getValue() instanceof Collection<?>) {
                final Collection<?> c = (Collection<?>) e.getValue();
                for (final Object value : c) {
                    attribute.getAttributeValues().add(newAttributeValue(value, AttributeValue.DEFAULT_ELEMENT_NAME));
                }
            } else {
                attribute.getAttributeValues().add(newAttributeValue(e.getValue(), AttributeValue.DEFAULT_ELEMENT_NAME));
            }
            attrStatement.getAttributes().add(attribute);
        }

        return attrStatement;
    }
```

In master branch it looks like this:

```
    /**
     * New attribute.
     *
     * @param setFriendlyName       the set friendly name
     * @param e                     the entry to process and turn into a saml attribute
     * @param configuredNameFormats the configured name formats. If an attribute is found in this collection, the linked name format
     *                              will be used.
     * @return the attribute
     */
    protected Attribute newAttribute(final boolean setFriendlyName,
                                     final Map.Entry<String, Object> e,
                                     final Map<String, String> configuredNameFormats) {
        final Attribute attribute = newSamlObject(Attribute.class);
        attribute.setName(e.getKey());

        if (setFriendlyName) {
            attribute.setFriendlyName(e.getKey());
        }
        addAttributeValuesToSamlAttribute(e.getKey(), e.getValue(), attribute.getAttributeValues());

        if (!configuredNameFormats.isEmpty() && configuredNameFormats.containsKey(attribute.getName())) {
            final String nameFormat = configuredNameFormats.get(attribute.getName());
            LOGGER.debug("Found name format [{}] for attribute [{}]", nameFormat, attribute.getName());
            switch (nameFormat.trim().toLowerCase()) {
                case "basic":
                    attribute.setNameFormat(Attribute.BASIC);
                    break;
                case "uri":
                    attribute.setNameFormat(Attribute.URI_REFERENCE);
                    break;
                case "unspecified":
                    attribute.setNameFormat(Attribute.UNSPECIFIED);
                    break;
                default:
                    attribute.setNameFormat(nameFormat);
                    break;
            }
            LOGGER.debug("Attribute [{}] is assigned the name format of [{}]", attribute.getName(), attribute.getNameFormat());
        } else {
            LOGGER.debug("Skipped name format, as no name formats are defined or none is found for attribute [{}]", attribute.getName());
        }

        LOGGER.debug("Attribute [{}] has [{}] value(s)", attribute.getName(), attribute.getAttributeValues().size());
        return attribute;
    }
```

It seems as adding the name format feature also changed the way the xml nodes are created. In master `addAttributeValuesToSamlAttribute(e.getKey(), e.getValue(), attribute.getAttributeValues());` is called which will create a SAML 1 XML tag because it uses:

`org.opensaml.saml.saml1.core.AttributeValue` instead of `org.opensaml.saml.saml2.core.AttributeValue`

in `AbstractSamlObjectBuilder`.

In the 5.0.x branch it created the attributes directly in the `AbstractSaml20ObjectBuilder` which uses the correct `Attributevalue`.

As I couldn't get the CAS workspace running so far I didn't create a PR but I hope the detailed description will help you.
 
Best
-- Robert

**Comment by mmoayyed** [comment]
Thanks. Your analysis is excellent. What seems to be the issue with the workspace setup?

**Comment by ledermueller** [comment]
It is just taking a lot time. Cloning the repo, Resolving the dependencies, etc. And than I have to see how to work with gradle (still an old fashioned maven user).

**Comment by mmoayyed** [comment]
Cool. LMK if I can help with that bit. Some docs are available here:
https://apereo.github.io/cas/developer/Build-Process.html

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.

**Comment by ledermueller** [comment]
Thanks for the link and fix I wasn't able to make it yet - sorry. But I will setup a workspace for the future and test the fix later.

**Comment by mmoayyed** [comment]
Not a problem at all. Consider this a friendly "nudge" in the right direction :) Be sure to post questions to the dev list if you need help getting set up. Works much better if you can diagnose, fix and test. You are 1/3rd of the way in already!

**Comment by mmoayyed** [comment]
@ledermueller Since you indicated that you are using ADFS 2.0 as SAML Service Provider, once you test and get this working, could I ask you to contribute docs, notes and your findings? You can paste them directly here, and I'll can turn them into a blog post here https://apereo.github.io/ Or you can directly write the blog post yourself. That would be a very valuable contribution.

**Comment by ledermueller** [comment]
Sure but I need to get this integration done first.
