### ISSUE TITLE
Acceptable Usage Policy not accepting user choices

### ISSUE THREAD

**Issue by hdeadman** [apereo/cas#2464]
CAS 5.1 current snapshot, I am using X509 auth and LDAP auth (either/or is sufficient for login). If I add acceptable use dependency I can still authenticate with x509 auth but I don't get the acceptable use page before redirect back to the application. If I don't provide client cert and login via LDAP auth then it seems to fail trying to do x509 auth (after successful ldap auth), possibly en-route to the acceptable use page, which doesn't come up. Basically the login fails here: 

```
// X509CertificateCredentialsNonInteractiveAction(AbstractNonInteractiveCredentialsAction).doPreExecute(RequestContext) line: 32	

        final Credential credential = constructCredentialsFromRequest(context);
        if (credential == null) {
            LOGGER.warn("No credentials detected. Navigating to error...");
            return error();
        }
```
```java
X509CertificateCredentialsNonInteractiveAction(AbstractNonInteractiveCredentialsAction).doPreExecute(RequestContext) line: 32	
X509CertificateCredentialsNonInteractiveAction(AbstractAction).execute(RequestContext) line: 186	
ActionExecutor.execute(Action, RequestContext) line: 51	
EvaluateAction.doExecute(RequestContext) line: 77	
EvaluateAction(AbstractAction).execute(RequestContext) line: 188	
ActionExecutor.execute(Action, RequestContext) line: 51	
```

```
2017-03-16 23:29:29,254 WARN [org.apereo.cas.web.flow.AbstractNonInteractiveCredentialsAction] - <No credentials detected. Navigating to error...>
2017-03-16 23:29:29,255 INFO [org.apereo.cas.web.flow.X509CertificateCredentialsNonInteractiveAction] - <Action execution disallowed; pre-execution result is 'error'>
```
 
I can try to fix this but any pointers on getting the programatically modified login webflow in a readable format?

**Comment by mmoayyed** [comment]
Sure' Lets do this in 2 phases. Step 1, lets make sure X509 alone when provided can navigate to AUP and Step 2, lets make sure LDAP-fallback can handle it all the same. They may be related actually, and perhaps once we fix the first the second might also be removed. 

You want to look at the final event that is resolved by X.509 authn flow and make sure it gets routed to AUP. Review the WebflowConfigurer component in X.509 module, and a similar component should exist for AUP. They need to be able to work together in harmony; (perhaps AUP also needs to reinsert its states into the X509 states/transitions, etc)

**Comment by mmoayyed** [comment]
I wrote a blog post a while back that should hopefully provide some insight into how flows are constructed:
https://apereo.github.io/2016/10/07/webflow-extcfg/

It applies to 5.0.x, but the ideas are all the same for 5.1 as well.

**Comment by hdeadman** [comment]
OK thanks. By the way, in 5.0.x it was working slightly better/differently.
The AUP didn't show up for x509 but it did show up for fallback LDAP auth.
Right now if AUP is enabled (along with x509), it seems like the x509 flow
blocks the AUP from showing up and you end up back on the login page.

**Comment by mmoayyed** [comment]
@hdeadman Is this still an issue you're working on? If so, do you think you could prepare a patch/etc by this Friday and if not, shall we push this to 5.1 RC4 instead?

**Comment by hdeadman** [comment]
@mmoayyed I would still like to fix it but some of my free time is being taken up by tiling my parent's floor and doing their taxes, so 5.1 RC4 is probably more realistic. There is also a chance that the work project where I was intending to use CAS 5.x might instead use an existing CAS 4.x installation, but that is up in the air. It's not really my main priority at work and when I do try to work on it it takes a long time to build CAS (because I have been building the whole thing) so I have been thinking about how to increase the velocity of making a change and trying it out. I should probably copy the classes I need to modify into my overlay project and get them working there so I am not having to rebuild CAS.

What are your thoughts on trying to test spring webflow with a unit test? [AbstractXmlFlowExecutionTests](http://docs.spring.io/autorepo/docs/webflow/2.4.2.RELEASE/reference/html/testing.html)

Seems like it might be difficult to do in CAS since the beans are created by the existence of a jar. I would probably have to write the unit test in my overlay project and they don't look very fun to write.

**Comment by mmoayyed** [comment]
All good. Thank you for the update. I moved this over to RC4 for the time being.

Personally, I welcome any and all unit tests. However in this particular case I am not sure `AbstractXmlFlowExecutionTests` would be all that practical because the actual XML webflow definitions are very small, and everything else is injected and configured dynamically at runtime by various modules and jars as you point out. It *might* still work, but I wouldn't bet on it, and you're right; not a very fun thing to do. I generally would attack this under "need to test" banner and I am not quite sure it would be viable for this particular issue.

I might be able to help with the build speed. Now granted, I generally work on the core platform itself (and so my overlay itself is the CAS webapp directly) but there are tricks you can use. For instance, you don't need to build/install everything. Just the modules you care about. Build via `--offline` and in parallel, turn on the daemon and give the build at least 4GB of memory. On my machine, it all gets done in about 2 minutes from top to bottom.
