### ISSUE TITLE
X509 CRL ResourceExpiredPolicy fails

### ISSUE THREAD

**Issue by fedon** [apereo/cas#2466]
I have included the following in my report:

- [] CAS server version 5.0.x
- [] Container/environment type/version Tomcat, Linux
- [] Steps to duplicate the problem along with your CAS settings and properties

cas.authn.x509.revocationChecker=resource
cas.authn.x509.crlResources[0]=file:///path/to/file.crl
cas.authn.x509.crlResourceExpiredPolicy=ALLOW
\# cas.authn.x509.crlResourceExpiredPolicy=THRESHOLD
\# cas.authn.x509.revocationPolicyThreshold=172800

All files are expired.

- [] Stacktraces and CAS logs where appropriate.
2017-03-17 13:50:12,533 ERROR [org.apereo.cas.support.rest.TicketsResource] - <sun.security.x509.X509CRLImpl cannot be cast to java.lang.Void>
java.lang.ClassCastException: sun.security.x509.X509CRLImpl cannot be cast to java.lang.Void
        at org.apereo.cas.adaptors.x509.authentication.revocation.policy.AllowRevocationPolicy.apply(AllowRevocationPolicy.java:15) ~[cas-server-support-x509-5.1.0-RC3-SNAPSHOT.jar:5.1.0-RC3-SNAPSHOT]

DENY throws the same exception instead Security one. THRESHOLD if all files are expired but inside tolerance period renders CRL useless (as if NoOp).

If only some of files are expired they are ignored as if they do not exist regardless of policy.

**Comment by mmoayyed** [comment]
Pass along DEBUG logs please; this will surely require stepping into the code to diagnose the cast issue. Feel free to submit a patch when you figure this out.

**Comment by mmoayyed** [comment]
Also I am not sure you're running 5.0.x, because you're using the REST api and the recent x509 support for it, which only exist in master/5.1, Right?

**Comment by fedon** [comment]
The root cause for the exception is AllowRevocationPolicy and DenyRevocationPolicy implementation. Both have @since 3.4.6 tag. So, it is **not REST** related.
As for unexpected behavior in general it is a result of unlucky design of RevocationPolicy. Relevant code is part of AbstractCRLRevocationChecker which is also marked with @since 3.4.6 tag.
Un/fortunately the code is out of our main path. I'll fix it if/when I'll have time.

**Comment by mmoayyed** [comment]
Cool. Post back when you have the results
