### ISSUE TITLE
Outdated CAS versions "news" on Apereo Website

### ISSUE THREAD

**Issue by robertoschwald** [apereo/cas#2468]
Seems the Apereo Website wasn't updated for ages and still states 4.2.1 as the latest version.

https://www.apereo.org/projects/cas

Unfortunately, thats the topmost hit on Google if you search for "apereo cas server".

**Comment by mmoayyed** [comment]
The content needs to be updated by Apereo staff; it would be best to contact them directly via https://www.apereo.org/content/contact-and-mail-lists
