### ISSUE TITLE
SAML2 InResponseTo missing in SAML response

### ISSUE THREAD

**Issue by ledermueller** [apereo/cas#2476]
I'm using `5.1.0-RC3-SNAPSHOT` and encountered a problem about missing `InResponseTo` attribute during authentication.

I could track the issue down to this part of the code in `AbstractSaml20ObjectBuilder`:

```
    public Response newResponse(final String id, final ZonedDateTime issueInstant,
                                final String recipient, final WebApplicationService service) {

        final Response samlResponse = newSamlObject(Response.class);
        samlResponse.setID(id);
        samlResponse.setIssueInstant(DateTimeUtils.dateTimeOf(issueInstant));
        samlResponse.setVersion(SAMLVersion.VERSION_20);
        setInResponseToForSamlResponseIfNeeded(service, samlResponse);
        return samlResponse;
    }
```
The method `setInResponseToForSamlResponseIfNeeded` from `AbstractSamlObjectBuilder` will only set the `InResponseTo` attribute if the service is of type `SamlService` which I guess isn't true anymore.
In addition the `SamlRegistredService` doesn't contain the `RequestId` anymore but is provided via the String `recipient`. 

```
    public static void setInResponseToForSamlResponseIfNeeded(final Service service, final SignableSAMLObject samlResponse) {
        if (service instanceof SamlService) {
            final SamlService samlService = (SamlService) service;
            final String requestId = samlService.getRequestID();
            if (StringUtils.isNotBlank(requestId)) {
                if (samlResponse instanceof org.opensaml.saml.saml1.core.Response) {
                    ((org.opensaml.saml.saml1.core.Response) samlResponse).setInResponseTo(requestId);
                }
                if (samlResponse instanceof org.opensaml.saml.saml2.core.Response) {
                    ((org.opensaml.saml.saml2.core.Response) samlResponse).setInResponseTo(requestId);
                }
            }
        }
    }
```

I would suggest to set the recipient as `InResponseTo` attribute if it is not null.

I can provide a PR for this if you like.

Best
-- Robert

**Comment by mmoayyed** [comment]
Thank you for your excellent analysis.

>I would suggest to set the recipient as InResponseTo attribute if it is not null. I can provide a PR for this if you like.

I think that's a safe move. Please do. Look forward to the patch.
