### ISSUE TITLE
Setting custom exceptions via cas.properties fails

### ISSUE THREAD

**Issue by dima767** [apereo/cas#2480]
According to https://apereo.github.io/cas/development/installation/Configuration-Properties.html#authentication-exceptions it should take a String list form of FQN exception class names.

In practice, when setting this property like so: `cas.authn.exceptions.exceptions=com.my.CustomAuthnException`

results in ClassCastException at runtime:

```java
...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authenticationExceptionHandler' defined in class path resource 
[org/apereo/cas/config/CasCoreAuthenticationSupportConfiguration.class]: Bean instantiation via factory method failed; nested exception is 
org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apereo.cas.web.flow.AuthenticationExceptionHandler]: Factory method 
'authenticationExceptionHandler' threw exception; nested exception is java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Class

```

The https://github.com/apereo/cas/blob/master/core/cas-server-core-authentication/src/main/java/org/apereo/cas/web/flow/AuthenticationExceptionHandler.java#L100 takes a `List<Class>` , so perhaps some voodoo needs to be done here: https://github.com/apereo/cas/blob/master/core/cas-server-core-authentication/src/main/java/org/apereo/cas/config/CasCoreAuthenticationSupportConfiguration.java#L42 to do the conversion.

**Comment by mmoayyed** [comment]
Appears to be fixed in today's 5.0.5 snapshots.
