### ISSUE TITLE
OAuth2 / OIDC access token isn't invalidated on logout

### ISSUE THREAD

**Issue by pkolaric** [apereo/cas#2489]
After logging out of CAS SSO Session (/cas/logout),  any OAuth2 or OIDC access token created by that session doesn't get invalidated and is still reported as valid on 
OAuth2 profile endpoint  /cas/oauth2.0/profile or OIDC endpoint /cas/oidc/profile

Tested on 5.0.4 and 5.1.0-RC2

Steps to reproduce:

1.  sign on via OAuth2 implicit flow /cas/oauth2.0/authorize?response_type=token&client_id=clientid&redirect_uri=http%3A%2F%2Fhello
or
 OIDC implicit flow (5.1.0-RC2)  /cas/oidc/authorize?response_type=token&client_id=clientid&redirect_uri=http%3A%2F%2Fhello

1. validate the access token via /cas/oauth2.0/profile?access_token= or /cas/oidc/profile?access_token=
1. logout 
1. re-validate the same access token.  It will still be reported as valid.

**Comment by mmoayyed** [comment]
Excellent diagnosis. 

Are you prepared to submit a pull request to resolve the issue?

**Comment by pkolaric** [comment]
I've only briefly checked the code. It seems that AT tickets' life cycle is completely unaware of TGT.  I think that the AT tickets should behave the same way as service tickets (TicketGrantingTicketImpl.trackServiceSession..) but i'm not very familiar with the overall design to be certain.

Short-term wise i don't have the free time nor an excuse to commit to the task (we're not using CAS yet, just evaluating it), but i'll try to help if nobody else beats me to it :)

**Comment by mmoayyed** [comment]
Excellent. Thanks for the response. It's very unlikely that someone might beat you to this :) I'll go ahead and get this issue closed for the time being, but as soon as you find the time and your deployments moves in a more serious direction, please circle back so we can revisit the issue and make some progress. And thanks again for raising and documenting the issue here.
