### ISSUE TITLE
Docker Latest Tag

### ISSUE THREAD

**Issue by madhavajay** [apereo/cas#2491]
Hi,
The instructions here on docker hub don't work because there is no "latest" tag:
https://hub.docker.com/r/apereo/cas/

```
docker pull apereo/cas
```

Please push the latest version tagged as "latest" and make it part of the docker build and push process.

**Comment by mmoayyed** [comment]
Please move the issue to the CAS docker repository: https://github.com/apereo/cas-webapp-docker
