### ISSUE TITLE
Missing Recipient in SAML2 Response - SubjectConfirmationData

### ISSUE THREAD

**Issue by ledermueller** [apereo/cas#2496]
After some tests with CAS (5.1.0-RC3-SNAPSHOT) as SAML 2 IdP and SAP as SAML 2 SP we encountered that SAP demands the `Recipient` attribute within the `SubjectConfirmationData`. Even if SAP is complaining about an invalid `NotBefore` attribute we could find out in the SAP code that the Expression lead to this Exception also checks that a `Recipient` is present :see_no_evil: 

After some investigation of the CAS code I found out that CAS tries to use the `AssertionConsumerServiceURL` from the `AuthNRequest`. I didn't check the SAML 2 spec and I'm not sure what is the right handling here.

I did read [1] that the `Recipient` is mandatory if the Assertion is signed during the investigation of the SAP issue.

So probably the `Recipient` in the `SubjectConfirmationData` should be the same as the  `Destination` of the SAML Response. In fact SAP is accepting my CAS SAML response if it is set that way.

I found that the `Destination` is determined in the `SamlIdPUtils.preparePeerEntitySamlEndpointContext()`. Here the first `AssertionConsumerService` is used without any checking. This might be the problem of #2493 as the same method is used to build the `MessageContext` for the SOAP binding too, if I followed the code correctly (not that easy because all the different builder using the same interface).

```
        final Endpoint endpoint = assertionConsumerServices.get(0);
        if (StringUtils.isBlank(endpoint.getBinding()) || StringUtils.isBlank(endpoint.getLocation())) {
            throw new SamlException("Assertion consumer service does not define a binding or location for " + adaptor.getEntityId());
        }
```

So I'm not really sure what's the best way to fix the missing recipient in the `Subject` as I don't want to duplicate this logic which may differ in the near future.

```
    private Subject buildSubject(final HttpServletRequest request,
                                 final HttpServletResponse response,
                                 final AuthnRequest authnRequest, final Assertion assertion,
                                 final SamlRegisteredService service,
                                 final SamlRegisteredServiceServiceProviderMetadataFacade adaptor) throws SamlException {
        final NameID nameID = this.ssoPostProfileSamlNameIdBuilder.build(authnRequest, request, response, assertion, service, adaptor);
        final String recipient = adaptor.getAssertionConsumerService().getLocation();
        final ZonedDateTime validFromDate = ZonedDateTime.ofInstant(assertion.getValidFromDate().toInstant(), ZoneOffset.UTC);
        final Subject subject = newSubject(nameID.getFormat(), nameID.getValue(),
                recipient,
                validFromDate.plusSeconds(this.skewAllowance),
                authnRequest.getID());
        subject.setNameID(nameID);
        return subject;
    }

```

Best
-- Robert

[1] https://lists.oasis-open.org/archives/saml-dev/200711/msg00002.html

**Comment by mmoayyed** [comment]
> Here the first AssertionConsumerService is used without any checking. This might be the problem of #2493 as the same method is used to build the MessageContext for the SOAP binding too

Yes. You want to handle this one as well? You could use the same solution provided here https://github.com/apereo/cas/commit/94fa16a7920ff1fbc0a4ff8d7be41d575d6883cc#commitcomment-21554165 though it still needs a bit of work. 

I'll take a look at this bit:
> So probably the Recipient in the SubjectConfirmationData should be the same as the Destination of the SAML Response. 

Sound good?

**Comment by mmoayyed** [comment]
I ran a quick test after a few changes, and here is what I see:

```xml
<?xml version="1.0" encoding="UTF-8"?><saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" 
Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" Destination="https://mmoayyed.unicon.net:9443/sp/saml/SSO" 
ID="_5335885234031651031" InResponseTo="a1fb1a0b96j5134c3f14ebafgbe4600"
 IssueInstant="2017-03-30T11:22:31.484Z" Version="2.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" 
Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://mmoayyed.unicon.net:8443/idp</saml2:Issuer>

...

   <saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="_1341558091995025942" 
IssueInstant="2017-03-30T11:22:12.867Z" Version="2.0">
      <saml2:Issuer>https://mmoayyed.unicon.net:8443/idp</saml2:Issuer>
      <saml2:Subject>
         <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">casuser</saml2:NameID>
         <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
            <saml2:SubjectConfirmationData InResponseTo="a1fb1a0b96j5134c3f14ebafgbe4600" NotOnOrAfter="2017-03-30T11:22:12.853Z" 
Recipient="https://mmoayyed.unicon.net:9443/sp/saml/SSO"/>
         </saml2:SubjectConfirmation>
      </saml2:Subject>
     ...
</saml2p:Response>
```

Is this good?

**Comment by mmoayyed** [comment]
Fixed via https://github.com/apereo/cas/commit/b21d7be6ee00c60a62c0e1fd203574615a1151ac and family.

**Comment by mmoayyed** [comment]
When you get a chance, please confirm this and if the issue persists, we can investigate further.

**Comment by ledermueller** [comment]
Thanks for the quick response and solution! I have to work on another project the rest of the day but I will try to test it in the evening and will report back any finding.

**Comment by ledermueller** [comment]
Tested with SAP and ADFS 2.0 and everything seems to work.
Thank you very much. Now lets see that I get some notes together for contribution :)

**Comment by mmoayyed** [comment]
Excellent. Thanks. This seems like the ideal location for the notes: https://apereo.github.io/ or all other mediums are fine too!

**Comment by mmoayyed** [comment]
How are the docs coming along @ledermueller ? Any updates?

**Comment by ledermueller** [comment]
Nope, not yet - sorry.

**Comment by yuzhiquan** [comment]
Does this issue fixed?
I use lastest relase v5.0.5, receive request from SAP system, everything looks like ok,and the response for the request build ok, but SAP system raise an exception,like this:
```bash
Caused by: CX_SAML20_ASSERTION:  element  'SubjectConfirmationData'  attribute  'NotBefore' is invaild. 
```
