### ISSUE TITLE
Build Failed: Could not get unknown property 'java' for project ':api' of type org.gradle.api.Project

### ISSUE THREAD

**Issue by raphaelAME** [apereo/cas#2499]
Hello, 

I try to build cas-5.0.4 on debian Jessie, but it fail . When i launch` dev-build.sh` (I suppose that's I have to do... ) I can see the following message :

> Skipping pom generation for [cas-server-support-bom], letting it create <dependency-management> entries.

> The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_4esrtn6p9k9tmsgtqicfsdbe1$_run_closure5.doCall(/root/cas-5.0.4/build.gradle:87)

> FAILURE: Build failed with an exception.

>  Where: Build file '/root/cas-5.0.4/build.gradle' line: 179

>  What went wrong:

> A problem occurred evaluating root project 'cas-server'.
> Could not get unknown property 'java' for project ':api' of type org.gradle.api.Project.

> BUILD FAILED

And not know which Info are needed, but here the output of javac -version: `javac 1.8.0_121`

I attach the list of .deb which are installed on mys debian Jessie. 

What can I do? Where can i found more documentation?

**Comment by mmoayyed** [comment]
https://apereo.github.io/cas/developer/Build-Process.html

**Comment by vistier** [comment]
修改build.gradle文件中206行

```
def currentTime = java.time.ZonedDateTime.now()
```

改成

```
// def currentTime = java.time.ZonedDateTime.now()
    def currentTime = new Date().format("yyyy-MM-dd", TimeZone.getTimeZone("UTC"))
```
