### ISSUE TITLE
CAS 5.0 first auth request very slow to respond 

### ISSUE THREAD

**Issue by hsj1606** [apereo/cas#2503]
When I restart the CAS server, it will cost 3-4 minutes to respond the request (only the first request per user after server restart). The server log at this line: 

DEBUG [org.springframework.webflow.engine.ViewState] - <Entering state 'viewLoginForm' of flow 'login'>

after 3-4 minutes , it will print:

DEBUG [org.springframework.webflow.engine.impl.FlowExecutionImpl] - <Assigned key ***

**Comment by mmoayyed** [comment]
Thank you for the issue report. Please investigate further and diagnose the issue, and then preferably provide a patch that fixes the problem.

**Comment by hsj1606** [comment]
Solved. Add system property: -Djava.security.egd=file:/dev/./urandom
