### ISSUE TITLE
Case Insensitive tooltip error in CAS Services Management app

### ISSUE THREAD

**Issue by karlgrose** [apereo/cas#2509]
CAS server version: (Management app from the 5.0.4 tree)
Container/environment type/version (Java, OpenJDK 1.8.0_121)

Steps to duplicate the problem:

Hover mouse over the ? symbol next to the "Case Insensitive" item in the Services Management app UI. See the wrong tooltip text (duplicates the tooltip for the item above, the Unauthorized Redirect Url).

I suspect that the code in this source file:

    /cas/webapp-mgmt/cas-management-webapp/src/main/resources/templates/fragments/serviceform/accessstrategy.html

has mixed up the text to be displayed.

**Comment by mmoayyed** [comment]
Via https://github.com/apereo/cas/commit/edd13bf52ed62e4fbc9eae796dca828b0f541561
