### ISSUE TITLE
ldap build fails - Dn format cannot be empty/blank (baseDn config is given in cas.properties)

### ISSUE THREAD

**Issue by jphilipsen05** [apereo/cas#2512]
I am deploying a docker container using the github apereo/cas-docker-webapp. It pulls from apereo/cas-overlay-template and I make these following changes:

added to pom.xml which places the ldap dependency in the pom file:
```
sed -i '/<\/dependency>/a\
        <dependency>\
            <groupId>org.apereo.cas</groupId>\
            <artifactId>cas-server-support-ldap</artifactId>\
            <version>${cas.version}</version>\
        </dependency>' /cas-overlay/pom.xml
```

for cas.properties:

```
cas.server.name: https://localhost:8443
cas.server.prefix: https://localhost:8443/cas

cas.adminPagesSecurity.ip=127\.0\.0\.1

logging.config: file:/etc/cas/config/log4j2.xml

cas.authn.ldap[0].type=AD
cas.authn.ldap[0].ldapUrl=ldap://company.com:389
cas.authn.ldap[0].useSsl=false
cas.authn.ldap[0].useStartTls=false
cas.authn.ldap[0].baseDn=DC=place,DC=holder,DC=com
```

note: I am using ldap for testing and will move it to ldaps once I get it running. 

Everytime that I run the build I get "Dn format cannot be empty/blank for active directory authentication" If I take out the baseDn=... in my cas.properties the build says baseDn is not specified and moves on.

I'm not sure how to fix this. I have even tried using the exact cas.properties from the documentation and it does not work. I can't get past this error for type=AD. I did put in tyep=AUTHENTICATION, but I am using my windows AD box and want to authenticate with the sAMaccount info.

I'm sorry if this is an easy fix, but I have spent a couple days researching the error in the attached log file and have not found a solution. 

Thanks!

I have included the following in my report:

- [5.0.4] CAS server version
- [x] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
- [x] Steps to duplicate the problem along with your CAS settings and properties
- [X] Stacktraces and CAS logs where appropriate.
- [ ] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

[casbuild.txt](https://github.com/apereo/cas/files/903860/casbuild.txt)

**Comment by mmoayyed** [comment]
> I'm not sure how to fix this. 
I am not sure why you are not sure :) The error is telling you that you have not defined a dnFormat and that the type of authentication you are using/after requires a dnFormat. You insist that you have played around with baseDn. That has nothing to do with what the error is describing to you. A dnFormat is not the same thing as the baseDn.

> I have even tried using the exact cas.properties from the documentation and it does not work. 

You have not. There is nothing in your collection of settings that describes a dnFormat, as the error is asking. 

> I'm sorry if this is an easy fix, but I have spent a couple days researching the error in the attached log file and have not found a solution.

Again, I am not sure why. All you need to do is, review the error message carefully, apply the thing it's asking for that is missing and then take a look at the source code and locate the error message and trace the conditions back. That's the beauty of open source. The source is open.

**Comment by mmoayyed** [comment]
The log is also telling you where to look:

```
Caused by: java.lang.IllegalArgumentException: Dn format cannot be empty/blank for active directory authentication
	at org.apereo.cas.config.LdapAuthenticationConfiguration.getActiveDirectoryAuthenticator(LdapAuthenticationConfiguration.java:270)
```

So you look at `LdapAuthenticationConfiguration`, function `getActiveDirectoryAuthenticator` at line 270 and you can see what the code is doing. 

The error is saying that it needs a DN Format because you have opted to using the AD authentication type. So, if you go over here:
https://apereo.github.io/cas/5.0.x/installation/Configuration-Properties.html#ldap-authentication

...and look for dnFormat, you'll find the setting. Adjust that for your AD environment and you should be up and running.

I hope that makes sense, and serves a recipe for future troubleshooting.
