### ISSUE TITLE
NPE in ThreadContextMDCServletFilter

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2515]
The fix you committed in ceee39d78215c9aca11c4d83b0a255a6fa57c04f doesn't work correctly.

ThreadContextMDCServletFilter can still throw an exception when request.getAttribute(a) is null, because of the toString conversion:
```
Collections.list(request.getAttributeNames())
    .forEach(a -> addContextAttribute(a, request.getAttribute(a).toString()));
```

**Comment by mmoayyed** [comment]
Thanks for the catch! via https://github.com/apereo/cas/commit/eed44f363c6b351883a7aee1c2d5356172f56526
