### ISSUE TITLE
When name missing in service json

### ISSUE THREAD

**Issue by cifren** [apereo/cas#2517]
Hi,

I encountered a bug on services, not really a bug actually it is more a missing error handler. 

When name is missing, the log system and error handler doesn't catch it, and displays an error not really helpful about it : 'null' of flow 'login' -- action execution attributes were 'map[[empty]]'"

Related GG discussion https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/qN0VH9zzj14

**Comment by mmoayyed** [comment]
Closed via #2516

**Comment by cifren** [comment]
This ticket was to maybe add a handler into the code in order to tell the user that the name was maybe missing into the config file

**Comment by mmoayyed** [comment]
We could certainly consider that, but I tend to think that's more of a documentation issue; otherwise if you feel like you want to work on this by all means file a pull request any time.
