### ISSUE TITLE
JPA service registry: uninitialized "canonicalizationMode" causes NPEs

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2518]
I recently upgraded from 5.1.0-RC2 to the latest 5.1.0-RC4-SNAPSHOT.

I use a JPA service registry and the content of the registry was filled using the cas-management application.

The problem is that the USERNAME_ATTR field contained a serialized DefaultRegisteredServiceUsernameProvider without the canonicalizationMode field introduced in commit d3e15992ef4aa2dce45c435709a81d432f592b16, so it was initialized with null.
This made it impossible to validate a ticket, because this would result in a NPE in BaseRegisteredServiceUsernameAttributeProvider.resolveUsername. Which also made it impossible to login to the cas-management application to fix this.

I had to clear the existing service registry and recreate it by hand.

Could you either:
1. Support 0-initialized values for all newly introduced fields, or
2. Implement some kind of upgrade system for the service registry?

**Comment by mmoayyed** [comment]
Absolutely. Your first suggestion is probably what we should do, because adding a new field should never result in BC issues or NPEs for that matter. I wish you hadnt cleared the registry, because I could use your help testing fixes.

**Comment by mmoayyed** [comment]
This should be taken care of. Please confirm when you get the chance.
