### ISSUE TITLE
No attributes from REST authentication response

### ISSUE THREAD

**Issue by bjoernHeneka** [apereo/cas#2520]
Hi together, 

I'm using the CAS server v5.0.4 with REST authentication. 
The response of the auth request looks fine and authentication works. 
I just don't get the attributes set to the principle. 

- CAS server version: 5.0.4
- Container/environment type/version: cas-overlay-docker on debian jessie
- Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

**Comment by mmoayyed** [comment]
You will either need to set up person directory to get attributes, or you of course need to mod the code to accept attributes from the response. Examine the master branch and I believe you'll find a solution in this area. Work that into the 5.x branch and then submit a PR please. 

Thanks for raising this issue.
