### ISSUE TITLE
TGC Cookie without "Httponly" Flag

### ISSUE THREAD

**Issue by ale68es** [apereo/cas#2524]
- CAS server version: 5.0.3.1
- Container/environment type/version : tomcat 8 and Java 1.8
- Steps to duplicate the problem along with your CAS settings and properties
- Stacktraces and CAS logs where appropriate.
- Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/

By default, the TGC cookie does not have the "HttpOnly" flag. If the application (with CAS) had an
XSS vulnerability, someone could inject JS and read the TGC cookie and send it to the CAS server,
even if it is encrypted and signed, the CAS server will not know that this TGC cookie is from an
attacker. Currently I see a security problem. The ideal would be to have a variable that will 
configure whether or not to use the "httponly" flag for the TGC cookie.
Thanks you very much.

**Comment by mmoayyed** [comment]
The CAS server will know and reject the cookie specially because it's signed and encrypted and specially because the cookie is linked to the server.

This is also handled in 505.
