### ISSUE TITLE
Unable to get authentication against Active Directory working

### ISSUE THREAD

**Issue by heinlja** [apereo/cas#2525]
Hello,

I'm trying to get authentication against Active Directory (i.e. over LDAP)  to work.
I have a CAS overlay version 5.0.2 running on Tomcat 8.

In pom.xml I have included the required LDAP dependency:
```xml
        <dependency>
            <groupId>org.apereo.cas</groupId>
            <artifactId>cas-server-support-ldap</artifactId>
            <version>${cas.version}</version>
        </dependency>
```

The following configuration against a lightweight LDAP server works nicely and I am able to authenticate users:
```properties
cas.authn.ldap[0].type=AUTHENTICATED
cas.authn.ldap[0].ldapUrl=ldap://localhost:8389
cas.authn.ldap[0].useSsl=false
cas.authn.ldap[0].connectTimeout=5000
cas.authn.ldap[0].baseDn=ou=people,dc=acer,dc=eu
cas.authn.ldap[0].bindDn=uid=ldap_test_user,ou=people,dc=acer,dc=eu
cas.authn.ldap[0].bindCredential=secret
cas.authn.ldap[0].principalAttributeId=uid
cas.authn.ldap[0].principalAttributePassword=userPassword
cas.authn.ldap[0].userFilter=uid={user}
```

Then I tried authentication against an Active Directory, with configuration like this:
```properties
cas.authn.ldap[0].type=AD
cas.authn.ldap[0].ldapUrl=ldap://192.168.0.2:3268
cas.authn.ldap[0].useSsl=false
cas.authn.ldap[0].useStartTls=false
cas.authn.ldap[0].connectTimeout=5000
cas.authn.ldap[0].baseDn=OU=people,DC=rkas,DC=rk
cas.authn.ldap[0].bindDn=MYDOMAIN\\ldapUser
cas.authn.ldap[0].bindCredential=******
cas.authn.ldap[0].principalAttributeId=sAMAccountName
cas.authn.ldap[0].principalAttributePassword=userPassword
cas.authn.ldap[0].principalAttributeList=sAMAccountName,uid
cas.authn.ldap[0].userFilter=sAMAccountName={user}
cas.authn.ldap[0].dnFormat=sAMAccountName=%s
```

And it fails with following message in log:
```ssh
04-12 17:55:36,831 WARN [org.apereo.cas.authentication.PolicyBasedAuthenticationManager] - <Authentication has failed.
            Credentials may be incorrect or CAS cannot find authentication handler that supports [jaanus.heinlaid] of type [UsernamePasswordCredential],
            which suggests a configuration prob
04-12 17:55:36,838 INFO [org.apereo.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN
========================================================
jaanus.heinlaid
 Supplied credentials: [jaanus.heinlaid]
N: AUTHENTICATION_FAILED
CATION: CAS
 Wed Apr 12 17:55:36 EEST 2017
T IP ADDRESS: 0:0:0:0:0:0:0:1
R IP ADDRESS: 0:0:0:0:0:0:0:1
========================================================
```

So it's clear that connection to LDAP works, but authentication of users fails.
Now, I have tried with numerous options and values for the above properties.
I've tried all I could find in Apereo CAS configuration README. And I've googled for hours for possible solution, but still no luck.

Could somebody suggest what might be wrong?
This would be greatly appreciated!

Thank you!

**Comment by mmoayyed** [comment]
Please see https://apereo.github.io/cas/development/installation/Troubleshooting-Guide.html

**Comment by mmoayyed** [comment]
Also see https://apereo.github.io/cas/development/planning/Security-Guide.html#announcements

**Comment by tfrancois** [comment]
How was this resolved? I am having the issue authenticating with my AD server using 5.1.0-RC3-SNAPSHOT.  Thanks in advance.

**Comment by tfrancois** [comment]
It appears as if leaving everything unchanged while connecting to Active Directory via LDAP works with:

cas.authn.ldap[0].type=AUTHENTICATED

...as previously indicated.  Changed the value to 'AD' generates an error.  Not sure why...but previously value works.

**Comment by heinlja** [comment]
Finally got this working.
`cas.authn.ldap[0].type=AUTHENTICATED` did not help me in any way. I had to leave it `=AD`

The trick was in `cas.authn.ldap[0].dnFormat`.

First of all, I found no place in documentation that would hint that this is a required attribute in order for authentication againast AD to work. Later it found it here: #2402.

Secondly, there is also no clear hint about what's the expected value of that attribute. In my case (authenticating against a very standard Active Directory instance) it turned out that the value had to match the format of "userPrincipalName" attribute in Active Directory. More precisely, in my case the value had to be "%s@mycompany.com" where `%s` is the login name user has provided in login window.
So in my AD, the values of "userPrincipalName" attribute are like "login_name@mycompany.com".

So it works, but the documentation requires some hints on this.

These are the "cas.authn.ldap[0].*" properties that finally got it working for me:
(not sure if _all_ of them are required, but I don't dare to touch any more)

```properties
cas.authn.ldap[0].type=AD
cas.authn.ldap[0].ldapUrl=ldap://192.168.0.2:3268
cas.authn.ldap[0].useSsl=false
cas.authn.ldap[0].useStartTls=false
cas.authn.ldap[0].connectTimeout=5000
cas.authn.ldap[0].baseDn=OU=My organisation,DC=myorg,DC=ee
cas.authn.ldap[0].bindDn=MYORG\\myuser
cas.authn.ldap[0].bindCredential=mypassword
cas.authn.ldap[0].principalAttributeId=sAMAccountName
cas.authn.ldap[0].principalAttributePassword=unicodePwd
cas.authn.ldap[0].principalAttributeList=sAMAccountName,sn,cn
cas.authn.ldap[0].userFilter=(sAMAccountName={user})
cas.authn.ldap[0].dnFormat=%s@mycompany.com
cas.authn.ldap[0].allowMultiplePrincipalAttributeValues=true
cas.authn.ldap[0].subtreeSearch=true
cas.authn.ldap[0].usePasswordPolicy=false
cas.authn.ldap[0].failFast=false
```

**Comment by jhitt25** [comment]
For reference, here is our configuration:

```
cas.authn.ldap[0].type=AD
cas.authn.ldap[0].ldapUrl=ldaps://ourdomain.org
cas.authn.ldap[0].usePasswordPolicy=false
cas.authn.ldap[0].dnFormat=%s@ourdomain.org
cas.authn.ldap[0].baseDn=unused
cas.authn.ldap[0].userFilter=unused
```

This configuration allows us to have login form based authentication against our AD infrastructure, for any valid user.
