### ISSUE TITLE
IE maximum URL length

### ISSUE THREAD

**Issue by todd-pratt** [apereo/cas#2526]
CAS Version: 5.0.3.1
Container: Tomcat 8.5 on Linux

When clicking the link on the login message view in IE it gets truncated after 2083 characters, which is the limit IE has with URL's.  To fix this issue with I updated the casLoginMessageView.html file to post a form instead.  Below is a link to the update.

[casLoginMessageView.html.zip](https://github.com/apereo/cas/files/917581/casLoginMessageView.html.zip)

**Comment by mmoayyed** [comment]
Thanks. I applied the fix to master. You're more than welcome to submit a pull request for the 5.0.x branch as well.
