### ISSUE TITLE
AuthenticationTransaction#service null

### ISSUE THREAD

**Issue by jaantark** [apereo/cas#2534]
Scenario:
* CAS 5.0.4 maven overlay with no additional configuration
* Log in providing a service, e.g.: .../login?service=https://www.apereo.org
(* Use static username/password)

AuthenticationResultBuilder gets constructed (with no information about the service).
https://github.com/apereo/cas/blob/v5.0.4/core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/resolver/impl/InitialAuthenticationAttemptWebflowEventResolver.java#L45

This will cause AuthenticationTransaction to null the service associated with the transaction:
https://github.com/apereo/cas/blob/v5.0.4/api/cas-server-core-api-authentication/src/main/java/org/apereo/cas/authentication/AuthenticationTransaction.java#L61

It will be later picked up here:
https://github.com/apereo/cas/blob/v5.0.4/core/cas-server-core-authentication/src/main/java/org/apereo/cas/authentication/RegisteredServiceAuthenticationHandlerResolver.java#L34

Service being nulled by AuthenticationTransaction will render the following if-block useless - which is essential in implementing the following feature - which I can't seem to get working properly:
cas.authn.policy.requiredHandlerAuthenticationPolicyEnabled=true

**Comment by dima767** [comment]
It's been fixed in the `master`: https://github.com/apereo/cas/blob/master/core/cas-server-core-webflow/src/main/java/org/apereo/cas/web/flow/resolver/impl/InitialAuthenticationAttemptWebflowEventResolver.java#L68
