### ISSUE TITLE
Management Application requires server.contextPath

### ISSUE THREAD

**Issue by rfrovarp** [apereo/cas#2537]
For CAS 5.0.4, the management application requires that server.contextPath be set in the application.properties file.

If it isn't, it will NPE on line 391 in cas/webapp-mgmt/cas-management-webapp-support/src/main/java/org/apereo/cas/mgmt/config/CasManagementWebAppConfiguration.java. The concat() call does a length call on what is passed in to it.

I'm guessing there is a better way to get the context path than via that call. The issue is that the documentation states that property is for the embedded Tomcat. If I deploy in my own Tomcat, I'm under the impression that I shouldn't need any of those attributes that start with "server". And it appears that the only one required is that one.

**Comment by mmoayyed** [comment]
I had a look and I don't think we can find a better way to to identify the context path, just yet. Ran a few experiments and they all ended up uglier than setting a single prop. If you find a better way, by all means please post back a PR. Thanks for the report!

**Comment by rfrovarp** [comment]
How about creating a cas.mgmt.contextPath property? You could then document it in the list of properties for the management application. Right now the documentation states: "The following properties are related to the embedded Tomcat container that ships with CAS." That's true for every property in the list except for this one which is also required here.

**Comment by mmoayyed** [comment]
That is the same thing as `server.contextPath` surely; So what you have in mind seems like more of a documentation issue.  We could just document: Please remember to set `server.contextPath` etc
