### ISSUE TITLE
How to validate accessToken from spring security oauth application ( as a Resource Server)?

### ISSUE THREAD

**Issue by stefli** [apereo/cas#2547]
CAS version 5.0.4

Cas as Authentication Server, and a spring security oauth application as Resource Server.
In the Spring security application, there is a RemoteTokenServices(org.springframework.security.oauth2.provider.token.RemoteTokenServices) to validate the accessToken from Authentication Server, now i configured the checkTokenEndpointUrl with "http://casserver/profile".

But, the Spring requires the response should contain below properties:
![image](https://cloud.githubusercontent.com/assets/56305/25321374/b542afd4-28e0-11e7-8e14-f2b7418a1d9d.png)

How can i make it works, make the Resource Server works with Cas?
Using OIDC or JWT?
Any suggestion, thanks.

**Comment by leeyc0** [comment]
It is the scope of OAuth2 token introspection (RFC 7662), however it is unimplemented in CAS. Correct me if wrong.

Another method I can think of is checking directly with ticket storage backend, if you are using some sort of database...

**Comment by leeyc0** [comment]
Or the resource server uses this ticket to check /oauth2/profile endpoint, if it success you would assume this ticket is valid, I don't know if this it have any security issue...

**Comment by stefli** [comment]
There is a blog that described how to solve the issue like what you said.
[http://blog.arnoldgalovics.com/2017/02/05/google-oauth-with-spring-security-as-separated-resource-server/](http://blog.arnoldgalovics.com/2017/02/05/google-oauth-with-spring-security-as-separated-resource-server/)

But any safe problem? i don't know.

**Comment by leeyc0** [comment]
https://developers.google.com/identity/protocols/OAuth2UserAgent
Actually it is the Google way to validate ticket, but seems CAS do not have expiry information

**Comment by mmoayyed** [comment]
Access tokens are passed to the /profile endpoint. You may start there.
