### ISSUE TITLE
Services management RFE: required attributes UI should match that of rejected attributes

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2550]
Version: 5.1.0-RC4-SNAPSHOT

## Issue

The possible required attributes for the service access strategy are currently predefined in the application.properties file of the cas-management application:

```
cas.authn.attributeRepository.stub.attributes.uid=uid
cas.authn.attributeRepository.stub.attributes.displayName=displayName
cas.authn.attributeRepository.stub.attributes.cn=commonName
cas.authn.attributeRepository.stub.attributes.affiliation=groupMembership
cas.authn.attributeRepository.stub.attributes.lastName=lastName
cas.authn.attributeRepository.stub.attributes.firstName=firstName
cas.authn.attributeRepository.stub.attributes.givenName=givenName
```

However, my CAS instance is configured to return the following attributes:
`uid, sn, title, mail, telephoneNumber, mobile, manager, roles`
 
Currently, my only option is to add or replace these attributes in my own cas-management config file, but I can't remove the ones that are not used (unless setting one of the above properties to an empty string would do that).

## Suggestion

It would be much more elegant if the the UI for required attributes in the cas-management application would be the same as for rejected attributes (start with an empty list and allow me to specify my own required attributes).

**Comment by mmoayyed** [comment]
> my only option is to add or replace these attributes in my own cas-management config file, but I can't remove the ones that are not used 

I am not sure I understand your last statement. Why can't you remove those? If `application.properties` file of the cas-management application controls those attributes, they should have no impact to CAS behavior right? Or do I misunderstand?

**Comment by mmoayyed** [comment]
> It would be much more elegant if the the UI for required attributes in the cas-management application would be the same as for rejected attributes (start with an empty list and allow me to specify my own required attributes).

I think this is a very good suggestion. We can surely track this for a release beyond 5.1, given there's no time left really unless you want to take up the UI work yourself.

**Comment by mmoayyed** [comment]
pinging @mindblender as well to debate possible options and ideas.

**Comment by Condor70** [comment]
Yes, I can change application.properties (I actually am doing that), but application.properties is an integral part of the application and imho should not be modified.

(and especially because I'm currently using the snapshot release, the application.properties file could change every day)

**Comment by mmoayyed** [comment]
Gotcha. 

I believe you can externalize your configuration of the management app much in the way you can do so with CAS itself. Either in etc/cas/config or some such, define your own properties file and keep changes there. 

You should never change or overlay the embedded application.properties file. That simply leads to issues down the line as you noted.

**Comment by Condor70** [comment]
That is exactly my point. When using an external properties file it is not possible to remove properties that are already defined in application.properties.

**Comment by mmoayyed** [comment]
Ah, I understand. We surely could remove the defaults; you're totally right.

**Comment by mmoayyed** [comment]
The defaults are removed and you should no longer have to put in special overrides to remove those. 
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.

**Comment by Condor70** [comment]
This would also mean modifying the Attribute Release policy UI (because attributes would no longer be predefined).

**Comment by mmoayyed** [comment]
Reviewed this option some more; For the time being we are going to stick with pre-defined attributes in config files and can revisit this later.
