### ISSUE TITLE
CAS SSO Status

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2551]
Version: 5.1.0-RC4-SNAPSHOT

The CAS status dashboard contains an "SSO Status" link to /cas/status/sso, but this url is not handled and returns an HTTP 410 error.

**Comment by mmoayyed** [comment]
This is likely a config issue on your part. See https://jasigcas.herokuapp.com/cas/status/sso and https://jasigcas.herokuapp.com/cas/status/dashboard

**Comment by Condor70** [comment]
I don't understand. The link you posted behaves exactly the same and returns a HTTP 410 error!

**Comment by mmoayyed** [comment]
Something must be interfering with that http request, because I surely can get to the URL:

![image](https://cloud.githubusercontent.com/assets/1205228/25341415/9ad8a2f2-28bd-11e7-9ca4-fa14d7990fc5.png)

Watch your logs, in particular Spring Boot and Spring Security.

**Comment by Condor70** [comment]
You are getting the same response as I! This page has a HTTP error status 410 code (try opening it with Internet Explorer).

**Comment by Condor70** [comment]
Also, what is this page supposed to display? Is it really supposed to just display "no"?

**Comment by mmoayyed** [comment]
Ah I see! I understood your original issue report to be: "I can't get to the page because it's 410 and gone" :) So ok, we have a bit of a "lost in translation" issue here!

So 410 I think intends to explain that there is no session and it's "gone". Do you have a better alternative for the http status?

**Comment by mmoayyed** [comment]
This might be helpful: https://apereo.github.io/cas/development/installation/Monitoring-Statistics.html

**Comment by Condor70** [comment]
What is an "active SSO session"? Because I configured /status to use internal CAS authentication, so I assumed it would have an active SSO session.

**Comment by mmoayyed** [comment]
an active SSO session is exactly that; it's the establishment of single sign on. However this endpoint does not look at whether CAS has an active sso session internally. It attempts to do that on a per-request per-user basis This is a bit of an experimental feature. 

Currently one way for a client application to determine if there is an SSO session is to use the gateway feature and sort of "heartbeat" the CAS server to see if the SSO session tied to the browser for the request and user is still valid. This endpoint should attempt to make that easier.
