### ISSUE TITLE
Google Authenticator tables warning

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2552]
Version: 5.1.0-RC4-SNAPSHOT

A CAS configured with cas-server-support-gauth logs the following warnings during startup:
```
[org.hibernate.cfg.AnnotationBinder] - <HHH000139: Illegal use of @Table in a subclass of a SINGLE_TABLE hierarchy: org.apereo.cas.adaptors.gauth.repository.token.GoogleAuthenticatorToken>
[org.hibernate.cfg.AnnotationBinder] - <HHH000139: Illegal use of @Table in a subclass of a SINGLE_TABLE hierarchy: org.apereo.cas.adaptors.gauth.repository.credentials.GoogleAuthenticatorAccount>
```

This is because GoogleAuthenticatorToken and GoogleAuthenticatorAccount inherit from OneTimeToken and OneTimeTokenAccount, but also have a @Table annotation.

The @Table annotation should be removed from GoogleAuthenticatorToken and GoogleAuthenticatorAccount and be added to OneTimeToken and OneTimeTokenAccount.

Alternatively, you could annotate OneTimeToken and OneTimeTokenAccount with @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS), but I don't think that was your intended table strategy.

**Comment by mmoayyed** [comment]
You're right. This is an oversight and those annotations should be removed and moved over. 

What is the database you're seeing this with by the way?

**Comment by Condor70** [comment]
This is a Hibernate warning and it is database-independent (tables named OneTimeToken and OneTimeTokenAccount are created and used).

ps. I'm using DB2 for i V7R1 (org.hibernate.dialect.DB2400Dialect).

**Comment by mmoayyed** [comment]
Thanks. Reviewing this more, I realize we likely should annotate OneTimeToken and OneTimeTokenAccount because those are designed to be "generic" types on top of which GAuth can build upon. (Already been working on extensions of those that have nothing do with GAuth). So the preference would be to let the parent class define inheritance rules and have each impl define its own table naming scheme.

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.
