### ISSUE TITLE
CasVersion can't handle wsjar protocol

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2553]
Version: CAS-5.1.0-RC4-SNAPSHOT

This is a really minor issue, but I get the following warning when starting CAS on a WebSphere Liberty server:
`[org.apereo.cas.util.CasVersion] - <Unhandled url protocol: [wsjar] resource: [wsjar:file:/mypath/cas-server-webapp/WEB-INF/lib/cas-server-core-util-5.1.0-RC4-SNAPSHOT.jar!/org/apereo/cas/util/CasVersion.class]>`

Could you add the wsjar protocol to CasVersion? It looks like it is structurally the same as the jar protocol.

**Comment by dima767** [comment]
I'd personally rather not complect CAS components with proprietary protocols and such. For this situation, it's possible to configure WS server to use "standard" jar protocol: http://www-01.ibm.com/support/docview.wss?uid=swg1PM99378

**Comment by Condor70** [comment]
Thanks for the link. I wasn't aware of the config option.
