### ISSUE TITLE
x509 webflow doesn't handle authenticationFailure state

### ISSUE THREAD

**Issue by hdeadman** [apereo/cas#2554]
- CAS server version - 5.1 RC4-SNAPSHOT (built locally on about 4/21)
- Container/environment type/version - Tomcat, Windows
- To recreate: Authenticate with a validate certificate but principal lookup against attribute should fail
The following setting prevents principal from being used from certificate as a fallback: 
cas.authn.x509.principal.returnNull=true

I am working on a patch to handle the authenticationFailure state. When I tried sending flow to the login form (same flow as for ERROR) I get error due to this:

```
Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'username' cannot be found on object of type
 'org.apereo.cas.adaptors.x509.authentication.principal.X509CertificateCredential' - maybe not public?
```
Do I need create an action or do something to clear everything left over from X509 auth attempt out of the flow scope (or at least the credentials)?  Or should those credentials be removed when null is returned instead of the fallback to value from cert?

**Comment by mmoayyed** [comment]
There should be an action already that would clear the webflow scope altogether so it can attempt to reinitialize the scoped credential object. It is `ClearWebflowCredentialAction`.  You want to somehow tie `clearWebflowCredentialsAction` into the webflow as appropriate. I suspect X509 does that already somewhere. Perhaps incorrectly.
