### ISSUE TITLE
Enhance delegated authentication: clients should not be assumed to be CAS applications

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#2558]
Today, CAS clients that intend to take advantage of delegated authentication via pac4j are always assumed to be CAS clients. They are provided an ST, etc.
This issue intends to allow CAS to remove that assumption and become client-aware, so that CAS, SAML2 or OIDC clients can be used to take advantage of delegated authentication making the platform very much protocol agnostic as much as possible.

**Comment by mmoayyed** [comment]
The deployment I was working on to add this support no longer is need of this functionality. Going to close for the time being and we can revisit later.

**Comment by rrenomeron** [comment]
FWIW, I will eventually require this, as we're using SAML delegated authentication and are almost certain to add OIDC support to our CAS deployment in the medium term.

**Comment by mmoayyed** [comment]
Sounds terrific. You are of course welcome to work on it. Happy to accept all improvements.
