### ISSUE TITLE
CAS v5.0.5 Hazelcast Ticket Registry Doesn't Work

### ISSUE THREAD

**Issue by zimai** [apereo/cas#2559]
We're currently testing with CAS 5.0.5 and the Hazelcast Ticket Registry, and the embedded Tomcat fails to start, giving the following error.

We're using the embedded Tomcat with Oracle Java 8 and running linux (Centos 7) and Docker.
Even going back to the default pom.xml and just adding the dependency and corresponding properties in "cas.properties", it still seems to give this error, so for now we will have to stick with 5.0.4 until this is resolved.

I've attached the files used for testing here.
[cas505.zip](https://github.com/apereo/cas/files/952931/cas505.zip)

_ERROR [org.springframework.boot.context.embedded.tomcat.TomcatStarter] - <Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'casLoggingConfiguration': Unsatisfied dependency expressed through field 'ticketRegistrySupport'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'casCoreTicketsConfiguration': Unsatisfied dependency expressed through field 'ticketRegistry'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcastTicketRegistry' defined in class path resource [org/apereo/cas/config/HazelcastInstanceConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apereo.cas.ticket.registry.TicketRegistry]: Factory method 'hazelcastTicketRegistry' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hazelcast' defined in class path resource [org/apereo/cas/config/HazelcastInstanceConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.hazelcast.core.HazelcastInstance]: Factory method 'hazelcast' threw exception; nested exception is java.lang.IllegalArgumentException: PortableFactory[-1] is already registered! com.hazelcast.spi.impl.SpiPortableHook$1@61fb0572 -> com.hazelcast.spi.impl.SpiPortableHook$1@730dc907>
2017-04-24 15:44:03,682 WARN [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat>_

**Comment by dima767** [comment]
This problem is surfacing itself most likely due to multiple HZ versions jars/dependencies got their way into the classpath

**Comment by mmoayyed** [comment]
Thanks for the logging the issue report. Please investigate the problem, and whenever reasonable, file a pull request to address this case. Thanks very much!

**Comment by zimai** [comment]
As a quick update, I tried manually changing the version used for cas-server-support-hazelcast-ticket-registry to 5.0.4, while using 5.0.5 for the CAS server and everything else, and it seems to work.  I wasn't able to find where the bean was already registered that was causing the bean in HazelcastInstanceConfiguration to fail, but if so, I'll create the pull request as requested.

Thanks!

**Comment by mmoayyed** [comment]
Examine the changelog for 5.0.5: https://github.com/apereo/cas/milestone/53?closed=1

You'll find a number of hazelcast-related changes, at least two: one that fixes an issue with ticket encryption and the other that removes RefreshScope from the registry. My guess is the latter is causing you harm here, but please investigate and see if that fix applied to 5.0.5 is in fact the issue.

**Comment by mmoayyed** [comment]
This specifically https://github.com/apereo/cas/pull/2541

**Comment by mmoayyed** [comment]
Pinging @ravomavain: are you seeing the same issue reported here as well?

**Comment by zimai** [comment]
The RefreshScope annotation was already removed in the source as mentioned in that issue.  However, I tried modifying the Bean annotation on the hazelcastTicketRegistry function as mentioned in https://github.com/apereo/cas/pull/2565 and this seems to work, but I'm not sure if this modification will result in other issues.

Thanks!

**Comment by mmoayyed** [comment]
Are you getting this error when you run java -jar? or are you also getting this error when you deploy into an external tomcat? I am trying to remove variables (docker, etc)

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT. I am also going to open an issue with hazelcast to report this.

**Comment by zimai** [comment]
Thanks! And sorry for the delay, though it sounds like a fix was found!  It seemed to be with the embedded Tomcat only.  I tried an external Tomcat (8.5.8) and the issue does not seem to surface.

This was using java -jar with the embedded Tomcat (which seems to be version 8.5.13).  In either case (embedded or external Tomcat), this was using Docker.

I'll try the 5.0.6 version and see if the issue still arises.

Thanks!

**Comment by mmoayyed** [comment]
Excellent. Thanks for the good news. See linked issue to learn more about why this is happening: https://github.com/hazelcast/hazelcast/issues/10438

**Comment by mmoayyed** [comment]
@zimai switch to 5.0.6 SNAPSHOT and please retest.

**Comment by zimai** [comment]
5.0.6-SNAPSHOT seems to have resolved this issue.  Thanks!
