### ISSUE TITLE
Duo MFA Integration broken on/after Builds 5.1.x+ - Maybe missing dependencies 

### ISSUE THREAD

**Issue by tfrancois** [apereo/cas#2566]
In my testing, it appears that Duo multi-factor authentication **has stopped working**.  I've noticed that the dependency has also changed (and needs to be documented) to **cas-server-support-duo-core** from _cas-server-support-duo_ for builds 5.1.x onward.

With Duo support enabled, once I authenticate successfully against my LDAP source, the CAS login screen returns _"Invalid credentials."_ despite correct user ID/password (log confirms this) and authentication fails.  

I'll include my configuration settings and logs below for troubleshooting.
```
- CAS version: 5-1.0-RC4-SNAPSHOT
- Build environment/container: Tomcat 8.5.13/Linux-RHEL7 
- Java/JVM Version: 1.8.0_131-b11
```

I've added to my pom.xml:
**cas-server-support-duo-core**  (Using _cas-server-support-duo_ for 5.1.x+ builds does not work)

Upon successfully authenticating via LDAP (AD), the instance shows the following error:
```
=============================================================
WHO: EPaw
WHAT: Supplied credentials: [epaw]
ACTION: AUTHENTICATION_SUCCESS
APPLICATION: CAS
WHEN: Tue Apr 25 13:01:37 EDT 2017
CLIENT IP ADDRESS: XXX.XXX.XXX.XXX
SERVER IP ADDRESS: XXX.XXX.XXX.XXX
=============================================================

>
2017-04-25 13:01:37,949 ERROR [org.apereo.cas.web.flow.resolver.impl.GlobalMultifactorAuthenticationPolicyEventResolver] - <No multifactor authentication providers are available in the application context to handle mfa-duo>
2017-04-25 13:01:37,951 INFO [org.apereo.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN
=============================================================
WHO: EPaw
WHAT: No supported authentication handlers found for given credentials
ACTION: AUTHENTICATION_EVENT
APPLICATION: CAS
WHEN: Tue Apr 25 13:01:37 EDT 2017
CLIENT IP ADDRESS: XXX.XXX.XXX.XXX
SERVER IP ADDRESS: XXX.XXX.XXX.XXX
=============================================================

>
2017-04-25 13:01:37,960 ERROR [org.apereo.cas.web.flow.AuthenticationExceptionHandler] - <Unable to translate handler errors of the authentication exception [org.apereo.cas.authentication.AuthenticationException: No supported authentication handlers found for given credentials]Returning [UNKNOWN]>
2017-04-25 13:01:54,109 INFO [org.apereo.cas.ticket.registry.DefaultTicketRegistryCleaner] - <[0] expired tickets removed.>
2017-04-25 13:01:55,752 INFO [org.apereo.cas.services.DefaultServicesManager] - <Loaded [3] service(s) from [InMemoryServiceRegistry].>

```
Here is the appropriate section in my cas.properties file for MFA config:
```
cas.authn.mfa.globalProviderId=mfa-duo
cas.authn.mfa.contentType=application/cas
cas.authn.mfa.globalFailureMode=OPEN
cas.authn.mfa.authenticationContextAttribute=authnContextClass

# CAS DUO MFA Settings
cas.authn.mfa.duo.duoApplicationKey=######################################### [=40 chars]
cas.authn.mfa.duo.duoSecretKey=$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
cas.authn.mfa.duo.duoIntegrationKey=xxxxxxxxxxxxxxxxxxxxxxxxx
cas.authn.mfa.duo.duoApiHost=api-XXXXXXXXX.duosecurity.com
cas.authn.mfa.duo.rank=0
cas.authn.mfa.duo.trustedDeviceEnabled=true
```
Below is my entire log for troubleshooting:
[cas-log.txt](https://github.com/apereo/cas/files/955950/cas-log.txt)

For more information, here is my pom.xml:
[pom.xml](https://github.com/apereo/cas/files/955980/pom.xml.txt)

If I remove support for Duo in my pom.xml, I authenticate successfully and the web flow/ticketing to my client service works flawlessly.  

Would love to get Duo integration working again.  I'm available to help test at anytime.  Thanks.

**Comment by mmoayyed** [comment]
First, the module name should remain as it was. 
Second, please see this https://apereo.github.io/2016/12/23/51rc1/#duo-security-multiple-configurations-1 Then see https://apereo.github.io/cas/development/installation/Configuration-Properties.html#duosecurity

**Comment by mmoayyed** [comment]
Also relevant https://github.com/spring-projects/spring-boot/issues/7961

**Comment by tfrancois** [comment]
HI @mmoayyed:

Here's what my log looks like when I change it to the cas-support-support-duo
[cas_log-2.txt](https://github.com/apereo/cas/files/956049/cas_log-2.txt)

My instance doesn't even permit the CAS instance to load.

**Comment by mmoayyed** [comment]
Sure. See `No configuration/settings could be found for Duo Security. Review settings and ensure the correct syntax is used`

That's because your settings are misplaced. Make the changes recommended in the docs and that blog post and the issue goes away.

**Comment by tfrancois** [comment]
Thank you @mmoayyed.  As you stated, changing my dependency in pom.xml back to the documented **cas-support-support-duo** and modifying my cas.properties file to below:
```
cas.authn.mfa.globalProviderId=mfa-duo
cas.authn.mfa.contentType=application/cas
cas.authn.mfa.globalFailureMode=OPEN
cas.authn.mfa.authenticationContextAttribute=authnContextClass

# CAS DUO MFA Settings
cas.authn.mfa.duo[0].duoApplicationKey=uGaZn4PYZhyfJ49tfBkYdtTpisYOjpWNNf6LMUyk
cas.authn.mfa.duo[0].duoSecretKey=K1NZcGRUsCpIX3wCvbW88M5l10BAfYb3ITG6kSk2
cas.authn.mfa.duo[0].duoIntegrationKey=DISEZCMYKD3HFUYYAH7K
cas.authn.mfa.duo[0].duoApiHost=api-cb677dac.duosecurity.com
cas.authn.mfa.duo[0].rank=0
cas.authn.mfa.duo[0].trustedDeviceEnabled=false
```
...worked flawlessly.  Duo dual-factor authentication and the web flow worked perfectly!

**Comment by mmoayyed** [comment]
Great.

**Comment by mmoayyed** [comment]
Also note that you probably don't need these:

```
cas.authn.mfa.contentType=application/cas
cas.authn.mfa.authenticationContextAttribute=authnContextClass
cas.authn.mfa.duo[0].rank=0
cas.authn.mfa.duo[0].trustedDeviceEnabled=false
```

Only keep what you actually use.
