### ISSUE TITLE
5.0.4: /oauth2.0/accessToken endpoint requires POST

### ISSUE THREAD

**Issue by stefli** [apereo/cas#2571]
Version: 5.0.4

Access the /oauth2.0/accessToken endpoint with wrong request method(GET, but POST required), the response likes:
![image](https://cloud.githubusercontent.com/assets/56305/25472097/68a6f88c-2b5c-11e7-9737-c9391ef39779.png)

But if access it with wrong client id, the response likes:
![image](https://cloud.githubusercontent.com/assets/56305/25472147/9e57fec2-2b5c-11e7-9820-ee4e820c7855.png)

The format is quite different, How can i uniform the response?

**Comment by mmoayyed** [comment]
You should be able to test this in about an hour or so, by using the new 5.0.6 SNAPSHOT. In general you need to review the access token controller class and change the request mapping, if it's not already there, and then post a pull request that contains that change, or any other changes needed.

**Comment by stefli** [comment]
@mmoayyed another requirement: how to custom the response json format? the format likes:
{
  "code": "SOME CODE",
  "message": "SOME MESSAGES",
  "data": {}
}

Use a custom "DefaultOAuth2ExceptionRenderer" can make some response to above format. But can't format below response:
![image](https://cloud.githubusercontent.com/assets/56305/25495847/61b2d352-2bb1-11e7-83c5-a7c13705181b.png)

**Comment by mmoayyed** [comment]
https://github.com/apereo/cas/blob/5.0.x/support/cas-server-support-oauth/src/main/java/org/apereo/cas/support/oauth/web/OAuth20ProfileController.java#L89

**Comment by mmoayyed** [comment]
If you review the same component, you can see how it attempts to write out error messages back as well.

**Comment by stefli** [comment]
Got it, thanks.
