### ISSUE TITLE
Internationalization not complete

### ISSUE THREAD

**Issue by Condor70** [apereo/cas#2577]
My users are mainly Dutch. Since the Dutch messages file was really outdated, I took the English messages and retranslated all texts (here: [messages-nl.properties](https://github.com/apereo/cas/files/963897/messages-nl.properties.txt)).

I noticed however that not all texts in the templates are internationalized. Could all texts be moved from the templates to the messages files?

**Comment by mmoayyed** [comment]
Thanks for raising this. 

Yes, we do this on a needs-to-be-done basis when we do UI work mostly. Ideally, everything should be moved over to messages files. Going to ping @mindblender as he's mostly done a great job moving things over. In the meantime, if there are tests you wish to translate to dutch and that they need moving to bundles, this is an easy contribution to make.
