### ISSUE TITLE
HTTP response header X-Application-Context exposes internal servlet container deployment configuration

### ISSUE THREAD

**Issue by leeyc0** [apereo/cas#2578]
When I was checking with HTTP response using curl:
`# curl -v https://cas.example.com/cas/yadis.xml`
I found that there is a response header X-Application-Context inserted
`X-Application-Context: cas:standalone:8443`
Which is the actual deployment configuration in tomcat.

In such a piece of security-conscious software, exposing server internals is certainly a bad idea. Although I can add this option in cas.config to disable this header:
`management.add-application-context-header=false`
It would be much better to make it be default.

**Comment by mmoayyed** [comment]
I agree. Please make this be the default.

**Comment by mmoayyed** [comment]
Also related https://github.com/spring-projects/spring-boot/issues/1308
