### ISSUE TITLE
OIDC Scope mapping side effect

### ISSUE THREAD

**Issue by tsschmidt** [apereo/cas#2583]
Working with the latest 5.1.x branch.  

In order for attributes to be released when using a scope in OIDC, attributes need to mapped in cas.properties to the correct OIDC name for those attributes. For instance given name comes out of LDAP as "givenName" and needs to be mapped to "given_name" to be released by OIDC.  With the current implementation of mapping attributes, the side effect is that given name will always be released as "given_name" even for non-OIDC requests.

Suggest to find a way to map attributes for OIDC that does not alter the names released by other protocols.

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.

**Comment by mmoayyed** [comment]
Also https://apereo.github.io/cas/development/installation/OIDC-Authentication.html#mapping-claims
