### ISSUE TITLE
CAS 5.1.0-RC4 In-memory ticket registry still starting when using Hazelcast ticket registry

### ISSUE THREAD

**Issue by zimai** [apereo/cas#2591]
CAS 5.1.0-RC4 seems to have an issue where the in-memory ticket registry still seems to be starting even after configuring CAS to use the Hazelcast ticket registry.
Configuration was done according to the documentation [here ](https://www.google.com/url?q=https%3A%2F%2Fapereo.github.io%2Fcas%2Fdevelopment%2Finstallation%2FHazelcast-Ticket-Registry.html&sa=D&sntz=1&usg=AFQjCNHNP2deV4Ane57RJLrMUXFPuLcrxQ) by adding the dependency and configuring the properties in cas.properties.

The following warning shows up in the logs even though the logs clearly show that an HZ ticket registry was setup prior to this point in the logs.

_WARN [org.apereo.cas.config.CasCoreTicketsConfiguration] - <Runtime memory is used as the persistence storage for retrieving and managing tickets. Tickets that are issued during runtime will be LOST upon container restarts. This MAY impact SSO functionality.>_

...which shows up after the following line:

_INFO [org.apereo.cas.ticket.registry.HazelcastTicketRegistry] - <Setting up Hazelcast Ticket Registry instance [HazelcastInstance{name='devcas5Tickets', node=[xx.xx.xx.xx]:5701}]>_

It seems as if the bean called "ticketRegistry" that should be registered by HZ is either not being registered or recognized by the time CAS checks if it should load the default in-memory ticket registry.

This seems to interfere with the ticket registry working properly.  For example, when trying to access a test application that is setup to use this instance of CAS server, I can't get past the CAS login screen.  After entering the credentials and hitting enter, I'm redirected back to the login screen.  In the logs, it seems to show that CAS is unable to find the ST in the ticket registry because the ticket was probably stored in memory, but CAS is looking in HZ.

Here are some logs showing this confusion due to the two registries being used.

_WARN [org.apereo.cas.ticket.registry.HazelcastTicketRegistry] - <No ticket definition could be found in the catalog to match [ticket]>

WARN [org.apereo.cas.web.flow.GenerateServiceTicketAction] - <Could not grant service ticket [ticket]. Routing to [authenticationFailure]>_

The section generating the log message and that seems to incorrectly start the default ticket registry appears to be here:

cas-5.1.0-RC4\core\cas-server-core-tickets\src\main\java\org\apereo\cas\config\CasCoreTicketsConfiguration.java

Line 180 starts the definition for public TicketRegistry ticketRegistry(), which is annotated with @ConditionalOnMissingBean(name = "ticketRegistry"), which should not be missing since HZ should be creating its own "ticketRegistry" bean.

Environment:
- Docker
- Embedded Tomcat
- CAS 5.1.0-RC4
- Centos 7

Thanks,
Matt

**Comment by zimai** [comment]
Looks like some of the log messages didn't paste correctly, recopying below:

_WARN [org.apereo.cas.config.CasCoreTicketsConfiguration] - <Runtime memory is used as the persistence storage for retrieving and managing tickets. Tickets that are issued during runtime will be LOST upon container restarts. This MAY impact SSO functionality.>_

_INFO [org.apereo.cas.ticket.registry.HazelcastTicketRegistry] - <Setting up Hazelcast Ticket Registry instance [HazelcastInstance{name='devcas5Tickets', node=[xx.xx.xx.xx]:5701}]>_

_WARN [org.apereo.cas.ticket.registry.HazelcastTicketRegistry] - <No ticket definition could be found in the catalog to match [ticket]>_

_WARN [org.apereo.cas.web.flow.GenerateServiceTicketAction] - <Could not grant service ticket [ticket]. Routing to [authenticationFailure]>_

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.
