### ISSUE TITLE
Cas30ResponseView throws NPE if attribute value is NULL

### ISSUE THREAD

**Issue by robertoschwald** [apereo/cas#2599]
Cas 5.0.4 Cas30ResponseView throws an NPE on line 125 if an attribute value is NULL.
Maybe this is still the case for the master branch, haven't checked, yet.

Have not found any documentation stating that attribute values must be non-null in any documentation.

In my AttributeDao implementation, I filter out null-valued attributes for now.

**Comment by mmoayyed** [comment]
Thanks for the logging the issue report. Please file a pull request to address this case. Thanks very much!

**Comment by robertoschwald** [comment]
Closed the unresolved issue? Seriously?

**Comment by robertoschwald** [comment]
For me, this is a bug.
