### ISSUE TITLE
Mark CAS beans with @ConditionalOnMissingBean

### ISSUE THREAD

**Issue by robertoschwald** [apereo/cas#2600]
To give implementors a chance to re-define bean definitions, the CAS bean definitions must be marked @ConditionalOnMissingBean, otherwise re-defining beans does not work.

See ML post: https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/Th7nuWMXPgI

**Comment by robertoschwald** [comment]
Would be great if this could be introduced to the 5.0.x branch as well.

**Comment by mmoayyed** [comment]
Thanks for the logging the issue report. Please file a pull request to address this case. Thanks very much!

**Comment by robertoschwald** [comment]
Closed the unresolved issue? Seriously?

**Comment by mmoayyed** [comment]
Yes. I don't see anything humorous in my last comment. You don't need an issue to then create a pull request only to then close the pull request to close the issue. Just do the PR.
