### ISSUE TITLE
CAS overlay 5.0.5 does not work.

### ISSUE THREAD

**Issue by kras01** [apereo/cas#2611]
I am using 5.0.5 overlay and attempting to run it but I get an exception. It appears to be related to the logging configuration file. I have tried a number of different properties including adding a line in bootstrap.properties but then I get other exceptions regarding it being unable to create some beans.

`2017-05-12 17:02:03,362 WARN [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext] - <Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.loggingConfigController': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: ServletContext resource [/-Djava.util.logging.config.file="C:/Program Files/Apache Software Foundation/apache-tomcat-8.5.15/conf/logging.properties"] cannot be resolved to URL because it does not exist>
2017-05-12 17:02:03,374 ERROR [org.springframework.boot.SpringApplication] - <Application startup failed>
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.loggingConfigController': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.io.FileNotFoundException: ServletContext resource [/-Djava.util.logging.config.file="C:/Program Files/Apache Software Foundation/apache-tomcat-8.5.15/conf/logging.properties"] cannot be resolved to URL because it does not exist
	`

CAS Version: 5.0.5
Apache Tomcat Version: Apache Tomcat/8.5.15
Build Date/Time: 2017-04-21T10:24:20Z
System Temp Directory: C:\Program Files\Apache Software Foundation\apache-tomcat-8.5.15\temp
Java Home: C:\Program Files\Java\jdk1.8.0_65\jre
Java Vendor: Oracle Corporation
Java Version: 1.8.0_65
JCE Installed: no
OS Architecture: amd64
OS Name: Windows 10
OS Version: 10.0

**Comment by dima767** [comment]
Please use CAS mailing lists for questions like these.
