### ISSUE TITLE
Remove CAS/Stormpath integration module/docs

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#2612]
From stormpath: 

> This is an important system reminder that the Stormpath API is shutting down on August 17th at noon PDT. All data in Stormpath will be deleted at that time and must be exported beforehand.

**Comment by dima767** [comment]
Just one note: why not remove it in 5.1?

**Comment by mmoayyed** [comment]
possible, though we are technically in freeze mode, and this is not quite a bug fix. I guess it also allows anyone to take advantage of the integration until August 17th :) and there is no rush to doing this.

**Comment by dima767** [comment]
Got ya.. Well, one warning - whoever is using this module (anyone really?) in 5.1 would be "pleasantly" surprised after August 17... But, in all fairness, not a CAS problem ;-)

**Comment by leleuj** [comment]
Thanks. I missed that information. I'll do the same on pac4j side: https://github.com/pac4j/pac4j/issues/910

**Comment by mmoayyed** [comment]
Should be able to test the fix in about an hour or so, by using the new SNAPSHOT.
