### ISSUE TITLE
findbugs stops build, unable to achieve "functional build"

### ISSUE THREAD

**Issue by ruckc** [apereo/cas#2618]
in attempting to build locally to support providing a PR for some of the `contribution suitable`, but not resolved issues.  I can't quite get a functional build as findbugs fails the build.

In looking in detail at the errors, shouldn't these have been fixed before the classes committed?

```
 Bad practice Warnings
Code 	Warning
Se 	Class org.apereo.cas.support.events.config.CasConfigurationCreatedEvent defines non-transient non-serializable instance field file
	
Se 	Class org.apereo.cas.support.events.config.CasConfigurationDeletedEvent defines non-transient non-serializable instance field file
	
Se 	Class org.apereo.cas.support.events.config.CasConfigurationModifiedEvent defines non-transient non-serializable instance field file
	
Se 	Class org.apereo.cas.support.events.ticket.CasServiceTicketValidatedEvent defines non-transient non-serializable instance field assertion
```

**Comment by mmoayyed** [comment]
Good for you.

Start with https://apereo.github.io/cas/developer/Build-Process.html#build and try to skip FindBugs?

**Comment by mmoayyed** [comment]
And yes, those should/could have been fixed.
