### ISSUE TITLE
Wrong couchbase ticket registry configuration

### ISSUE THREAD

**Issue by FeyFre** [apereo/cas#2638]
[spring.factories](https://github.com/apereo/cas/blob/5.1.x/support/cas-server-support-couchbase-ticket-registry/src/main/resources/META-INF/spring.factories) in cas-server-support-couchbase-ticket-registry loads absolutely wrong configuration file - file from MongoDB module.

Was it tested?

**Comment by mmoayyed** [comment]
Thanks for the find. You should submit a pull request that fixes the problem and then start testing.

**Comment by rdev5** [comment]
@FeyFre Due to bad edit in [6ae24ed](https://github.com/apereo/cas/commit/6ae24ed5f4766d32dc3f1ce1bfc31894ffd35608#diff-80c9a744efcbc818c667aef5623d19d8).

It was reverted in 52f83fb but hasn't been published out to the repositories yet. I'm still getting the same error at CAS 5.1.1 (Gradle)

**Comment by rdev5** [comment]
Just noticed the [build config](https://travis-ci.org/apereo/cas/jobs/250897484/config) is configured to publish to `sonatype`. Should be published soon.
