### ISSUE TITLE
Expires_in is always set to 7200 when access token is returned

### ISSUE THREAD

**Issue by klewczuk** [apereo/cas#2644]
Affects CAS 5.0.6.
In cas.properties I have the following settings:
cas.authn.oauth.accessToken.timeToKillInSeconds=60

But when calling /cas/oauth2.0/accessToken endpoint I get an access token with expires_in parameter set to 7200. No matter what value is set in properties, CAS always returns 7200.

**Comment by mmoayyed** [comment]
You do want to debug the code to figure out how the expiration policy for ATs is set up and how that value is used in the final response. If you find the problem, please post a patch that fixes it. Thanks very much!
