### ISSUE TITLE
Access token does not expire when expected

### ISSUE THREAD

**Issue by klewczuk** [apereo/cas#2645]
Affects CAS 5.0.6.
In cas.properties I have the following settings:
cas.authn.oauth.accessToken.timeToKillInSeconds=60

But after 60 seconds access token does not actually expire and it is still possible to get the user profile with this access token. While debugging I found out that in `OAuth20ProfileController` there is a check for the access token: `accessTokenTicket.isExpired()` - this calls `OAuthAccessTokenExpirationPolicy.isExpired(ticketState)` which checks if `(ticketState.getLastTimeUsed().isAfter(expirationTime))`. Although I call the /cas/oauth2.0/profile endpoint few times, `getLastTimeUsed()` method always returns the same timestamp, which represents the creation time of access token.

**Comment by mmoayyed** [comment]
You do want to debug the code to figure out how the expiration policy for ATs is set up. If you find the problem, please post a patch that fixes it. Thanks very much!
