### ISSUE TITLE
Wrong redirection when authorizing after session timeout

### ISSUE THREAD

**Issue by klewczuk** [apereo/cas#2646]
Affects CAS 5.0.6.
In authorization code flow there is a wrong redirection to "/" after session timeout.
Steps to reproduce:
1. Authorize the user with authorization code grant.
2. Wait till the session expires.
3. Try to access /cas/oauth2.0/authorize again. Because the session is expired, the user will be redirected to the login page.
4. Fill in credentials and click login button.
5. The browser redirects to "/".
6. The user is actually authenticated, so refreshing the page will show the correct page (with share profile button), but the redirection was wrong.

After analyzing the code I found out that the cause is session cookie reset when calling GET /login, which is incorrect, because later when calling GET /callbackAuthorize CAS tries to get the redirect_uri from session store - it finds nothing (because there was a session reset in the meantime) and redirects to "/".
Please see screenshots in attachment - I made a screen for each request (and its cookies) to the CAS server.
[requests.zip](https://github.com/apereo/cas/files/1047792/requests.zip)

**Comment by mmoayyed** [comment]
Thank you. Excellent analysis. Please follow this up with the fix that removes the extra "/" at fault.
