### ISSUE TITLE
Enable Deployer-Specified Name for SAML2 pac4j clients

### ISSUE THREAD

**Issue by rrenomeron** [apereo/cas#2647]
In order to differentiate multiple SAML2 Delegated AuthN clients on the login page, expose the "Name" field of the SAML2Client pac4j class via CAS properties such that deployers can set a unique name for each SAML2 client like this:

cas.authn.pac4j.saml[0].clientName = This Org
cas.authn.pac4j.saml[1].clientName = That Org

- CAS server version 5.1.0 
- Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc) Tomcat 8.5 on Linux

**Comment by rrenomeron** [comment]
I have a patch for this, but it will take some time for me to fiddle around with github and get the CLA stuff in place to ask for a pull request.

**Comment by mmoayyed** [comment]
Outstanding. Please speak up if you run into any issues with that process and worst case,  feel free to paste/attach the patch here and we'll import it under your name.

**Comment by mmoayyed** [comment]
Also, you may want to two pull requests: one for 5.1.x and one for master as target branches. Or, do one branch and I can lend a hand with porting it to the other relevant branches if needed.

**Comment by mmoayyed** [comment]
Hi there, have you had a chance to review this issue again and make progress?

**Comment by rrenomeron** [comment]
I've been promised an answer on the CLA by the beginning of next week.  I'll push to my repo and start a pull request then.

**Comment by mmoayyed** [comment]
Outstanding. Please remember that CLA's on our side are *optional* for all contributors. The ask is only a sign of good will. So you perfectly CAN start with the work without ever having to sign the CLA. 

If you were to become a committer, different issue.

**Comment by rrenomeron** [comment]
So the organization sponsoring my work (not my employer) has declined the CLA, but they're happy for me to put my changes on github and do a pull request, which I'll once master builds successfully again.

**Comment by mmoayyed** [comment]
Outstanding. Master should be back to normal. Check with Travis for full clarity.
