### ISSUE TITLE
Why all of return value type are array, if request '/p3/serviceValidate?format=JSON' ?

### ISSUE THREAD

**Issue by kogayushi** [apereo/cas#2654]
Hi, this is Yushi.

I'm wondering about something.

If call `/p3/serviceValidate` endpoint with query of `format=JSON`, like his.
```bash
$ curl -v "http://localhost:8080/cas/p3/serviceValidate/?format=JSON&service=http%3A%2F%2Flocalhost%3A8080%2Fsomeclient%2F&ticket=ST-1-XXXXXXXXXXXXXXXXXXXX-y-koga
```

Then it returns response but all value type of attributes are array.
```json
{
  "serviceResponse" : {
    "authenticationSuccess" : {
      "user" : "casuser",
      "attributes" : {
        "username" : [ "casuser" ]
        "isFromNewLogin" : [ true ],
        "authenticationDate" : [ 1496713383.644000000 ],
        "successfulAuthenticationHandlers" : [ "AcceptUsersAuthenticationHandler" ],
        "authenticationMethod" : "AcceptUsersAuthenticationHandler",
        "longTermAuthenticationRequestTokenUsed" : [ false ],
      }
    }
  }
}
```

Although, it's written that [we can request JSON at Section 2.5.1 of CAS protocol specification](https://apereo.github.io/cas/5.1.x/protocol/CAS-Protocol-Specification.html#head2.5.1),
Is `JSON format` supported officially ?

- [x] CAS server version
    - I've confirmed with `5.1.0`.
- [x] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
    - Java8, I'm running the CAS web application as an executable WAR.
- [ ] Steps to duplicate the problem along with your CAS settings and properties
    - n/a
- [ ] Stacktraces and CAS DEBUG logs where appropriate.
    - n/a
- [ ] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/ or attached to the issue.
    - n/a

**Comment by mmoayyed** [comment]
Yes it is supported officially. After all, you're getting JSON.
