### ISSUE TITLE
Change thymeleaf layout:decorate instructions to supress warning

### ISSUE THREAD

**Issue by AndrewRichardScully** [apereo/cas#2657]
The CAS HTML source templates with the line...

```
<html xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
	**layout:decorate="layout"**>
```

...need to change to read...

```
<html xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
	**layout:decorate="~{layout}"**>
```

...instead. Otherwise a warning is published when the server is first used.

See:
https://github.com/ultraq/thymeleaf-layout-dialect/issues/159

https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/aCQ71UA3SQQ

- [5.1.0] CAS server version
- [Glassfish] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)

**Comment by mmoayyed** [comment]
Thanks for the issue report. Could you please turn this into a pull request please?
