### ISSUE TITLE
Extract ServiceWatcher into a multi-purpose PathWatcher

### ISSUE THREAD

**Issue by DavidRG13** [apereo/cas#2678]
Given the work done on #2676 we could extract a serviceWatcher as it could be logic agnostic.

- where would it live? (which package/module)
- any preferred name? (directoryWatcher? pathWatcher?)

**Comment by mmoayyed** [comment]
Just so I understand this better, by logic-agonostic, I take it that you wish to have it also be used for watching the config directory and files? If so, that's great. How about we stuff it into the util module for now? pathWatcher makes sense to me.

**Comment by DavidRG13** [comment]
Yeah, that's it.
I'll work on it

**Comment by DavidRG13** [comment]
Quick question: the only difference I can spot between the 2 watchers is that the configuration one has a ```MONITOR_INTERVAL```, is it useful? or is it preferred to process all the file events triggered?

**Comment by mmoayyed** [comment]
I think both have some sort of monitoring interval. Except that one, for services, is configurable and the other for config file seems to be hardcoded. I think it makes sense for them have a reasonable defaults as an option. (i.e. in production, you dont want the config files to be monitored as such, but you may need service monitoring). Does that help?
