### ISSUE TITLE
Create own EventPublisher class

### ISSUE THREAD

**Issue by DavidRG13** [apereo/cas#2689]
Following this comment on #2680

> I mean that by this approach there is no need to pass ```applicationEventPublisher``` all around. Just use the publish consumer that expect an ```AbstractCasEvent``` or even better a ```Supplier<? extends AbstractCasEvent>```.
> 
> If this makes sense, this publish consumer should live somewhere accessible from everywhere

Changes to be done:
- Create new publisher Class under core:events module
- All components using the current ```eventPublisher``` to use the new one
- Question: is CAS listening for this events? or it's a future feature? (if it depends on the user we could make it configurable and only create and publish the event if needed)

**Comment by mmoayyed** [comment]
Q: In the new proposal, you would not be passing around `ApplicationEventPublisher`. You would be passing around `CasApplicationEventPublisher`, right? What exactly is the difference? What advantages are there in centralizing the event publisher provided by Spring, if we end up passing "our" instance around anyway?

**Comment by DavidRG13** [comment]
In first place, as you said, it would be centralized and usable via API, so the internal could change.
(Please answer my question in the first comment to be sure) I was thinking on adding it to the core, and only expose the ```Consumer<? extends AbstractCasEvent> publish(Supplier<? extends AbstractCasEvent> )```, this way we could construct the event object only if it's needed (if it's configurable)

**Comment by mmoayyed** [comment]
If this were to be done I'd prefer `Supplier<? extends AbstractCasEvent>`, sure. 

But I am still not sure what problem is getting solved, exactly. Do we have use cases we might want to abstract way the event publishing process to hide the internals? What might those be like? Is this purely a code change without a concrete use case, or are we aware of limitations with the current event publishing process that require a change? (I don't mean technical limitations; I mean things that cannot be done from a functional perspective). 

If that question does not have a rather clear answer, my vote would be to pause on this and focus on other things that require more immediate attention. It is up to you after all. Before making a change, you want to make sure it's worth it, and that we are not just creating abstractions for no practical reason.

**Comment by DavidRG13** [comment]
Could you please tell me if CAS needs this event functionality to work properly or it's optional?

**Comment by mmoayyed** [comment]
Events are certainly used by CAS, yes. But mostly the focus is on the *consumer* side and not the publisher side. The publishing capability is (and I suppose will always be) based on Spring's own mechanisms. The consumers however get interesting because they have the ability to track, record and process event data. So the consumers is where "functionality" would live. 

One thing to note is, in order for a downstream system to receive an event from CAS, that component would need to live inside CAS on the classpath, but I think @dima767 simply solved that problem by creating an event listener that in turn took around and published events into a message queue. 

All of which is why I think this is more or less,  for the time being at least, a solved problem unless you have something specific in mind. 

HTH.

**Comment by DavidRG13** [comment]
Cool! so lets focus on a different thing like the cassandra registry ;)

**Comment by dima767** [comment]
Yes, here's the prototype code (if anyone is interested) that publishes sample event as JSON payload to external RabbitMQ broker (but the destination could be anything that you could imagine, supported by spring cloud stream): https://github.com/UniconLabs/cas-publish-events-via-spring-cloud-stream

**Comment by mmoayyed** [comment]
Outstanding. Thanks for keeping up! There's lots more that needs solving. Let me know if you are looking for "contribution-suitable" issues, but as far as I know, all issues are suitable for contributions :)
