### ISSUE TITLE
Custom Authentication Exception

### ISSUE THREAD

**Issue by jasp255** [apereo/cas#2691]
# Issue Report

I try make a custom authentication exception on cas 5.1.0 but is not working, its work in cas 5.0.2, but not in the new 5.1.0 version.

I debug application and in "handle" method of "AuthenticationExceptionHandlerAction" class obtains null in de exception parameter.
So, when I try launch a any Exception alwais show UNKNOWN

- [] CAS server version: 5.1.0
- [] Container/environment type/version:tomcat 8.0.5 windows/linux
- [] Configuration width Overlay

**Comment by kyletitus** [comment]
This was fixed in a recent commit (https://github.com/apereo/cas/commit/7f1d64bc31961ea249de43b4b95477b5e3d8d104) overlaying that change into your instace will fix your issue until it can be included in a new release.
