### ISSUE TITLE
CAS does not shutdown gracefully when jdbc audit trail manager is used

### ISSUE THREAD

**Issue by PavlikPolivka** [apereo/cas#2700]
Hi,
We are using the JdbcAuditTrailManager and CAS will not shutdown properly.
I did some investigation:
- JdbcAuditTrailManager  has the DisposableBean interface and has the correct destroy method https://github.com/apereo/inspektr/blob/master/inspektr-support-spring/src/main/java/org/apereo/inspektr/audit/support/JdbcAuditTrailManager.java#L77
- the destroy method is never called in CAS
- JdbcAuditTrailManager is not created as spring bean in CAS https://github.com/apereo/cas/blob/61c26f17f2de72be81d4b2f8c6fa3475a0d2fe42/support/cas-server-support-audit-jdbc/src/main/java/org/apereo/cas/audit/config/CasSupportJdbcAuditConfiguration.java#L44-L59
- it's created with new JdbcAuditTrailManager  and than wrapped by DefaultDelegatingAuditTrailManager
- this way it's never registred as bean and the destroy method is never called

In our code I fixed this by creating a bean from JdbcAuditTrailManager  and injecting it to the DefaultDelegatingAuditTrailManager.
I can create merge request with the same fix for official cas if this makes sense.

**Comment by dima767** [comment]
Yes, please, feel free to create a pull request.

**Comment by PavlikPolivka** [comment]
For which branch? 5.1.x and master?

**Comment by mmoayyed** [comment]
Generally, all changes should be targeted to master. Whether you wish to backport to others would be up to you. Thanks for the pull!

**Comment by mmoayyed** [comment]
Also, just so it might make things easier for you: if you have already applied a change locally for you which you think is a reasonable change, bug fix,  etc that should be merged feel free to submit a PR directly without opening an issue. PR is the issue! You have already done the change to solve a problem, the work is done. Worst that can happen is somehow will review the PR and would say no there is an easier way, or they'd say thank you this is wonderful. Either case, less noise :)
