### ISSUE TITLE
MongoDB Ticket Registry usage leads to StackOverflow

### ISSUE THREAD

**Issue by karlbanke** [apereo/cas#2718]
Regardless of any additional configuration, we observe a StackOverflowError as soon as the dependency for the MongoDB Ticket Registry is inserted and a service ticket is created for a CAS Client. 
Login itself works properly. The error occurs when the client application tries to validate the service ticket against the CAS server. Note that the StackOverflowException occurs within the CAS Server not within the Client Application.

As client application, we are simply using the cas-service-management application. As service definition, we are using the generic "allow all" service definition shipped with CAS.  

- 5.1.0 CAS server version
- Tomcat Standalone running in Docker Container  

- Artifact included in overlay

<dependency>
    <groupId>org.apereo.cas</groupId>
    <artifactId>cas-server-support-mongo-ticket-registry</artifactId>
    <version>${cas.version}</version>
</dependency>

- Stack Trace

[[1;31m2017-06-22 13:30:43,869 ERROR [org.apereo.cas.ticket.registry.MongoDbTicketRegistry] - <Failed adding [ST-1-LdYuJ7iBKdKSfNlIoizm-cas]: [java.lang.IllegalArgumentException: com.fasterxml.jackson.d
atabind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver["beanFactory"]->org.spri
ngframework.beans.factory.support.DefaultListableBeanFactory["autowireCandidateResolver"]->org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver["beanFactory"]->org.springfra
mework.beans.factory.support.DefaultListableBeanFactory["autowireCandidateResolver"]->org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver["beanFactory"]->org.springframewor
k.beans.factory.support.DefaultListableBeanFactory["autowireCandidateResolver"]->org.springframework.context.annotation.ContextAnnotationAutowireCandidateResolver["beanFactory"]->org.springframework.bea
ns.fa.......

- MongoDB Ticket Registry Definition

cas.ticket.registry.mongo.idleTimeout=30000
cas.ticket.registry.mongo.port=27017
cas.ticket.registry.mongo.dropCollection=false
cas.ticket.registry.mongo.socketKeepAlive=false
cas.ticket.registry.mongo.collectionName=cas_ticket_registry
cas.ticket.registry.mongo.timeout=5000
cas.ticket.registry.mongo.writeConcern=NORMAL
cas.ticket.mongo.conns.lifetime=60000
cas.ticket.mongo.conns.perHost=10
cas.serviceRegistry.mongo.password=M3[0m-89
cas.serviceRegistry.mongo.databaseName=cas-mongo-database

**Comment by mmoayyed** [comment]
Fixed. Please try with the new snapshot.

**Comment by karlbanke** [comment]
How do I obtain this Snapshot? When I set the cas.version to 5.2.0-RC1 in my Overlay the dependencies can not be resolved.

**Comment by mmoayyed** [comment]
That's because it's not a snapshot. What you're trying is an RC that is not released. You want to try the snapshot:
https://github.com/apereo/cas/blob/master/gradle.properties#L24

**Comment by mmoayyed** [comment]
And as an example for the maven overlay: https://github.com/apereo/cas-overlay-template#build

**Comment by karlbanke** [comment]
When I enter <cas.version>5.2.0-RC1-SNAPSHOT</cas.version> into my Maven Overlay, I get "Could not resolve dependencies". Which Repository is the SNAPSHOT in?

**Comment by mmoayyed** [comment]
https://oss.sonatype.org/content/repositories/snapshots

**Comment by karlbanke** [comment]
Cross checked. Login to client app now works.

**Comment by mmoayyed** [comment]
Very nice. Thank you for confirming.
