### ISSUE TITLE
MongoDB User Attributes not resolved

### ISSUE THREAD

**Issue by karlbanke** [apereo/cas#2734]
Environment

- CAS server version 5.1 and 5.2.0-RC1
- Standalone Tomcat running in Alpine Linux Docker Container

We want to use MongoDB as our primary and only data source for authentication and user profile information. Sadly the user attributes never show up on the user attributes page. It is my understanding that this is supposed to happen automagically as soon as I use MongoDB authentication and declare properties in the configuration, as below. While authentication works propertly, no attributes are ever found. 

<dependency>
    <groupId>org.apereo.cas</groupId>
    <artifactId>cas-server-support-mongo</artifactId>
    <version>${cas.version}</version>
</dependency>

2) Included the following properties

#
# Mongo DB Authentication
#
cas.authn.mongo.mongoHostUri=mongodb://cas:*******@cas-mongo/cas-mongo-database
cas.authn.mongo.usernameAttribute=username
cas.authn.mongo.attributes=first_name,last_name
cas.authn.mongo.passwordAttribute=password
cas.authn.mongo.collectionName=users
#cas.authn.mongo.name=

# cas.authn.mongo.principalTransformation.suffix=
cas.authn.mongo.principalTransformation.caseConversion=NONE
# cas.authn.mongo.principalTransformation.prefix=

# cas.authn.mongo.passwordEncoder.type=NONE|DEFAULT|STANDARD|BCRYPT|SCRYPT|PBKDF2|com.example.CustomPasswordEncoder
cas.authn.mongo.passwordEncoder.type=DEFAULT
cas.authn.mongo.passwordEncoder.characterEncoding=UTF-8
cas.authn.mongo.passwordEncoder.encodingAlgorithm=SHA-256
# cas.authn.mongo.passwordEncoder.secret= 

The user collection in the database looks like this

> db.users.find()

{ "_id" : ObjectId("594bc3c32d5c8c3cf244f3bb"), "username" : "casuser", "password" : "****", "first_name" : "Cas", "last_name" : "User" }

I debugged the login and profile generation process and it seems that the profile data is correctly retrieved from the MongoDB and later discarded, because the are not known in the CachingPersonAttributeDaoImpl which is the attributeRepository of the PersonDirectoryPrincipalResolver. 

I have been working on this problem quite a while and there is no obvious hint in the documentation about what one needs to do to make these attributes visible.

Debugging outcome:

- The profile is created in by the profile creator called from the MongoAuthenticationHandler that extends AbstractWrapperAuthenticationHandler
- As expected, the profile has two attributes last_name -> User, first_name -> Cas
- This is then passed to create a new DefaultHandlerResult in the AbstractPac4jAuthenticationHandler
- It then reaches the AbstractAuthenticationManager.authenticateAndResolvePrincipal as a Handler Result where the principal has the two attributes
  correctly set.
- Here the resolvePrincipal method is called with the following attributes:

handler:    MongoAuthenticationHandler
resolver:   org.apereo.cas.authentication.principal.resolvers.PersonDirectoryPrincipalResolver
credential: UsernamePasswordCredential
principal:  The aforementioned Principal

After this call, the principal has no attributes left.

Within the PersonDirectoryPrincipalResolver the method retrievePersonAttributes(principalId, credential) returns null, which makes sense, since there are none defined. The attribute list is obtained from the attributeRepository which is by default an instance of CachingPersonAttributeDaoImpl.
There the person with the given id has no attributes assigned, since the only way it could have been loaded is by the process that now tries to resolves the attributes. Is there any other place where I have to declare what the possible attributes are?!

**Comment by mmoayyed** [comment]
Should be fixed in the most recent snapshot.
