### ISSUE TITLE
CAS uses the entityId as a service instead of the service itself

### ISSUE THREAD

**Issue by lsenecaux** [apereo/cas#2735]
**CAS 5.1.2-SNAPSHOT**

When CAS is configured to display the SAML metadata (cas-server-support-saml-mdui), I get an "unauthorized application to use CAS" error.
However, the service called as a parameter (here, my shibboleth IDP) is declared as an authorized service.
It would appear that CAS takes the entityId parameter as a service instead of my IDP.
I think the entityId parameter should only be used to display the service description.
Indeed, it is not possible to define ALL the services of a federation of identities.

**Comment by mmoayyed** [comment]
> Indeed, it is not possible to define ALL the services of a federation of identities.

Valid point, indeed. I have not looked at the code yet, but I envision this would be most reasonable:

- Find the entityId in metadata
- Find the entityId in service registry
- Service not authorized.

If the entityId is found in metadata sources or in the registry (removing the need for metadata), then that should work. Otherwise, the service is unauthorized.

Makes sense?

**Comment by lsenecaux** [comment]
Yes, that seems correct

**Comment by mmoayyed** [comment]
Sweet. Is this something you're prepared to handle with a PR?

**Comment by lsenecaux** [comment]
After reflection, in my opinion, only the service should be present in the registry.
The entityId is already in the "registry" of the IdP. Indeed, the SP metadata is the services authorized by the IdPs.
So only information such as name, description and logo should override the definition of the CAS service in the registry (which should be the IdP).

As for the pull request, I'm afraid not to be stuck enough in programming (especially JAVA), sorry (only for a few basic things).

However, it is with pleasure that I will help for other simpler things.

Regards,

**Comment by mmoayyed** [comment]
> After reflection, in my opinion, only the service should be present in the registry.
> The entityId is already in the "registry" of the IdP.

This is perfectly valid only with the assumption that there is metadata available for SPs in the MDUI model. This would allow you to enforce authz rules by simply saying: "SP not found in metadata, so unrecognized SP".

However, you can set up MDUI without any metadata and you can have it simply look into the CAS service registry to pull in information...in which case the SP must also be in the registry. Because you dont want `cas/login?service=myValidId&entityId=4577834567843757834658734657863478sdjhfbdjshfghjdsf` to be considered a valid request if it's not found in the metadata AND it's not found in the registry. 

I can take a look later next week possibly to ensure whether the above description matches working code. Thanks for the follow up.

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.

**Comment by lsenecaux** [comment]
I ported back the code to version 5.1 and it works like desired.

However, would it be possible to read the name and description of the metadata information only in the browser language, and if not, the English language (if available) and not all of the information in all languages ?

Thanks

**Comment by mmoayyed** [comment]
The metadata information comes from the metadata, in whatever languages they are written in. We don't translate what's in the metadata.

**Comment by lsenecaux** [comment]
I don't want to translate information.
I would to know if it possible to pick up them in browser language if available (or the first if not) instead of a concatenation of all

**Comment by mmoayyed** [comment]
I don't understand what you mean by "pick up them in browser language".

**Comment by lsenecaux** [comment]
SAML metadata can be defined like

<md:EntityDescriptor entityId="foo">
<mdui:UIInfo>
<mdui:DisplayName xml:lang="en">FOO</mdui: DisplayName>
<mdui:DisplayName xml:lang="fr">Test</mdui: DisplayName>
</mdui:UIInfo>
</md:EntityDescriptor>

I would like to know if it possible to display French "DisplayName" if I use a French browser (or display English if French description is not available).

Sorry for my English 😓

**Comment by mmoayyed** [comment]
Gotcha. No it's not possible without code.

**Comment by lsenecaux** [comment]
Will it be possible in future version (CAS  5.2.0 GA) ?

**Comment by mmoayyed** [comment]
I am not sure what you mean by "possible". If you mean, is it "planned by someone to add that support"? then no, not that I know of.

**Comment by lsenecaux** [comment]
Ok, thanks for your response

**Comment by mmoayyed** [comment]
I can try to take a look myself some time next week, but I am not sure if I can promise anything. I am assuming you can make yourself available to test this? :)

**Comment by lsenecaux** [comment]
I think I found how to solve it.
I will try to make a PR next week.

**Comment by rdev5** [comment]
@mmoayyed @lsenecaux 

You guys realize this breaks `cas-server-support-shibboleth` as documented here?
 https://apereo.github.io/cas/5.1.x/installation/Configuring-Multifactor-Authentication-Triggers.html#entity-id-request-parameter

The intent was to "allow one to activate multifactor authentication policies based on the entity id that is registered in the CAS service registry" with a side benefit of the entityID being able to "take advantage of all other CAS features such as access strategies and authorization rules."

**Comment by mmoayyed** [comment]
Have you confirmed that 5.2 or 5.1 does is in fact broken? Do you have a sample project you can share that demonstrates this?

**Comment by rdev5** [comment]
@mmoayyed I'm on 5.1.1-SNAPSHOT and have done some fairly extensive testing with service definitions at this point.

With `cas-server-support-shibboleth` compiled in, my service definition containing only the **entityID** as the `serviceId` is not invoked when receiving a delegated authentication request from a Shibboleth 3 IdP:

Login URL:
````
https://cas.example.com/login?service=https%3A%2F%2Fidp.example.com%2Fidp%2FAuthn%2FExtCas%3Fconversation%3De1s1&entityId=https%3A%2F%2Fservice.example.com`
````

````
{
  "@class": "org.apereo.cas.services.RegexRegisteredService",
  "serviceId": "^https://service\\.example\\.com",
  "name": "Shibboleth - SP",
  "id": 1,
  ...
````

Definition a service with a lower priority that matches **idp.example.com** is invoked instead.

Unfortunately, I do not have a sample project prepared for sharing at this time.

**Comment by mmoayyed** [comment]
Thanks. Could you repeat the same test with 5.1.5 plz? Anything less than the current release for a given CAS line is probably not worth the effort and if there is a problem to be fixed, it would get fixed for 5.1.5+.

**Comment by rdev5** [comment]
Thanks for getting back to me on this. Rebuilding now...

**Comment by rdev5** [comment]
Just to clarify, per the [`cas.authn.shibIdP.serverUrl`](https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties.html#shibboleth-integrations) property, given that the service URL will come through as following:

````
https://idp.example.com/idp/Authn/ExtCas?conversation=e1s1
````
Should the value of this property still be `https://idp.example.com`?

**Comment by rdev5** [comment]
Well, it appears to be detecting it... I need to actually go back to 5.1.1-SNAPSHOT to test something because I didn't have that property in there previously.

There does appear to be at least a bug in extracting the entityID in that I get the following error in `catalina.out`:

````
Unauthorized Service Access. Service [https%3A%2F%2Fservice.example.com] is not found in service registry.
````

However, as before, that is how Shibboleth IdP 3 is formatting that URL when it goes to delegate auth to CAS.

**Comment by rdev5** [comment]
Alright, results are in:

- 5.1.1-SNAPSHOT - Completely broken. CAS no longer cares about `entityID`.
- 5.1.5-SNAPSHOT - At least acknowledges the presence of an `entityID` but fails to properly URL decode it.

Best workaround to date appears to be including URL-encoded version of `serviceId`.

Example:
````
{
  "@class": "org.apereo.cas.services.RegexRegisteredService",
  "serviceId": "^(https://|https%3A%2F%2F)service\\.example\\.com$",
  "name": "Shibboleth - SP",
  "id": 1,
  "proxyPolicy": {
    "@class": "org.apereo.cas.services.RefuseRegisteredServiceProxyPolicy"
  },
  ...
}
````

**Comment by rdev5** [comment]
Just as an aside, in 5.1.5-SNAPSHOT, CAS does not displayed the "Application Not Authorized to Use CAS" message in the UI as it normally does when it is unable to find it in the service registry.

Upon successful login, the user gets returned to the same login page with the following error thrown in the logs:
````
org.apereo.cas.services.UnauthorizedServiceException: Unauthorized Service Access. Service [http%3A%2F%2Fservice.example.com] is not found in service registry.
````

**Comment by rdev5** [comment]
To update, we're abandoning this issues due to one that takes higher precedence for us here: https://github.com/apereo/cas/issues/3054
