### ISSUE TITLE
Bug in EhCacheTicketRegistry removes all tickets from ticket registry

### ISSUE THREAD

**Issue by klewczuk** [apereo/cas#2741]
CAS 5.1.0

After migration from CAS 5.0.4 to CAS 5.1.0 Authorization Code and Implicit flows do not work when using Ehcache as a ticket registry. The problem is that when getting a ticket from ehcache ticket registry there is a check if the ticket is expired:
```
EhCacheTicketRegistry.getTicket(String) line: 127
    if (element.isExpired(config) || ticket.isExpired()) {
        LOGGER.debug("Ticket [{}] has expired", ticket.getId());
        this.ehcacheTicketsCache.evictExpiredElements();
        this.ehcacheTicketsCache.flush();
        return null;
    }
```
This code is called twice for ST ticket (while performing login in Authorization Code flow). When it is called the second time, the check if ST ticket is expired returns true and then flush() on cache is called, which removes all tickets from registry. I do not use any disk store. I store tickets only in memory and the memory store is cleared by default when calling flush(). I guess remove(Object) should be used instead of flush().

This bug makes not only Authorization Code and Implicit flows do not work (because TGT is removed and later in the authorize controller cas tries to get it from the cache basing on cookie), but also removes all other tickets. This means that when one user tries to authorize through the web flow (Authotization Code or Implicit) every single ticket for every user will not work anymore.

Switching to DefaultTicketRegistry or HazelcastTicketRegistry makes the problem disappear and everything works correctly.

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.
