### ISSUE TITLE
PAC4J - Authentication Attributes are ignored by CAS 5.1.x

### ISSUE THREAD

**Issue by ssoguroo** [apereo/cas#2751]
**Environment:**
CAS 5.1.0 & 5.1.1
Tomcat 8.5

**Issue:**
CAS is configured to delegate authentication to PAC4J. When PAC4J has finished authentication, the attributes received by pac4j authentication are supposed to be passed to the AuthenticationHandler attributes. CAS can finally send them to CAS Clients based on the other configuration.

Same is the case for SAML2Client. We can clearly see the attributes sent by SAML IDP in the saml request. Somehow CAS drops those attributes sent in SAML Response.

The behavior is same for all the PAC4J Auth types: Facebook or SAML2 or Google or LinkedIn:

[cas.properties]
cas.authn.pac4j.name=facebook login
cas.authn.pac4j.typedIdUsed=true
cas.authn.pac4j.autoRedirect=true
..
..

cas.authn.pac4j.facebook.id=123
cas.authn.pac4j.facebook.secret=123
cas.authn.pac4j.facebook.scope=public_profile,email
cas.authn.pac4j.facebook.fields=id,name,first_name,middle_name,last_name,email

**Comment by ghenadiibatalski** [comment]
also 5.1.2 is affected of this problem

**Comment by ghenadiibatalski** [comment]
as of 5.2.0-RC2 from current master, the problem doesn't exist anymore (5.0.5 was also ok).
