### ISSUE TITLE
References to Jasig (instead of Apereo) in Polish and Ukrainian message files.

### ISSUE THREAD

**Issue by WhiteMarlin** [apereo/cas#2752]
Sorry for not following all the guidelines, but I'm not sure how to do the pull request in this case. (I'm not even sure this is the right repository in which to log the issue.)

Steps to reproduce on Mac OS X 10.12.5:

```
git clone https://github.com/apereo/cas-overlay-template.git
cd cas-overlay-template
mvnw clean package
grep -i jasig target/cas/WEB-INF/classes/*.properties
```

I believe there should be no output from the grep. In fact, the output is:

```
target/cas/WEB-INF/classes/messages_pl.properties:logo.title=Id\u017a na stron\u0119 domow\u0105 Jasig
target/cas/WEB-INF/classes/messages_pl.properties:copyright=Copyright &copy; 2005&ndash;2012 Jasig, Inc. Wszelkie prawa zastrze\u017cone.
target/cas/WEB-INF/classes/messages_uk.properties:application.title=Jasig Central Authentication Service
```
(And the occurrence of application.title may be vestigial.)

**Comment by mmoayyed** [comment]
First, please follow the issue template to submit issues. It's there for good reason :) It's not clear what CAS version this issue applies to? Could you elaborate?

**Comment by mmoayyed** [comment]
At any rate, the contribution guidelines are documented here https://apereo.github.io/cas/developer/Contributor-Guidelines.html Please investigate, and file a patch. If you run into a problem with that process, please post back.

**Comment by WhiteMarlin** [comment]
I am happy to elaborate! And again, I apologize, but the template did not seem appropriate. :-) As I hope the `git clone https://github.com/apereo/cas-overlay-template.git` makes clear, this is in the master branch, and not a particular version.

- [] CAS server version: ??? master branch
- [] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc): N/A
- [] Steps to duplicate the problem along with your CAS settings and properties: please see above
- [] Stacktraces and CAS DEBUG logs where appropriate.: N/A
- [] Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/ or attached to the issue.: ???

**Comment by mmoayyed** [comment]
Outstanding, thank you. 

So let me help. The overlay you run has the CAS version listed here:
https://github.com/apereo/cas-overlay-template/blob/master/pom.xml#L72

Noted by the explicit `<cas.version>` tag. 

Which means you're currently running CAS 5.1.1. 

The master branch is marching towards this version: https://github.com/apereo/cas/blob/master/gradle.properties#L24 and the next maintenance branch for 5.1.x release line is 5.1.2. Milestones are listed here https://github.com/apereo/cas/milestones

So you want to:

1. Clone the CAS repository here
2. Checkout the branch 5.1.x
3. Follow the guide to create topic branches and make changes. When done submit a PR.

**Comment by mmoayyed** [comment]
When the change is in, you can simply go back to your overlay and change the version to match this line https://github.com/apereo/cas/blob/5.1.x/gradle.properties#L24 to consume the change immediately (in about an hour actually) .

**Comment by WhiteMarlin** [comment]
Thank you. That is very helpful.

**Comment by WhiteMarlin** [comment]
I believe I have now complied. Please let me now if anything looks wrong. Thank you.

**Comment by WhiteMarlin** [comment]
FYI, re your "consume the change immediately" comment: I also had to blow away the contents of the `$HOME/.m2/repository/org/apereo/cas` directory, in order to cause a new copy of `cas-server-webapp-tomcat/5.1.2-SNAPSHOT` to be downloaded.

And ironically, the 5.1 version seems to no longer have the language selectors on the login page! I must have been running the 4.2 version before. Oh, well.

**Comment by mmoayyed** [comment]
You should not have had to. There is this:
https://github.com/apereo/cas-overlay-template#build

Use the `-U` command next time to update snapshots. If you don't see that command and script for your overlay, then chances are you were running a different version other than 5.1. 

SNAPSHOT released are published by the automatic Travis CI process:
https://travis-ci.org/apereo/cas/builds

As soon as a PR is merged, you want to track its build status and once it turns green, you should be good to update snapshots via that -U command.

Language selectors are no longer on the login page; but you can still trigger them to show up: https://travis-ci.org/apereo/cas/builds

**Comment by WhiteMarlin** [comment]
Doh! I forgot about the -U option. Thanks!

**Comment by WhiteMarlin** [comment]
You said, "Language selectors are no longer on the login page; but you can still trigger them to show up: https://travis-ci.org/apereo/cas/builds". I have two questions:

1. Should I expect to see something at that link about triggering language selectors? I don't.
1. I do see at that link that "my" master build seems to have failed, due to a timeout. Do I need to take action re that?

Thanks again.

**Comment by mmoayyed** [comment]
My apologies. Bad link. This is the correct one:
https://apereo.github.io/cas/5.1.x/installation/User-Interface-Customization-Localization.html

You do not need to take action. Leave that to me.

**Comment by WhiteMarlin** [comment]
Perfect. Thank you.
