### ISSUE TITLE
Why CAS 5.0.x  REST Authentication can not get a custom attribute value?

### ISSUE THREAD

**Issue by judasn** [apereo/cas#2753]
-------------------------------------------------------

- Development Environment :
	- **CAS Server** : 5.0.5
	- **CAS Server Authentication** : REST Authentication
	- **CAS Client** : Spring Boot import cas-client-core 3.4.1
	- **CAS Client Protocol** : CAS3

------------------------------------------------------- 

REST Authentication Server Controller return result to Cas Server is :

HTTP Response Status 200, JSON result :

``` json
{
  "id": "meek@gmail.com",
  "attributes": {
    "enName": "Meek",
    "userId": "2377"
  }
}
```

------------------------------------------------------- 

I debug the CAS Server code, In this position :

`cas-server-core-authentication-5.0.5-sources.jar!\org\apereo\cas\authentication\AbstractAuthenticationManager.java >>> protected void authenticateAndResolvePrincipal()`

Line 209 `final HandlerResult result` variables are still available, but line 231 `builder.setPrincipal(principal);` is invalid.

And my cas client is invalid too, I can not get a custom attribute value.

------------------------------------------------------- 

I hope cas client can get my custom attribute value, eg :

```
"attributes": {
	"enName": "Meek",
	"userId": "2377"
}
```

What should I do?
 
By the way, CAS Server JDBC Authentication is ok, thks!

-------------------------------------------------------

My Cas Server `application.properties` :

``` ini
server.context-path=/cas
server.port=8070
		
server.ssl.key-store=file:/etc/cas/thekeystore
server.ssl.key-store-password=changeit
server.ssl.key-password=changeit
server.max-http-header-size=2097152
server.max-http-post-size=2097152
server.ssl.enabled=false
		
server.tomcat.basedir=build/tomcat
server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%t %a "%r" %s (%D ms)
server.tomcat.accesslog.suffix=.log
server.tomcat.max-threads=5
server.tomcat.port-header=X-Forwarded-Port
server.tomcat.protocol-header=X-Forwarded-Proto
server.tomcat.protocol-header-https-value=https
server.tomcat.remote-ip-header=X-FORWARDED-FOR
server.tomcat.uri-encoding=UTF-8
server.error.include-stacktrace=ALWAYS
		
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true
		
spring.cloud.bus.enabled=false
		
endpoints.enabled=true
endpoints.sensitive=true
management.context-path=/status
endpoints.restart.enabled=false
endpoints.shutdown.enabled=false
		
server.session.timeout=300
server.session.cookie.http-only=true
server.session.tracking-modes=COOKIE
		
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
		
server.context-parameters.isLog4jAutoInitializationDisabled=true
		
spring.aop.auto=true
spring.aop.proxy-target-class=true
		
cas.authn.rest.uri=https://www.abc.com/sysUser/verify
cas.authn.rest.passwordEncoder.type=NONE
```

------------------------------------------------------- 

CAS is beautiful, thks!!

**Comment by mmoayyed** [comment]
https://apereo.github.io/2017/06/30/520rc1-release/#026-attribute-repository-merging

**Comment by judasn** [comment]
@mmoayyed 

 thks!!!!

I tried the 5.2.0-RC1 is ok.

**Comment by chenjw1985** [comment]
@judasn Did you encounter this problem as below when configuring CAS 5.0.x REST certification?

- missing property '@class' that is to contain type id
- Could not read JSON document: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property '@class' that is to contain type id (for class org.apereo.cas.authentication.principal.SimplePrincipal)
