### ISSUE TITLE
Support for "duplicate" attributes (alias)?

### ISSUE THREAD

**Issue by rdev5** [apereo/cas#2764]
I'm able to successfully implement attribute resolution and release in LDAP in CAS 5.1.1 but have a rather particular requirement for a *duplicate* attribute due to limitations in the third party client application.

Below is the expected response:
````
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    <cas:authenticationSuccess>
        <cas:user>username</cas:user>
        <cas:attributes>
            <cas:displayName>John Doe</cas:displayName>

            <cas:idAttribute>INTERNAL_ID</cas:idAttribute>
            <cas:duplicateIdAttribute>INTERNAL_ID</cas:duplicateIdAttribute>

            </cas:attributes>
    </cas:authenticationSuccess>
</cas:serviceResponse>
````
Here, consider `idAttribute` some native or custom attribute sent by LDAP. We essentially need to duplicate the same value in the CAS response, but given an alternate attribute name (i.e. `duplicateIdAttribute`).

I realize we should probably implement this as a service-specific attribute release configuration, but it seems this "facility" is almost already implemented where you already have the ability to rename attributes (i.e. `cas.authn.ldap[0].principalAttributeList=idAttribute:duplicateIdAttribute`).

The only problem is listing `idAttribute` more than once in the same list (either `defaultAttributesToRelease` or `principalAttributeList`) seems to get clobbered and you get one or the other, not both, even with `cas.authn.attributeRepository.merger=ADD`.

The only way I'm presently able to accomplish the above is by "cloning" LDAP connection settings as an attribute repository (i.e. `cas.authn.attributeRepository.ldap[0].ldapUrl=${cas.authn.ldap[0].ldapUrl}`) under this merge strategy and then adding the duplicate attribute to the repository's attributes (i.e. `cas.authn.attributeRepository.ldap[0].attributes.idAttribute=duplicateIdAttribute`).

My understanding of attribute resolution is that while this does in fact work, it will incur an additional hop to LDAP for this duplicate attribute. It seems like a small code change to treat `principalAttributeList` as an array vs. a set (unique keys) would achieve this and save the extra hop.

Thoughts?

**Comment by mmoayyed** [comment]
> The only problem is listing idAttribute more than once in the same list (either defaultAttributesToRelease or principalAttributeList) seems to get clobbered and you get one or the other, not both, even with cas.authn.attributeRepository.merger=ADD.

You want to investigate and figure out why this gets clobbered before making a change. Once you do find it, that would be the area to make the change. Follow that up with a PR so that it can be reviewed with follow-up suggestions.

**Comment by mmoayyed** [comment]
I also suspect that this isn't possible because that list turns into a map at some point which disallows duplicate keys. You may need to resort to 1) custom change 2) a separate attribute repository.

However, the best option is to yell at the application though it may not be all that practical.

**Comment by mmoayyed** [comment]
Also, perhaps a bit of synttactic sugar might be useful here:

`cas.authn.ldap[0].principalAttributeList=idAttribute:(idAttribute,duplicateIdAttribute)`

Where the underlying machinery is smart enough to rename idAttribute to what is listed in the parenthesis. Would that work?

**Comment by mmoayyed** [comment]
So thought about this some more. The issue is that the underlying store for handling renames is a map which disallows duplicate keys.

Because you ideally want to be able to do:

```
cas.authn.ldap[0].principalAttributeList=idAttribute:idAttribute, idAttribute:duplicateIdAttribute
```

Or

```
cas.authn.ldap[0].principalAttributeList=idAttribute, idAttribute:duplicateIdAttribute
```

So you want to look into the area that transforms these definitions into a Map and change its behavior so it can keep track of a list under a key (hint: Multimap) and then change the other areas that can operate based on this. I dont think this solution is any prettier than what you have, and is most definitely not appropriate for 5.1.x. So I'd recommend you stick with the changes you have now and if it peaks your interest, add the change to `master` and get it in 5.2.x.

**Comment by rdev5** [comment]
I'll stick with the changes I have now and try to pretend I don't see that second hop. All in all, small price to pay to achieve the data set we need and only incurred once per session anyways.

Per the original application-specific requirements, I think my preferred long-term fix would be to create a service-specific attribute release policy for that application vs. making these code changes.

**Comment by mmoayyed** [comment]
Yup that's probably a better choice, or worst case you simply write a groovy script that does it all. I would however think about this for `master` and see how that might work, because this sort of thing was/is possible with the old person directory configuration and CAS today should be able to support it.

**Comment by mmoayyed** [comment]
You may also want to try with 5.2 RC2 SNAPSHOT which I think fixes/allows for this sort of thing. Sorry, should have checked earlier :)
