### ISSUE TITLE
CAS 5.0.4  click "Reset your password" not working

### ISSUE THREAD

**Issue by hsj1606** [apereo/cas#2796]
![default](https://user-images.githubusercontent.com/12151317/28320495-50be6984-6c03-11e7-8775-42743e6c0503.png)

CAS 5.0.4 , the "#misagh" form does not exist, I want use change password feature with following config:

cas.authn.pm.enabled=true
cas.authn.pm.policyPattern=^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[$@$!%*?&])[A-Za-z\\d$@$!%*?&]{8,10}

cas.authn.pm.reset.text=Reset your password with this link: %s
cas.authn.pm.reset.subject=Password Reset Request
cas.authn.pm.reset.from=
cas.authn.pm.reset.expirationMinutes=1
cas.authn.pm.reset.emailAttribute=mail
cas.authn.pm.reset.securityQuestionsAttributes.attrQuestion1=attrAnswer1
cas.authn.pm.reset.securityQuestionsAttributes.attrQuestion2=attrAnswer2
cas.authn.pm.reset.securityQuestionsAttributes.attrQuestion3=attrAnswer3

**Comment by mmoayyed** [comment]
Thanks for the logging the issue report. This seems like something that might need fixing. As the next step, please [review this guide](https://apereo.github.io/2017/07/05/cas-contribution-guide/) to get started.

You can also learn how to build and run CAS [from here](https://apereo.github.io/cas/developer/Build-Process.html).

Thanks again!
