### ISSUE TITLE
JPA Ticket Registry Cleaner not found transaction

### ISSUE THREAD

**Issue by aleixce** [apereo/cas#2798]
TransactionRequiredException: No EntityManager with actual transaction available for current thread

- Affected modules: cas-server-support-jpa-ticket-registry
- CAS server version: 4.2.6 / 4.2.7
- Container/environment type/version: Tomcat 8.0.28 and JBoss EAP 7

1. org.jasig.cas.ticket.registry.TicketRegistryCleaner uses registry.deleteTicket(ticket.getId());
2. This method is implemented by org.jasig.cas.ticket.registry.AbstractDistributedTicketRegistry, not by org.jasig.cas.ticket.registry.JpaTicketRegistry
3. TransactionInterceptor is not attached to this method, so no transaction is available when delete is called.

To fix is only needed to add this code on: 

**[cas-server-support-jpa-ticket-registry] org.jasig.cas.ticket.registry.JpaTicketRegistry**

```
    @Override
    public int deleteTicket(final String ticketId) {
    	return super.deleteTicket(ticketId);
    }
```

This grants that TransactionManager will be atached to this method, and jpa cleaner works fine.

Wrong stack trace:
	SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(Object, Method, Object[]) line: 277	
	$Proxy90.remove(Object) line: not available	
	JpaTicketRegistry.removeTicket(Ticket) line: 89	
	JpaTicketRegistry.deleteTicketsFromResultList(List<Ticket>) line: 211	
	JpaTicketRegistry.deleteTicketGrantingTickets(String) line: 241	
	JpaTicketRegistry.deleteSingleTicket(String) line: 167	
	JpaTicketRegistry(AbstractTicketRegistry).deleteTicket(String) line: 98	
	AbstractTicketRegistry$$FastClassBySpringCGLIB$$b70f3271.invoke(int, Object, Object[]) line: not available	
	MethodProxy.invoke(Object, Object[]) line: 204	
	CglibAopProxy$DynamicAdvisedInterceptor.intercept(Object, Method, Object[], MethodProxy) line: 651	
	JpaTicketRegistry$$EnhancerBySpringCGLIB$$32e89c2b.deleteTicket(String) line: not available	
	NativeMethodAccessorImpl.invoke0(Method, Object, Object[]) line: not available [native method]	
	NativeMethodAccessorImpl.invoke(Object, Object[]) line: 62	
	DelegatingMethodAccessorImpl.invoke(Object, Object[]) line: 43	
	Method.invoke(Object, Object...) line: 497	
	AopUtils.invokeJoinpointUsingReflection(Object, Method, Object[]) line: 302	
	JdkDynamicAopProxy.invoke(Object, Method, Object[]) line: 202	
	$Proxy91.deleteTicket(String) line: not available	
	TicketRegistryCleaner.execute(JobExecutionContext) line: 150	
	JobRunShell.run() line: 202	
	SimpleThreadPool$WorkerThread.run() line: 573

**Comment by mmoayyed** [comment]
https://apereo.github.io/cas/developer/Maintenance-Policy.html

_Sent from my Google Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
