### ISSUE TITLE
Thread block when starting

### ISSUE THREAD

**Issue by hsj1606** [apereo/cas#2799]
CAS 5.1.2 using json service registry

![image](https://user-images.githubusercontent.com/12151317/28398459-dee0c112-6d39-11e7-9269-7689ff5587d1.png)

**Comment by mmoayyed** [comment]
Have you looked into the code to figure out what's happen and why?

**Comment by hsj1606** [comment]
No, that's why I'm asking for help

**Comment by mmoayyed** [comment]
There is not much to glean from your report. The best approach would be to step into the code and figure out why this is happening. Looks like it might be related to the functionality where service files are monitored and watched. You may want to experiment with that.

Once you figure out a solution, by all means post a patch that fixes the problem.
