### ISSUE TITLE
MongoDB Configuration broken

### ISSUE THREAD

**Issue by karlbanke** [apereo/cas#2806]
We are using 5.2.0-RC1 and are experiencing unexpected issues with MongoDB. We are using both the MongoDB Ticket and Service Registry. Configuration of the two as per the documentation seems to imply that these are two different configuration with two distinct data sources. This is not the case! The first datasource generated will win. The reason is that the actual construction of the datasource takes place in the abstract superclass AbstractMongoConfiguration. This superclass creates a MongoTemplate and a MongoRegistryFactory and defines beans with the respective method names.  When called for the second time the call will be intercepted and the object created returned.

**Comment by mmoayyed** [comment]
Thanks for the logging the issue report. This seems like something that might need fixing. As the next step, please [review this guide](https://apereo.github.io/2017/07/05/cas-contribution-guide/) to get started.

You can also learn how to build and run CAS [from here](https://apereo.github.io/cas/developer/Build-Process.html).

Thanks again!
