### ISSUE TITLE
Can't close Hibernate log like this ：  Hibernate:XXX

### ISSUE THREAD

**Issue by Tinet-lizheng** [apereo/cas#2818]
I can not control the log like this：Hibernate: select properties0_.AbstractRegisteredService_id as Abstract1_2_0_, properties0_.properties_id as properti2_2_0_, properties0_.properties_KEY as properti3_0_, defaultreg1_.id as id1_1_1_, defaultreg1_.property_values as property2_1_1_ from RegisteredServiceImpl_Props properties0_ inner join RegexRegisteredServiceProperty defaultreg1_ on properties0_.properties_id=defaultreg1_.id where properties0_.AbstractRegisteredService_id=?

please tell me where to close it

**Comment by mmoayyed** [comment]
https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties-Common.html#hibernate--jdbc

**Comment by Tinet-lizheng** [comment]
Thank you very much！
