### ISSUE TITLE
SAML ticket validation in 5.x

### ISSUE THREAD

**Issue by kingjared** [apereo/cas#2836]
CAS server version: 5.1.2
Container: Tomcat

I believe I've come across a bug in the SAML ticket validation feature as of version 5.x. In 4.x there was a 30 second interval between the `NotBefore` and `NotOnOfAfter` conditions in the SAML assertion, like the one below:
```
<Conditions NotBefore="2008-12-10T14:12:14.817Z" NotOnOrAfter="2008-12-10T14:12:44.817Z">
```

As of version 5.x, the two timestamps are the same by default, which is causing an application we use to see the assertions as expired. From what I've been able to determine, the SAML object builder is expecting an `issueLength` parameter ([see here](https://github.com/apereo/cas/blob/v5.1.2/support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/util/Saml10ObjectBuilder.java#L121)) but the value is set by the `skewAllowance` property ([see here](https://github.com/apereo/cas/blob/v5.1.2/support/cas-server-support-saml/src/main/java/org/apereo/cas/support/saml/web/view/Saml10SuccessResponseView.java#L89)). I'm assuming this is a mistake since the `skewAllowance` property is set to zero by default.

I've been able to work around this issue temporarily by hardcoding a value of `30000` for the `intervalLength` (30 secs), and I can confirm this results in correct values for the `NotBefore` and `NotOnOfAfter` conditions. My apologies for not including a pull request with this, but I'm not much of a Java developer and don't know how this should be handled going forward. Maybe add a `cas.samlCore.intervalLength` property?

**Comment by mmoayyed** [comment]
> I'm assuming this is a mistake since the skewAllowance property is set to zero by default.

If you adjust skewAllowance, does the problem go away?

**Comment by mmoayyed** [comment]
Added defaults for skewAllowance up to 5 seconds.

**Comment by kingjared** [comment]
I did try the skewAllowance, but that just controls how many seconds (forward or backward) to shift the assertion validity period. The intervalLength also uses milliseconds (with a default of 30000 in 4.x), so I can't use this property to adjust that effectively.

**Comment by mmoayyed** [comment]
The skewAllowance that is passed to the `Saml10SuccessResponseView` builds the conditions block:

```
final Conditions conditions = this.samlObjectBuilder.newConditions(issuedAt, service.getId(), this.skewAllowance);
```

And as you note, the allowance is used to skew the `NotOnOrAfter`:

```
conditions.setNotOnOrAfter(DateTimeUtils.dateTimeOf(issuedAt.plus(issueLength, ChronoUnit.MILLIS)));
```

You can try changing the above line to:

```
conditions.setNotOnOrAfter(DateTimeUtils.dateTimeOf(issuedAt.plus(issueLength, ChronoUnit.SECONDS)));
```

and that should allow you to keep both consistent. Would that work?

**Comment by kingjared** [comment]
Unfortunately that still wouldn't work - the skewAllowance is currently used to shift the validity period backwards by the number of seconds specified (and forwards for negative values). For example, a value of 30 would set `NotBefore` to 30 seconds in the past. The `NotOnOrAfter` value would be 30 seconds later as expected, but the assertion would still end up with an expired validity period.

**Comment by mmoayyed** [comment]
Excellent diagnosis; so in addition to making time units consistent, how about we ensure the assertion validity period uses the same sort of logic as the conditions block?

Meaning both:

1. Use seconds
2. Positive skew shifts the period forward.
3. Negative skew pushes the period backward.

This seems like the better approach altogether and it's less confusing overall (and I cant think of a case where you want to be able to control these things individually and separately, that is the issue length and the condition), but if you feel like a separate property is easier to do and understand, by all means please do.

**Comment by kingjared** [comment]
I agree completely about making that consistent - using seconds and making positive values shift that forward instead of backward would be much more intuitive. That being said, I think the validity interval should be independent from the skewAllowance property, which has a completely different purpose. Ideally I'd like to see the default behavior restored back to what was in 4.x - meaning a default validity interval of 30 seconds by default and a skewAllowance of zero. The application we use with this feature (Ellucian Banner) is expecting 4.x behavior and I'm guessing this would make it easier for Ellucian to certify 5.x in the future.

**Comment by mmoayyed** [comment]
Sounds very reasonable. In fact, there is no reason why we can't do both options and in the meanwhile, restore the behavior back to what 4.1 is doing in terms of defaults, etc. 

Given we have consensus here (and thank you very much for reporting this and sticking with me throughout this brainstorming session) I am going to tag this appropriately. Feel free to submit the PR when and where you can.

**Comment by crdaudt** [comment]
Thanks all for your good work on this, which got us up and running with Ellucian Banner 9 SSO.  We upgraded our production CAS server yesterday to v5.1.3, then discovered that CAS authentication for our Banner 9 instance (not yet in production) failed due to the SAML ticket validation failure resulting from an invalid SAML assertion (i.e., because it was immediately expired).  As pointed out in this thread, CAS 4.x allowed for a 30 second interval for which the SAML assertion, so Banner 9 SSO worked with the older CAS.  CAS 5.1.x up through 5.1.3 allowed zero seconds, leaving Banner 9 SSO broken.

The good news is that, since you implemented the cas.samlCore.issueLength property in CAS v5.1.4, Banner 9 SSO works like a charm without our having to configure anything else.  Thank you!
