### ISSUE TITLE
Cas30ResponseView can generate invalid XML if an attribute key has invalid XML character

### ISSUE THREAD

**Issue by jeffreyindc** [apereo/cas#2841]
- [] CAS server version 5.1 & 5.2
- [] Container/environment type/version ALL

My usernames can be emails.  The LdapAuthenticationHandler  adds an attrbute LdapAuthenticationHandler.{username} .  An example is LdapAuthenticationHandler.fredfred6@mailinator.com.  

The Cas30ResponseView will then generate invalid XML for the attribute <cas:LdapAuthenticationHandler.fredfred6@mailinator.com>fredfred6@mailinator.com</cas:LdapAuthenticationHandler.fredfred6@mailinator.com>

You could argue that the error is not in Cas30ResponseView but in the class that caused the attribute to be created.  I think that would require may separate modules to know how the protocols work.  

I fixed it on my server by overriding Cas30ResponseView.java with the following code.  I code make a pull request but XMLChar is from xalan and that is not a dependency of cas-server-support-validation.  If you have another suggestion I would do that to.  

```
15d4
< import org.apache.xml.utils.XMLChar;
136c134
<             final String kEscaped = fixElementName(k);
---
> 
139c137
<                         .append("<cas:".concat(kEscaped).concat(">"))
---
>                         .append("<cas:".concat(k).concat(">"))
141c139
<                         .append("</cas:".concat(kEscaped).concat(">"))
---
>                         .append("</cas:".concat(k).concat(">"))
148,163d145
<     }
<     
<     private String fixElementName(String data) {
<     	final StringBuilder builder = new StringBuilder();
<     	
<     	for (int i = 0; i < data.length(); i++) {
<             char c = data.charAt(i);
< 			if (XMLChar.isName(c)) {
<                 builder.append(c);
<             } else {
<             	builder.append('_');
<             }
<         }
< 
<     	
<     	return builder.toString();
```

Here is the full XML generated and top of the exception thrown by the client

```xml
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    <cas:authenticationSuccess>
        <cas:user>fredfred6@mailinator.com</cas:user>
        <cas:attributes>
            <cas:LdapAuthenticationHandler.fredfred6@mailinator.com>fredfred6@mailinator.com</cas:LdapAuthenticationHandler.fredfred6@mailinator.com>
            <cas:isFromNewLogin>true</cas:isFromNewLogin>
            <cas:authenticationDate>2017-08-10T17:12:24.724-04:00[America/New_York]</cas:authenticationDate>
            <cas:authenticationMethod>LdapAuthenticationHandler</cas:authenticationMethod>
            <cas:successfulAuthenticationHandlers>LdapAuthenticationHandler</cas:successfulAuthenticationHandlers>
            <cas:fromCas>true</cas:fromCas>
            <cas:longTermAuthenticationRequestTokenUsed>false</cas:longTermAuthenticationRequestTokenUsed>
            <cas:username>fredfred6@mailinator.com</cas:username>
            </cas:attributes>
    </cas:authenticationSuccess>
</cas:serviceResponse>
```

```
Aug 10 17:12:25 Jeff[9998] ERROR org.jasig.cas.client.util.XmlUtils  - Element type "cas:LdapAuthenticationHandler.fredfred6" must be followed by either attribute specifications, ">" or "/>".
SAXParseException: Element type "cas:LdapAuthenticationHandler.fredfred6" must be followed by either attribute specifications, ">" or "/>".
  at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(null:Unknown)
  at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(null:Unknown)
```

 Steps to duplicate the problem along with your CAS settings and properties
Make a attribute with a @ in the name

**Comment by mmoayyed** [comment]
- In 5.2 simply set the setting to not collect dn as an attribute
- Backport the same sort of setting to 5.1 if you wish to turn off the same behavior
- If you do need DN as an attribute, you need to add the special @ character into the CASProtocolAttributeEncoder and do things there where "special" attributes are hex encoded. 

Thanks very much.
