### ISSUE TITLE
Leading space on username causes p3/serviceValidate template error

### ISSUE THREAD

**Issue by tsschmidt** [apereo/cas#2853]
Found this working on 5.1.2.

If a user puts a leading space on the username when authenticating, our LDAP must trim or ignore it, because validation succeeds.  Protocols v1 and v2, don't seem to have a problem with it, but when using v3  the template errors because an invalid xml tag is created:

```
<cas:LadapAuthenticationHandler. username>
```

line 213 in LdapAuthenticationHandler seems to be the cause:

```java
   final String dnAttribute = getName().concat(".").concat(username);
```

switching the "username" field for what was retrieved in "id" earlier in the method, seems to be the way to go since that is the checked username from Ldap.

**Comment by mmoayyed** [comment]
Closed via https://github.com/apereo/cas/commit/35620a54566b8f3a75ea2847ff2bf0bf2607a041
