### ISSUE TITLE
CAS SSO SERVICE_TICKET_VALIDATE_FAILED 

### ISSUE THREAD

**Issue by anouar99pac** [apereo/cas#2860]
Hi all,

I'm facing a problem of ticket validating on cas 4.2.7.
I do tests with curl.
There is the steps I do to reproduce problem :

1/Login and get TGT

`curl -X POST https://int-sso.example.com/cas/v1/tickets -d "username=xxx&password=xxx"`

--> I catch TGT : TGT-14-scrMLORgxLfThHRCOnVh66wI2f9DrPOzSasCRfseSECZnGcXM4-int-sso.example.com
Get ST according to TGT

`curl -X POST https://int-sso.example.com/cas/v1/tickets/TGT-14-scrMLORgxLfThHRCOnVh66wI2f9DrPOzSasCRfseSECZnGcXM4-int-sso.example.com -d "service=https%3A%2F%2Fapp.example.com%2Flogin"`

--> I catch ST : ST-1764-1lAgfQwbrmpIsp5c2kcT-int-sso.example.com

**Finally**, I ask CAS to validate my ticket, and I always have same answer :

Call : 
`https://int-sso.example.com/cas/p3/serviceValidate?ST-1764-1lAgfQwbrmpIsp5c2kcT-int-sso.example.com&service=https%3A%2F%2Fapp.example.com%2Flogin`

**response :**

```
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
    <cas:authenticationFailure code='INVALID_TICKET'>
            Ticket &#039;ST-1764-1lAgfQwbrmpIsp5c2kcT-int-sso.example.com&#039; not recognized
    </cas:authenticationFailure>
</cas:serviceResponse>
```

And in catalina.out, I have the same thing :

> WHO: audit:unknown
> WHAT: TGT-***********************************************t0Tc3Y9B3x-int-sso.example.com
> ACTION: TICKET_GRANTING_TICKET_CREATED
> APPLICATION: CAS
> WHEN: Thu Aug 17 16:49:11 CEST 2017
> CLIENT IP ADDRESS: xxx
> SERVER IP ADDRESS: 172.20.1.8

> WHO: user@xx.com
> WHAT: ST-1764-1lAgfQwbrmpIsp5c2kcT-int-sso.example.com for https://app.example.com/login
> ACTION: SERVICE_TICKET_CREATED
> APPLICATION: CAS
> WHEN: Thu Aug 17 16:49:42 CEST 2017
> CLIENT IP ADDRESS: xxx
> SERVER IP ADDRESS: 172.20.1.8
> 

> 2017-08-17 16:50:09,663 DEBUG [org.jasig.cas.audit.spi.TicketOrCredentialPrincipalResolver] - <Resolving argument [String] for audit>
> 2017-08-17 16:50:09,663 DEBUG [org.jasig.cas.CentralAuthenticationServiceImpl] - <Ticket [ST-1764-1lAgfQwbrmpIsp5c2kcT-int-sso.example.com] by type [Ticket] cannot be found in the ticket registry.>
> 2017-08-17 16:50:09,665 DEBUG [org.jasig.cas.audit.spi.TicketOrCredentialPrincipalResolver] - <Could not locate ticket [ST-1764-1lAgfQwbrmpIsp5c2kcT-int-sso.example.com] in the registry>
> 2017-08-17 16:50:09,665 INFO [org.jasig.inspektr.audit.support.Slf4jLoggingAuditTrailManager] - <Audit trail record BEGIN
> 

> WHO: audit:unknown
> WHAT: ST-1764-1lAgfQwbrmpIsp5c2kcT-int-sso.example.com
> ACTION: SERVICE_TICKET_VALIDATE_FAILED
> APPLICATION: CAS
> WHEN: Thu Aug 17 16:50:09 CEST 2017
> CLIENT IP ADDRESS: xxx
> SERVER IP ADDRESS: 172.20.1.8
> 

Am I doing something wrong ?

Thanks

**Comment by anouar99pac** [comment]
Why you closed the issue without comment !!!

**Comment by mmoayyed** [comment]
I believe the tag explains it all.
