### ISSUE TITLE
Difference in behavior when an error occurs with refresh_token grant type compared to other grant types

### ISSUE THREAD

**Issue by madyx** [apereo/cas#2903]
In the case of a token (oidc) or access_token (OAuth) request using "refresh_token" as grant_type, if we provide an invalid refresh_token, then we get an error with status code 400 (bad request) with the message "invalid_grant".

However if I list and compare all grant types behaviors, then we have :
 - **grant_type=authorization_code**
   401 Unauthorized error (with json response body) if the code is invalid
 - **grant_type=password**
   401 Unauthorized error (with json response body) if the login/password pair is invalid
 - **grant_type=refresh_token**
   _400 Bad request error (with raw text message "invalid_grant" in response body) if the refresh_token is invalid_

This is happening with either OAuth or OpenIdConnect cases.

In my opinion the refresh_token grant type should behave like authorization_code or password. Is the current behavior wanted this way ?

**Comment by mmoayyed** [comment]
It's likely an oversight. You are more than welcome to change this of course.
