### ISSUE TITLE
MongoDB ticket registry not working as expected

### ISSUE THREAD

**Issue by j2ro** [apereo/cas#2908]
**To Reproduce**

My setup validates the username and password against a MySQL database using the cas.authn.jdbc.query. It also uses MongoDB for the service registry and ticket registry.

Unfortunately when I enable the MongoDB ticket registry, I get errors when trying to log in to services, e.g. https://localhost:8443/cas/login?service=http://localhost:3000 (although strangely enough, login seems to work fine when no services are specified).

**Issue Report**

**CAS server version** 
5.1.0

**Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)**
Jetty via Overlay on MacOX El Captain 

**Steps to duplicate the problem along with your CAS settings and properties**
See attached properties file and pom.xml

[cas-config-and-logs.zip](https://github.com/apereo/cas/files/1277267/cas-config-and-logs.zip)

**Stacktraces and CAS DEBUG logs where appropriate**
See attached log files

**Configuration/Overlay pushed to https://github.com/cas-projects/cas-issues/ or attached to the issue.**

**Comment by mmoayyed** [comment]
Your best course of action is to first upgrade to the latest 5.1.x line, join the mailing list and then debug the code to figure out why the error happens. Post back once you find something. Thank you.

**Comment by j2ro** [comment]
Seems to be working with CAS 5.1.3. Thank you!

**Comment by mmoayyed** [comment]
Outstanding. Thank you for the feedback!

**Comment by mmoayyed** [comment]
PS remember to keep up with releases and when in doubt, always upgrade.
