### ISSUE TITLE
Need documentation update for configuring CAS Service Management Web App

### ISSUE THREAD

**Issue by rdev5** [apereo/cas#2913]
Can we please get this documentation updated for CAS 5.1.x?

https://github.com/apereo/cas/blob/5.1.x/docs/cas-server-documentation/installation/Configuration-Properties.md#management-webapp

- Clarify which settings should go into [`management.properties`](https://github.com/apereo/cas-services-management-overlay/blob/master/etc/cas/config/management.properties) loaded by the `cas-management` application and which should go into `cas.properties` (documentation implied).
- Specify how to define the same service registry. For example, defining `cas.serviceRegistry.config.location` in `cas.properties` to use Resource-based (JSON) service registry is not presently applied by the CAS Management Web App as shown by `catalina.out` logs (CAS reports # services loaded from JsonServiceRegistryDao whereas CAS Management Web App reports 0 services loaded from InMemoryServiceRegistry)
- There are notable configuration differences between [4.2.x](https://apereo.github.io/cas/4.2.x/installation/Installing-ServicesMgmt-Webapp.html), [5.0.x](https://apereo.github.io/cas/5.0.x/installation/Configuration-Properties.html#management-webapp), and [5.1.x](https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties.html#management-webapp) but they all reference the same [web app](https://github.com/apereo/cas-services-management-overlay). Need the latest list of settings we should be using for at least CAS 5.1.x to see changes take effect.

**Comment by mmoayyed** [comment]
I'll try to take a pass tomorrow and write some. Thanks for the feedback. I'd say that the focus should be on 5.1 and master for the time being, and all else can be "backported" conditionally on demand with help. master/5.1 should be identical at this point I believe (except master looks so much cooler!) so I'll write a bit and have you review it to see if you have other questions that I can answer before moving the same batch over to 5.1. Sound good?

**Comment by rdev5** [comment]
Sounds like a plan. Thanks!

**Comment by mmoayyed** [comment]
So some high level answers; I'll let you riff on these and add/remove as best as you see fit:

The management web application has the ability to run with an embedded tomcat. In that case, any setting that applies to an embedded tomcat container in a spring boot application applies. If you decide to run externally, then tomcat-related settings do not apply.

The overlay that ships should give you all the baseline expected settings required of you to change. If you need to do more stuff, you need to look at the relevant settings in the docs to, for instance, figure out how to execute elaborate authz rules if you need to.

Then, per the docs:

> You MUST keep in mind that both applications (the CAS server and the services management webapp) share the same service registry configuration for CAS services. The persistence storage for services MUST be the same as that of the CAS server.

Which would stand to reason that if you have added dependency X to manage services in CAS, the same dependency in the same exact way (gradle vs maven aside) would need to be added to that webapp too, along with all of its settings that would then be placed inside management.properties file.

**Comment by mmoayyed** [comment]
@rdev5 Is what is described above helpful? do you need more specifics?

**Comment by rdev5** [comment]
Sorry for the delay in replying.

I think it does help clarify a little bit. I just looked at our `build.gradle` file again this morning and noticed that we did have `cas-server-support-json-service-registry` declared in the CAS project but not necessarily in the management web application which I presume is why it wasn't picking it up.

I guess the only point of clarification left from my standpoint would be to review the CAS configuration properties specific to the [Management Webapp](https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties.html#management-webapp) and consider **moving them** to `management.properties` documentation in that project to eliminate confusion as to where they should be defined.

Any settings on the [Configuration Properties](https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties.html) suggests the use of `cas.properties` which in this case may not apply.

Thoughts?

**Comment by mmoayyed** [comment]
No worries.

>...which I presume is why it wasn't picking it up.

Yes.

> Any settings on the Configuration Properties suggests the use of cas.properties which in this case may not apply.

Valid point. I suggest the following:

- For management webapp overlay (and perhaps for CAS' own documentation as well) add a new notes that clarify the explicit use of `management.properties`. You have to keep in mind that these are two separate applications, deployed at times entirely separately that know nothing about each other. They share only the name "cas". Therefore, while I understand the confusion, there is very little that they can *automatically* share (as in, just because you have a cas.properties file, it doesn't mean everything in it would get used by the management app; that would be assuming too much)

- In terms of updating the documentation, I would suppose the bare minimum you have in management.properties should do fine. You might want to try moving a number of boot specific properties over too, (like server.*, etc). I am not sure you need much though really...and it depends also whether you wish to use the embedded tomcat or an external one, in which case some of those settings simply dont apply (yet folks tend to copy everything and confuse themselves!) But if you feel like moving some over and clarifying these would be best, by all means.

**Comment by mmoayyed** [comment]
Closing in favor of the conversation at this PR https://github.com/apereo/cas-services-management-overlay/pull/20
