### ISSUE TITLE
Non web based SSO Authentication - Best Practice CAS 5.1.1 server

### ISSUE THREAD

**Issue by danoharehss** [apereo/cas#2917]
We are evaluating CAS 5.1 server with LDAP configured for we based applications.

I am looking into protecting an external standalone java application using CAS alongside some other web based applications.

This standalone application ideally needs to authenticate through a library, but obviously will not have cookie access. Is there a recommended approach for this scenario or are Rest API and CAS Proxy Authentication the only options? 

Particularly if the standalone application authenticates after the web based applications register an authentication how does it acquire the correct CAS context?

Alternatively if the external application authenticates first, is there anything special needed to create a cookie that can be seen by the other protected web applications, or will the cas server take care of this?

We intend to use a single user context across all applications, once authentication has been successful.

Many Thanks,

Dan

**Comment by mmoayyed** [comment]
Please join the mailing list to start the discussions. This is not the relevant place. Thank you.

**Comment by danoharehss** [comment]
Here is a link to what I raised on the mailing lists https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/D6rrJWf1vX8 on September 4th 2017
