### ISSUE TITLE
Intermittent memcached deserialization exception

### ISSUE THREAD

**Issue by bsandiford** [apereo/cas#2921]
[deserialze_debug_log.txt](https://github.com/apereo/cas/files/1296311/deserialze_debug_log.txt)
CAS server version 5.1.3
  (1.0 cas server overlay)
Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
  embedded tomcat in the cas server overlay project
Steps to duplicate the problem along with your CAS settings and properties
  See PR on cas server overlay from bsandiford, titled "memcached deserialize"
Stacktraces and CAS DEBUG logs where appropriate.
See attached debug

**Comment by mmoayyed** [comment]
Thanks for the logging the issue report. This seems like something that might need fixing. As the next step, please [review this guide](https://apereo.github.io/2017/07/05/cas-contribution-guide/) to get started.

You can also learn how to build and run CAS [from here](https://apereo.github.io/cas/developer/Build-Process.html).

Thanks again!
