### ISSUE TITLE
CAS delegate cas protocol configuration problem.

### ISSUE THREAD

**Issue by CobraFlow** [apereo/cas#2939]
CAS Server: 5.1.4
cas-server-support-pac4j-webflow : 5.1.4

When I try to set the property cas.authn.pac4j.cas[0].protocol to CAS20 I get a malformed URL exception.

I think that this is due to the incorrect CasConfiguration constructor (String, String) being called. The Pac4jProperties.Cas protocol property should be of type CasProtocol.

If this is the correct diagnosis, I can patch it and create a PR.

Cheers

**Comment by mmoayyed** [comment]
Thanks for the find. Your diagnosis is correct. Rather than changing the type, simply parse and cast in the ctor. (`CasProtocol.valueOf(...)`)
