### ISSUE TITLE
Provide flow and views for managing password request questions

### ISSUE THREAD

**Issue by marwatk** [apereo/cas#2950]
Is there any interest in allowing users to manage security questions in CAS itself? We have a home-grown interface to do so bolted on to CAS 4 right now. As part of our migration to CAS 5 I need to either make the old one work or modify cas-server-support-pm and related modules to allow for editing security questions.

I'd much rather go the second route and get it built in to base CAS (fewer migration issues in the future). But, if I go this route and I _can't_ get it in base CAS it'll end up far worse than the first option since I'd be editing/overlaying actual CAS files.

Let me know...

**Comment by mmoayyed** [comment]
May I see some screenshots?

**Comment by mmoayyed** [comment]
and also, I'd like to see how you have managed to do this with CAS 4. Seeing a concrete impl would help to evaluate; even if it's just notes at a high level.

**Comment by marwatk** [comment]
"Bolted on" was probably the wrong term to use. The CAS 4 implementation we have is not really how it would/should/could be implemented for CAS 5 (whether into base CAS or not). To start off, the existing add-on replaces both `login-webflow.xml` and `web.xml` with heavily modified versions. The new CAS 5 stuff we're doing doesn't use xml at all. We're trying to avoid modifying/overlaying CAS code altogether. I'm not really sure how much of the existing code is even usable while maintaining a small modification footprint.

I'll see if I can get approval to share screenshots.

If question management isn't a feature you guys are interested in including in `cas-server-support-pm` I'll probably take the guts of `cas-server-support-consent` or `cas-server-support-aup` and create a `cas-server-support-pm-editquestions` (or a better named version). Maybe that's the right approach to take regardless?

**Comment by marwatk** [comment]
![image](https://user-images.githubusercontent.com/3507341/30830123-16ed92e2-a200-11e7-9121-8866f2f9c89f.png)

![image](https://user-images.githubusercontent.com/3507341/30830168-42c5ced4-a200-11e7-9511-6f9b0b57f7ef.png)

These are the two portions that handle the question stuff. There's an 'Update my settings' link on the login page that will trigger the flow interruption.

The second shot is where the actual changes are made.

**Comment by mmoayyed** [comment]
Thanks for the screenshot. It goes without saying that we (I) are interested. I'd recommend that you start with a WIP pull request and continue. Remember the cutoff for RC4 and note that it's rare for changes to go in post RC4. Time yourself accordingly, or worse we shall push this into the 5.3 line. Also remember that this behavior you are adding must not be tied to a specific store implementation for pm. Regardless of store, all should be supported (which might increase your initial scope).

If you need help with anything, please post back. 

> Maybe that's the right approach to take regardless?

Yes, that what you will need to be doing anyways. I'd welcome a better-named module for sure.

**Comment by mmoayyed** [comment]
Going to close this for now. I look forward to reviewing the PR and working with you to finalize this.
