### ISSUE TITLE
Duo MFA breaks Remember Me

### ISSUE THREAD

**Issue by jmulvey123** [apereo/cas#2957]
I am trying to get CAS 5.1.2 to use Duo MFA, and also to have "Remember me" functionality. So the code shows that "Remember me" looks to the initial credentials POST and looks for a parameter "&rememberMe=true". However, when Duo is enabled, this POST is not the TGC issuing event -- the TGC is issued in a separate POST that happens after successful multi-factor validation, and the parameter is lost in that subsequent POST.

I've found that if I inject "&rememberMe=true" into the POST data going to /cas/login that happens immediately after successful Duo MFA, then I get what I want: A shiny new *perisistent* TGC cookie.

All of this suggests to me that the approach in org.apereo.cas.web.support.CookieRetrievingCookieGenerator.addCookie, where it looks for the "&rememberMe=true" parameter, is the wrong approach for an implementation with Duo.

I am not a developer, but I've been digging into the code to get this far. Am I on the right track here?

**Comment by mmoayyed** [comment]
Yes you're on the right track. I suppose the cookie generator will also need to consult the webflow to determine if remember-me is turned on rather than just seeing it as a parameter.
