### ISSUE TITLE
Wrong text snippet in error page title tag

### ISSUE THREAD

**Issue by ohinckel** [apereo/cas#2958]
https://github.com/apereo/cas/blob/26842a2c3a0ff4aa768e8a6b94735dfb93e74882/webapp/resources/templates/error.html#L5

Just notice that this text snippet in the title tag is wrong. It indicates bad hours error, but the page is used for general errors (like exceptions).

**Comment by mmoayyed** [comment]
Thanks for the logging the issue report. This seems like something that might need fixing. As the next step, please [review this guide](https://apereo.github.io/2017/07/05/cas-contribution-guide/) to get started.

You can also learn how to build and run CAS [from here](https://apereo.github.io/cas/developer/Build-Process.html).

Thanks again!
