### ISSUE TITLE
Bcrypt password won't match (PHP vs Spring)

### ISSUE THREAD

**Issue by defrox** [apereo/cas#2959]
Hi there, I have an issue between CAS and Moodle (a PHP LMS) where the passwords generated by PHP are encrypted with the fixed version of blowfish ($2y...) but in CAS 5.1.x that is using Spring security the blowfish version is not the fixed one ($2a...). Therefore I cant validate users. A manual fix is to change the $2y for $2a in the password and this works. Problem is that this can't be implemented. I've been trying to replace the Spring Security Bcrypt library for [JBcrypt library](https://github.com/jeremyh/jBCrypt) but I am new to the springframework and can't make it work. Tried to add it as a dependency on the project file and in the cas config as a custom password encoder but no luck. What would be the best way to solve this? What is your advice and how should I proceed? 
I am using CAS overlay 5.1.4
Thanks in advance,
Christian

**Comment by mmoayyed** [comment]
> the passwords generated by PHP are encrypted with the fixed version of blowfish ($2y...) but in CAS 5.1.x that is using Spring security the blowfish version is not the fixed one ($2a...)

Can you elaborate more on this please? What does "fixed" mean? and where in CAS do you see this behavior not "fixed"?

**Comment by mmoayyed** [comment]
Also, please note that as the issue template suggests, these sorts of questions are better answered either on mailing lists or in the chatroom:
https://apereo.github.io/cas/Support.html

**Comment by defrox** [comment]
By "fixed" I mean a temporary workaround, if in a php generated password ($2y...) letter "a" is replaced by "a" then the password is validated, but this won't happen with the original php one.

**Comment by mmoayyed** [comment]
I recommend the following:

1. If there is a version of Spring Security that contains the behavior you need, you need to find it, exclude what CAS ships and add your dependency for Spring Security in the overlay and see if that helps. If it does, you are welcome to shoot a PR and update the version of Spring Security that ships with CAS.
2. Write your own password-encoding strategy.
3. Change the way Moodle works.

**Comment by defrox** [comment]
Thanks, I'll try the #2 option, now I need to find out how to implement a custom password encoder. Would appreciate a link if available.
Thanks!

**Comment by mmoayyed** [comment]
Sure.

Depending on your authn scheme, there are blocks of settings that deal with password encoding:

```
cas.authn.something.passwordEncoder.type=com.example.CustomPasswordEncoder
```

See https://apereo.github.io/cas/5.1.x/installation/Configuration-Properties-Common.html#password-encoding

**Comment by defrox** [comment]
Just need to tell spring security to load the JBcrypt class, but can't find out how. Tried to add the dependency and changed the type setting as you said but without luck. Any suggestions?
