### ISSUE TITLE
cas-server-support-redis-ticket-registry does not support redis sentinel

### ISSUE THREAD

**Issue by ozayduman** [apereo/cas#2964]
Hi, 
cas-server-support-redis-ticket-registry library currently does not support redis sentinel configuration.
RedisObjectFactory gets single host information from cas.properties file (cas.ticket.registry.redis.host=localhost)  
It should be added to suppert hight avaliability.
thanks.

**Comment by mmoayyed** [comment]
Thanks for the logging the issue report. This seems like something that might need fixing. As the next step, please [review this guide](https://apereo.github.io/2017/07/05/cas-contribution-guide/) to get started.

You can also learn how to build and run CAS [from here](https://apereo.github.io/cas/developer/Build-Process.html).

Thanks again!
