### ISSUE TITLE
NPE on DefaultCasEventListener:123

### ISSUE THREAD

**Issue by DavidRG13** [apereo/cas#2975]
Version 5.1.4

Hi everyone,

I'm having a NPE on the next line:
final GeoLocationRequest location = WebUtils.getHttpServletRequestGeoLocation();
dto.putGeoLocation(location);

That's doing:
return getHttpServletRequestGeoLocation(WebUtils.getHttpServletRequest());

So I guess the ServletRequest is null.
Could you please add a check for this?

**Comment by mmoayyed** [comment]
You'll need to figure out the root cause of NPE and how it happens. And if that's something that does require extra checking, by all means shoot over a PR.

Thank you.

**Comment by DavidRG13** [comment]
@mmoayyed I know when it happens, when you have no servletRequest (we are trying shiny new things ;) )

I'll submit a PR

**Comment by mmoayyed** [comment]
Good for you! Thanks for PR. 

What might contribute to the absence of servletRequest?

**Comment by DavidRG13** [comment]
We are trying to migrate REST over to GRPC, so there is no servletRequest/spring/tomcat

**Comment by mmoayyed** [comment]
Ah, excellent. Thanks for the diagnosis. So that's what you mean by new shiny things :)

**Comment by DavidRG13** [comment]
@mmoayyed could we have this change in 5.1.5?

**Comment by mmoayyed** [comment]
That would be rather impossible given 5.1.5 is released.

**Comment by DavidRG13** [comment]
5.1.6 then? would it be released before 5.2? when are they planed to be released?

**Comment by mmoayyed** [comment]
https://github.com/apereo/cas/milestones
