### ISSUE TITLE
Default ddlAuto of create-drop will destroy audit table upon migration

### ISSUE THREAD

**Issue by marwatk** [apereo/cas#2978]
The current default `ddlAuto` for every hibernate backed store is `create-drop` which will result in a table being dropped if it doesn't match the required schema. For most tables I can see this not being a problem, but it also applies to the audit table. Somewhere between CAS 4 and 5.2-RC3 the audit table added an `id` column. Anyone attempting to upgrade will see their audit table dropped if they don't notice and change the default.

I'm not sure if it should be changed, but I wanted to bring it up in case that wasn't the intended behavior.

I tried setting it to `update` to see what happens, but it doesn't properly update the table (it creates an generic non-null id column with no auto-increment). The only values that would avoid this are `validate` or `none`.

**Comment by mmoayyed** [comment]
Thanks for the update. Could you please document the same sort of description here as well in form of a PR?
https://apereo.github.io/cas/development/installation/Configuration-Properties-Common.html#ddl-configuration

**Comment by mmoayyed** [comment]
Closed via https://github.com/apereo/cas/pull/2982
