### ISSUE TITLE
JPA Service Registry always loads JSON into database on startup.

### ISSUE THREAD

**Issue by CobraFlow** [apereo/cas#2987]
When cas.service-registry.init-from-json = true the Dao should only populate the database with missing services.
The ServiceRegistryInitializer first tries to use serviceRegistryDao.findServiceById() which uses a regex match on the serviceId which will always fail (The actual pattern is the serviceId). It then attempts to use the id which, on a database with autoincrement columns may/may not fail depending on ids and data.

I would suggest that 
a) The first check should be done as an .equals() comparison on the serviceId (regex in this case)
b) The database should not use autoincrement on the regex_registered_service table.

Does this make sense?

Cheers

**Comment by mmoayyed** [comment]
Does this help https://github.com/apereo/cas/pull/2946?

**Comment by CobraFlow** [comment]
Yes, that answers part a).
I'm not sure it should ever get to part b) if part a) works correctly.
Part b) is raised because the id in the JSON is not used to create the record in the table when it is an autoincrement column and therefore will probably never match it's own row.

Thanks

**Comment by mmoayyed** [comment]
Cool. Give it a try please and see how it works. B very much should go away if A does its job, as you say. If not, we can look further.
