### ISSUE TITLE
No display information of dashboard logging on 5.2.0-RC4

### ISSUE THREAD

**Issue by laomazi2006** [apereo/cas#2993]
Hi~

The following is my config.

application.properties
```properties
endpoints.sensitive=false
endpoints.enabled=true

endpoints.restart.enabled=true
endpoints.shutdown.enabled=true
endpoints.autoconfig.enabled=true
endpoints.beans.enabled=true
endpoints.bus.enabled=true
endpoints.configprops.enabled=true
endpoints.dump.enabled=true
endpoints.env.enabled=true
endpoints.health.enabled=true
endpoints.features.enabled=true
endpoints.info.enabled=true
endpoints.loggers.enabled=true
endpoints.logfile.enabled=true
endpoints.trace.enabled=true
endpoints.docs.enabled=true
endpoints.heapdump.enabled=true
```

and I open link `status/dashboard`，I saw `Status`,`Metrics`,`Statistics Panel`,`Configuration Panel`,`Logging` etc.

Next open link `status/logging` and show **Reading logging configuration**

---
I'm very curious, After I try the same as `5.1.4` ,is ok, showing some  loggers list, CAS Log continuous output,Audit Log.

I find code differences.
https://github.com/apereo/cas/blob/master/webapp/resources/templates/monitoring/viewLoggingConfig.html
https://github.com/apereo/cas/blob/5.1.x/webapp/resources/templates/monitoring/viewLoggingConfig.html

master:

```html
<script type="text/javascript" th:inline="javascript">
        function jqueryReady() {
            head.load(
                    /*[[@{/css/loggingDashboard.css}]]*/
            );
            head.load(
                    /*[[@{/js/sockjs.js}]]*/,
                    /*[[@{/js/stomp.js}]]*/
            );
        }
    </script>
```

5.1.x:

```html
 <script type="text/javascript" th:inline="javascript">
        function jqueryReady() {
            head.load(
                    /*[[@{/css/loggingDashboard.css}]]*/
            );
            head.load(
                    /*[[@{/js/sockjs.js}]]*/,
                    /*[[@{/js/stomp.js}]]*/,
                    /*[[@{/js/loggingDashboard.js}]]*/
            );
        }
    </script>
```

---
**Is it a feature of the 5.2.0-RC4 or am I configured?**

Thanks.

**Comment by mmoayyed** [comment]
You should be able to test the fix in about an hour or so, by using the new SNAPSHOT.

**Comment by laomazi2006** [comment]
OK!

@mmoayyed 
Something else, for the [OAuth2 Delegate Authentication](https://apereo.github.io/cas/development/integration/Delegate-Authentication.html)

I want to use [Tencent QQ Login](http://wiki.connect.qq.com/%E5%BC%80%E5%8F%91%E6%94%BB%E7%95%A5_server-side), that is OAuth2 ,

---

Obtain Access Token:
https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=[YOUR_APP_ID]&client_secret=[YOUR_APP_Key]&code=[The_AUTHORIZATION_CODE]&state=[The_CLIENT_STATE]&redirect_uri=[YOUR_REDIRECT_URI]

```json
access_token=YOUR_ACCESS_TOKEN&expires_in=3600
```
Obtain profile（jsonp）:

https://graph.qq.com/oauth2.0/me?access_token=YOUR_ACCESS_TOKEN

```jsonp
callback( {“client_id”:”YOUR_APPID”,”openid”:”YOUR_OPENID”} );
```

application.properties
```properties
 cas.authn.pac4j.oauth2[0].id=
 cas.authn.pac4j.oauth2[0].secret=
 cas.authn.pac4j.oauth2[0].authUrl=https://graph.qq.com/oauth2.0/authorize
 cas.authn.pac4j.oauth2[0].tokenUrl=https://graph.qq.com/oauth2.0/token
 cas.authn.pac4j.oauth2[0].profileUrl=https://graph.qq.com/oauth2.0/me
 cas.authn.pac4j.oauth2[0].profileVerb=GET
 cas.authn.pac4j.oauth2[0].clientName=qq
```


How I can do?
* fork the code and support `QQ`  login?  `org.pac4j.scribe.builder.api.GenericApi20`default is 'OAuth2AccessTokenJsonExtractor‘ but qq is 'OAuth2AccessTokenExtractor'


thank you!
