### ISSUE TITLE
MFA Remember Device Fails with MariaDb due to keyword conflict

### ISSUE THREAD

**Issue by atilling** [apereo/cas#2998]
CAS 5.1.4 with Tomcat 7, Java 8 and MariaDb 10

Columns for Remember this device conflict with MariaDb Keywords, specifically `Date` and `Key` the column names are not backticked so SQL fails with SQL Syntax error.

Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'key, name, principal) values ('2017-10-11', '136.244.201.1@Mozilla/5.0 (Macintos' at line 1
Query is: insert into MultifactorAuthenticationTrustRecord (date, geography, key, name, principal) values (?, ?, ?, ?, ?), parameters ['2017-10-11','136.244.201.1@Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36','atilling@136.244.201.1@Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36','My Dekstop','atilling']
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:146) ~[mariadb-java-client-2.1.2.jar:?]
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:217) ~[mariadb-java-client-2.1.2.jar:?]
	at sun.reflect.GeneratedMethodAccessor195.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]

Issue is discussed at length here: 
https://groups.google.com/a/apereo.org/forum/#!msg/cas-user/3Je3HiqdAhU/2oJZbbGvBwAJ

Overlay is here:
https://github.com/ConnCollege/cas-5/tree/MFAConfig

**Comment by dima767** [comment]
The JPA-mapped class is here: https://github.com/apereo/cas/blob/5.1.x/support/cas-server-support-trusted-mfa/src/main/java/org/apereo/cas/trusted/authentication/api/MultifactorAuthenticationTrustRecord.java

Pull Requests are welcomed ;-)

**Comment by mmoayyed** [comment]
Looks like this is corrected in master. As Dima says, you're more than welcome to port back the change.

**Comment by atilling** [comment]
I'll look to port back the change in cas-server-support-trusted-mfa I was looking at writing the same changes, I also noted there are issues with the old column names in cas-server-support-trusted-mfa-jdbc and these are not corrected in master.

https://github.com/apereo/cas/blob/master/support/cas-server-support-trusted-mfa-jdbc/src/main/java/org/apereo/cas/trusted/authentication/storage/JpaMultifactorAuthenticationTrustStorage.java

Will "fix schema issues with reserved keywords" go forward with 5.1.5 or will that only go into the 5.2 branch?

**Comment by mmoayyed** [comment]
Start with 5.1.x please and if there are any outstanding changes, we'll port them forward to master/5.2. If you can manage the 5.1 changes by EOD of tomorrow, they can included in 5.1.5!

Thanks.

**Comment by atilling** [comment]
Timing wise it looks like I missed the 5.1.5 release?

**Comment by mmoayyed** [comment]
Yes, but you should be able to try with 5.1.6-SNAPSHOT.
