### ISSUE TITLE
Detecting autofill of credentials isn't 100%

### ISSUE THREAD

**Issue by rfrovarp** [apereo/cas#2999]
We're running 5.1.1, and the code looks like it is the same in master at this moment.

https://github.com/apereo/cas/blob/master/webapp/resources/static/js/cas.js

has a 100 ms check to see if an autocomplete triggered to fill in the username and password. We're seeing cases where that is sometimes not working in Chrome. We haven't had a chance to test in Firefox or other browsers.

I don't know what it takes for Chrome to fill in that value, but those requirements might not be complete by the time the timeout kicks off. Chrome may be waiting for images or CSS before filling the form in, and the timeout isn't. It might need to check a few times for the first second? That might make it more reliable. It's also possible using the required attribute on the form fields might have the same effect.

**Comment by rfrovarp** [comment]
It's been pointed out to me that there is now a conditional check at line 109 that controls if the timeout at 110 is applied. That conditional check is missing from 5.1.1. None of the changes reference addressing autofill detection.

**Comment by mmoayyed** [comment]
Thanks for the diagnosis. I recommend you try to fiddle around with various timeout options in the script, and put together a PR to address any and all issues. Look forward to working with you on this.
