### ISSUE TITLE
Successful password change action should trigger login flow?

### ISSUE THREAD

**Issue by marwatk** [apereo/cas#3011]
Currently in CAS 5.2 after a user successfully changes their password they are redirected to the normal login screen to re-enter the password they just created in order to log in. Our business rules (and how we have it configured with CAS 4) is to send the user through the login flow with their new credentials as if they had specified the new password on the login form, without actually sending them there.

Should this be the behavior of base CAS?

If so I'll start work on a PR, otherwise I'll work to adapt the flow via an add-on (and you can close this).

**Comment by mmoayyed** [comment]
I think that's perfectly reasonable. I would say either option is somewhat common on average and I would welcome the change provided you also allow a toggle that can flip the behavior in either direction. Keeping the default as is, of course to play nice with what exists out there. Do please file the PR when you find the chance, and as always, thank you very much for stepping up!

**Comment by marwatk** [comment]
I'm working on this but ran into a roadblock and wanted to get feedback.

Because the login and pswdreset flows are isolated (one is not a subflow of the other) the only ways for pswdreset to communicate the credential with login are:

1. url params (not the best place to store a password)
2. session scope (feels super hacky)

The proper way forward is to make pswdreset a subflow of login allowing passing in flow scope (assuming I can kickoff a subflow from a link... TBD). But that would feels like a big change so I'm not 100% opposed to using the session (storing the pswdreset credential and then checking for and clearing it as part of the login submit flow) 

Thoughts or other ideas?

(This isn't a problem for the change during warning flow since that lives in login)

**Comment by mmoayyed** [comment]
Without knowing too much about the details of the subflow, I can tell you that at least right now that is the best option. (There may be better ones, don't know yet) Neither 1 and 2 ar acceptable. 1 for obvious reasons and 2 because session state is transcoded and stored on the client, (though encrypted and signed).

**Comment by marwatk** [comment]
Well that makes it easy. I'll see what I can come up with.
