### ISSUE TITLE
Allow CAS customisation without WAR overlay

### ISSUE THREAD

**Issue by maciejmiklas** [apereo/cas#3018]
We’ve been using CAS for years and we are really happy with it! So we’ve decided to update to 5.1 but there is one serious issue:
proper customisation can be archived with `cas-gradle-everlay-template` meaning that it extracts WAR into another one, this has some drawbacks:

1. You cannot relay on Gradle dependency management since you are merging already existing WAR with all its libraries into another one.
2. No proper IDE support. Overlay it’s a Gradle project, but it has compile dependency to `cas-server-webapp` and this is a WAR. In this case, it will get copied into `WEB-INF/lib` as a WAR. This means, that before each deployment a Gradle task needs to be executed. 
3. In order to merge two WAR files together, `cas-gradle-overlay-template` executes Gradle scripts from `dl.bintray.com` and `raw.githubusercontent.com` . What happens when those hosts are down? How about security? Some could modify those scripts and no one would notice. 

I would be happy if there would be a standard way to customise CAS and I think that it should be possible with small structural changes. You would have to refactor structure within `https://github.com/apereo/cas/tree/master/webapp` :
1. create a new project: `webapp/cas-server-webapp-lib` as JAR
2. Move dependencies section from `webapp/gradle/webapp.gradle` into `cas-server-webapp-lib/build.gradle`
3. Move `/webapp/resources` into `cas-server-webapp-lib/src/main`
4. Set `cas-server-webapp-lib` as dependency in `cas-server-webapp`

Doing so we've created a new JAR containing web resources and dependencies for web project.

Now it's possible to customise CAS by importing `cas-server-webapp-lib` into any web-project, simple as that. 

Each web resource can be still overwritten because its placed in a JAR (`as-server-webapp-lib`) and new files will be stored in `WEB-INF/classes`. This should also apply to Spring Boot executable war.

**Comment by mmoayyed** [comment]
What you're describing essentially is the foundation of https://github.com/UniconLabs/gradle-cas-plugin in some ways. I recommend you review that repository and see how far it gets you. If that doesn't work, I recommend you look into the cas-server-webapp-init module, add the dependencies you need and create your own overlay project if what is provided is of concern. Once and if you do and you find improvements with a working prototype, please post back and we'd be happy to review, merge, etc.
