### ISSUE TITLE
remoteAddress MDC does not respect cas.audit.alternateClientAddrHeaderName property

### ISSUE THREAD

**Issue by joshgrochowski** [apereo/cas#3032]
The [MDC](https://apereo.github.io/cas/5.1.x/installation/Logging.html#mapped-diagnostic-context) variable for `remoteAddress` does not respect the `cas.audit.alternateClientAddrHeaderName` [Audits](https://apereo.github.io/cas/5.0.x/installation/Configuration-Properties.html#audits) property.

**How to Replicate**

The following properties in `cas.properties` are relevant to this issue:
```
cas.audit.alternateClientAddrHeaderName=X-FORWARDED-FOR
```
The above property works as expected to override the CLIENT IP ADDRESS with the OOB Audit logging. This works because there is a [conditional check](https://github.com/apereo/cas/blob/3eff06b4f9587c759484af5dd3052882b19ea4bf/core/cas-server-core-audit/src/main/java/org/apereo/cas/audit/spi/config/CasCoreAuditConfiguration.java#L87) to see if the above configuration property is set.

```
=============================================================
WHO: <PRINCIPAL>
WHAT: TGT-**********************************************tdEX5OSvGN-cas6
ACTION: TICKET_GRANTING_TICKET_CREATED
APPLICATION: CAS
WHEN: Sat Oct 28 08:44:24 EDT 2017
CLIENT IP ADDRESS: <X-FORWARDED-FOR CLIENT IP>
SERVER IP ADDRESS: <SERVER IP>
=============================================================
```
However, when using MDC variables to create a custom logging format, the `remoteAddress` variable does not respect the alternative header specified in `cas.audit.alternateClientAddrHeaderName`. Instead, it uses the IP Address making the request which is not desired when this property is set to an alternative header value.

This can be replicated by adding the following simple example to `log4j2.xml`:

```xml
<Appenders>
       <Console name="mdc_dump" target="SYSTEM_OUT">
            <PatternLayout pattern="MDC remoteAddress: %X{remoteAddress}"/>
        </Console>

        <CasAppender name="mdc_dump_console">
            <AppenderRef ref="mdc_dump" />
        </CasAppender>
</Appenders>

<Loggers>
        <AsyncRoot level="warn">
            <AppenderRef ref="mdc_dump_console"/>
        </AsyncRoot>
</Loggers>
```

The above configuration outputs the following to console:

```
MDC remoteAddress: <REQUEST IP, NOT X-FORWARDED-FOR IP>
```

**Expected Behavior**

The `remoteAddress` MDC variable should return the header value mapped in the `cas.audit.alternateClientAddrHeaderName` property.

**Version Information**

```
CAS Version: 5.1.5
CAS Commit Id: dd67c8066700545fa6fe92fb681277fabded6115
CAS Build Date/Time: 2017-10-28T12:42:56Z
Spring Boot Version: 1.5.3.RELEASE
------------------------------------------------------------
System Date/Time: 2017-10-28T08:43:00.895
System Temp Directory: /tmp
------------------------------------------------------------
Java Home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-2.b11.el7_3.x86_64/jre
Java Vendor: Oracle Corporation
Java Version: 1.8.0_131
JCE Installed: yes
------------------------------------------------------------
OS Architecture: amd64
OS Name: Linux
OS Version: 3.10.0-514.16.1.el7.x86_64
------------------------------------------------------------
Apache Tomcat Version: Apache Tomcat/8.5.20
------------------------------------------------------------
```

**Comment by mmoayyed** [comment]
The MDC's `remoteAddress` would never consider a setting that deals with audit logs. However, if you wish you have MDC process alternative headers for remoteAddress, I think that's a sound idea. Please file a pull request to address the change at your earliest convenience.
