### ISSUE TITLE
AUP check ignored when auth succeeds with warning

### ISSUE THREAD

**Issue by Brian-Cole** [apereo/cas#3039]
Using 5.2.0-RC4 in a simple dev environment with minimal configuration.  I have added the both a password policy and the acceptable usage policy check.  When a user authentications who has not completed the check and has a password expiration outside of the warning period, the AUP check is displayed.  If i set the password policy warning days to a large value, say 365 to force the password policy warning to show, the password policy warning shows as required.  However, when the user clicks the continue button, the AUP check should display, it does not, it proceeds directly to the service.

**Comment by mmoayyed** [comment]
Cool. Thanks for the issue report. It sounds like password policy and AUP flows need a small adjustment in their webflow config to work together. Definitely worth looking into. Please investigate & file a pull request to address the case. Thanks again!
