### ISSUE TITLE
Incorrect Error Transition Configuration for Login Flow

### ISSUE THREAD

**Issue by code-4-fun** [apereo/cas#3040]
**Cas Configuration:**
> CAS v5.1.5
> cas.pm.authn.enabled=true

**Use Case:**
When Authentication service raises `AccountPasswordMustChangeException`, CAS maps the error to view - `CasWebflowConstants.VIEW_ID_MUST_CHANGE_PASSWORD `. At this state, if `PasswordChangeAction` returns false or raises exception, CAS incorrectly shows Account Disabled page instead of 'CasWebflowConstants.VIEW_ID_MUST_CHANGE_PASSWORD' with error message.

**Cause:**
`PasswordManagementWebflowConfigurer` configures 3 views for Error event. Hence, whenever action returns error event, the flow shows AccountDisabled view.

**Comment by mmoayyed** [comment]
Thanks for reporting the issue. Sounds like something that needs fixing. Please consider filing a pull requests to fix the problem.

**Comment by code-4-fun** [comment]
yeah, just found it! Pull request on its way soon!
