### ISSUE TITLE
Introspection Request token mismatch

### ISSUE THREAD

**Issue by number133** [apereo/cas#3048]
- [5.2.0-RC1] CAS server version
- [wildfly-10.1.0.Final, Windows 7] Container/environment type/version (Tomcat, Jetty, Java, Linux/Windows, etc)
- Steps to duplicate the problem along with your CAS settings and properties
1. Include oidc dependency
2. Call Introspect endpoint /cas/oidc/introspect

Introspect endpoint /cas/oidc/introspect (class org.apereo.cas.oidc.web.controllers.OidcIntrospectionEndpointController)
expects request parameter "access_token", while in RFC for "https://tools.ietf.org/html/rfc7662#section-2.1" this parameter is named "token". 

1. Is this implementation mismatch or am I not getting the specs right?

**Comment by mmoayyed** [comment]
If the spec says so, then it's a mismatch. Please file a pull request at your earliest convenience to address the case.
