### ISSUE TITLE
Redis Ticket Registry : JedisConnectionException using DNS

### ISSUE THREAD

**Issue by amoscatelli** [apereo/cas#3051]
CAS server version : 5.2.0-RC4
Host Machine : Windows 10 Pro 64 bit
Docker : 17.09.0-ce-win33
Docker Image : Apache Tomcat 8.5.23
Java : 1.8.0_141

Let 'xxx.hostname.yyy.zzz' be the hostname of the redis endpoint
Let 'redis.example.com' be a dns pointing to 'xxx.hostname.yyy.zzz' 

When using :
cas.ticket.registry.redis.host=redis.example.com

I get a :

redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
Caused by: java.net.SocketTimeoutException: connect timed out

When using
cas.ticket.registry.redis.host=xxx.hostname.yyy.zzz

Everything works.

'telnet redis.example.com 6379' from the host running tomcat containing cas also works.

So this is not a DNS resolver problem.

'redis-cli -h redis.example.com from the host running tomcat containing cas also works.

**Comment by mmoayyed** [comment]
Thanks for reporting the issue in good detail. We appreciate you trying out this feature and testing it. As the next step, we ask that you investigate further and file a pull request to fix the problem.

Big blue box on top of the page:
https://apereo.github.io/cas/developer/Contributor-Guidelines.html

If you need help with getting started, please do not hesitate to ask questions.

**Comment by mmoayyed** [comment]
Also please study this for future reference: https://apereo.github.io/2017/07/05/cas-contribution-guide/
