### ISSUE TITLE
TARGET parameter no longer valid in CAS 5.1.5 for service login or ticket validation (affects CAS integration in Ellucian Banner 9)

### ISSUE THREAD

**Issue by rdev5** [apereo/cas#3054]
Just wanted to point out that under CAS 5.1.5, applications that used to pass their service URLs via the `TARGET` parameter are now broken while this still works in CAS 5.1.1.

Login URL (example): `https://cas.example.com/login?TARGET=...`

Under CAS 5.1.1:
````
AUTHENTICATION_EVENT_TRIGGERED
SERVICE_TICKET_CREATED
SERVICE_TICKET_VALIDATED

AUTHENTICATION_EVENT_TRIGGERED
SERVICE_TICKET_CREATED
SERVICE_TICKET_VALIDATED
````

Under CAS 5.1.5:
````
AUTHENTICATION_EVENT_TRIGGERED
SERVICE_TICKET_CREATED

AUTHENTICATION_EVENT_TRIGGERED
SERVICE_TICKET_CREATED
````

Users are merely presented with the "Login successful" page and CAS does not perform any service redirect nor receives service ticket validation of the same.

For this reason, we will not be deploying CAS 5.1.5 as it breaks CAS integration in **Ellucian Banner 9**.

**Comment by mmoayyed** [comment]
Thanks for the logging the issue report. This seems like something that might need fixing. As the next step, please [review this guide](https://apereo.github.io/2017/07/05/cas-contribution-guide/) to get started.

You can also learn how to build and run CAS [from here](https://apereo.github.io/cas/developer/Build-Process.html).

Thanks again!
