### ISSUE TITLE
JAAS fails login due to NullPrincipal

### ISSUE THREAD

**Issue by tsschmidt** [apereo/cas#3055]
Found this issue in the current master and is also present in the 5.1.x branch since 5.1.5 release.

JaasAuthenticationHandler is calling logout() before the principal is being retrieved and passes a null principal on.  This did not cause problems until the change in CasCoreAuthenticationPrincipalConfiguraton to use ChainingPrincipalResolovers with the EchoPrincipalResolver being the default.  Since no principal was set in the Authentication, it now throws UnresolvedPrincipalException.

**Comment by mmoayyed** [comment]
Closing in favor of https://github.com/apereo/cas/pull/3056. (No need for issues if you are following up with a PR. Much faster that way)

**Comment by tsschmidt** [comment]
Got it.
