### ISSUE TITLE
Implement OIDC via CAS OAuth module

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#514]
*  limited set of attributes
*  impersonation
*  enable/disable confirmation screen (enabled by default)
* missing grant types? 
* make sure attributes are returned for each service after validation?

Generate access\_token according to the service, not a global one (TGT)

**Comment by mmoayyed** [comment]
@leleuj I know we discussed this a while back. Do you have a solution in mind that would work without refactoring the codebase to a great extent? 

When the TGT is passed to the profile endpoint, is there anyway to look up the service requesting information, without breaking protocol compliance? Could we expect that a service parameter be sent as well?

**Comment by leleuj** [comment]
My latest attempt to use Spring Security was unsuccessful. I haven't thought about it since a while.

The thing is that we must know the service which has requested the access token and we need this new kind of token (which not a TGT, nor a ST). I have no easy solution right now, but I should definitely  work on this. For 4.2.

**Comment by mmoayyed** [comment]
Take a look at MitreId Connect's Java Spring server. I am working on a similar project, and what they have seems like a good example.

**Comment by mmoayyed** [comment]
We could require a service parameter to be passed to the endpoint, but I don't know if that violates the protocol.

**Comment by leleuj** [comment]
We could certainly as I don't think the OAuth protocol specifies the way to use the access token on a resource endpoint. Though, we should already have this information when we grant the access token and it should be straightforward.

**Comment by leleuj** [comment]
The MitreId Connect's Java Spring server seems to be very promising. It makes me wonder if we should really keep the OAuth server support in the CAS server itself, it makes things really complicated and it's a huge work in itself to define everything.
Seeing the MitreId Connect's server leads me to the conclusion that it would make sense to build a new OAuth server (let's support OpenID Connect as well) on top of something already existing, secure and known by people who want to customize it. It would be a matter of customizing it to work with CAS.

I'll go in that direction for now. To follow my work: https://github.com/leleuj/cas-oidc-server

**Comment by mmoayyed** [comment]
Yes that is the same library I am using to add OIDC support to the Shib IdP.

**Comment by mmoayyed** [comment]
https://github.com/uchicago/shibboleth-oidc

**Comment by mmoayyed** [comment]
I fully support moving towards MitreID and supporting OIDC as well. Less "custom" code the better, and this move should solve other issues that we have now with OAuth as well.

**Comment by leleuj** [comment]
Just that I want to insist on the fact that currently, we have the `cas-server-support-oauth` module of the `cas-server` project which turns the CAS server into an OAuth server (authentication + authorization + resource). We configure the CAS server to support OAuth.

In my vision, we would have a new webapp supporting OAuth + OpenID Connect (authorization + resource) based on the MitreId project, let's say: `cas-oidc-server`, it would be a separate project  configured to authenticate with a CAS server.

**Comment by mmoayyed** [comment]
If I understand your proposal correctly, then :-1: 

The OAuth+OIDC module needs to be built "into" the CAS server, as one platform. Deploying a separate webapp with different configuration, look and feel and workflow isn't going to work. If we want to rip off the oauth module and simply use the MitreID APIs to add support to CAS, that's fine. But using their webapp and having external authentication is a no-go. The CAS server needs to act as an authentication protocol hub, not as a client.

**Comment by mmoayyed** [comment]
I have in mind that we should get rid of all the custom code we have for oauth and openid, and deprecate them. Then use the MitreID SDK only to put together components and write adapters for CAS so the entire functionality is contained within the CAS project. So the CAS server provide OAuth+OIDC functionality, and it makes it much easier for people to manage and deploy. Adopters would include the OAUth module in their overlay and they are done. That should be it. Otherwise, you could say CAS supports ADFS because it can delegate authentication to it, and CAS supports SAML because it can delegate authentications to a SAML IDP and CAS supports OAUth and OIDC because it can delegate authentication to a different server that actually does that. We do that today, we are unsuccessful and none of that really "sells".

**Comment by leleuj** [comment]
I would not say that external bridges (like shib-cas-authentX for example) are unsuccessful. I'm really hesitating on this topic but I'll go for the solution we already proposed (embedded OAuth/OpenID Connect support) as it will provide a seamless transition. I think that external supports are not necessarily bad things: a project like the MitreID server is well-known on its own so I don't think deployers would be surprised and deceived to have the right overlay pre-configured for the CAS server.

**Comment by mmoayyed** [comment]
Sure, understood. I don't think external bridges are "bad" per se; my position is that declaring platform X can support Y because it is able to delegate authentications to an external entity is a bit of false advertising so to speak. It is certainly true that the integration can be done and support for Y achieved, (in fact MitreID is based on Spring Security which already supports CAS so there is not much left for us to do other than to configure it to use CAS) and it some cases a bridge makes perfect sense. Ideally though, delegation to external entities creates more issues/work. When I evaluate, I see a lot more downsides. When I think about the easiest approach I would see something like "include the oidc dependency in your maven overlay, and then you're done!" :)

Of course, I am in favor of removing all custom oauth/OIDC code that CAS offers. We should build upon what MitreID has already achieved with Spring Sec OAuth, and remove maintenance burden, and only fill in the gaps. 

I am working on the same approach for the shibboleth identity provider, to build OIDC directly into the platform, by relying on MitreID APIs only. I am sure it will be easier to do this for CAS.

**Comment by leleuj** [comment]
I started working on this: it's more work than just creating an overlay on top of the MitreId server where the authentication is delegated to the CAS server. I see your work on Shibboleth / OpenID Connect and indeed, it's a big project.

I disabled all default classes from MitreId and create "CAS empty" ones to see what needs to be initialized.

So it raises a few questions:

- default classes in the MitreId server are based on the database: I plan to create new classes based on memory as we generally do in CAS
- Many things can be set in the MitreId server from various REST API endpoints: I plan to disable everything, the only setting available will be the OAuth clients defined as CAS services via the CAS services management webapp, other options may be set via properties.

What do you think?

**Comment by mmoayyed** [comment]
>default classes in the MitreId server are based on the database: I plan to create new classes based on memory as we generally do in CAS

Agreed, yes. 

> Many things can be set in the MitreId server from various REST API endpoints: I plan to disable everything, the only setting available will be the OAuth clients defined as CAS services via the CAS services management webapp, other options may be set via properties.

Also agreed. Disable dynamic disovery, introspection, dynamic registration, etc. there should be an authorize endpoint, a token endpoint, a jwk endpoint and a userinfo endpoint. 

Just so I am clear, are you doing this in an overlay style, or building support directly into CAS? I hope it's the latter.

**Comment by mmoayyed** [comment]
Also no UIs, no management interfaces.

**Comment by leleuj** [comment]
As we said, I gave up the overlay style to build a new `cas-server-support-oauth-oidc` module: source code is for now directly available in the https://github.com/leleuj/cas-oidc-server, I'll build the module at the end.

**Comment by mmoayyed** [comment]
Ah, excellent. Sorry I forgot to check. Is there anything I can help?

Maybe this quick intro based on my Shib Idp experience can help:

MitreId is heavily based on Spring Security. The initial request goes to authorize endpoint, which bombs because it needs to be authentication. An exception is thrown for insufficient authentication. The spring security takes over and routes the request to a login endpoint. once you authentication, an approval process kicks in, and then token is generated. Once the token is next validated via the /token endpoint, an id token is passed that is signed. Client app verifies the signature, gets data and logs the user in by contacting the userinfo endpoint. 

The IdP codebase is much more complicated because it's entirely SWF based, and it has no concept of Spring webflow.

**Comment by mmoayyed** [comment]
One other thing; the design of clients and etc must be based on service registry of CAS. The authentication is handled by CAS obviously with a TGT and ST, but we could Spring OAuth for OAuth-related tokens.

**Comment by leleuj** [comment]
I've worked on using the MitreID server for OAuth support. I'm not completely happy with result: https://github.com/leleuj/cas-oidc-server
I have many default classes which must be reimplemented and exclude many default classes from the MitreID server. And I finally have the complex Spring Security configuration (hard to escape from it).

Though, there are great ides here: the first one is that a good OAuth server support is made from custom code (Spring OAuth) and security configuration, which is not the case from our current implementation (which is only custom code). So I'm wondering if I could go into that direction, based on the spring-webmvc-pac4j library.

@mmoayyed : what do you think ?

**Comment by mmoayyed** [comment]
>I have many default classes which must be reimplemented and exclude many default classes from the MitreID server.

I have had to do the same thing for the Shib IdP. Had to exclude all Repository annotations and wrote the default impls for many classes. Not the best solution, but so far it seems to be functional. You are 100% right that Spring Oauth is tied heavily to Spring Sec, which is another thing I am not happy about w.r.t the configuration.

I am generally find with the direction you propose. I would say this though that the end goal is to make the configuration dead simple for the deployer, and hide all of the complexity. So I don't mind a complex solution as long as the deployer is not asked to do it. I gather you want to try using Spring OAuth with pac4j-webmvc? I would be OK with that. Spring Security does not give us much here, and in fact for Shib IdP, I am slowly working my way towards removing it. It's only real job is to handle the userinfo endpoint, which we are going to have to rip out anyway since that data comes from CAS attributes, etc.

**Comment by mmoayyed** [comment]
Some additional notes: lots of the folks in the community are interested in OIDC support. Many many. That and MFA. I am hoping we can deliver something before Open Apereo. These in my mind are the two biggest items we should focus on.

**Comment by leleuj** [comment]
Currently, we only have custom code. Very simple but error prone.

I tried to use Spring Security + Spring OAuth in various enviroment, but I'm not very happy with the result: powerful, but very complicated and a lot of useless layers.

My proposal was to keep some of our custom code (less than today) and use spring-webmvc-pac4j: custom code replaces Spring OAuth and spring-webmvc-pac4j replaces Spring Security.

I'm not sure how Spring OAuth would work with pac4j, as a matter of facts, it's less complicated than Spring Security even it still requires to build adapters.

What would be the difference exactly between the OpenID support and the OAuth support (in the CAS server)?

**Comment by mmoayyed** [comment]
Summary of our discussion: OIDC exposes a few additional endpoints. It also supports signed and encrypted authentication requests, as well as JWTs. It also provides support for a number of standard claims and structures. There is also consent. 

TBH, I am less concerned about how this gets implemented, than it gets implemented :) Use whatever you think makes sense in the long run to provide the functionality. Do you think, planning ahead, that this might be something we could deliver for 4.3? June 2016 timeline?

**Comment by leleuj** [comment]
You're right, it's been too long since I should have implemented this. I haven't been able to find the right way to proceed. The implementation based on MitreId Connect didn't feel good either: too much overhead. I lean towards custom code even if it feels bad. I also thought I could maybe use the Nimbus OAuth OpenID Connect SDK.

I'm a bit stuck on this: maybe I should be less ambitious and at least improve our current OAuth implementation instead of a giant step embracing a full OAuth / OpenId Connect support. And to avoid the use of custom code, rely on pac4j as much as possible.

I'm committed to work on that in January (I'll slowdown on pac4j).

What do you think of this simple plan?
1) use JWT for access tokens
2) update the current flow by protecting it with the pac4j CasClient
3) add the implicit grant type
4) add the resource owner password credentials grant type

**Comment by dima767** [comment]
@leleuj @mmoayyed Take a look at this: https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions - could be worthwhile examining it and see if this SDK would be the right fit for this work

**Comment by mmoayyed** [comment]
> I'm a bit stuck on this: maybe I should be less ambitious and at least improve our current OAuth implementation instead of a giant step embracing a full OAuth / OpenId Connect support. And to avoid the use of custom code, rely on pac4j as much as possible.

I like this plan as a first step. It is a good start. I believe Pac4j already uses the framework Dima is suggesting, (or maybe it was Nimbus?) so we should build on that as much as we can. 

> 1) use JWT for access tokens

Yes. 

> 2) update the current flow by protecting it with the pac4j CasClient

Yes. 

> 3) add the implicit grant type

Sounds like a second-iteration effort, but also yes. 

> 4) add the resource owner password credentials grant type

Sounds like a second-iteration effort, but also yes. 

OIDC isn't that much. You just need to ensure all endpoints are supported, (by way of extending the current OAuth functionality) and ensure standard claims are also passed (which we can do via cas attribute mapping). The only other bit we need is to ensure signed and encrypted authN requests are supported. 

Leave out the following:

1. Dynamic Discovery
2. Dynamic Registration
3. Webfinger functionality
4. Consent.

**Comment by leleuj** [comment]
Yes, I was referring to the Nimbus OAuth Oidc SDK...

**Comment by leleuj** [comment]
First step: https://github.com/Jasig/cas/issues/1387

**Comment by leleuj** [comment]
Second step: https://github.com/Jasig/cas/issues/1425

**Comment by mmoayyed** [comment]
Note that our implementation MUST pass https://openid.net/certification/testing/

**Comment by mmoayyed** [comment]
Good progress. What is the 3rd step?

**Comment by leleuj** [comment]
Next step is: https://github.com/Jasig/cas/issues/1478

**Comment by mmoayyed** [comment]
Good momentum. I assume the next step is to add various grant_types?

**Comment by leleuj** [comment]
I feel the pressure ;-) I'm already working on it...

**Comment by mmoayyed** [comment]
Ah, sorry :D just trying to not to lose momentum and capture work items for the roadmap and upcoming calls. Keep at it. Good progress so far.

**Comment by leleuj** [comment]
Here it comes: https://github.com/Jasig/cas/issues/1525

My only regret on this topic: having lost a lot of time with **unappropriate** security libraries.

**Comment by mmoayyed** [comment]
No worries. Knowing what not to do is almost as important as knowing what to do :) The working you are doing is very much appreciated.

**Comment by leleuj** [comment]
Next step: https://github.com/Jasig/cas/issues/1527

**Comment by mmoayyed** [comment]
@leleuj planning ahead; I think the next step is the JSON response for the endpoints right? Would you still say we could deliver OIDC around May?

**Comment by leleuj** [comment]
Exactly, JSON should not take too much time. And I hope OIDC will be not too complicated based on what we already have.

**Comment by leleuj** [comment]
Last step for OAuth: https://github.com/Jasig/cas/issues/1644

**Comment by mmoayyed** [comment]
Quick note that we should probably hold off on this change until #1577 is merged in some shape or form. Would make merges (and possibly development of this issue) easier.

**Comment by leleuj** [comment]
It's notice. Thanks

**Comment by mmoayyed** [comment]
Quick note: I have added some baseline changes for OIDC under a specific module. I mostly just have wired in the discovery endpoint that would be `/cas/oidc/.well-known` and `/cas/oidc/.well-known/openid-configuration`. We can resume this more seriously once the boot merge is done.

**Comment by mmoayyed** [comment]
I started slowly with this one, building on top of our laugh module and testing with the mitreid connect client. It's super simple :) should have a prototype before the end of this week.

**Comment by mmoayyed** [comment]
![image](https://cloud.githubusercontent.com/assets/1205228/14973041/27a04210-1098-11e6-8a51-a80f616cccfe.png)

Almost done here, tested the new OIDC functionality with the MITREID Client above. Seems to work very well. Going through test cases before submitting a PR.
