### ISSUE TITLE
Automate functional testing

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#536]
Automate functional tests outlined here: https://wiki.jasig.org/display/CAS/CAS+Functional+Tests with Geb framework: http://www.gebish.org/

> I have created an initial set of tests that live now here: https://github.com/Unicon/iam-labs/tree/master/cas-functional-tests

**Comment by mmoayyed** [comment]
@dima767 can this module become part of CAS so we could have a fully automated functional test suite? This should tremendously help with QA and the release process if we could verify the functionality of the core protocol, leaving feature testing to unit tests.

**Comment by dima767** [comment]
There exists this: https://github.com/wcrowell/cas-functional-tests which is an excellent base for the functional test. I am personally not sure if it's feasible to integrate into an already growing CAS server project code base. If anything, I'd rather make this one an "official" CAS functional test suite and fork it under https://github.com/cas-projects umbrella.

**Comment by mmoayyed** [comment]
This exists now https://github.com/cas-projects/cas-functional-tests
