### ISSUE TITLE
Configuration Wizard; CAS Overlay Initializer

### ISSUE THREAD

**Issue by mmoayyed** [apereo/cas#599]
Create a web configuration wizard that will handle Spring configuration for users. I envision it having at the very least dropdowns that allow users to select which plugins they want to plug in to each extension point, and also the ability to set properties for those plugins.

**Comment by robertoschwald** [comment]
Good idea.
Maybe with a config wizard for JPA ticket + service registry support and even for the mgmt application.

**Comment by mmoayyed** [comment]
Notes so far from here and there:

Separate solution from CAS; provide a web-based wizard to handle generation of a possible CAS deployment script. Ask for modules, settings, etc and walk the user through list of options. Produce a downloadable deployment package that is promised to function correctly.

Suggested names for this app have thus far been:

- Yadon
- Biruda
- Bob
- Gandalf

Take inspiration from [start.spring.io](start.spring.io).

Working with @dima767 on this.

**Comment by dima767** [comment]
Just adding more notes for the context and boo keeping here:

One other possible name would be a "CAS curator" as it might evolve over time into more than just building/generating the initial CAS server operator artifact such as overlay/DSL build, but to be a full-blown solution to maintain CAS configs at run time (beyond CAS mgmt app).

So the possible names to add to the list are:

* Kyureta (Curator in Japanese)
* Curatr (ala Inspektr), as Curator name is taken by Netflix already: https://github.com/Netflix/curator

So far no actual development work has been done, but time has been spent on preliminary evaluating new and exciting technology that might fit the bill nicely here, called Atomist: https://www.atomist.com/

Once the first open source code drop is available, we could build the first prototype to validate the idea.

**Comment by mmoayyed** [comment]
We have begun to more seriously evaluate atomist and rug editors thus far. One pending issue: https://github.com/atomist/rug-cli/issues/111

**Comment by hdeadman** [comment]
One way to make it a little easier to get started with trying out different modules, would be to put each cas plugin in its own Maven profile (in the overlay's pom). This would allow someone to try out CAS via:

build.sh package -Pldap,x509,jsonsr,aup
build.sh run

and get a cas.war with ldap, x509, json service registry and acceptable use page module. Alternatively the user could modify the pom.xml to activate certain profiles/plugins they wanted to use by default so they wouldn't have to specify profiles each build. 

This doesn't address configuring the plugins and the pom would be very long due to the large number of cas plugins but it would save people from having to edit the pom.xml as much and they could go straight to configuration.

**Comment by mmoayyed** [comment]
Very good suggestions, thanks.

I think our initial stab at this would be to see what can be done to customize a spring.io deployment to fit CAS' needs. Once we sort that out, I am sure could auto-generate a pom that contains relevant profiles based on user selections of modules and plugins. 

The code behind start.spring.io is not quite released to central yet and I think it's safe to hang on for a while until it's 1.0'ed before taking action.

**Comment by mmoayyed** [comment]
An initial prototype is running under the *initializer* branch of the repo, that is auto-deployed to heroku whose link is accessible from the docs homepage. @dima767 and I reviewed road and options for automating documentation and builds. @hdeadman you may want to take a look (The proposal eventually is to deprecate the current overlays and simply have folks build up the overlay from the initializr)

**Comment by mmoayyed** [comment]
A sample is running over here: https://casinitializr.herokuapp.com/

I believe @dima767 is working on an approach to handle properties and doc-generation tasks that relate. At a high level:

1. Design a strategy in which CAS properties and settings can become self-documenting in code.
2. Allow a REST endpoint to respond to documentation queries.
3. Potentially, design a CLI that can take advantage of the endpoint for overlays
4. Use the endpoint in the initializr to auto-prep properties for overlays.

**Comment by mmoayyed** [comment]
Also a very nice-to-have: may integrate the CAS gradle plugin with the overlay that is generated by the initializr; work led by @scalding.

**Comment by mmoayyed** [comment]
In my list above, 1 2 3 are now done. We can begin to refocus efforts on the initializr past the 5.2 RC2 release. Closing this for now.
